### DISCUSSION TITLE
How do I get my `patch` version incremented automatically on `main` without tags nor specific commit messages?

### DISCUSSION THREAD

**Discussion by franknarf8** [GitTools/GitVersion#2660] [Q&A] [answered]
Hello,

I have just upgraded my GitVersion to the latest, but I can't find a way to reproduce the behavior I expect, and used to achieve with the previous GitVersion. (the change appeared between since 5.0.0)

When using `Mainline`, I would expect that each merge commits to `master` cause the `patch` version to increment. (Without any commit messages required)

Using the following `GitVersion.yml` (I'm generating pip versions here, please disregard the `branches`) :

```
mode: Mainline
next-version: 1.0.0
branches:
  release:
    tag: 'rc'
  feature:
    regex: ^features?[/-]|^(pull|pull\-requests|pr)[/-]
    tag: 'dev'
  develop:
    tag: 'a'
  hotfix:
    tag: 'post'
ignore:
  sha: []
merge-message-formats: {}
```

With this dummy git repo :
```
*   0bac05d 3 minutes ago  (HEAD -> master)
|\
| * 2922409 3 minutes ago  (feature/first-feature)
| * 2246a3e 7 minutes ago
|/
* bc00c9f 7 minutes ago  (tag: 1.2.3)
```

GitVersion 5.6.8 is inferring : `1.2.3`
whereas 5.0.0 inferred : `1.2.4`

I would expect `1.2.4` here, how can I achieve this?

**Comment by franknarf8** [comment]
I see that all commit-base increments [now force the usage of pre-release tags](https://gitversion.net/docs/reference/version-increments#incrementing-per-commit)

The way we have things set up now is the following : 
- Everything goes through PRs, and devs can't push tags themselves
- Pushes to `develop`, `main`, `release/*` and `hotfix/*` all build & publishes packages (pip packages)
- Every push to `main` is considered a new released version (no pre-release tags)
- We are using `release/*` occasonially to bump the `MAJOR` or `Minor` versions
- Most of our contributions are from `feature/*` branches and are directly merged into `main`
- On successful `main` build, we are tagging the repo for tracability
- We want every merge to `main` to generate a different version
    - Versionned branch merges (e.g. `release/*`) bump the `MAJOR` or `Minor`
    - Unversionned branch merges (e.g. `feature/*`) bump the `patch`

Ideally, we don't want to have to bump or manage versions manually; in commit messages or elsewhere (that's kinda why we started using GitVersion for these type of projects)

Do you guys have any idea about how I could achieve this?

Thanks a lot in advance :)

**Comment by franknarf8** [comment, marked as answer]
Eh, that's weird; removing the `next-version: 1.0.0` config fixes it. The following config yields the expected result :

Is that a bug?

```
mode: Mainline
branches:
  release:
    tag: 'rc'
  feature:
    regex: ^features?[/-]|^(pull|pull\-requests|pr)[/-]
    tag: 'dev'
  develop:
    tag: 'a'
  hotfix:
    tag: 'post'
```
