### DISCUSSION TITLE
Commit tag version differentation between release and non-release branch

### DISCUSSION THREAD

**Discussion by geenafong** [GitTools/GitVersion#2707] [Q&A] [answered]
Hi there,
I have been using gitversion and have been tagging commits to increment to the next version. I have a release branch that is equivalent to the code that is in production and a non-release branch for development. I would want the develop branch to be one minor version ahead of the release branch but I am having a hard time increasing the version of the non-release branch to consistentaly be ahead of the release branch. Here are the specs in my gitversion.yml file:

```yaml
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: 
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 5
build-metadata-padding: 5
commit-message-incrementing: Enabled
branches:  
  develop:    
    mode: ContinuousDeployment   
    tag: unstable    
    increment: Minor    
    prevent-increment-of-merged-branch-version: true    
    track-merge-target: false  
  stable:   
    source-branches: ['develop']    
    regex: stable    
    mode: ContinuousDeployment    
    tag: release    
    increment: Patch    
    prevent-increment-of-merged-branch-version: false    
    track-merge-target: false
```

Again, my goal is for the unstable/develop branch to be one minor version ahead of the stable/release branch. Any help to fix this would be much appreciated.

**Comment by dxynnez** [comment]
I am looking for the same solution - develop to only bump patch version (1.0.1-beta -> 1.0.2-beta) and release would bump the minor after merging the latest develop into it (1.0.0 -> 1.1.0).

Then the counter of develop branch would be reset to 1.1.0-beta.

I looked at the [document ](https://gitversion.net/docs/reference/configuration#prevent-increment-of-merged-branch-version) and seems like the `track-merge-target` flag is exactly for this purpose, but I just can't get it to work.

@geenafong  did you find a resolution?

**Comment by asbjornu** [comment, marked as answer]
What you describe sounds like the default behaviour for `main`, which by default is configured as such:

```yaml
  main:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
```

Have you tried just replacing `regex` and `tag` in this configuration with your branch names? Also, is there a good reason not to use `main` as your stable branch?
