### DISCUSSION TITLE
Increment version number based on branch type

### DISCUSSION THREAD

**Discussion by niko124a** [GitTools/GitVersion#3025] [Q&A] [answered]
Hi,

I am trying to find a way to make GitVersion increment the version, depending on which type of branch I am using when merging to my master branch (I am using Git-flow).

Examples of how I want it to be:

Merge release branch into master - Increment minor
Merge Hotfix branch into master - Increment patch

I have already tried to add `increment: Minor` and `increment: Patch` to the `release` and `hotfix` branch config.

Here is my `GitVersion.yml` file:

```yaml
branches:
  develop:
    regex: dev(elop)?(ment)?$
    mode: ContinuousDelivery
    tag: beta
  feature:
    regex: features?[/-]
    mode: ContinuousDelivery
    tag: alpha.{BranchName}
  release:
    regex: releases?[/-]
    mode: ContinuousDelivery
    tag: beta
  hotfix:
    regex: hotfix(es)?[/-]
    mode: ContinuousDelivery
    tag: beta
  master:
    mode: ContinuousDeployment
```
