### DISCUSSION TITLE
Help setting Mainline mode

### DISCUSSION THREAD

**Discussion by Tilgoron** [GitTools/GitVersion#3136] [Q&A] [answered]
Hey guys,

I am trying to introduce GitVersion in our team for the very first time, but unfortunately nobody have any experience, therefore I am kindly asking for help.

Our repo in DevOps have main branch locked by policy, we deploy to production from there and it is only possible to push via PR from either a "feature" or a "hotfix" branch.

1) First issue

What I am trying to achieve is the following:
- When a PR from "feature" goes into main -> Bump Minor version
- When a PR from hotfix goes into main -> Bump Patch version
(We Bump Major version manually by creating a new tag on Main).

2) Second issue

Our Pipeline can build and publish two types of NuGet, production ready from main branch, and test packages from building features branch.
To avoid Pipeline creating same NuGet package on multiple features/branch running in parallel, feature/hotfix versions should be generated by also looking at main.

Example:

- main is -> 1.0.0
- User1 create feature/f1 branch -> 1 commit-> 1.1.0-alpha+1
- User2 create feature/f2 branch  -> 2 commit -> 1.1.0-alpha+2
- User1 push feature/f1 branch into main and delete source branch
- main is 1.1.0
- User2 that still have feature/f2 branch active in development should see 1.2.0-alpha+2 when running GitVersion, since 1.1.0 is already in production.

Is this logic correct? I am just trying to find a way to build unique packages since multiple features branch are active at the same time.

My GitVersion.yml is as following:
```yml
assembly-versioning-scheme: MajorMinorPatch
mode: Mainline
branches:
  main:
    tag: ""
    is-mainline: true
    increment: none
    is-source-branch-for: ['feature', 'hotfix']
  feature:
    regex: ^features?[/-]
    tag: alpha-{BranchName}
    increment: Minor
    source-branches: ['main', 'master']
  hotfix:
    regex: ^hotfix(es)?[/-]
    tag: beta-{BranchName}
    increment: Patch
    source-branches: ['main', 'master']
ignore:
  sha: []
merge-message-formats: {}
````
