### DISCUSSION TITLE
Proper setup for workflow

### DISCUSSION THREAD

**Discussion by JDCain** [GitTools/GitVersion#3158] [Q&A] [answered]
I'm looking to configure GitVersion so that builds generate the same version if the code has not changed. 

I have been unable to get it working. Mainline almost works except we also use it with Dev and that branch seems to be way off on the verson number. ContinuousDelivery almost works but it does not keep the version from feature or dev.

Something like the following:
Main: 1.0.0
clone to Dev
Dev: 1.0.0-alpha
clone dev to feature/newFeature
feature/newFeature: 1.0.0-newfeature OR 1.1.0-newfeature
merge feature/newFeature to Dev
Dev: 1.1.0

Our workflow is odd as we need to release to dev from dev, and then merge into main when ready to send through the pipeline to all of the other test environments.

**Comment by asbjornu** [comment]
Only use `mode: Mainline` if you're using trunk based development. If you're not, you should not add a `GitVersion.yml` file at all and instead just go with the defaults. Is the name of your branch `Dev`? Just a note of caution: I would recommend that you don't use casing to indicate word separation in Git, as different file systems have different behavior wrt. case sensitivity. Please see #864, #2593 and #3015 for examples of problems you may run into by not having a strict all-lowercase rule for branch names.

Otherwise, your current workflow seems to be an almost good fit with GitVersion defaults and the Git Flow model.

**Reply by JDCain** [reply]
The problem I am having with the defaults is that when I merge from dev to main I expect it to keep the verion number generated for dev but instead it only raises it by a patch version number. 

My expectation is that the same code history should produce the same version number on any branch and increment by the increment setting on that current branch when something is added. Instead, dev produces 1.2.0-beta.2 and main produces 1.1.1 with the same history. 

If I set it up with the following it works as I expected, except in the case of hotfix which instead of showing the correct version of 1.2.0 on copying from main shows 1.1.1

``` yaml
branches: 
  main:
    tag: ""
    increment: inherit
  develop:
    tag: "beta"
    increment: inherit
  feature:
    tag: "alpha"
    increment: minor
  hotfix:
    tag: "alpha"
    regex: ^(fix|hotfix)(es)?[/-]
    increment: patch
```
