### DISCUSSION TITLE
Access GitVersion variables in different azure devops pipeline jobs

### DISCUSSION THREAD

**Discussion by niko124a** [GitTools/GitVersion#3290] [Q&A]
Hi

I have my azure devops pipeline like this

```yaml
trigger:
- develop
- feature/*

pool:
  vmImage: 'windows-2019'

variables:
  solutionFolder: 'Source'
  solution: '$(solutionFolder)/XXXX.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  repositories:
    - repository: templates #the name used to reference this resource
      type: git #the type for azure git repos
      name: XXXX/Pipeline-templates #the azure git repo name
      ref: refs/heads/main

jobs:
- template: azure-pipelines-gitversion-template.yml@templates
  parameters:
    gitToolsConfigFilePath: 'XXXX/GitVersion.yml'

- job: BuildAndUnitTests
...

- template: azure-pipelines-create-version-tag-template.yml@templates
  parameters:
    jobDependencyName: 'BuildAndUnitTests'
```

My `azure-pipelines-create-version-tag-template.yml` look like this

```yaml
parameters:
- name: jobDependencyName
  type: string
  default: ''


jobs:
- job: CreateVersionTag
  steps:
  - checkout: self
    persistCredentials: true
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/master') }}:
      - pwsh: |
          $buildNumber = $env:Build_BuildNumber
          Write-Output "Try to tag - Fingers crossed"
          if (git tag | select-string "$buildNumber") {
              Write-Output "tag already exists for $buildNumber. I will do absolutely nothing about it and assume everything is good"
          }
          else {
              git tag "$buildNumber"
              git push origin "$buildNumber"
              Write-Output "Tagging $(Build.Repository.Name) with $buildNumber"
        
          }
  dependsOn:
  - ${{ parameters.jobDependencyName }}
  condition: in(dependencies.${{ parameters.jobDependencyName }}.result, 'Succeeded', 'SucceededWithIssues')
```

I want to access GitVersion variable `MajorMinorPatch` inside my `CreateVersionTag` job.

Do anyone know how I can do this or if it is even possible?
I have already tried replacing `$buildNumber` with `$(GitVersion.MajorMinorPatch)` and `$(GitVersion_MajorMinorPatch)` without success.

I can access the variable just fine within my other template, which is where I have the `gitversion/setup@0` and `gitversion/execute@0` tasks.

**Comment by asbjornu** [comment]
I don't use AzDO myself, but in GitHub Actions you have to explicitly export output variables from a job in order to consume them from another job. Is something like that possible in AzDO, perhaps?

**Comment by fourpastmidnight** [comment]
Yes, you can! But you have to use a special syntax: `$[ stageDependencies.<stage_name>.<job_name>.outputs['<step_name>.<variable_name>'] ]`. Be aware that if you are using job matrixes, then this syntax changes just a little: `$[ stageDependencies.<stage_name>.<job_name>.outputs['<matrix-leg>.<step_name>.<variable_name>'] ]`. I mention this because I am using job matrixes.

When GitVersion runs, it creates variables that can be used by tasks running in the same job simply as `$(GitVersion_MajorMinorPatch)`, for example. But it also creates _output_ variables that can be used by different jobs in the same stage and in jobs in different stages.

So, in your case, since the job you want to access the GitVersion variable from is in a different stage from the job that created the variable, you must use this `stageDependencies` syntax:

Here's a really simple pipeline that defines two stages where the first stage calculates the version using GitVersion and the second stage merely consumes a variable.

```yaml
---
parameters:
  - name: configFilePath
    type: string
    default: GitVersion.yml

stages:
  - stage: versioning
    displayName: Calculate Version
    pool:
      name: MyBuildPool
    dependsOn: []
    jobs:
      - job: calculateVersion
        displayName: Calculate Version
        steps:
        - checkout: self
          clean: true
          persistCredentials: true
          fetchDepth: 0 # By default, AzureDevOps does a shallow clone, but we need full history for GitVersion

        # I actually also use a template for GitVersion. I also do not use the built-in AzureDevOps task
        # because in my organization, I'm unable to use it because it goes to the internet to an unapproved
        # location--to get updated files. So I use the dotnet tool version instead....
        # I'm going to inline my template here
        - pwsh: |-
            Write-Host '##[command]dotnet tool restore'
            dotnet tool restore
          displayName: Restore Required dotnet tools

        - pwsh: |-
            $ConfigFile = '${{ parameters.configFilePath }}'
            Write-Host "##[command]dotnet gitversion -config "$ConfigFile" -output buildserver"
            dotnet gitversion -config "$ConfigFile" -output buildserver
          displayName: Calculate Version and Set Build Pipeline Variables
          name: calculateVersion

  - stage: consumeGitVersion
    displayName: Consume GitVersion Variables
    dependsOn: [versioning]
    pool:
      name: MyBuildPool
    jobs:
    - job: useGitVersion
      displayName: Display Calculated Full Semver
      variables:
        # You MUST set a variable in this section with the stage dependency variable
        GitVersion.FullSemver: $[ stageDependencies.versioning.outputs['calculateVersion.GitVersion.FullSemVer'] ]
      steps:
        -pwsh: |-
           Write-Host "Calculated Full Semver: $(GitVersion.FullSemver)"
```
