### DISCUSSION TITLE
[Prabably Bug] Calculating metadata changes base version

### DISCUSSION THREAD

**Discussion by Pretasoc** [GitTools/GitVersion#3333] [Q&A]
Hi folks,

i am experiencing some weird behavior and i can't quite figure out why. The last version of my project was correctly calculated as `0.6.5`. When i released the next version (tagged as `0.7.0`) gitversion calculated it as `1.0.0`.

Between those two commits is a commit (`d99dc0eabd77f9c9e732590f685f5331300cae25`) that contains `+semver: +breaking`. But the wrong version is calculated even, when i ignore that commit.

From reading the [log](https://github.com/GitTools/GitVersion/files/10361522/log.txt), i don't really understand, why the major is incremented at this stage. I still think is has something to do with the commit `d99dc0eabd77f9c9e732590f685f5331300cae25` mentioned above, since the correct base version is calulated and then bumped, as the metadata are computed. 

As far as i understand the [documentation](https://gitversion.net/docs/reference/version-sources) the tag should prevent any changes to the version before the `+`.

This is the config i use:

``` yaml
assembly-versioning-scheme: MajorMinorPatch
mode: Mainline
branches:
  develop:
    mode: ContinuousDeployment
  feature:
    mode: ContinuousDeployment
  hotfix:
    mode: ContinuousDelivery
  release:
    mode: ContinuousDeployment
    tag: pre
ignore:
  sha: [ d99dc0eabd77f9c9e732590f685f5331300cae25 ]
merge-message-formats: {}
```
