### DISCUSSION TITLE
Trunk Based development

### DISCUSSION THREAD

**Discussion by Echarnus** [GitTools/GitVersion#3360] [Q&A] [answered]
Hi,

We are using trunk based development and I want to implement something such as https://blog.fkan.se/post/simple-release-versioning-with-trunkbased-development-semver-and-conventional-commits/ . Yet, is there any possibility to work without git commits? It should be automated. 

Because I can't figure out how I should apply a minor/ patch on main, based upon the source branch. 

Kind regards

**Comment by Echarnus** [comment, marked as answer]
My config for the moment, but after adding a feature my patch is just increased. 

```
mode: Mainline
branches:
  main:
    regex: ^main$|^master$
    increment: Inherit
    is-mainline: true
  develop:
  # Match nothing - Unused
    regex: ^\b$
  release:
    regex: ^release?[/-]
    increment: None
  feature:
    regex: ^feature[/-]
    tag: useBranchName
    increment: Minor
    is-source-branch-for: [ 'main' ]
  pull-request:
    # Match nothing - Unused
    regex: ^\b$
  hotfix:
    regex: ^fix[/-]
    tag: useBranchName
    increment: Patch
    is-source-branch-for: [ 'main', 'release' ]
  support:
    # Match nothing - Unused
    regex: ^\b$
ignore:
  sha: []
merge-message-formats: {}
```
