### DISCUSSION TITLE
Correctly joining semantic version metadata depending on if available or not

### DISCUSSION THREAD

**Discussion by a-ctor** [GitTools/GitVersion#3362] [Q&A]
Hi,

I am trying to override the informational version to no longer include the branch information but still include the SHA information. For this I am trying to set it using the following setting:

```
assembly-informational-format: '{MajorMinorPatch}{PreReleaseLabelWithDash}+{BuildMetaData}.Sha.{Sha}'
```

This works fine for pre-release version where build metadata is emitted: `6.0.0-alpha+5.Sha.7d1bd...`

But when building the actual release version `BuildMetaData` is `null` and thus the informational version produced is `6.0.0-alpha+.Sha.7d1bd...`, which is not a valid semantic version as the build metdata should start with a letter/digit. The version I would like to end up in this case does not start with a `.`:  `6.0.0-alpha+Sha.7d1bd...`.

I know of `??` but that does not help in this case as I want the opposite behavior printing the right value if the left side is *not-null*, an empty string otherwise. With a ternary like operator it could solve it like this:

```
assembly-informational-format: '{MajorMinorPatch}{PreReleaseLabelWithDash}+{BuildMetaData}{BuildMetaData ? "." : ""}Sha.{Sha}'
```

Is there a way to achieve this with the current variable formatting functionality?

Kind regards

**Comment by HHobeck** [comment]
I'm not hundret percentage sure what you like to achive but maybe this helps you:
```yaml
assembly-versioning-scheme: MajorMinorPatchTag
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{MajorMinorPatch}+{Sha}'
...
```
