### DISCUSSION TITLE
The patch version is being incremented , even if the increment tag is set to none

### DISCUSSION THREAD

**Discussion by kabilanmani93** [GitTools/GitVersion#3430] [Q&A] [answered]
**Describe the bug**
The patch version is being incremented , even if the increment tag is set to none

## Expected Behavior
To patch version should not be incremented , if the increment attribute in gitversion.yml is set to None under the specified branch
```
  hotfix:
    regex: '(hotfix)([/-])'
    tag: 'hotfix'
    increment: None
    prevent-increment-of-merged-branch-version: false
    source-branches: ['release']
    is-source-branch-for: []  
```

## Actual Behavior
The patch version is being incremented 

## Context
We are working on hotfixes on release branch ( refer the below sc for the graph)

-We create a release tag(on Gitlab using release-cli) only on master/main branch based on semversion ( gitversion tool)
-When a release branch is created out of master , the artifacts uploaded with the release tag (main) are used automatically

**issue is when we start having bugs on release branches**
- Current execution
           - We checkout the hotfix branch from release ( pipeline publishes artifacts with pipeline id)
           - when merged to release branch ( we have to manually override the env variable to pull the artifacts which needs to be deployed) ---> this is a manual task, we need to eliminate this by running semversion and create a releasetag in hotfix branch and use the same tag in release branch ( by running the gitversion command)
           
           **issue here is that**
            --> when i make a commit on hotfix branch the patch is incrementing. i do not want that to increment
           --> secondly is there a way to add a prefix having the commitid or random-number. say 2.0.2-hotfix:ef245.5

i have taught of below way of tagging.

![image](https://user-images.githubusercontent.com/46244764/223524922-d57c8285-6c4d-456e-828e-73fe7eed4978.png)

## Your Environment
Gitlab : 14.10.5
Gitlab runners on EKS

**Comment by HHobeck** [comment]
Hi @kabilanmani93 

It's quite difficult for me to follow your thoughts. The default supported workflow in GitVersion is the GitHub workflow (see https://gitversion.net/docs/learn/branching-strategies/gitflow/examples). If you want to customize the workflow then you can do this and overwrite the configuration file.

Are you sure this is a bug or do you want to know how you are going to setup GitVersion properly?

If it is a bug please try to simplify your scenario and create a integration test like:

```csharp
    [Test]
    public void Just_A_Test()
    {
        // * 2373a87 58 minutes ago  (HEAD -> main)

        var configuration = GitFlowConfigurationBuilder.New
            .WithVersioningMode(VersioningMode.ContinuousDeployment)
            .WithBranch("main", builder => builder
                .WithLabel("ci")
                .WithVersioningMode(VersioningMode.ContinuousDeployment)
            )
            .Build();

        using var fixture = new EmptyRepositoryFixture();

        fixture.MakeACommit();

        // ✅ succeeds as expected
        fixture.AssertFullSemver("0.0.1-ci.1", configuration);

        // or

        // ❌ expected: 0.0.1-ci.5"
        fixture.AssertFullSemver("0.0.1-ci.1", configuration);

        fixture.Repository.DumpGraph();
    } 
```
Please use the latest version in the main branch which contains the latest development initiatives. Thank you.

**Comment by kabilanmani93** [comment]
@HHobeck 

I have already setup the gitversion, but based on the gitversion.yml setting, the hotfix branch should not increment. but it is

Secondly, is it possible to have a dynamic tag ? example i have made the **tag as hotfix**. Can it prefix with a dynamic variable say commitid ? hotfix.commitid

```
  hotfix:
    regex: '(hotfix)([/-])'
    tag: 'hotfix'
    increment: None
    prevent-increment-of-merged-branch-version: false
    source-branches: ['release']
    is-source-branch-for: [] 
```

**Comment by HHobeck** [comment]
You can think of that the increment strategy is used to determine the next version. Therefor the tool calculates:

1. a list of one or more base versions using different IVersionStrategy implementation,
2. takes the highes version number and
3. increments the version depending on the increment strategy of the branch

Using the `IncrementStrategy.None` is very exceptional and I'm not sure if it is the right configuration for you. I would suggest you to read the documentation of GitVersion to get familiar how the configuration affects the version generation.

Anyway if you take this integration test you see that the `IncrementStrategy.None` value works like expected:

```csharp
    [TestCase(IncrementStrategy.None, "1.1.0-just_a_label.1+1")]
    [TestCase(IncrementStrategy.Patch, "1.1.1-just_a_label.1+1")]
    public void Just_A_Test(IncrementStrategy incrementStrategy, string expectedVersion)
    {
        // * 5245f56 56 minutes ago  (HEAD -> main)
        // * 5b3b55d 58 minutes ago  (tag: 1.1.0)

        var configuration = GitFlowConfigurationBuilder.New
            .WithBranch("main", builder => builder
                .WithLabel("just_a_label")
                .WithIncrement(incrementStrategy)
            ).Build();

        using var fixture = new EmptyRepositoryFixture("main");

        fixture.MakeATaggedCommit("1.1.0");
        fixture.MakeACommit();

        // ✅ succeeds as expected
        fixture.AssertFullSemver(expectedVersion, configuration);

        fixture.Repository.DumpGraph();
    }
```

**Reply by kabilanmani93** [reply]
Having IncrementStrategy.None should not increment the patch. But it is incrementing

**Reply by HHobeck** [reply]
If you define `IncrementStrategy.None` the patch number will be not incremented. The question is what is the number before the incrementation step (so called base version) in your scenario? If the base version is 2.0.2 then this number will be not incremented and the result will be still 2.0.2. Hope that's understandable.

**Reply by kabilanmani93** [reply]
My base version is 2.0.2 

when i take a hotfix branch checkout from release branch >> make a commit to hotfix branch and now calculate the semversion >> it is 2.0.3-hotfix.1

**command used to calculate the gitversion**: /tools/dotnet-gitversion

**expected**: 2.0.2-hotfix.1

**Docker file:**
```
FROM gittools/gitversion:5.12.0-alpine.3.14-3.1
WORKDIR /tools
ADD GitVersion.yml .
ENTRYPOINT ["/tools/dotnet-gitversion"]
```


**Gitversion configuration file**

```
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
assembly-informational-format: '{InformationalVersion}'
mode: Mainline
branches:
  master:
    regex: ^master$|^main$
    tag: ''
    increment: Inherit
    prevent-increment-of-merged-branch-version: true
    is-source-branch-for: [ 'feature', 'release', 'patch' ]
    is-release-branch: false
    is-mainline: true
  patch:
    regex: '(patch|bugfix)([/-][--])'
    tag: ''
    increment: Patch
    source-branches: ['master', 'main']
    is-source-branch-for: []
  hotfix
    regex: '(hotfix)([/-])'
    tag: 'hotfix'
    increment: None
    prevent-increment-of-merged-branch-version: true
    source-branches: ['release']
    is-source-branch-for: []  
  release:
    regex: ^release?[/-]
    tag: ''
    prevent-increment-of-merged-branch-version: true
    source-branches: [ 'main', 'master' ]
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    is-source-branch-for: ['hotfix']
  feature:
    regex: ^feature?[/-]
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches: ['master', 'main']
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    is-source-branch-for: []
```

**Reply by HHobeck** [reply]
May I ask you to try [6.0.0-beta.1](https://github.com/GitTools/GitVersion/releases/tag/6.0.0-beta.1)? Also without steps to reproduce I cannot help you.

**Reply by HHobeck** [reply]
In version 6.x the configuration has breaking changes and needs to be adapted

```yaml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
assembly-informational-format: '{InformationalVersion}'
mode: Mainline
branches:
  main:
    regex: ^master$|^main$
    label: ''
    increment: Inherit
    prevent-increment-of-merged-branch-version: true
    is-source-branch-for: [ 'feature', 'release', 'patch' ]
    is-release-branch: false
    is-mainline: true
  patch:
    regex: '(patch|bugfix)([/-][--])'
    label: ''
    increment: Patch
    source-branches: ['main']
    is-source-branch-for: []
  hotfix:
    regex: '(hotfix)([/-])'
    label: 'hotfix'
    increment: None
    prevent-increment-of-merged-branch-version: true
    source-branches: ['release']
    is-source-branch-for: []  
  release:
    regex: ^release?[/-]
    label: ''
    prevent-increment-of-merged-branch-version: true
    source-branches: [ 'main' ]
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    is-source-branch-for: ['hotfix']
  feature:
    regex: ^feature?[/-]
    label: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches: ['main']
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    is-source-branch-for: []
```
