### DISCUSSION TITLE
Help applying flow

### DISCUSSION THREAD

**Discussion by facusantillo** [GitTools/GitVersion#3469] [Q&A]
If this is a bug please tell me and I'll report it.

Testing version 6.0.0-beta.2 I'm not achieving the flow I'm looking for, it goes as follows:

ITERATION I:

develop has tag **1.0.0**
feature/minor_bump_1 merges into develop generating version **1.1.0-rc.1**
feature/minor_bump_2 merges into develop generating version **1.1.0-rc.2**
version **1.1.0-rc.2** it's released to production, so we tag develop as **1.1.0**

ITERATION II:
develop has tag **1.1.0**
feature/minor_bump_3 merges into develop generating version **1.2.0-rc.1** (so far so good)
a bug is encountered in prod version **1.1.0** (aka **1.1.0-rc.2**).
a branch is created to fix the bug from that tag, therefore: release/1.1.0_fixes
hotfix/fix_1 merges into release/1.1.0_fixes generating version **1.1.0-rc.3** (this is the unwanted behavior)

I want the hotfix to generate version **1.1.1-rc.1** because it's configured as patch, but somehow when the pull request is merged, the calculated version is finally **1.1.0-rc.3** (it's not taking into consideration the increment: Patch on release branch)

How can this be achieved? What I'm doing wrong?

This is my gitversion file:

```
mode: ContinuousDelivery
commit-message-incrementing: enabled

branches:
  release:
    mode: ContinuousDelivery
    regex: ^release?
    label: 'rc'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    tracks-release-branches: false
    track-merge-target: false
    source-branches:
      - develop
      - hotfix
    is-release-branch: true
    is-mainline: false

  develop:
    mode: ContinuousDelivery
    regex: ^develop$
    prevent-increment-of-merged-branch-version: true
    label: 'rc'
    tracks-release-branches: false
    track-merge-target: true
    increment: Minor
    is-release-branch: false
    is-mainline: true
    source-branches: []
    pre-release-weight: 60000

  hotfix:
    mode: ContinuousDelivery
    regex: ^hotfix?
    prevent-increment-of-merged-branch-version: false
    label: hotfix
    tracks-release-branches: true
    track-merge-target: true
    increment: Patch
    is-release-branch: false
    is-mainline: false    
    source-branches:
      - main
      - release
    pre-release-weight: 30000

  pull-request:
    mode: ContinuousDeployment
    label: 'PR'
    increment: Inherit
    regex: ^pull?
    is-release-branch: false
    prevent-increment-of-merged-branch-version: false
    is-mainline: false
    tracks-release-branches: false
    track-merge-target: false
    source-branches:
      - feature
      - hotfix
      - develop
      - release
    pre-release-weight: 30000
    
  feature:
    mode: ContinuousDelivery
    label: 'rc'
    increment: Inherit
    regex: ^feature?
    is-release-branch: false
    prevent-increment-of-merged-branch-version: false
    is-mainline: false
    tracks-release-branches: false
    track-merge-target: true
    source-branches:
      - feature
      - hotfix
      - develop
      - release
    pre-release-weight: 30000
```

The CI platform used is Azure Pipelines

**Comment by arturcic** [comment]
@HHobeck

**Comment by facusantillo** [comment]
I have managed to achieve but not sure if this is the correct configuration:

```
mode: ContinuousDelivery
commit-message-incrementing: enabled

branches:
  release:
    mode: ContinuousDelivery
    regex: ^release?
    label: 'rc'
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    tracks-release-branches: true
    track-merge-target: true
    source-branches:
      - develop
      - hotfix
    is-release-branch: true
    is-mainline: false

  develop:
    mode: ContinuousDelivery
    regex: ^develop$
    prevent-increment-of-merged-branch-version: true
    label: 'rc'
    tracks-release-branches: true
    track-merge-target: true
    increment: Minor
    is-release-branch: false
    is-mainline: true
    source-branches: []
    pre-release-weight: 60000

  hotfix:
    mode: ContinuousDelivery
    regex: ^hotfix?
    prevent-increment-of-merged-branch-version: false
    label: hotfix
    tracks-release-branches: true
    track-merge-target: true
    increment: Patch
    is-release-branch: false
    is-mainline: false    
    source-branches:
      - main
      - release
    pre-release-weight: 30000

  pull-request:
    mode: ContinuousDeployment
    label: 'PR'
    increment: Inherit
    regex: ^pull?
    is-release-branch: false
    prevent-increment-of-merged-branch-version: false
    is-mainline: false
    tracks-release-branches: true
    track-merge-target: true
    source-branches:
      - feature
      - hotfix
      - develop
      - release
    pre-release-weight: 30000
    
  feature:
    mode: ContinuousDelivery
    label: 'rc'
    increment: Inherit
    regex: ^feature?
    is-release-branch: false
    prevent-increment-of-merged-branch-version: false
    is-mainline: false
    tracks-release-branches: true
    track-merge-target: true
    source-branches:
      - feature
      - hotfix
      - develop
      - release
    pre-release-weight: 30000
```

I switched the following props to true:

```
tracks-release-branches: true
track-merge-target: true
```
