### DISCUSSION TITLE
How to use CommitsSinceVersionSource as PreReleaseNumber

### DISCUSSION THREAD

**Discussion by rcdailey** [GitTools/GitVersion#3492] [Q&A] [answered]
I have the following `GitVersion.yml`:

```yml
mode: ContinuousDelivery
tag-prefix: 'v'
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-]*\\))?:"
patch-version-bump-message: "^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"

branches:
  master:
    tag: dev
```

For my normal release process, I always want ContinuousDelivery. I always wait to release until I have a chance to test changes on `master`, and I make several commits before I do a release. I do not use a sophisticated branching strategy. Since I'm the only contributor on my FOSS project, I commit directly to `master` and make a release directly on master by creating a tag, pushing that tag up, and having my Github Workflow do a release on that tag (and not on `master` itself).

If I *do* make a release on `master`, it's considered an "edge" build and for testing purposes only. For `master` itself, I suppose it's fair to say it is closer to ContinuousDeployment, because each commit is a release of an "edge" build.

For those `master`-based builds, I like the end result of the above YAML configuration, except for the `PreReleaseNumber` value. It remains stuck at 1 (so it looks like `-dev.1`). I understand why; it is waiting on me to tag that edge build so it can increment to `-dev.2`. However, I do not want to tag every commit on `master` just to increment that number. What I really want is for `PreReleaseNumber` to be the same value as `CommitsSinceVersionSource`.

Is this possible? Do I need to do a per-branch configuration for tags & master separately to get this kind of behavior? I'm honestly not sure how to set this up. I'm not even sure if tags can be configured like branches in `GitVersion.yml`. And even if I'm able to set up `master` as ContinuousDeployment, I only want that to affect the prerelease tag; not the primary version number (the major/minor/patch components should be governed by tags only, and follow ContinuousDelivery semantics).

I hope what I'm asking for makes sense. I tried to give a lot of examples and detail. Let me know if there's more I can provide. Thanks in advance for any help.

**Comment by HHobeck** [comment, marked as answer]
Hi Robert,

Actually it's a little bit difficult for me to understand what you are trying to achieve. Could you maybe simplify your scenario? Or better create a integration test based on the main branch (because it targets the next 6.x version of GitVersion). Please let me know if you are not familiar with integration tests.

Thank you.

**Reply by rcdailey** [reply]
I'm not sure that an integration test would be appropriate here, since I'm not really discussing existing behavior. In my opinion, this paragraph pretty clearly states what I'm asking about:

> For those `master`-based builds, I like the end result of the above YAML configuration, except for the `PreReleaseNumber` value. It remains stuck at 1 (so it looks like `-dev.1`). I understand why; it is waiting on me to tag that edge build so it can increment to `-dev.2`. However, I do not want to tag every commit on `master` just to increment that number. What I really want is for `PreReleaseNumber` to be the same value as `CommitsSinceVersionSource`.

I don't know how to word it differently. I basically want `-dev.{CommitsSinceVersionSource}` instead of `-dev.{PreReleaseNumber}`.

**Reply by HHobeck** [reply]
If you want to use the fourth number like a revision number to count your release candidates, you can do this with the following configuration:

```yaml
assembly-versioning-scheme: MajorMinorPatchTag
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{MajorMinorPatch}+{Sha}'
mode: ContinuousDeployment
```

Use the following variables and pass it to the dotnet compiler (AzureDevOps dotnet build command):

`-p:Version=$(GitVersion.InformationalVersion) -p:AssemblyVersion=$(GitVersion.AssemblySemVer)`

**Reply by rcdailey** [reply]
Thank you very much for the response! I'll admit I don't fully understand the solution. I went back to the Configuration docs page and reviewed what each setting does. 

When I apply your configuration to my repo, I get this output:

```json
"SemVer": "5.0.0-dev.191"
```

This looks better, as the pre-release number isn't just stuck at `1` anymore. However, where did `191` come from? I tried counting the commits since my latest tag:

```txt
$ git rev-list --count v4.4.1...origin
53
```

I get 53 commits, not 191. Where does 191 come from?

Note that my test was done by modifying `GitVersion.yml` and simply running `dotnet-gitversion`. I didn't pass in the `-p` switches. Which is my next question: Why do you configure the assembly version and then pass those in via 2 properties?

I know you've already committed quite a bit of time helping me out. I very much appreciate it. Hopefully my follow up questions are not too unreasonable.

**Reply by HHobeck** [reply]
> This looks better, as the pre-release number isn't just stuck at 1 anymore. However, where did 191 come from?

I cannot answer this question because I don't know your repository. Actually that's is exactly the reason why I'm asking you to create a integration test to easily play with and have a basis to talk about.

```csharp
[Test]
public void Just_A_Test()
{
    var configuration = GitFlowConfigurationBuilder.New
        .WithAssemblyVersioningScheme(Extensions.AssemblyVersioningScheme.MajorMinorPatchTag)
        .WithAssemblyFileVersioningScheme(Extensions.AssemblyFileVersioningScheme.MajorMinorPatchTag)
        .WithAssemblyInformationalFormat("{MajorMinorPatch}+{Sha}")
        .Build();

    using EmptyRepositoryFixture fixture = new("main");

    fixture.MakeATaggedCommit("1.0.0");
    fixture.BranchTo("develop");
    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.1.0-alpha.1", configuration);

    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.1.0-alpha.2", configuration);

    fixture.BranchTo("release/1.1.0");
    fixture.MakeACommit();

    // ✅ succeeds as expected
    fixture.AssertFullSemver("1.1.0-beta.1+1", configuration);
    var variables = fixture.GetVersion(configuration);
    var variablesAsString = ConfigurationSerializer.Serialize(variables);
}
```

The output of variablesAsString is:
```yaml
- key: Major
  value: 1
- key: Minor
  value: 1
- key: Patch
  value: 0
- key: BuildMetaData
  value: 1
- key: FullBuildMetaData
  value: 1.Branch.release-1.1.0.Sha.aae4b0684168c1a291453d26c197466e34862962
- key: BranchName
  value: release/1.1.0
- key: EscapedBranchName
  value: release-1-1-0
- key: Sha
  value: aae4b0684168c1a291453d26c197466e34862962
- key: ShortSha
  value: aae4b06
- key: MajorMinorPatch
  value: 1.1.0
- key: SemVer
  value: 1.1.0-beta.1
- key: FullSemVer
  value: 1.1.0-beta.1+1
- key: AssemblySemVer
  value: 1.1.0.1
- key: AssemblySemFileVer
  value: 1.1.0.1
- key: PreReleaseTag
  value: beta.1
- key: PreReleaseTagWithDash
  value: -beta.1
- key: PreReleaseLabel
  value: beta
- key: PreReleaseLabelWithDash
  value: -beta
- key: PreReleaseNumber
  value: 1
- key: WeightedPreReleaseNumber
  value: 30001
- key: InformationalVersion
  value: 1.1.0+aae4b0684168c1a291453d26c197466e34862962
- key: CommitDate
  value: 2023-05-25
- key: VersionSourceSha
  value: 7c5549b9471541fc747e59e3d60663c46832b548
- key: CommitsSinceVersionSource
  value: 1
- key: UncommittedChanges
  value: 0
```

> Note that my test was done by modifying GitVersion.yml and simply running dotnet-gitversion. I didn't pass in the -p switches. Which is my next question: Why do you configure the assembly version and then pass those in via 2 properties?

If you have a csharp dll you need to distinguish up to three different version information (see https://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin):
1. AssemblyVersion
2. AssemblyFileVersion
3. AssemblyInformationalVersion

When calling the dotnet compiler you can pass in this information separatly (see https://stackoverflow.com/a/52340631).
