### DISCUSSION TITLE
GitVersion.yml to advance version on master branch on any pull request

### DISCUSSION THREAD

**Discussion by will-scc** [GitTools/GitVersion#3660] [Q&A]
I'm struggling to get GitVersion to do what I want. I'm sure it's user error, but I can't quite make sense of it.

My branch strategy looks like this:

* master
* dev
* hotfix*

Releases are done from the master branch. Any pull request into master triggers a build (releases are triggered manually). New builds for testing are triggered from any pull request into dev (basically we do a feature branch, merge into dev, that goes out to testing automatically). Once dev is at a good place, a pull request from dev -> master is done which triggers the next build, and release is triggered manually.

If a hotfix is required, a hotfix branch is created (e.g. hotfix-bug#1111) and this gets merged into master. Latterly we do a merge from master back to dev to pull across any hotfixes.

I'm trying to get it so that any pull request into master advances `Minor` and sets `Patch` to 0, except when it's from a hotfix branch, then it should advance the `Patch`. For example 3.4.0 goes to 3.4.1 upon hotfix, but 3.4.1 goes to 3.5.0 upon pull request from dev.

At the moment my master branch ends up with a version like this: `Update build number to 3.4.1+2 for build 222`. I don't understand why I'm getting a commit count when the master branch is set to advance Patch.

Any help would be much appreciated.

Below is my GitVersion.yml, but it's a bit of a mess as I've been trying various different things to get this working.

```yml
next-version: 3.3.0
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
mode: Mainline
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
tag-pre-release-weight: 60000
commit-message-incrementing: Enabled
branches:
  develop:
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: ^dev(elop)?(ment)?$
    source-branches: []
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 0
  main:
    mode: ContinuousDelivery
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$|^main$
    source-branches:
    - develop
    - hotfix
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: true
    pre-release-weight: 55000
  hotfix:
    mode: ContinuousDeployment
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^hotfix(es)?[/-]
    source-branches:
    - release
    - main
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
ignore:
  sha: []
increment: Inherit
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
```

**Comment by HHobeck** [comment]
Please start with the following configuration (preview 6.0.0-beta.3):

```yaml
workspace: GitFlow/v1
next-version: 3.3.0
branches:
  feature:
    increment: Minor
  hotfix:
    increment: Patch
```

Sequence diagrams:
https://gitversion.net/docs/learn/branching-strategies/gitflow/examples

Inherited configuration (GitFlow/v1):
https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/Configuration/SupportedWorkflows/GitFlow/v1.yml

**Reply by will-scc** [reply]
I should have mentioned, I'm using GitTools in an Azure DevOps server, which is version `0.10.2.23031113`. I'm not sure what version of GitVersion that relates to... Is the above configuration valid for that?

**Reply by HHobeck** [reply]
Actually no. workspace is a new property in 6.x version but you can just skip it and try it.

**Reply by will-scc** [reply]
Sorry, I'm not quite sure what you mean.

If I was to have my config purely as:

```yml
next-version: 1.1.0
branches:
  feature:
    increment: Minor
  hotfix:
    increment: Patch
```

That obviously isn't going to do what I'm trying to achieve...

**Comment by HHobeck** [comment]
Have you tried this?
```yml
mode: Mainline
branches:
  feature:
    increment: Minor
  hotfix:
    increment: Patch
```
Please don't use next-version with Mainline mode. It's not compatible. It might be also a problem that you are not using the beta version. I know that alot of things has been done in the pre-release version 6.x.

Happy branching!
