### DISCUSSION TITLE
No ability to increment Patch on subsequent commits

### DISCUSSION THREAD

**Discussion by konek3** [GitTools/GitVersion#3676] [Q&A] [answered]
**Describe the bug**
The current flow of git in our repository is as follows:
1. main branch acts as stable branch.
2. feature branches are created from main branch.
3. pull requests are created from feature branch to main branch and merged.
4. During release, release branch is created from main branch with a format: "release/X.Y", where X is Major and Y is Minor.

The problem is GitVersion don't catch new commits that are pushed to release branch (for example cherry-picks from main branch in case of hotfixes). The version stays the same, but Patch number should be incremented. For example:

1. Branch "release/1.0" gets created. Gitversion generates version "1.0.0".
2. 3 new commits are pushed to release branch. GitVersion should generate version "1.0.3" but it stays at "1.0.0"

Property `CommitsSinceVersionSource` gets incremented though.

Current configuration I have:

```
mode: MainLine
branches:
  feature:
    regex: ^feature?[/-]
    source-branches: ["main"]
    increment: None
    tracks-release-branches: true
  release:
    regex: ^release?[/-]
    source-branches: ["main"]
    increment: Patch
    tag: ""
  main:
    is-mainline: true
    increment: None
    tag: useBranchName
    tracks-release-branches: true
    is-source-branch-for: ["feature", "release"]
    regex: (^main$|^origin\/main$)
update-build-number: true
```

## Expected Behavior
After pushing new commits to release branch, Patch number should be incremented accordingly.

## Actual Behavior
Patch number does not get incremented.

Is something wrong with my current configuration?
