### DISCUSSION TITLE
wrong number bumped on conventional-commits

### DISCUSSION THREAD

**Discussion by mrt181** [GitTools/GitVersion#3681] [Q&A] [answered]
**Describe the bug**
Given this history

```shell
$ git log --max-count 27 --pretty="%C(auto)%h %(describe) %s" | awk -F':' '{print $1}'
a03a4d2 1.0.0-35-ga03a4d2 ci
8cf0672 1.0.0-34-g8cf0672 ci
dbe3aac 1.0.0-33-gdbe3aac Add renovate.json
c8f65f5 1.0.0-32-gc8f65f5 chore
f193afc 1.0.0-31-gf193afc ci
4e44801 1.0.0-30-g4e44801 ci
1516cce 1.0.0-29-g1516cce ci
be1f963 1.0.0-28-gbe1f963 ci
d62399f 1.0.0-27-gd62399f build
67408a8 1.0.0-26-g67408a8 ci
1117058 1.0.0-25-g1117058 ci
a6a437c 1.0.0-24-ga6a437c ci
bab150b 1.0.0-23-gbab150b chore
2fc16c0 1.0.0-22-g2fc16c0 feat(csharp)
22a687d 1.0.0-21-g22a687d build
58ccbef 1.0.0-20-g58ccbef build
813491f 1.0.0-19-g813491f docs
e10a246 1.0.0-18-ge10a246 build
92f25fa 1.0.0-17-g92f25fa Merged PR 1782
e1dac61 1.0.0-16-ge1dac61 docs
a811312 1.0.0-15-ga811312 build
ae78c6c 1.0.0-14-gae78c6c docs
7586e6f 1.0.0-13-g7586e6f Merged PR 1778
10a4d19 1.0.0 release
65b7297 1.0.0-beta.2-1-g65b7297 docs
8c7a1c3 1.0.0-beta.2 release
d5bb6e8 1.0.0-beta.1-41-gd5bb6e8 Merged PR 1777
```

The latest tag is `1.0.0` at commit `10a4d19`

## Expected Behavior
I should get a version like this
```shell
dotnet gitversion | jq '.FullSemVer'
"1.1.0+35"
```

Because of the `1.0.0` tag and the feature commit `2fc16c0 1.0.0-22-g2fc16c0 feat(csharp)` that appears later.

## Actual Behavior
But I get a version like this
```shell
dotnet gitversion | jq '.FullSemVer'
"1.0.1+35"
```

## Context
I am trying to create packages containing proto files only for java and dotnet.
For java I am using this plugin [Git.SemVersioning.Gradle](https://github.com/jmongard/Git.SemVersioning.Gradle)

This one returns the expected version:
```shell
$ ./gradlew printVersion | grep 'Version: ' | awk -F' ' '{print $2}'
1.1.0-SNAPSHOT+035.sha.a03a4d2
```

## Your Environment
This is my gitversion.yml
```yaml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
assembly-informational-format: '{InformationalVersion}'
mode: Mainline
continuous-delivery-fallback-tag: ci
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-]*\\))?:"
patch-version-bump-message: "^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"
update-build-number: false
```
- Version Used:
- Ubuntu 23.04
- GitVersion 5.12.0

**Comment by HHobeck** [comment]
Please only create a bug issue if you are certain that you have found a bug. Thank you very much!

**Reply by HHobeck** [reply]
Per default the main branch has the setting `increment: Patch`
Please see the documentation: https://gitversion.net/docs/reference/configuration

**Comment by mrt181** [comment]
I have tried to recreate the history here:
[git-test](https://github.com/mrt181/git-test)

```shell
$ git log --pretty="%C(auto)%h %(describe) %s"
a8f7c0b 1.0.0-beta.1-3-ga8f7c0b build: update config
34a9934 1.0.0-beta.1-2-g34a9934 chore: add files
31192ef 1.0.0-beta.1-1-g31192ef fix: some fix
3456f26 1.0.0-beta.1 release: v1.0.0-beta.1
5d0cfde 0.1.0-2-g5d0cfde fix: something
32ff4d8 0.1.0-1-g32ff4d8 chore: something
a09d356 0.1.0 release: v0.1.0
b543a18  chore: something
57f3c03  initial commit
```
I have created two annotated tags, `0.1.0` and `1.0.0-beta.1`.

I would expect to see the `PreReleaseLabel` set to `beta` in the output but it's missing.
```shell
$ dotnet gitversion
{
  "Major": 1,
  "Minor": 0,
  "Patch": 0,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "WeightedPreReleaseNumber": 60000,
  "BuildMetaData": 3,
  "BuildMetaDataPadded": "0003",
  "FullBuildMetaData": "3.Branch.main.Sha.a8f7c0b494da8580913353074ca05bc3070437a5",
  "MajorMinorPatch": "1.0.0",
  "SemVer": "1.0.0",
  "LegacySemVer": "1.0.0",
  "LegacySemVerPadded": "1.0.0",
  "AssemblySemVer": "1.0.0.0",
  "AssemblySemFileVer": "1.0.0.0",
  "FullSemVer": "1.0.0+3",
  "InformationalVersion": "1.0.0+3.Branch.main.Sha.a8f7c0b494da8580913353074ca05bc3070437a5",
  "BranchName": "main",
  "EscapedBranchName": "main",
  "Sha": "a8f7c0b494da8580913353074ca05bc3070437a5",
  "ShortSha": "a8f7c0b",
  "NuGetVersionV2": "1.0.0",
  "NuGetVersion": "1.0.0",
  "NuGetPreReleaseTagV2": "",
  "NuGetPreReleaseTag": "",
  "VersionSourceSha": "3456f269f03a0cd2379bbb05f9a08db1d946aa5c",
  "CommitsSinceVersionSource": 3,
  "CommitsSinceVersionSourcePadded": "0003",
  "UncommittedChanges": 6,
  "CommitDate": "2023-09-05"
}
```

**Comment by mrt181** [comment]
After adding tag `1.0.0` and a `feat` commit, the version is incremented to `1.0.1` instead of the expected `1.1.0`.

The repo has this branch setting:
```yaml
branches:
  main:
    regex: ^master$|^main$
    mode: Mainline
    tag: ''
    increment: None
    is-release-branch: true
    is-mainline: true
```

What am I missing here?
