### DISCUSSION TITLE
useBranchName appending ".1" to end of branch

### DISCUSSION THREAD

**Discussion by kalden2** [GitTools/GitVersion#3692] [General]
I have a very simple GitVersion.yml file:

```
mode: ContinuousDelivery
branches: 
  develop:
    tag: useBranchName
ignore:
  sha: []
merge-message-formats: {}
``` 

my branch name is "devops".  When I run "gitversion -showvariable FullSemVer" I get:
0.1.0-devops.1+90

My main and dev branches don't do this.  Running "git rev-parse --abbrev-ref HEAD" returns "devops".  I'm not sure where this ".1" is coming from.
