### DISCUSSION TITLE
Squash Commits and Version Calculation

### DISCUSSION THREAD

**Discussion by ArnavBhutaniLithia** [GitTools/GitVersion#3697] [Q&A] [answered]
Hello!

I have run into some issues working with a very standard gitflow release structure as described on the GitVersion documentation: https://gitversion.net/docs/learn/branching-strategies/gitflow/

However when making squash merges or single commits to the main branch, the version calculation gets messed up.

Eg)
```
commit 4100fd0728b92bcb93fe1b16bd498e1a9ac03709 (HEAD -> main, tag: v1.82.0)

gitversion
{
  "Major": 1,
  "Minor": 82,
  "Patch": 0,
  ...
}

git merge release/1.83.0 --squash

git commit -m 'Merged PR 123123: Merge release/1.83.0 to main

gitversion
{
  "Major": 1,
  "Minor": 82,
  "Patch": 1,
  ...
}
```

This also happens on commits to main (I am aware that  the docs above specify that you only merge release and hotfix branches in main, I'm just wondering if this is an intentional design or if it is not possible).

From what I understand: 
https://learn.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=azure-devops 
Squash commits still make commits on main, so as long as the commit message format fits the defined regex it should trigger the new version. But this doesn't appear to be the case. Is there an explanation somewhere for the behavior I am observing? In the end this isn't a big deal, but I would like to make sure that my versioning scripts are as resilient as possible to user error, and if there is a way to avoid running into release failures that would be preferable.

Gitversion.yaml file:
```
mode: ContinuousDelivery
branches:
  main:
    is-source-branch-for:
      - develop
      - hotfix
  release:
    mode: ContinuousDeployment
    tag: rc 
    source-branches:
      - develop
  hotfix:
    mode: ContinuousDeployment
    tag: rc
    is-release-branch: true
ignore:
  sha: []
merge-message-formats:
  tfs: '^Merged (?:PR (?<PullRequestNumber>\d+)): (M|m)erge (?<SourceBranch>.+) (in)?to (?<TargetBranch>.+)'
```

Thanks,
Arnav
