### DISCUSSION TITLE
Increment version (based on +semver: *) on every merge from feature/ to dev

### DISCUSSION THREAD

**Discussion by neexs** [GitTools/GitVersion#3715] [Q&A] [answered]
Hi, 

We create our features on feature/* branches and we make Pull Requests on Azure DevOps to merge them on dev branch.

On the PR, we have a template that suggest to choose between Fix, Minor or Major. Selecting one of the options will trigger the corresponding commit `(+semver: (major|minor|patch))` in the build validation pipeline.

This is the template :

``` markdown
## Type of update 
    - [ ] Fix
    - [ ] Feature
    - [ ] Major Change
```

This is the build validation pipeline : 

``` yaml
trigger:
- none

pool:
  vmImage: ubuntu-latest

## Job to calculate semantic version
jobs:
  - job: CalculateVersion
    displayName: Semantic versioning

    steps:
      # Checkout with persist credentials
      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      # Install GitVersion
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.x'

      # Retrieve Pull Request Description
      - task: PullRequestDescription@0
        name: RetrievePullRequestDescription
        displayName: Retrieve Pull Request description
        inputs:
          action: 'view'
          outputVariable: 'PullRequest.DescriptionContent'
          isOutput: true
          stripIdentifiers: false

      # Add git commit message that will be picked up by GitVersion ("+semver: patch/minor/major")
      # Depending on the Pull Request description, where the developer has marked the type of change
      - task: PowerShell@2
        displayName: Add git commit message for SemVer
        inputs:
          targetType: inline
          script: |
            Write-Host "Configuring git author info.." -ForegroundColor Cyan
            git config user.email "Azure DevOps pipeline"
            git config user.name "Azure.Devops@pipeline.com"
            Write-Host "Doing git checkout..." -ForegroundColor Cyan
            git checkout -b $("$(System.PullRequest.SourceBranch)".replace('refs/heads/', ''))
            Write-Host "Checking Pull Request description..." -ForegroundColor Cyan
            $PRdesc = "$(RetrievePullRequestDescription.PullRequest.DescriptionContent)"
            if ($PRdesc -match '(\[x\] \bFix\b)') {
              Write-Host "Adding git (empty) commit message to mark this branch as a 'patch' SemVer increment." -ForegroundColor Cyan
              git commit -a -m "+semver: patch [skip azurepipelines]" --allow-empty
            } elseif ($PRdesc -match '(\[x\] \bFeature\b)') {
              Write-Host "Adding git (empty) commit message to mark this branch as a 'minor' SemVer increment." -ForegroundColor Cyan
              git commit -a -m "+semver: minor [skip azurepipelines]" --allow-empty
            } elseif ($PRdesc -match '(\[x\] \bMajor Change\b)') {
              Write-Host "Adding git (empty) commit message to mark this branch as a 'major' SemVer increment." -ForegroundColor Cyan
              git commit -a -m "+semver: major [skip azurepipelines]" --allow-empty
            } else {
              Write-Host "##vso[task.LogIssue type=error;]Please select the type of change in the Pull Request description, and Re-queue the validation." -ForegroundColor Cyan
              $PRdesc
              exit 1
            }
            Write-Host "Doing git push.." -ForegroundColor Cyan
            git push -f --set-upstream origin $("$(System.PullRequest.SourceBranch)".replace('refs/heads/', ''))
            Write-Host "Done." -ForegroundColor Cyan

      # Determine the semantic version
      - task: gitversion/execute@0
        displayName: Determine SemVer
        inputs:
          useConfigFile: True
          configFilePath: ".azuredevops/gitversion.yml"
          updateAssemblyInfo: true
```

When merge is done, we tag version on dev based on the semver. 

**Question**: Currently, every merge of feature/* into dev branch will increment (minor, major or patch, according to the checked box in the Pull Request's description) based on the last version of main. How can we make it increment based on the last version made on the dev branch instead ?

Expected flow : 
![image](https://github.com/GitTools/GitVersion/assets/12820536/a0ca459d-dc57-46d0-9111-6399dab72e15)

Current flow :
![image](https://github.com/GitTools/GitVersion/assets/12820536/f89be239-96a3-4323-9645-ab3ef77d02c7)

Thank you in advance for your help :)
