### DISCUSSION TITLE
How to update patch without using tag? where is PreReleaseNumber coming from?

### DISCUSSION THREAD

**Discussion by EmilAlipiev** [GitTools/GitVersion#3894] [Q&A]
Is there a way to get patch version increased at PR or hotfix without using a tag? if yes which strategy can be used?  my Gitversion.yml file is as below. I dont have a release branch and i want to use main and develop as release branches. Anything merged on develop should release beta and on main without any suffix.

```

ext-version: 1.1.0
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
assembly-informational-format: '{InformationalVersion}'
commit-message-incrementing: Enabled

branches:
  main:
    regex: ^master$|^main$
    mode: ContinuousDeployment
    label: ''      
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'develop' ]
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: true
    label-number-pattern: ''
    pre-release-weight: 55000
  develop:
    regex: ^dev(elop)?(ment)?$|^staging$
    mode: ContinuousDeployment
    label: beta
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    source-branches: []
    tracks-release-branches: true
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 0
  feature:
    regex: ^features?[/-]|^PBI[/-]
    mode: ContinuousDelivery
    label: useBranchName
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches: [ 'develop', 'main', 'release', 'feature', 'support', 'hotfix' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    label: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    label-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    source-branches: [ 'develop', 'main', 'release', 'feature', 'support', 'hotfix' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    regex: ^hotfix(es)?[/-]
    mode: ContinuousDelivery
    label: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches: [ 'develop', 'main', 'support' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  support:
    regex: ^support[/-]
    mode: ContinuousDelivery
    label: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'main' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 55000
```

I have a problem with this that it results in version with PreReleaseNumber as shown below and it will produce 1.1.0-56 as version. I would like this to produce 1.1.1 not append  number with dash on main/master. 

```
Executing GenerateBuildLogOutput for 'AzurePipelines'.
{
  "AssemblySemFileVer": "1.1.0.0",
  "AssemblySemVer": "1.1.0.0",
  "BranchName": "master",
  "BuildMetaData": null,
  "CommitDate": "2024-02-02",
  "CommitsSinceVersionSource": 56,
  "EscapedBranchName": "master",
  "FullBuildMetaData": "Branch.master.Sha.sadsafdfdf",
  "FullSemVer": "1.1.0-56",
  "InformationalVersion": "1.1.0-56+Branch.master.Sha.sadsafdfdf",
  "Major": 1,
  "MajorMinorPatch": "1.1.0",
  "Minor": 1,
  "Patch": 0,
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": 56,
  "PreReleaseTag": "56",
  "PreReleaseTagWithDash": "-56",
  "SemVer": "1.1.0-56",
  "Sha": "dfdfdf",
  "ShortSha": "fdacf03",
  "UncommittedChanges": 0,
  "VersionSourceSha": "sadsafdfdf",
  "WeightedPreReleaseNumber": 55056
}

```
