### DISCUSSION TITLE
Main branch version after merge not matching version from merged branch

### DISCUSSION THREAD

**Discussion by clementhervy** [GitTools/GitVersion#3944] [Q&A] [answered]
Hey there. I'm looking to implement the exact behaviour described in the unit test pictured in [this comment](https://github.com/GitTools/GitVersion/issues/1221#issuecomment-1455024274) with GitVersion 5.
I noticed the test class is entirely commented out nowadays. Has this behaviour been deprecated in some way?

Target behaviour:
```
GitVersion SemVer:    1.0.0                         1.1.0
branches         : main-o-----------------------------o-------->
                         \                   pull request merge
                          \ ------feature/new-----o/
                                         1.1.0-feature-new.1
```

Current behaviour - only the patch number is incremented:
```
GitVersion SemVer:    1.0.0                         1.0.1  ⚠
branches         : main-o-----------------------------o-------->
                         \                   pull request merge
                          \ ------feature/new-----o/
                                         1.1.0-feature-new.1
```

I also tried tagging the `feature/new` branch with the `1.1.0-feature-new.1` version but it would not change anything.

Currently my GitVersion.yml seems to copy the configuration in the unit test well enough:

```
# Default values reference: https://gitversion.net/docs/reference/configuration
commit-message-incrementing: Disabled
mode: Mainline
merge-message-formats:
  github: ^.*from repository\/(?<SourceBranch>.+)$
  # Also tried:
  # github: ^.*from repository/(?<SourceBranch>.+)$
branches:
  main:
    regex: ^main$
    increment: Inherit
    # prevent-increment-of-merged-branch-version: false
    # track-merge-target: true
    # tracks-release-branches: true
    # is-release-branch: true
  feature:
    regex: ^feature/
    increment: Minor
    source-branches: [ 'main', 'support' ]
```

Am I missing anything?

**Comment by HHobeck** [comment]
I'm not sure which version you are using exactly but maybe this helps:
```yaml
branches:
  main:
    mode: Mainline
    increment: None
  feature:
    mode: Mainline
    increment: Minor
  hotfix:
    mode: Mainline
    increment: Patch
```

The Mainline mode is deprecated yes and will be replaced with the TrunkBased workflow in the next pre-release package in version 6.0.0-beta.6. The unit tests are commented out temporary and will be reactivated soon.

Happy Branching! ;)

**Reply by clementhervy** [reply]
Hey Hardy,
Thank you for your answer. I'm using 5.12.0.
I followed your advice and tried setting `mode` at the branch level, but I get this error:

```
GitVersion.Configuration.ConfigurationException: Mainline mode only works at the repository level, a single branch cannot be put into mainline mode
```

What would be the difference between setting `mode` at the global and branch levels?

`increment: None` on `main` does get me `1.1.0` but only out of Mainline mode.

**Comment by HHobeck** [comment]
> What would be the difference between setting `mode` at the global and branch levels?

Yes you are right you need to specify it on the root level as well. On global level the value will be used as a fallback for the branches.

> `increment: None` on `main` does get me `1.1.0` but only out of Mainline mode.

What do you mean with that!? Is it working?

**Reply by clementhervy** [reply]
I mean that:
```
mode: Mainline
branches:
  main:
    increment: None
```
gets me an incorrect `1.0.0`

```
mode: Mainline
branches:
  main:
    # increment: None
```
gets me an incorrect `1.0.1`

```
# mode: Mainline # note this is commented out
branches:
  main:
    increment: None
```
gets me the expected `1.1.0`, but I think need Mainline mode for other desirable behaviours.
