### DISCUSSION TITLE
MergeMessage Strategy using Azure DevOps & Squash Merges

### DISCUSSION THREAD

**Discussion by DSpirit** [GitTools/GitVersion#3964] [Q&A] [answered]
Hello,

we are using GitVersion 6.0.0-beta.7 in our Azure DevOps environment and have configured it as follows:

``` yaml
workflow: GitHubFlow/v1
tag-prefix: '[vV]?'
update-build-number: true
strategies:
- MergeMessage
- TaggedCommit
- TrackReleaseBranches
- VersionInBranchName
branches:
  main:
    regex: ^master$|^main$
    label: 'ci'
    prevent-increment:
      of-merged-branch: true
  release:    
    regex: ^release(s)?[/-](?<BranchName>.+)
    label: 'rc'
    is-release-branch: true
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: false
  unknown:
    increment: Inherit
    regex: (?<BranchName>.+)
ignore:
  sha: []
```

Let's assume we create release branches following this format: `release/2.0.0` and want to merge it back to main to increment the version as specified. This works **only as long as we don't use Squash Commits**, as the MergeMessage strategy needs **at least 2 parent commits** before getting active in the GitVersion task - this isn't given when using the Azure DevOps Squash Merge Policy.

If we choose `Basic Merge`, the version gets incremented as expected.

Is there any reason for the MergeMessage to expect 2 parent commits and / or is there any workaround to increment the main version as defined in the release branch despite of using Squash merges?
