### DISCUSSION TITLE
Not bumping version

### DISCUSSION THREAD

**Discussion by dnyandeobharambe** [GitTools/GitVersion#3979] [General]
I am using gitversion 5.11.1 in azure devops pipeline When I am using +semversion:patch it should increase the version. But it keep giving me same version. I tried different ways but did not help. Here is my code and configuration. Let me know what is wrong

```yaml
steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true
    - task: gitversion/setup@0
      displayName: 'Install GitTools'
      inputs:
        versionSpec: '5.11.1'
    - task: gitversion/execute@0
      name: CalculateSemVer
      displayName: 'Calculate SemVer'
      inputs:
        useConfigFile: true
        configFilePath: './azure-pipelines/GitVersion.yml'
    - bash: |
        currentVersion=$(GitVersion.SemVer)
        echo "currentversion is $currentVersion"
        echo "##vso[task.setvariable variable=semversion;isOutput=true;]$currentVersion"
      name: SetOutputVariable
```

```yaml
mode: Mainline
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
commit-message-incrementing: Enabled
branches:
  release:
    regex: ^releases?[/-]
    tag: ''
  feature:
    regex: ^feature?[/-]
    tag: ''
```

It always return currentversion as 8162023.0.11. This is really strange

**Comment by dnyandeobharambe** [comment]
I try to increase minor it works fine. Next time I increase patch . This time instead of patch it again increased minor. Really strange. I am testing it in my feature branch and I configured it accordingly in configuration file

**Reply by asbjornu** [reply]
Can you paste the output of running the command `git tag` in your repository?

**Reply by dnyandeobharambe** [reply]
I have multiple repos with this problem. I cleaned my tag couple of times and try new run too. When I clean it show nothing when I ran it show results. Sometime git tag shows me nothing even tag exists (generally this happened and I use different combination to see list).
Example I have tags now But it showing nothing 
![image](https://github.com/GitTools/GitVersion/assets/39019068/33bdc40d-85ca-45d8-b601-1499a25b58bc)
When I use git fetch --tags I get following output 

$ git fetch --tags
remote: Enumerating objects: 163, done.
remote: Counting objects: 100% (163/163), done.
remote: Compressing objects: 100% (163/163), done.

Receiving objects: 100% (163/163), 44.79 KiB | 2.24 MiB/s, done.
Resolving deltas: 100% (110/110), done.
From bitbucket.org:pivotalcommware/wavescape-webapp
 * [new branch]      bugfix/WAV-4246-clean-up-web-services-app-insight-logs -> origin/bugfix/WAV-4246-clean-up-web-services-app-insight-logs
   eac50a2..7c41f92  dev-int     -> origin/dev-int
 * [new tag]         3082024.0.0 -> 3082024.0.0
 * [new tag]         3082025.0.0 -> 3082025.0.0
 * [new tag]         3082025.1.0 -> 3082025.1.0
 * [new tag]         3082025.2.0 -> 3082025.2.0
 * [new tag]         3082026.0.0 -> 3082026.0.0
 * [new tag]         3082027.0.0 -> 3082027.0.0
 * [new tag]         3082028.0.0 -> 3082028.0.0

Let me know 

Additionally I am using this code to read commit message , do you think it might be cause,even not related

check_semver_format() {
            # Function definition here
            semver_pattern='\+semver:(breaking|major|feature|minor|fix|patch)'
            if [[ $1 =~ ^$semver_pattern ]]; then
                echo "startsWith"
            else
                if [[ $1 =~ $semver_pattern ]]; then
                    echo "contains"
                else
                    echo "doesNotMatch"
              fi
          fi
          }
          # Example usage
          given_string=$(git log --format=%B -n 1)
          result=$(check_semver_format "$given_string")
          echo "Result: $result"
          # Set a variable for use in subsequent jobs
          echo "##vso[task.setvariable variable=SemverResult;isOutput=true]$result"
        name: RunBashScript 

I saw something this in log, is this tell some story
NextVersion in GitVersion configuration file: 1.0.0 with commit count source External Source
    INFO [03/28/24 22:42:04:20] Fallback base version: 0.1.0 with commit count source f74fcc191954fcbe0e4fb581e7ccb9180932b889
    INFO [03/28/24 22:42:04:32] Git tag '3082027.0.0': 3082027.0.0 with commit count source 2822b01e984b65296aa8ff36cbe81e836748949a
    INFO [03/28/24 22:42:04:32] Git tag '3082026.0.0': 3082026.0.0 with commit count source 3ada2dfd8cf6673644979fabbde05391d5cd3aea
    INFO [03/28/24 22:42:04:32] Git tag '3082025.2.0': 3082025.2.0 with commit count source 50bb9b516f92e6967f471248b289e76b2cc205e5
    INFO [03/28/24 22:42:04:32] Git tag '3082025.1.0': 3082025.1.0 with commit count source 003a163ac018b3c6cc7050f6feefb9c1b9998b95
    INFO [03/28/24 22:42:04:32] Git tag '3082025.0.0': 3082025.0.0 with commit count source bef360d130251fdf46203c31b9ec0d92ef1b0b80
    INFO [03/28/24 22:42:04:32] Git tag '3082024.0.0': 3082024.0.0 with commit count source fd73a6a755168499312bfc49d259c84279f1a286

**Reply by dnyandeobharambe** [reply]
Here is complete log
[log-gitversion.txt](https://github.com/GitTools/GitVersion/files/14841475/log-gitversion.txt)

**Comment by dnyandeobharambe** [comment]
is any body replying me , I really stuck on this

**Comment by dnyandeobharambe** [comment]
This is answer

```yaml
mode: Mainline
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
commit-message-incrementing: Enabled
ignore:
  commits-before: 2024-03-09T06:02:00
branches:
  main:
    regex: ^vertest$  # Matches your developement branch
    tag: ''  # No tag associated with the feature branch
    source-branches: []
```
