### DISCUSSION TITLE
gittool in azuredevops

### DISCUSSION THREAD

**Discussion by dnyandeobharambe** [GitTools/GitVersion#3993] [General]
Let me explain complete scenario and attaching log. I am not getting expected result, I feel either I am doing something fundamentally wrong or trying some scenario which you never tested.
I have existing repos which merge and deploy couple of times and versioning was not exist. Now I am trying to add it based on commands using gittools with gitversion 5.11.1 /5.12.   I am testing my feature branch but irrespective of command it bump major only. I enable debug and I can see command goes fine , but it consider to bump major onlt. In attached log I am using  +semver: minor.
Here is my config (I am ignoring past commit , that is reason ignore exist , and say I want to start version after this date only).
Very first time I provide +semver: patch it bumped to 1.0.0 (was expecting 0.1.1  )

In short I want to ignore all previous merge and start fresh after this date so it can start as above

```yaml
mode: Mainline
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
branches:
  release:
    regex: ^releases?[/-]
    tag: ''
  feature:
    regex: ^feature?[/-]
    tag: ''
```

I appreciate if someone can point the issue or thing I am doing wrong.
Attached log
[log-gittool.txt](https://github.com/GitTools/GitVersion/files/14890462/log-gittool.txt)

**Comment by dnyandeobharambe** [comment]
following changes works

```yaml
mode: Mainline
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
commit-message-incrementing: Enabled
ignore:
  commits-before: 2024-03-09T06:02:00
branches:
  main:
    regex: ^vertest$  # Matches your developement branch
    tag: ''  # No tag associated with the feature branch
    source-branches: []
```
