### DISCUSSION TITLE
what this error means

### DISCUSSION THREAD

**Discussion by dnyandeobharambe** [GitTools/GitVersion#3994] [Q&A] [answered]
GitVersion.GitVersionException: Cannot find commit 051ddec +semver: minor. Please ensure that the repository is an unshallow clone with `git fetch --unshallow`.

```yaml
- checkout: self
      fetchDepth: 100
      persistCredentials: true
    - task: gitversion/setup@0
      displayName: 'Install GitTools'
      inputs:
        arguments: '--debug'
        versionSpec: '5.11.1'
```

I want to ignore all past commit and want to start scratch from my new commit in my branch for version calculation.
But it look like Gitversion always need all history and for that I have to use fetchDepth : 0 which messup the thing.

What are options to me?

**Comment by asbjornu** [comment]
You need to set `fetchDepth` to `0` for GitVersion to work. If you want to start from scratch, you either need to use the `ignore` configuration in GitVersion or recreate the repository somehow.

**Reply by dnyandeobharambe** [reply]
[log-gittool-1.txt](https://github.com/GitTools/GitVersion/files/14909184/log-gittool-1.txt)
Thanks  Ignore not helping complete reset , when I use ignore it always bump major not consider command input 
mode: Mainline
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
commit-message-incrementing: Enabled
ignore:
  commits-before: 2024-04-03T13:57:00
branches:
  develop:
    regex: ^feature\/WAV-3509-refactor-webapp-pipeline-for-ve$  # Matches your feature branch
    tag: ''  # No tag associated with the feature branch
    source-branches: []

See attached log, It ignore all before dates and found 5.0.0 as a version which it will use to calculate next which it says will be 5.1.1(as command is to bump minor). But in actual I see it is 6.0.0 . I am not understanding why it happening. If somebody can explain me then that will be helpful

**Comment by dnyandeobharambe** [comment, marked as answer]
It worked with 

```yaml
mode: Mainline
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
commit-message-incrementing: Enabled
ignore:
  commits-before: 2024-03-09T06:02:00
branches:
  main:
    regex: ^vertest$  # Matches your developement branch
    tag: ''  # No tag associated with the feature branch
    source-branches: []
```
