### DISCUSSION TITLE
Is it intended that `regex` uses `EscapedBranchName` rather than `BranchName`?

### DISCUSSION THREAD

**Discussion by BenB196** [GitTools/GitVersion#3997] [Q&A]
Hi,

I'm testing out a config on [6.0.0-beta.7](https://github.com/GitTools/GitVersion/releases/tag/6.0.0-beta.7), and I'm somewhat curious if what I'm seeing is intended or not, as I don't see anything obvious in the docs about this.

For reference I have two branches:

Branch A:

```
GitVersion_BranchName=release/0.1.0
GitVersion_EscapedBranchName=release-0-1-0
```

Branch "bravo"
```
GitVersion_BranchName=release/0.1.0.bravo
GitVersion_EscapedBranchName=release-0-1-0-bravo
```

My base config (simplified) looks like:

```yaml
release:
  regex: ^releases?[/-]
  source-branches: [ 'release' ]
  label: 'beta'
  increment: Patch
  track-merge-target: true
  is-main-branch: true
  tracks-release-branches: true
  pre-release-weight: 0
```

My objective is that `GitVersion_SemVer`, should become:

```
0.1.0-beta.1
0.1.0-beta.bravo.1
```

When I try to use a capturing group regex that would match `GitVersion_BranchName`,

```yaml
release:
  regex: ^releases?[/-](?<ReleaseNumber>[0-9]+(\.[0-9]+){0,2})(?<SubRelease>\..+)?
  source-branches: [ 'release' ]
  label: 'beta{SubRelease}'
  increment: Patch
  track-merge-target: true
  is-main-branch: true
  tracks-release-branches: true
  pre-release-weight: 0
```

I see odd outcomes:

```
0.1.1-beta-1-0.1
0.1.1-beta-1-0-bravo.1
```

But, when I use a capturing group regex that would match `GitVersion_EscapedBranchName`

```yaml
release:
  regex: ^releases?[/-](?<ReleaseNumber>[0-9]+(-[0-9]+){0,2})(?<SubRelease>[/-].+)?
  source-branches: [ 'release' ]
  label: 'beta{SubRelease}'
  increment: Patch
  track-merge-target: true
  is-main-branch: true
  tracks-release-branches: true
  pre-release-weight: 0
```

I see slightly more "correct" outcomes:

```
0.1.1-beta.1       # This is desired
0.1.1-beta-bravo.1 # This is almost desired, but `-bravo` should be `.bravo`
```

So, it looks like that `regex` uses the `GitVersion_EscapedBranchName` value rather than the `GitVersion_BranchName`. Is this intended (the docs don't really mention this)? If this is intended, is there a way to achieve the outcome I'm looking for with my additional branch suffix?
