### DISCUSSION TITLE
Mainline not behaving as expected. PR and merge to main are not incremeted as expected

### DISCUSSION THREAD

**Discussion by LindnerBrewery** [GitTools/GitVersion#4024] [Q&A] [answered]
I'm having problems with wrong version when running GitHub actions on a PR and merging into main.
I'm using GitVersion in mainline mode. Here's my GitVersion.yml:
```
Mode: mainline
Branches:
  main:
    Tag:
    increment: Patch
    regex: ^master$|^main$
  release:
    tag: beta
    increment: None
    regex: ^releases?[/-].
  characteristic:
    tag: alpha
    Increment: Minor
    regex: ^features?[/-].
  pull-request:
    tag: preview
    increment: inherit
    tag-number-pattern: ''
  hotfix:
    tag: alpha
    increment: patch
    regex: ^hotfix(es)?[/-]|^patch?[/-].
```
I'll start with version 0.5.0 on my main branch. As soon as I create a new feature branch, the minor version is bumped to 0.6.0-alpha0000. Local testing confirms that it works. I update my code until i get to 0.6.0-alpha0003. After pushing it to GitHub, the action runs, and I get the expected version (0.6.0-alpha0003). Now I create a PR and the action runs again, but this time the version is not as expected, I get the version 0.5.1-preview00x and not 0.6.0-preview00x. Merging the PR into the main also gives me the wrong version (0.5.1).

If I merge the feature branch locally with `git merge feature/newbranch --no-ff`, the main branch will have the correct version. Without the --no-ff, the main branch version will only increment the patch as it does when running on GitHub actions. I tried it Azure DevOps and I got the same (wrong) result.

Any ideas on how to fix my problem?
