### DISCUSSION TITLE
6.0.0-rc.1

### DISCUSSION THREAD

**Discussion by arturcic** [GitTools/GitVersion#4039] [Announcements]
<hr /><em>This discussion was created from the release <a href='https://github.com/GitTools/GitVersion/releases/tag/6.0.0-rc.1'>6.0.0-rc.1</a>.</em>

**Comment by DSpirit** [comment]
Thanks for the update, glad to see it progressing :)

Unfortunately our current pipelines broke due to following issue:

``` 
Could not build the configuration instance because following exception occurred: 'Property 'tracks-merge-target' not found on type 'GitVersion.Configuration.BranchConfiguration'.' Please ensure that the /overrideconfig parameters are correct and the configuration file is in the correct format.
```

I've already tried adding these properties
``` yaml
tracks-merge-target: false
tracks-merge-message: true
```
 in my GitVersion.yml:
``` yaml
workflow: GitHubFlow/v1
tag-prefix: '[vV]?'
update-build-number: true
strategies:
- MergeMessage
- TaggedCommit
- TrackReleaseBranches
- VersionInBranchName
- TrunkBased
merge-message-formats:
  AzureDevOps: 'Merged PR (?<PullRequestNumber>\d+) from (?<SourceBranch>[^\s]*) into (?<TargetBranch>[^\s]*)'
branches:
  main:
    regex: ^master$|^main$
    mode: ContinuousDeployment
    label: 'ci'
    is-source-branch-for:
    - feature
    - hotfix
    - release
    tracks-merge-target: false
    tracks-merge-message: true
  feature:
    regex: ^feature(s)?[/-](?<StoryNo>[A-Za-z0-9]+)?
    mode: ContinuousDelivery
    label: 'beta.{StoryNo}'
    increment: Minor
    tracks-merge-target: false
    tracks-merge-message: true
  hotfix:
    regex: ^(hot|bug)fix(es)?[/-](?<StoryNo>[#A-Za-z0-9]+)?
    mode: ContinuousDelivery
    label: 'beta.{StoryNo}'
    increment: Patch
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    label: 'alpha'
    label-number-pattern: '[/-](?<number>\d+)'
    source-branches: [ 'main' ]
  release:
    regex: ^release(s)?[/-](?<BranchName>.+)
    label: 'rc'
    is-release-branch: true
  unknown:
    increment: Inherit
    regex: (?<BranchName>.+)
ignore:
  sha: []
```
but it's still failing. Is there anything I'm missing?

**Reply by arturcic** [reply]
@HHobeck do you mind checking this one?

**Reply by HHobeck** [reply]
I would recommend to only update the property you would like to override in your configuration. You can find the base configuration at the following link:
- https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Configuration/Workflows/GitHubFlow/v1.yml

Anyway in GitHubFlow you have no hotfix branch. You need to ensure that all mandatory properties like tracks-merge-target are set on branch level or at root level (to use it as a fallback). TrunkBased version strategy is not existing anymore and has been renamed to Mainline. I'm surprised that you use the Mainline strategy with others. I would recommend to use the Mainline strategy only as following otherwise it makes no sense:

```yaml
strategies:
- Mainline
- ConfiguredNextVersion
```

**Reply by HHobeck** [reply]
I would recommend you to start with the following configuration:

```yaml
workflow: GitFlow/v1
strategies:
- Mainline
- ConfiguredNextVersion
```

GitFlow/v1:
https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Configuration/Workflows/GitFlow/v1.yml

or 

```yaml
workflow: GitHubFlow/v1
strategies:
- Mainline
- ConfiguredNextVersion
```

GitFlow/v1:
https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Configuration/Workflows/GitHubFlow/v1.yml

**Reply by DSpirit** [reply]
Thanks for your answers. With the minimal configuration:
``` yaml
workflow: GitHubFlow/v1
strategies:
- Mainline
- ConfiguredNextVersion
```
 or even with the full configuration file, I get the same error:
 `Could not build the configuration instance because following exception occurred: 'Property 'tracks-merge-target' not found on type 'GitVersion.Configuration.BranchConfiguration'.' Please ensure that the /overrideconfig parameters are correct and the configuration file is in the correct format.
` using this release candidate in my Azure DevOps Pipeline using this task:
``` yaml
- task: gitversion/execute@0
    displayName: gitversion/execute
    inputs:
      targetPath: '$(Agent.BuildDirectory)/s'
      useConfigFile: true
      configFilePath: $(Agent.BuildDirectory)/s/GitVersion.yml
      updateAssemblyInfo: true
```

**Reply by HHobeck** [reply]
I think there is a typo in the `GitHubFlow/v1` template:

- `tracks-merge-target` needs to be `track-merge-target`
- `tracks-merge-message` needs to be `track-merge-message`

**Reply by DSpirit** [reply]
Does the default template affect the run? Assuming the template is getting read as-is, the error message throws on every run as it wouldn't be able to parse the configuration.
I've created a PR to fix the typos here: https://github.com/GitTools/GitVersion/pull/4041

**Reply by HHobeck** [reply]
As a workaround for now: If you specify the workflow with an empty string value means you are not using a base template and you are configuring from scratch. Of course you need to provide the whole configuration in your file (without typo) to have the GitHubFlow up and running:

```yaml
workflow: ''
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
tag-prefix: '[vV]?'
version-in-branch-pattern: (?<version>[vV]?\d+(\.\d+)?(\.\d+)?).*
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
tag-pre-release-weight: 60000
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
semantic-version-format: Strict
strategies:
- Mainline
- ConfiguredNextVersion
...
```
