### DISCUSSION TITLE
default bump keyword

### DISCUSSION THREAD

**Discussion by dnyandeobharambe** [GitTools/GitVersion#4049] [General]
I am using following configuration and it is working fine when add keyword in commit message. But as it is mainline I want to make default bump to patch when developer forget to add keyword(+semver: patch). How I can do it?
Here is my config 

```yaml
mode: Mainline
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
commit-message-incrementing: Enabled
ignore:
  commits-before: 2024-05-20T06:00:00
branches:
   main:
    regex: ^main$  # Matches your developement branch
    tag: ''  # No tag associated with the feature branch
    source-branches: []
    prevent-increment-of-merged-branch-version: true
```

Is default is patch bump? Right now I have custom logic to check this keywords , If keyword match then only it calculate version. If I remove that logic and keep open then is every commit will considered as bump ?(unless use skip). I mean if minor or major provide then it will bump accordingly. If not then it will bump patch for no keyword? Is this correct understanding?
