### DISCUSSION TITLE
Release Branches always use Release Branch Version

### DISCUSSION THREAD

**Discussion by BenB196** [GitTools/GitVersion#4058] [Q&A]
Hi All,

I'm having an issue trying to achieve a desired outcome and I'm hoping someone knows which setting(s) need to be changed.

**Objective:**

When merging a commit into a `release` branch, the version generated for the release branch should never increment.

Example:

If I have:
- A commit on `main` that is tagged `0.2.0-alpha.1`
- A release branch named `release/0.1.0`

If I merge `main` into `release/0.1.0`, it will currently make the release branch's tag to `0.2.0-1` (this is because it adds the commit to the release branch _with_ the `0.2.0-alpha.1` tag). I don't want this, instead, I want the tag to match the release branch name, and be `0.1.0-1`, even if there is a tag in the release branch that is greater than the release branch.

**Information**

I'm using, [6.0.0-rc.1](https://github.com/GitTools/GitVersion/releases/tag/6.0.0-rc.1), the default `workflow: GitFlow/v1`, with the following configuration modifications:

```yaml
mode: ContinuousDelivery
version-in-branch-pattern: (?<version>[vV]?\\d+(\\.\\d+)?(\\.\\d+)?).*
major-version-bump-message: "(\\\+semver:\\\s?(breaking|major))"
minor-version-bump-message: "(\\\+semver:\\\s?(feature|minor))"
patch-version-bump-message: "(\\\+semver:\\\s?(fix|patch))"
no-bump-message: '\\+semver:\\s?(none|skip)'
semantic-version-format: Strict
label:
branches:
  develop: # Overwrite the default `develop` config a bit
    regex: ^master((?<BranchName>[/-].+))?$|^main((?<BranchName>[/-].+))?$|^dev(elop)?(\.(?<BranchName>[/-].+))?$
    source-branches: [ ]
    label: 'alpha'
    increment: Patch
    track-merge-target: true
    is-main-branch: true
    tracks-release-branches: true
    pre-release-weight: 0
```

What I've been unable to determine is what configuration changes need to be made to the `release` branch configuration to achieve what I'm looking for.
