### DISCUSSION TITLE
Unable to get Main branch to update WeightedPreReleaseNumber

### DISCUSSION THREAD

**Discussion by joebeernink** [GitTools/GitVersion#4062] [Q&A]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

gittools/actions

### GitVersion version

5.x

### Operating system

Windows

### What are you seeing?

In our repo, we have a Main Branch and a Release Branch. 

We do pull requests to Main, which then publishes our Android App to Google Play with test settings that point to our test environment. Once testing is complete, we then push to the Release branch, and publish to a different Android App which then points to our production environment. We also publish to Apple Store the same way, but Apple is not affected by the issue I am about to describe. The Android build process uses the WeightedPreReleaseNumber to set the required "ApplicationVersion" for the Android app, which is an integer. The "ApplicationDisplayVersion" is a completely different field in the project config, and is a semVer string.

When we update the Release branch, everything works fine. The WeightedPreReleaseNumber is updated as expected. But updating the Main branch does not update the WeightedPreReleaseNumber. The semVer string is working fine, but I cannot figure out how to get the WeightedPreReleaseNumber to update on **Main** correctly.

Here is my gitversion config file. This is for an open-source project for an environmental non-profit. The repo is here: https://github.com/TrashMob-eco/TrashMob

Any help is appreciated. All the work on this project is being done by volunteers. If the only solution to this is to completely redo our build and release process in a major way, we'd love some assistance! 

``` 
assembly-versioning-scheme: MajorMinorPatch
mode: Mainline
tag-pre-release-weight: 1590664954
continuous-delivery-fallback-tag: ''
branches:
  main:
    regex: ^main$
    tag: ''
  release:
    regex: ^release$
    increment: Patch
    tag: ''
    is-release-branch: true
    pre-release-weight: 1590664954
    source-branches: ['main']
ignore:
  sha: []
merge-message-formats: {}
```

### What is expected?

Expect the WeightedPreReleaseNumber ont he Main branch to be updated with each update of Main.

### Steps to Reproduce

See repo: https://github.com/TrashMob-eco/TrashMob
And build is here: https://github.com/TrashMob-eco/TrashMob/actions/runs/9438722752

### Output log or link to your CI build (if appropriate).

```shell
https://github.com/TrashMob-eco/TrashMob/actions/runs/9438722752
```
