### DISCUSSION TITLE
Need help with configuring gitversion (6rc1)

### DISCUSSION THREAD

**Discussion by CJCombrink** [GitTools/GitVersion#4065] [Q&A] [answered]
Hi,

We have a simple workflow based on GitHubFlow but I am struggling to configure gitversion to do what I want.

Our main branch is `development`, any merge to `development` builds a release and publishes (it is an internal library)
We tag the commit using SemVer only after the build and publish was successful. 
In most cases the minor is stepped (currently manually, in the PR) for each release.

`ContinuousDeployment` looks like what we need, but it does not respect `when-current-commit-tagged`, is this expected or misconfigured?

I have stripped almost everything from the default GitHubFlow config to get to the following file
<details>

<summary>GitVersion.yml</summary>

```
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
tag-prefix: '[vV]?'
version-in-branch-pattern: (?<version>[vV]?\d+(\.\d+)?(\.\d+)?).*
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
tag-pre-release-weight: 60000
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
semantic-version-format: Strict
strategies:
- TaggedCommit
- Fallback
- ConfiguredNextVersion
- MergeMessage
- TrackReleaseBranches
- VersionInBranchName
branches:
  development:
    label: ''
    increment: Minor
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: true
    track-merge-target: false
    track-merge-message: true
    regex: ^development$
    source-branches: []
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: true
    is-main-branch: false
    pre-release-weight: 55000
ignore:
  sha: []
mode: ContinuousDeployment
label: '{BranchName}'
increment: Inherit
prevent-increment:
  of-merged-branch: false
  when-branch-merged: false
  when-current-commit-tagged: true
track-merge-target: false
track-merge-message: true
commit-message-incrementing: Enabled
regex: ''
source-branches: []
is-source-branch-for: []
tracks-release-branches: false
is-release-branch: false
is-main-branch: true

```

</details> 

My git history
```
> git lol
* a41ecf7 (HEAD -> development, tag: 0.5.0) Got semver to work on development
| * 1e14554 (tag: v0.3.0) Got semver to work on development
|/  
| * eb6c88f (tag: v0.2.0, tag: 0.2.0) Got semver to work on development
|/  
* 6b96756 (tag: 0.1.0) Initial version file from their site
* b742b30 initial commit
```

And the output of `gitversion`
```
{
  "AssemblySemFileVer": "0.6.0.0",
  "AssemblySemVer": "0.6.0.0",
  "BranchName": "development",
  "BuildMetaData": null,
  "CommitDate": "2024-06-10",
  "CommitsSinceVersionSource": 0,
  "EscapedBranchName": "development",
  "FullBuildMetaData": "Branch.development.Sha.a41ecf7af663b74feb048856deada834ba75ce25",
  "FullSemVer": "0.6.0",
  "InformationalVersion": "0.6.0+Branch.development.Sha.a41ecf7af663b74feb048856deada834ba75ce25",
  "Major": 0,
  "MajorMinorPatch": "0.6.0",
  "Minor": 6,
  "Patch": 0,
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "SemVer": "0.6.0",
  "Sha": "a41ecf7af663b74feb048856deada834ba75ce25",
  "ShortSha": "a41ecf7",
  "UncommittedChanges": 0,
  "VersionSourceSha": "a41ecf7af663b74feb048856deada834ba75ce25",
  "WeightedPreReleaseNumber": 60000
}
```

I would expect `SemVer` to be `0.5.0` since I am on a tag, but it is not.

If this is not possible it is not a major issue, it does however mean I won't be able to rebuild a specific version if needed.

Any help or suggestions will be appreciated

**Comment by HHobeck** [comment, marked as answer]
Please keep in mind that your are inheriting from the default workflow which is in your example the `GitFlow/v1` workflow. Because you choice development instead of develop, you are not overriding but defining a second definition for the development branch:

```yml
branches:
  develop:
    regex: ^dev(elop)?(ment)?$
    ...
  development:
    regex: ^development$
    ...
  ...
```
Saying: First comes first servers.

To the `workflow` property you will find the following documentation:
> workflow
> The base template of the configuration to use. Possible values are GitFlow/v1 or GitHubFlow/v1. Defaults to GitFlow/v1 if not set. To create a configuration from scratch without using a base template, please specify an empty string.

What you want is propably to define your configuration from scratch:
```yml
workflow: ''
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
tag-prefix: '[vV]?'
version-in-branch-pattern: (?<version>[vV]?\d+(\.\d+)?(\.\d+)?).*
...
```
