### DISCUSSION TITLE
GitHub Flow with Release Branches

### DISCUSSION THREAD

**Discussion by MrHinsh** [GitTools/GitVersion#4071] [Q&A]
Im trying to configure GitVersion for "Release Flow"... Thsi is models after the Azure DevOps teams branching strategy and 

![image](https://github.com/GitTools/GitVersion/assets/5205575/0d15d84b-22b1-4b45-a5f3-098ae948c53c)

- **main/master** = this is where all work is done, and like Git Flow any topic branches are merged.
- **Release/v0.3.0** = This is created as a release and is shipped to production. 

Working on `main` (v1.0.0-preview.12) and then creating `relase/v1.0.0` should trigger `main` to then version as v1.0.1-preview.1

I can currently get `release` to work, but I cant get `main` to increment once the `release` has been created... 

**Current GitVersion.yaml**

```
assembly-versioning-scheme: MajorMinorPatchTag
mode: ContinuousDelivery
next-version: 0.2.0
branches: 
  main:
      mode: ContinuousDelivery
      tag: 'preview'
      increment: Patch
      is-mainline: true
      prevent-increment-of-merged-branch-version: false
      tracks-release-branches: true
      regex: ^master$|^main$
  release:
    mode: ContinuousDelivery
    tag: ""
    increment: Patch
    track-merge-target: false
    regex: ^release(s)?[\/-]
    source-branches:
    - master
    - main
    is-release-branch: true
    is-mainline: false
ignore:
  sha: []
merge-message-formats: {}

```

**How can I configure main to increment to release+patch when the release branch is created?**

**Comment by HHobeck** [comment]
Maybe it is quite naive. But why not just using the `GitFlow` workflow and rename the `develop` branch to `main`?

```yaml
branches:
  develop:
    regex: ^master$|^main$
  main:
    regex: ^$
```

**Reply by MrHinsh** [reply]
It's an interested idea. 

With my limited testing what I have above is doing what I want. I've just not hit the edge cases yet.

**Comment by MrHinsh** [comment]
@HHobeck as I see you are the expert I'm a little stumped...

```
assembly-versioning-scheme: MajorMinorPatchTag
mode: ContinuousDelivery
continuous-delivery-fallback-tag: ''
next-version: 0.2.0
branches: 
  main:
      mode: ContinuousDelivery
      tag: 'Preview'
      increment: Patch
      is-mainline: true
      prevent-increment-of-merged-branch-version: false
      tracks-release-branches: true
      regex: ^master$|^main$
  release:
    mode: ContinuousDelivery
    tag: ""
    increment: Patch
    track-merge-target: false
    regex: ^releases?[/-]
    source-branches:
    - master
    - main
    is-release-branch: true
    is-mainline: false
ignore:
  sha: []
merge-message-formats: {}
```

Why would a branch named `release/v1.0.2` be flagged as preview?

I was expecting it to not have a tag at all!
