### DISCUSSION TITLE
GitVersion on Azure DevOps config seems to not work as expected

### DISCUSSION THREAD

**Discussion by denis-majorsky** [GitTools/GitVersion#4073] [Q&A]
Hello Community,

Would like to kindly ask for some help here with configuration of GitVersion.yaml config.
What my concern is that once I merge PR from develop to release my tag looks for example like this 1.3.0-release.1-98 and I do not expect to have these numbers in postfix.

1.3.0-develop.676 which is fine for me
1.3.0-release.1-98 which I would expect to be 1.3.0-release.1 and last number in postfix incrementing
and for master:
1.2.3-33 which should be 1.2.3 and patch number incrementing

Can anyone explain how to achieve this ?
If more details needed just let me know 👍🏼 

Currently I have my config like this :

```
---
mode: ContinuousDelivery
branches:
  develop:
    tag: develop
    increment: Minor
  release:
    regex: release[-/](?<name>\d+\.\d+)
    tag: rc
    increment: Patch
    is-release-branch: true
    track-merge-target: false
  master:
    increment: Patch
    tag: ''
ignore:
  sha: []
merge-message-formats: {}
```

However my tags are named differently.

For develop branch:
```
{
  "Major": 1,
  "Minor": 3,
  "Patch": 0,
  "PreReleaseTag": "develop.676",
  "PreReleaseTagWithDash": "-develop.676",
  "PreReleaseLabel": "develop",
  "PreReleaseLabelWithDash": "-develop",
  "PreReleaseNumber": 676,
  "WeightedPreReleaseNumber": 676,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.develop.Sha.2eedcdfc906524ebcfde64d004e4c3570c595890",
  "MajorMinorPatch": "1.3.0",
  "SemVer": "1.3.0-develop.676",
  "LegacySemVer": "1.3.0-develop676",
  "LegacySemVerPadded": "1.3.0-develop0676",
  "AssemblySemVer": "1.3.0.0",
  "AssemblySemFileVer": "1.3.0.0",
  "FullSemVer": "1.3.0-develop.676",
  "InformationalVersion": "1.3.0-develop.676+Branch.develop.Sha.2eedcdfc906524ebcfde64d004e4c3570c595890",
  "BranchName": "develop",
  "EscapedBranchName": "develop",
  "Sha": "2eedcdfc906524ebcfde64d004e4c3570c595890",
  "ShortSha": "2eedcdf",
  "NuGetVersionV2": "1.3.0-develop0676",
  "NuGetVersion": "1.3.0-develop0676",
  "NuGetPreReleaseTagV2": "develop0676",
  "NuGetPreReleaseTag": "develop0676",
  "VersionSourceSha": "d15e673a9a8e9f823884ce53506c8ad3d6d00b71",
  "CommitsSinceVersionSource": 98,
  "CommitsSinceVersionSourcePadded": "0098",
  "UncommittedChanges": 0,
  "CommitDate": "2024-06-11"
}
```

For release branch:

```
{
  "Major": 1,
  "Minor": 3,
  "Patch": 0,
  "PreReleaseTag": "release.1",
  "PreReleaseTagWithDash": "-release.1",
  "PreReleaseLabel": "release",
  "PreReleaseLabelWithDash": "-release",
  "PreReleaseNumber": 1,
  "WeightedPreReleaseNumber": 1,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.release.Sha.c3691971a391e0c704f449b51830b4b754d9bc24",
  "MajorMinorPatch": "1.3.0",
  "SemVer": "1.3.0-release.1",
  "LegacySemVer": "1.3.0-release1",
  "LegacySemVerPadded": "1.3.0-release0001",
  "AssemblySemVer": "1.3.0.0",
  "AssemblySemFileVer": "1.3.0.0",
  "FullSemVer": "1.3.0-release.1",
  "InformationalVersion": "1.3.0-release.1+Branch.release.Sha.c3691971a391e0c704f449b51830b4b754d9bc24",
  "BranchName": "release",
  "EscapedBranchName": "release",
  "Sha": "c3691971a391e0c704f449b51830b4b754d9bc24",
  "ShortSha": "c369197",
  "NuGetVersionV2": "1.3.0-release0001",
  "NuGetVersion": "1.3.0-release0001",
  "NuGetPreReleaseTagV2": "release0001",
  "NuGetPreReleaseTag": "release0001",
  "VersionSourceSha": "c3691971a391e0c704f449b51830b4b754d9bc24",
  "CommitsSinceVersionSource": 0,
  "CommitsSinceVersionSourcePadded": "0000",
  "UncommittedChanges": 0,
  "CommitDate": "2024-06-11"`
  }
  ```
  
  For master:
  ```
  {
  "Major": 1,
  "Minor": 3,
  "Patch": 0,
  "PreReleaseTag": "27",
  "PreReleaseTagWithDash": "-27",
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "-",
  "PreReleaseNumber": 27,
  "WeightedPreReleaseNumber": 55027,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.master.Sha.82ffa9bcda8a90621e8e78bcf646535ad274e2ee",
  "MajorMinorPatch": "1.3.0",
  "SemVer": "1.3.0-27",
  "LegacySemVer": "1.3.0-27",
  "LegacySemVerPadded": "1.3.0-0027",
  "AssemblySemVer": "1.3.0.0",
  "AssemblySemFileVer": "1.3.0.0",
  "FullSemVer": "1.3.0-27",
  "InformationalVersion": "1.3.0-27+Branch.master.Sha.82ffa9bcda8a90621e8e78bcf646535ad274e2ee",
  "BranchName": "master",
  "EscapedBranchName": "master",
  "Sha": "82ffa9bcda8a90621e8e78bcf646535ad274e2ee",
  "ShortSha": "82ffa9b",
  "NuGetVersionV2": "1.3.0-0027",
  "NuGetVersion": "1.3.0-0027",
  "NuGetPreReleaseTagV2": "0027",
  "NuGetPreReleaseTag": "0027",
  "VersionSourceSha": "82ffa9bcda8a90621e8e78bcf646535ad274e2ee",
  "CommitsSinceVersionSource": 0,
  "CommitsSinceVersionSourcePadded": "0000",
  "UncommittedChanges": 0,
  "CommitDate": "2024-06-03"
}
```

**Comment by denis-majorsky** [comment]
@HHobeck  I saw that you were advising others on such configuration may I kindly ask you if possible to take a look what seems to be an issue with my configuration ?

**Reply by HHobeck** [reply]
Your configuration is targeting the current released version 5.x. I cannot make any suggestion or analysis any old configurations (in the sense of the current development) because it takes me to much time and effort. I would suggest you to use the current preview version or the upcoming preview version `6.0.0-rc.2` (@arturcic please push this) and migrate your workflow. In case you are using the new version I can probably help you.

Please see the following sequence diagrams which illustrate a bunch of use cases:
https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/learn/branching-strategies/gitflow/examples.md
https://github.com/GitTools/GitVersion/tree/main/docs/input/docs/img/

![image](https://github.com/GitTools/GitVersion/assets/56404113/fadcc35b-3d1d-4147-b44f-742d8a014f67)

Please notice: The links are broken because it will be published on a website and not shown in github.

**Reply by denis-majorsky** [reply]
Im running now on a new version but old gitversion.yaml file is not longer valid there are redundant arguments such as tags. 

I was able to get gitversion cli in version 6 but can not see the option how to display all available arguments.

ERROR [06/27/24 12:03:17:12] An unexpected error occurred:
(Line: 5, Col: 5, Idx: 54) - (Line: 5, Col: 8, Idx: 57): Property 'tag' not found on type 'GitVersion.Configuration.BranchConfiguration'.

**Reply by arturcic** [reply]
Please check the https://github.com/GitTools/GitVersion/blob/main/BREAKING_CHANGES.md#configuration-changes and the https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/reference/configuration.md

**Reply by denis-majorsky** [reply]
Thank you guys, I was able to upgrade GitVersion used by POC pipeline. and now master branch is working as expected but others not really, also there is a problem that not all properties described in branch configuration under docs mentioned below are valid parameters, during dotnet-gitversion /showconfig I can see error messages saying that some of them are not found on type 'GitVersion.Configuration.BranchConfiguration'.https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/reference/configuration.md

for instance: 
track-merge-message
is-main-branch



this is how my configuration file is defined now, however im not sure how exactly it works :

mode: ContinuousDelivery  # Default mode for the repository unless overridden by specific branch configuration

```
branches:
  main:
    regex: ^master$|^main$
    mode: ContinuousDeployment
    increment: Patch
    label: ''
    track-merge-target: false
    pre-release-weight: 55000

  develop:
    regex: ^dev(elop)?$
    mode: ContinuousDelivery
    increment: None  # No version increment on direct commits or merges, only meta-data increments
    label: 'develop'
    track-merge-target: true
    source-branches: ['feature', 'main']  # Assuming main can also directly merge back to develop

  release:
    regex: ^release[/-]
    mode: ContinuousDelivery
    increment: Patch  # Increment patch number when merging into release
    label: 'release-{version}'
    source-branches: ['develop']
    is-release-branch: true

  feature:
    regex: ^feature/.*
    mode: ContinuousDelivery
    increment: None  # Do not change the version number, only the metadata (postfix)
    label: 'feature-{BranchName}'
    source-branches: ['develop']
    is-source-branch-for: ['develop']
    track-merge-target: false

  hotfix:
    regex: ^hotfix/.*
    mode: ContinuousDeployment
    increment: Patch  # Assuming hotfixes should increment the patch version
    label: 'hotfix-{BranchName}'
    source-branches: ['main']
    is-source-branch-for: ['main']
    track-merge-target: true

  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    increment: None  # Inherit increment strategy, do not bump version for PRs
    label-number-pattern: '[/-](?<number>\d+)[/-]'
    source-branches: ['develop', 'main', 'release', 'feature', 'hotfix']
    pre-release-weight: 30000

ignore:
  sha: []

```

What I wish to achieve is that master/main branch on PR from release or hotfix to master/main branch will increment only patch.
From master to develop merge it will bring major.minor.patch from master but in develop it will be something like major.minor.patch.develop 
Than each push to develop or PR from feature branches will increment only that metadata number or how do you call that example: 1.3.1.develop.<number to increment>
When merging develop to release Im not sure what is best practice here but I would expect that also postfix number is incremented.
There is a case in which we merge release to develop. Not sure what should be the behaviour in here.
And Major.Minor numbers in master/main branch I would like to have incremented only if its specified in PR title or description or what ever works in GitVersion tool.


I've spend like 2 months on this implementation and I'm already exhausted I would really appreciate your help and if needed I could also donate something to project as a gesture of gratitude for your efforts.

**Reply by HHobeck** [reply]
Thank you very much for providing information about problems you are facing when using the documentation. If you not mind could you please create a PR for this and fix it? I'm going to help you in case you have not the knowledge about the description. This will something part of the code review.

**Reply by HHobeck** [reply]
> Thank you guys, I was able to upgrade GitVersion used by POC pipeline. and now master branch is working as expected but others not really, also there is a problem that not all properties described in branch configuration under docs mentioned below are valid parameters, during dotnet-gitversion /showconfig I can see error messages saying that some of them are not found on type 'GitVersion.Configuration.BranchConfiguration'.https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/reference/configuration.md

Please see the following comment. This will be fixed in 6.0.0-rc.2:
https://github.com/GitTools/GitVersion/discussions/4039#discussioncomment-9543794

The problem with `is-main-branch` is not know to me. What do you mean?

**Reply by denis-majorsky** [reply]
> Thank you very much for providing information about problems you are facing when using the documentation. If you not mind could you please create a PR for this and fix it? I'm going to help you in case you have not the knowledge about the description. This will something part of the code review.

Yes sure why not I can create PR, but I woud appreciate some guidence from your side if possible. Im not that familiar with this project.

**Reply by denis-majorsky** [reply]
> > Thank you guys, I was able to upgrade GitVersion used by POC pipeline. and now master branch is working as expected but others not really, also there is a problem that not all properties described in branch configuration under docs mentioned below are valid parameters, during dotnet-gitversion /showconfig I can see error messages saying that some of them are not found on type 'GitVersion.Configuration.BranchConfiguration'.https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/reference/configuration.md
> 
> 
> 
> Please see the following comment. This will be fixed in 6.0.0-rc.2:
> 
> https://github.com/GitTools/GitVersion/discussions/4039#discussioncomment-9543794
> 
> 
> 
> The problem with `is-main-branch` is not know to me. What do you mean?

is-main-branch is not recognized as a parameter. When It's defined anywhere in configuration I get same error. not found on type 'GitVersion.Configuration.BranchConfiguration'.https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/reference/configuration.md

I would like to know if there will be som significant change in a project because I meed this for my clients production workflow in case there will be some change I would need to ajdust around 30 pipelines.

**Reply by HHobeck** [reply]
> is-main-branch is not recognized as a parameter. When It's defined anywhere in configuration I get same error. not found on type 'GitVersion.Configuration.BranchConfiguration'.https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/reference/configuration.md

Can you please provide the error message and the steps to reproduce. I don't see any reasons why this property would be not recognized. see https://github.com/GitTools/GitVersion/blob/4886101d48a52b8dd533636f09e521449535578d/src/GitVersion.Configuration/BranchConfiguration.cs#L78

Which version are you using?

**Reply by denis-majorsky** [reply]
The error message on this I can see when using dotnet-gitversion /showconfig
I'm using 6.0.0-alpha.1+Branch.main.Sha.fc5b3ff045ea0e0f59c9bf27096af9094ca17f0e dotnet-gitversion on MacOS.

Now I tired to do dotnet-gitversion init and when this generated the configuration file I get exactly the same error as before but for other parameter which is source-branches. Is there any chance to reach you somewhere else than here in this thread ? If yes please write me on info@denismajorsky.sk thanks alot .

**Reply by denis-majorsky** [reply]
> The error message on this I can see when using dotnet-gitversion /showconfig I'm using 6.0.0-alpha.1+Branch.main.Sha.fc5b3ff045ea0e0f59c9bf27096af9094ca17f0e dotnet-gitversion on MacOS.
> 
> Now I tired to do dotnet-gitversion init and when this generated the configuration file I get exactly the same error as before but for other parameter which is source-branches. Is there any chance to reach you somewhere else than here in this thread ? If yes please write me on [info@denismajorsky.sk](mailto:info@denismajorsky.sk) thanks alot .

Seems that the init mixed up old config with new configuration. so issue with source-branch is solved now.

**Comment by HHobeck** [comment]
For me it is very hard to understand your custom workflow. Normally it would be good to start with the `GitFlow` or `GitHubFlow` workflow (by defining the workflow property respectively) and change only minor configuration settings. Anyway you need to isolate your problems and put it in smaller parts.

If I see your configuration you are not defining your workflow from scratch but inheriting from the `GitFlow` workflow. This is because of backwards compatible reasons. Was this intended? If not you need to write: `workflow: ''`

If you take e.g. the following sequence diagram:
https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/img/DocumentationSamplesForGitFlow_DevelopBranch.png

What would be your expectation and why?

Edit: The configuration base template for the `GitFlow` workflow is documented in the configuration.md or can be viewed as following:
https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/workflows/GitFlow/v1.yml

**Reply by denis-majorsky** [reply]
Im even more confused now. What is the difference between GitFlow and workflow ? Based on a picture release branch is deleted in some point but we persist the release branch. I don't know how to explain this whole to you is there any chance we can have a quick meeting online ?

**Reply by denis-majorsky** [reply]
```
mode: ContinuousDelivery
branches:
  main:
    mode: ContinuousDeployment
    label: ''
    increment: Minor
    track-merge-target: false
    regex: ^master$|^main$
    pre-release-weight: 55000

  develop:
    mode: ContinuousDelivery
    label: develop
    increment: None
    track-merge-target: true
    regex: ^dev(elop)?$
    source-branches:
      - feature
      - release
      - main

  release:
    mode: ContinuousDelivery
    label: rc
    increment: Inherit
    regex: ^release[/-]
    source-branches:
      - develop
      - bugfix
    is-release-branch: true

  feature:
    mode: ContinuousDelivery
    label: feature-{BranchName}
    increment: None
    track-merge-target: false
    regex: ^feature/.*
    source-branches:
      - develop
    is-source-branch-for:
      - develop

  hotfix:
    mode: ContinuousDeployment
    label: hotfix-{BranchName}
    increment: Patch
    track-merge-target: true
    regex: ^hotfix/.*
    source-branches:
      - main
    is-source-branch-for:
      - main

  bugfix:
    mode: ContinuousDelivery
    label: bugfix-{BranchName}
    increment: Patch
    track-merge-target: true
    regex: ^bugfix/.*
    source-branches:
      - release
    is-source-branch-for:
      - release

  pull-request:
    mode: ContinuousDelivery
    increment: None
    label-number-pattern: '[/-](?<number>\d+)[/-]'
    regex: ^(pull|pull\-requests|pr)[/-]
    source-branches:
      - develop
      - main
      - release
      - feature
      - hotfix
    pre-release-weight: 30000
ignore:
  sha: []
```

This is how I have it at the moment. and to explain we have 3 branches develop release and master. we push features first in develop than we merge develop to release during codefreeze than if fix is needed we push it to release and at the end we merge release to master which is production branch in master we push only bugfix if needed. 

this is what I expect to do it : 

develop = 1.0.0-develop
feature/some-feature -- merge--to--develop --> 1.0.0-develop.1
feature/some-other-feature -- merge--to--develop --> 1.0.0develop.2
.... and so on ...

1.0.0develop.2 --merge--to--release --> 1.0.0release1
bugfix/some-bugfix --merge--to--release --> 1.0.0release1-1
bugfix/some-other-bugfix --merge--to--release --> 1.0.0release1-2

soft release/
1.0.0release1-2 --merge--to--develop --> 1.1.0 ???

1.0.0release1-2 --merge--to--master --> 1.1.0

master to develop
1.1.0 --merge--to--develop --> 1.1.0develop1

develop to release
1.1.0develop1 --merge--to--release -->  1.1.0release1

release to master
1.1.0release1 --merge--to--master --> 1.2.0

and in case I push hotfix to master than patch is incremented not major thats the expectation. Hopefully I explained
