### DISCUSSION TITLE
6.0.0

### DISCUSSION THREAD

**Discussion by arturcic** [GitTools/GitVersion#4108] [Announcements]
6.0.0

<hr /><em>This discussion was created from the release <a href='https://github.com/GitTools/GitVersion/releases/tag/6.0.0'>6.0.0</a>.</em>

**Comment by fmotas** [comment]
Hey @arturcic, I'm having some issues replacing "tag" with "label".
When I replace it, the label value is not being used as the tag used to, have you tested it using labels?

**Reply by arturcic** [reply]
Please check https://github.com/GitTools/GitVersion/blob/main/BREAKING_CHANGES.md

**Reply by fmotas** [reply]
Hey @arturcic thanks for answering so quickly! 

According to the breaking changes doc, if my config was:
```
develop:
    regex: ^dev(elop)?(ment)?$
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false   
```

I need to update it to:
```
  develop:
    regex: ^dev(elop)?(ment)?$
    mode: ContinuousDeployment
    label: alpha
    increment: Minor
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false    
```

Is it correct? if so, we have a problem, it doesn't work correctly because the tag/label is not attached to the version.
The result of the updated version is:
```
{
  "AssemblySemFileVer": "1.0.0.0",
  "AssemblySemVer": "1.0.0.0",
  "BranchName": "develop",
  "BuildMetaData": null,
  "CommitDate": "2024-07-23",
  "CommitsSinceVersionSource": 12,
  "EscapedBranchName": "develop",
  "FullBuildMetaData": "Branch.develop.Sha.aa8e111b1745de89097e8af9b982d08137336230",
  "FullSemVer": "1.0.0",
  "InformationalVersion": "1.0.0+Branch.develop.Sha.aa8e111b1745de89097e8af9b982d08137336230",
  "Major": 1,
  "MajorMinorPatch": "1.0.0",
  "Minor": 0,
  "Patch": 0,
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "SemVer": "1.0.0",
  "Sha": "aa8e111b1745de89097e8af9b982d08137336230",
  "ShortSha": "aa8e111",
  "UncommittedChanges": 1,
  "VersionSourceSha": "",
  "WeightedPreReleaseNumber": 60000
}
```

While the result of the previous version was:
```
{
  "Major": 1,
  "Minor": 0,
  "Patch": 0,
  "PreReleaseTag": "alpha.11",
  "PreReleaseTagWithDash": "-alpha.11",
  "PreReleaseLabel": "alpha",
  "PreReleaseLabelWithDash": "-alpha",
  "PreReleaseNumber": 11,
  "WeightedPreReleaseNumber": 11,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.develop.Sha.aa8e111b1745de89097e8af9b982d08137336230",
  "MajorMinorPatch": "1.0.0",
  "SemVer": "1.0.0-alpha.11",
  "LegacySemVer": "1.0.0-alpha11",
  "LegacySemVerPadded": "1.0.0-alpha0011",
  "AssemblySemVer": "1.0.0.0",
  "AssemblySemFileVer": "1.0.0.0",
  "FullSemVer": "1.0.0-alpha.11",
  "InformationalVersion": "1.0.0-alpha.11+Branch.develop.Sha.aa8e111b1745de89097e8af9b982d08137336230",
  "BranchName": "develop",
  "EscapedBranchName": "develop",
  "Sha": "aa8e111b1745de89097e8af9b982d08137336230",
  "ShortSha": "aa8e111",
  "NuGetVersionV2": "1.0.0-alpha0011",
  "NuGetVersion": "1.0.0-alpha0011",
  "NuGetPreReleaseTagV2": "alpha0011",
  "NuGetPreReleaseTag": "alpha0011",
  "VersionSourceSha": "2781208128072f47b9394dc7832217a195af6ff9",
  "CommitsSinceVersionSource": 11,
  "CommitsSinceVersionSourcePadded": "0011",
  "UncommittedChanges": 1,
  "CommitDate": "2024-07-23"
}
```
