### DISCUSSION TITLE
The label property is not considered when using ContinuousDeployment

### DISCUSSION THREAD

**Discussion by HHobeck** [GitTools/GitVersion#4109] [Q&A] [answered]
Originally ask by @fmotas:

According to the breaking changes doc, if my config was:
```
develop:
    regex: ^dev(elop)?(ment)?$
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false   
```

I need to update it to:
```
  develop:
    regex: ^dev(elop)?(ment)?$
    mode: ContinuousDeployment
    label: alpha
    increment: Minor
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false    
```

Is it correct? if so, we have a problem, it doesn't work correctly because the tag/label is not attached to the version.
The result of the updated version is:
```
{
  "AssemblySemFileVer": "1.0.0.0",
  "AssemblySemVer": "1.0.0.0",
  "BranchName": "develop",
  "BuildMetaData": null,
  "CommitDate": "2024-07-23",
  "CommitsSinceVersionSource": 12,
  "EscapedBranchName": "develop",
  "FullBuildMetaData": "Branch.develop.Sha.aa8e111b1745de89097e8af9b982d08137336230",
  "FullSemVer": "1.0.0",
  "InformationalVersion": "1.0.0+Branch.develop.Sha.aa8e111b1745de89097e8af9b982d08137336230",
  "Major": 1,
  "MajorMinorPatch": "1.0.0",
  "Minor": 0,
  "Patch": 0,
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "SemVer": "1.0.0",
  "Sha": "aa8e111b1745de89097e8af9b982d08137336230",
  "ShortSha": "aa8e111",
  "UncommittedChanges": 1,
  "VersionSourceSha": "",
  "WeightedPreReleaseNumber": 60000
}
```

While the result of the previous version was:
```
{
  "Major": 1,
  "Minor": 0,
  "Patch": 0,
  "PreReleaseTag": "alpha.11",
  "PreReleaseTagWithDash": "-alpha.11",
  "PreReleaseLabel": "alpha",
  "PreReleaseLabelWithDash": "-alpha",
  "PreReleaseNumber": 11,
  "WeightedPreReleaseNumber": 11,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.develop.Sha.aa8e111b1745de89097e8af9b982d08137336230",
  "MajorMinorPatch": "1.0.0",
  "SemVer": "1.0.0-alpha.11",
  "LegacySemVer": "1.0.0-alpha11",
  "LegacySemVerPadded": "1.0.0-alpha0011",
  "AssemblySemVer": "1.0.0.0",
  "AssemblySemFileVer": "1.0.0.0",
  "FullSemVer": "1.0.0-alpha.11",
  "InformationalVersion": "1.0.0-alpha.11+Branch.develop.Sha.aa8e111b1745de89097e8af9b982d08137336230",
  "BranchName": "develop",
  "EscapedBranchName": "develop",
  "Sha": "aa8e111b1745de89097e8af9b982d08137336230",
  "ShortSha": "aa8e111",
  "NuGetVersionV2": "1.0.0-alpha0011",
  "NuGetVersion": "1.0.0-alpha0011",
  "NuGetPreReleaseTagV2": "alpha0011",
  "NuGetPreReleaseTag": "alpha0011",
  "VersionSourceSha": "2781208128072f47b9394dc7832217a195af6ff9",
  "CommitsSinceVersionSource": 11,
  "CommitsSinceVersionSourcePadded": "0011",
  "UncommittedChanges": 1,
  "CommitDate": "2024-07-23"
}
```

**Comment by HHobeck** [comment, marked as answer]
The meaning of ContinuousDeployment has been changed in version 6.0.0. You will find the following section in the breaking change documentation:

> The versioning mode has been renamed to deployment mode and consists of following values:
> 
> ManualDeployment (previously ContinuousDelivery)
> ContinuousDelivery (previously ContinuousDeployment)
> ContinuousDeployment (new)

I would recommend you to use the GitFlow/v1 workflow and change just the properties you are aware of:

```yaml
workflow: GitFlow/v1
branches:
  develop:
    label: alpha
```

Reference [1]: https://github.com/GitTools/GitVersion/blob/main/docs/input/docs/reference/configuration.md#global-configuration
Reference [2]: https://gitversion.net/docs/learn/branching-strategies/gitflow/examples
Reference [3]: https://github.com/GitTools/GitVersion/blob/main/BREAKING_CHANGES.md
