### DISCUSSION TITLE
GitVersion 6.0.0 taking much longer than 5.12.0 to calculate version

### DISCUSSION THREAD

**Discussion by Cheesebaron** [GitTools/GitVersion#4112] [Q&A]
I have a repo where we've been running GitVersion forever and haven't had issues with it up until now.

It seems like switching to 6.0.0 the time to calculate version went from 57 seconds in CI to around 14 minutes.

We are using the GitVersion.Tool to run.

The config we have in place in 5.12.0 looks like this:

```yml
branches:
  release:
    regex: ^release[/]
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
  hotfix:
    regex: ^hotfix[/]
    mode: ContinuousDeployment
    tag: ''
    is-release-branch: true
    track-merge-target: false
    tracks-release-branches: false
    increment: Patch
  feature:
    source-branches: [ 'develop', 'main', 'release', 'feature', 'support', 'hotfix', 'epic' ]
  epic:
    regex: ^epic[/]
    mode: ContinuousDelivery
    tag: '{BranchName}'
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches: [ 'develop', 'main', 'release', 'feature', 'support', 'hotfix', 'epic' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  develop:
    tag: ci
```

I tried converting it to 6.0.0 and ended up with this. Which took 43 minutes on my local machine:

```yml
workflow: GitFlow/v1
branches:
  release:
    label: ''
    source-branches: [ 'develop', 'main', 'release' ]
  hotfix:
    label: ''
    source-branches: [ 'develop', 'main', 'release' ]
  feature:
    source-branches: [ 'develop', 'release', 'feature', 'support', 'hotfix', 'epic' ]
  epic:
    mode: ManualDeployment
    label: '{BranchName}'
    increment: Inherit
    prevent-increment:
      when-current-commit-tagged: false
    track-merge-message: true
    regex: ^epics?[/-](?<BranchName>.+)
    source-branches: [ 'develop', 'epic' ]
    is-source-branch-for: []
    is-main-branch: false
    pre-release-weight: 30000
  develop:
    label: ci

```

Then simply removed most of it and ended up with a config like this which takes 2 minutes to complete on my machine. Which is still significantly longer than the older version and it takes around 14 minutes in CI which I really don't want to wait for. The config for this looks like:

```yml
workflow: GitFlow/v1
branches:
  release:
    label: ''
  hotfix:
    label: ''
  develop:
    label: ci
```

I've tried to run with diagnostics enabled, but it doesn't really help me to pinpoint what is increasing the.

Can someone maybe help with where to look at what is causing these performance issues?

**Comment by HHobeck** [comment]
I think the best thing you can do is to play around with the `strategies `property and find out if the performance issue is related to a specific strategy implementation or related to how the branch configuration are determined.

**Reply by Cheesebaron** [reply]
Doesn't appear to me that changing the strategies takes effect. Tried with:

```yml
strategies:
- Fallback
```

Shouldn't this just directly fall back and give the version `0.1.0`?

I tried this with and without specifying workflow.

**Reply by HHobeck** [reply]
What do you mean it doesn't take effect!? Does it still take 15 minutes? Please test it with `ConfiguredNextVersion`.

```yaml
workflow: GitFlow/v1
NextVersion: 1.0.0
strategies:
- ConfiguredNextVersion
```

> Shouldn't this just directly fall back and give the version 0.1.0?

All version calculation classes are implementing the interface `IVersionStrategy` and can be controlled by the `strategies` property.

**Reply by Cheesebaron** [reply]
Yeah that doesn't work, getting this error in the log:

```
Could not build the configuration instance because following exception occurred: 'Property 'NextVersion' not found on type 'GitVersion.Configuration.GitVersionConfiguration'.' Please ensure that the /overrideconfig parameters are correct and the configuration file is in the correct format.
```

When I have only the Fallback strategy present, it takes 14 minutes locally and seems to be running all the strategies and not just fallback. This is the same if I for instance only specify TaggedCommit.

**Reply by HHobeck** [reply]
What about `next-version`? ;)

**Reply by HHobeck** [reply]
Try this:
```yaml
workflow: ''
next-version: 4.5.6
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
tag-prefix: '[vV]?'
version-in-branch-pattern: (?<version>[vV]?\d+(\.\d+)?(\.\d+)?).*
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
tag-pre-release-weight: 60000
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
semantic-version-format: Strict
strategies:
- ConfiguredNextVersion
branches:
  develop:
    mode: ContinuousDelivery
    label: alpha
    increment: Minor
    prevent-increment:
      when-current-commit-tagged: false
    track-merge-target: true
    track-merge-message: true
    regex: ^dev(elop)?(ment)?$
    source-branches:
    - main
    is-source-branch-for: []
    tracks-release-branches: true
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 0
  main:
    label: ''
    increment: Patch
    prevent-increment:
      of-merged-branch: true
    track-merge-target: false
    track-merge-message: true
    regex: ^master$|^main$
    source-branches: []
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: true
    pre-release-weight: 55000
  release:
    mode: ManualDeployment
    label: beta
    increment: Minor
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: false
    track-merge-target: false
    regex: ^releases?[/-](?<BranchName>.+)
    source-branches:
    - main
    - support
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: true
    is-main-branch: false
    pre-release-weight: 30000
  feature:
    mode: ManualDeployment
    label: '{BranchName}'
    increment: Inherit
    prevent-increment:
      when-current-commit-tagged: false
    track-merge-message: true
    regex: ^features?[/-](?<BranchName>.+)
    source-branches:
    - develop
    - main
    - release
    - support
    - hotfix
    is-source-branch-for: []
    is-main-branch: false
    pre-release-weight: 30000
  pull-request:
    mode: ContinuousDelivery
    label: PullRequest
    increment: Inherit
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: false
    label-number-pattern: '[/-](?<number>\d+)'
    track-merge-message: true
    regex: ^(pull|pull\-requests|pr)[/-]
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    is-source-branch-for: []
    pre-release-weight: 30000
  hotfix:
    mode: ManualDeployment
    label: beta
    increment: Inherit
    prevent-increment:
      when-current-commit-tagged: false
    regex: ^hotfix(es)?[/-](?<BranchName>.+)
    source-branches:
    - main
    - support
    is-source-branch-for: []
    is-release-branch: true
    is-main-branch: false
    pre-release-weight: 30000
  support:
    label: ''
    increment: Patch
    prevent-increment:
      of-merged-branch: true
    track-merge-target: false
    regex: ^support[/-](?<BranchName>.+)
    source-branches:
    - main
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: true
    pre-release-weight: 55000
  unknown:
    mode: ManualDeployment
    label: '{BranchName}'
    increment: Inherit
    prevent-increment:
      when-current-commit-tagged: true
    regex: (?<BranchName>.+)
    source-branches:
    - main
    - develop
    - release
    - feature
    - pull-request
    - hotfix
    - support
    is-source-branch-for: []
    is-main-branch: false
ignore:
  sha: []
mode: ContinuousDelivery
label: '{BranchName}'
increment: Inherit
prevent-increment:
  of-merged-branch: false
  when-branch-merged: false
  when-current-commit-tagged: true
track-merge-target: false
track-merge-message: true
commit-message-incrementing: Enabled
regex: ''
source-branches: []
is-source-branch-for: []
tracks-release-branches: false
is-release-branch: false
is-main-branch: false
```
