### DISCUSSION TITLE
How to get MM.mm from branch name

### DISCUSSION THREAD

**Discussion by CJCombrink** [GitTools/GitVersion#4161] [Q&A] [answered]
Hi, I am trying to get the version from my branch name for the `release` branch.
It works as expected when my branch is called `release/1.2.3` but if I only want to specify the Major and Minor versions the version is not extracted from the branch name, instead it uses the 'normal' behaviour

GitVersion: `6.0.1+Branch.main.Sha.0fd23d1af997a7b7c6f22f27310443270a91fb18`

<details>
<summary>GitVersion.yml</summary>

```
workflow: GitHubFlow/v1
branches:
  main:
    increment: Patch
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: true
    regex: ^development$
    is-release-branch: true
    is-main-branch: false
  release:
    mode: ContinuousDeployment
    prevent-increment:
      of-merged-branch: true
      when-branch-merged: false
      when-current-commit-tagged: true
    track-merge-target: false
    track-merge-message: false
    is-release-branch: true
    is-main-branch: true
  feature:
    mode: ContinuousDelivery
    label: alpha
    source-branches:
    - main
  pull-request:
    mode: ContinuousDelivery
    label: pre
    source-branches:
    - main
    - release
    - feature
mode: ContinuousDeployment
is-main-branch: true
```

</details>

I have specifically not specified `version-in-branch-pattern` since by just reading the regex it seems like it should work as-is

I expect this to work (my expectation might be wrong)
```
$ git rev-parse --abbrev-ref HEAD
release/1.2
$ gitversion /v SemVer
0.9.1
```

This works
```
$ git rev-parse --abbrev-ref HEAD
release/1.2.3
$ gitversion /v SemVer
1.2.3
```

My commit history looks something like this
```
* 6c0a65b (HEAD -> release/1.2, release/1.2.3) test
*   7c4d1a4 (tag: 0.9.0, origin/development, origin/HEAD, development) Pull request #197: ...
*
```

Any help will be appreciated

**Comment by HHobeck** [comment, marked as answer]
Have you tried the following configuration property?

```yaml
semantic-version-format: Loose
```

**Reply by CJCombrink** [reply]
Hi @HHobeck 

This has the interesting side effect that my `pull-request` section behaves not as I want.

When I set `semantic-version-format: Loose` for my pull-request settings it now takes the PR number as the major version.
This is my current pull-request config
```
  pull-request:
    mode: ContinuousDelivery
    label: pre
    regex: ^PR-
```

Perhaps I need to modify the `label-number-pattern` (which is not specified thus uses the default) or my `regex`


```
$ git rev-parse --abbrev-ref HEAD
PR-202
$ gitversion /v SemVer
202.0.0-pre202.4
```
