### DISCUSSION TITLE
Can't get feature branch to version correctly

### DISCUSSION THREAD

**Discussion by leorg99** [GitTools/GitVersion#4163] [Q&A]
I am trying configure a simple workflow where I only have master and feature branches.
I want to do the following:
- Continuous deployment on master branch with 'pre' tag.
- Continuous deployment on feature branch with 'alpha' tag.
- On master -> new feature branch, increment patch, reset pre-release counter. (2.0.2-pre00005 -> 2.0.3-alpha00001)
- On feature merge -> master, reset pre-release counter, start using 'pre' tag. (2.0.3-alpha00008 -> 2.0.3-pre00001)
- Increment patch version on new feature branches (master: 2.0.2, new branch -> 2.0.3)

In GitHub, I am using a manual workflow to trigger a release build without the 'pre' tag.

Here is what I have: 

```
mode: ContinuousDeployment
branches:
  main:
    tag:
  develop:
    # Match nothing
    regex: ^\b$
  feature:
    # Match everything except master/main
    regex: ^(?!master$|main$).*$
    tag: alpha
    increment: Patch
    source-branches:
      - 'main'
  release:
    # Match nothing
    regex: ^\b$
  pull-request:
    # Match nothing
    regex: ^\b$
  hotfix:
    # Match nothing
    regex: ^\b$
  support:
    # Match nothing
    regex: ^\b$
ignore:
  sha: []
```

This is not doing what I want.
- It doesn't increment the patch on new feature branch.
- It doesn't reset the pre-release counter on new feature branches.

Thanks!
