### DISCUSSION TITLE
How to use `/output buildserver` in GitLab CI

### DISCUSSION THREAD

**Discussion by David-Hari** [GitTools/GitVersion#4164] [Q&A]
The doco says that it will "write out the variables to whatever build server it is running in".
For GitLab CI [with PowerShell](https://docs.gitlab.com/ee/ci/variables/index.html#with-powershell), I thought I would be able to access the variables either like `$GitVersion_SemVer` or as an environment variable like `$env:GitVersion_SemVer`.

However, neither of those work. When I print all environment variables with [`dir env:`](https://docs.gitlab.com/ee/ci/variables/index.html#list-all-variables) I don't see any of the GitVersion ones.

I am running the CI stage in a docker image, and that image has GitVersion installed using choco. Since I found that variables are not preserved from one stage to another, I had to run GitVersion in the same stage as it is used. e.g.:
```
script:
  - gitversion /output buildserver
  - mvn install -Drevision=$GitVersion_SemVer
```

Any idea why that still isn't working?

**Comment by AlphaYankee** [comment]
The variables are getting written to `gitversion.properties`. You should be able to use that as a dotenv to push it to the other steps, but GitLab has a limit on the number of variables you can have in there. So what I do is take only the variables I need and write them into a new env file.

Example:
```
GitVersion:
    stage: Prepare
    image: gitversion:6.0.2-alpine.3.18-8.0
    variables:
        GIT_STRATEGY: fetch
        GIT_DEPTH: 0
    cache: []
    script:
        - |
          /tools/dotnet-gitversion /output buildserver
          grep 'GitVersion_MajorMinorPatch=' gitversion.properties >> version.env
          grep 'GitVersion_FullSemVer='      gitversion.properties >> version.env
          grep 'GitVersion_AssemblySemVer='  gitversion.properties >> version.env
    artifacts:
        reports:
            dotenv: version.env
```

You could then use those three variables in the next steps.
