### DISCUSSION TITLE
Config for a workflow with a single, reused release branch?

### DISCUSSION THREAD

**Discussion by BartSchuurmans** [GitTools/GitVersion#4168] [Q&A]
A project I joined uses the following git workflow:
- New feature branches are branched off from `develop` and merged into `develop` when ready. Each push to `develop` triggers a deployment to a test environment.
- When it's time to prepare a release, the `develop` branch is merged into the `release` branch (note: this is the same branch for every release), which triggers a deployment to a staging environment.
- When the staging deployment is OK, `release` is merged into `main`, which triggers a deployment to the production environment.

I currently use this GitVersion config:
```yaml
workflow: GitFlow/v1
branches:
  develop:
    label: beta
    mode: ContinuousDelivery
  release:
    label: rc
    mode: ContinuousDelivery
    regex: ^release$
  main:
    mode: ContinuousDeployment
```

This seems to kind of accidentally work, but what I would actually like is the following:
- When I merge from `develop` to `release`, the version from `develop` gets transferred to `release` (completely ignoring any earlier tags on `release`) except it is turned from a beta release (`v1.2.3-beta.34`) into an rc release (`v1.2.3-rc.1`)
- I would like the prerelease number to start from 1 for each new version number on the `release` branch
- When I merge from `release` to `main`, I want the version number from the `release` branch (`v1.2.3-rc.4`) to be transferred to the `main` branch (`v1.2.3`)

Is this possible with GitVersion?
