### DISCUSSION TITLE
`GitVersion` does not append the label + pull-request number on PRs

### DISCUSSION THREAD

**Discussion by IT-VBFK** [GitTools/GitVersion#4181] [Q&A] [answered]
Hi

With v5 we had a `GitVersion.yml` config for PRs which looked like this:

```yml
pull-request:
    mode: ContinuousDeployment
    regex: ((pull|pull\-requests|pr)[/-]|[/-](merge))
    tag: pr
    tag-number-pattern: '[/-]?(?<number>\d+)'
    prevent-increment-of-merged-branch-version: false
```

To be clear: we have a small routine in our build that generates this version like: `1.2.3-[pr number].[build number]`

This produces the following version (e.g. from build pipeline output):

```
Branch spec refs/pull/2733/merge is a pull request. Adding build number 3437
SemVer = 6.13.0-pr2733.3437
```

So, the version generated by gitversion was 6.13.0-pr.2733

With v6 we now have the following issue:

First, fix the yaml for v6 to

```yml
pull-request:
    mode: ContinuousDeployment
    regex: ((pull|pull\-requests|pr)[/-]|[/-](merge))
    label: pr
    label-number-pattern: '[/-]?(?<number>\d+)'
    prevent-increment:
      of-merged-branch: false
```

Now, the version generated from `GitVersion` is (also from build output):

```
SemVer before: 7.0.0
Branch spec refs/pull/1/merge is a pull request. Adding build number 562
SemVer = 7.0.562
``` 

SemVer should be: `7.0.0-pr1.562` in this case

So, there is no `-pr.[pr number]` label generated.

I'm pretty sure this is a misconfiguration, but cannot find it.

Help is really appreciated.

Thank you
