### DISCUSSION TITLE
Does GitVersion 6 still support the logic to step minor on feature/XX and path on bugfix/xx branches?

### DISCUSSION THREAD

**Discussion by CJCombrink** [GitTools/GitVersion#4217] [Q&A] [answered]
This is very much related to this feature: #1221 
The last screenshot in that discussion is almost exactly what I want

My current config is rather basic, using `GitHubFlow/v1` and `ContinuousDeployment` on my main branch.
I want `increment` to be based on the last branch that was merged, so that `feature/xx` branches step the minor and `bugfix/xx` step the patch.
I also want to control this using the messages if possible (probably for major versions)

I tried searching the net but can only find answers for GitVersion < 6

<details>
<summary>This is my current configuration</summary>

````
workflow: GitHubFlow/v1
tag-prefix: ''
version-in-branch-pattern: (?<version>[vV]?\d+(\.\d+)?(\.\d+)?).*
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
semantic-version-format: Strict
branches:
  main:
    mode: ContinuousDeployment
    increment: Minor
    prevent-increment:
      when-current-commit-tagged: true
    regex: ^development$
    is-release-branch: true
  release:
    mode: ContinuousDeployment
    prevent-increment:
      when-current-commit-tagged: true
    track-merge-message: true
    is-release-branch: true
  feature:
    mode: ContinuousDelivery
    label: alpha
    regex: ^feature/(?<BranchName>.+)
  pull-request:
    mode: ContinuousDelivery
    label: pre
    regex: ^PR-
mode: ContinuousDeployment
is-main-branch: true
````
</details>

The issue with `increment: Minor` in main is that I can never use a message to just step the patch due to the logic discussed [here](https://github.com/GitTools/GitVersion/discussions/3933#discussioncomment-8600888)
And setting it to `Increment: Patch` would require that one almost always ad the `+semver: minor` to commit messages, defeating the use of GitVersion since we need patches very seldom, and we already use the branch names to differentiate. 

Any help will be appreciated
