### DISCUSSION TITLE
PR is not calculating patch based on inherit prop

### DISCUSSION THREAD

**Discussion by facusantillo** [GitTools/GitVersion#4227] [Q&A]
This is the following scenario, and I'm not sure if this is correct or it's a bug.

I have a Main branch with tag 1.2.0

I create from that tag a release branch: release/1.2.0

I create a hotfix branch from the release branch: hotfix/1.2.0_fixes

At this point, I have 3 branches and 1 tag.

I commit to the hotfix branch and create a PR targeting the release branch. The version should be calculated as 1.2.1-prXXXXX.XX but the version is being calculated as 1.3.0-prXXXXX.XX

```
Main (1.2.0 Tag)
   |
   v
release/1.2.0
   |
   v
hotfix/1.2.0_fixes
   |
   v
PR: hotfix -> release
```

Here is my yaml:

```
mode: ManualDeployment
commit-message-incrementing: Enabled
strategies:
- Fallback
- MergeMessage
- TaggedCommit

branches:
  main:
    mode: ManualDeployment 
    label: 'rev'
    increment: Minor
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: true
    track-merge-target: true
    track-merge-message: true
    regex: ^main$|^master$
    source-branches: []
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: true
    pre-release-weight: 60000

  develop:
    mode: ManualDeployment
    label: 'rev'
    increment: Minor
    prevent-increment:
      when-current-commit-tagged: false
    track-merge-target: true
    track-merge-message: true
    regex: ^develop$
    source-branches: []
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 60000

  release:
    mode: ManualDeployment
    label: 'rev'
    increment: Patch
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: false
    track-merge-target: true
    regex: ^releas(e|es)?[/-]
    source-branches: []
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: true
    is-main-branch: false
    pre-release-weight: 30000

  feature:
    mode: ContinuousDelivery
    label: '{BranchName}'
    increment: Inherit
    prevent-increment:
      when-current-commit-tagged: false
    track-merge-target: true
    track-merge-message: true
    regex: ^features?[/-](?<BranchName>.+)
    source-branches:
    - feature
    - hotfix
    - develop
    - main
    - release
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 30000

  pull-request:
    mode: ContinuousDelivery
    label: 'pr'
    increment: Inherit
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: false
    label-number-pattern: '[/-](?<number>\d+)'
    track-merge-target: true
    track-merge-message: true
    regex: ^pull?
    source-branches:
    - develop
    - main
    - release
    - feature
    - hotfix
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 30000

  hotfix:
    mode: ContinuousDelivery
    label: '{BranchName}'
    increment: Patch
    prevent-increment:
      when-current-commit-tagged: false
    track-merge-target: true
    regex: ^hotfix(es)?[/-]
    source-branches:
    - main
    - develop
    - release
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 30000

ignore:
  sha: []
```

Thanks!

**Comment by HHobeck** [comment]
So you have multiple branches which can be used for inheriting. In your case it is:
- a hotfix branch with patch increment
- a release branch with patch increment and
- a main branch with minor increment

GitVersion calculates for all branches (it can inherit from) the version number and uses the highest number.

```yaml
branches:
  pull-request:
    increment: Inherit
    source-branches:
    - develop
    - main
    - release
    - feature
    - hotfix
...
```

Hope that makes sense.

**Reply by HHobeck** [reply]
> So you have multiple branches which can be used for inheriting. In your case it is:
> 
> * a hotfix branch with patch increment
> * a release branch with patch increment and
> * a main branch with minor increment
> 
> GitVersion calculates for all branches (it can inherit from) the version number and uses the highest number.
> 
> ```yaml
> branches:
>   pull-request:
>     increment: Inherit
>     source-branches:
>     - develop
>     - main
>     - release
>     - feature
>     - hotfix
> ...
> ```
> 
> Hope that makes sense.

Of course you could argue that it is not really detecting the inheritance structure like in your graphic:

```
Main (1.2.0 Tag)
   |
   v
release/1.2.0
   |
   v
hotfix/1.2.0_fixes
   |
   v
PR: hotfix -> release
```

I think the problem is the way how commits and branches are represented in git. If you find a way how to workaround this, I'm happy to hear your solution.

**Reply by facusantillo** [reply]
From my perspective, what I'm mainly interested in from the pull-request standpoint is how the next version will look compared to a given branch, specifically the target branch.

If I'm working in a release branch that's configured for a patch, showing a minor version bump wouldn’t make sense. When merging that specific pull request, I expect the pull request to reflect how the next version bump would occur.

I'm not sure how we can work around it, and I'm not sure to fully understand how inheritance property works...

**Reply by HHobeck** [reply]
The algorithm works like I sayed. GitVersion detects the source branches based on the actual branch:

![image](https://github.com/user-attachments/assets/3fa40b06-a439-4655-a21f-bbcf9faba056)
https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/VersionCalculation/EffectiveBranchConfigurationFinder.cs#L37

![image](https://github.com/user-attachments/assets/f9e95af9-cfab-48db-bed8-9d9c6e6ae56c)
https://github.com/GitTools/GitVersion/blob/main/src/GitVersion.Core/Core/RepositoryStore.cs#L116

Please try to improve the algorithm. Because we have a lot of tests for the existing use cases, you can focus on your scenario and see if it breaks something else.

**Reply by facusantillo** [reply]
I'll give it a shot. Shouldn't be taking into consideration the track-merge-target prop and if it's set to true just use that branch as the source?

**Reply by HHobeck** [reply]
The `track-merge-target` property is not used for inheritance. It is used to detect the tag on merged commits. Normally you would use the `source-branches` property for this. Please notice the algorithm is recursive.

**Reply by facusantillo** [reply]
I have tested and like you said, if I configure the yaml to only take into consideration the release branch, then the version is calculated accordingly.

As soon as I throw in there the main branch, the PR grabs the higher available version.

I think the PR only should take into consideration the target branch. In which scenarios should it focus on the higher version? 

The easiest way it's to add a flag here to just support this use case, by default would be disabled but for those like me that need to focus only on the target version would be enough.

**Reply by HHobeck** [reply]
> In which scenarios should it focus on the higher version?

I'm confused!! I haven't understood your proposal. GitVersion takes always the highest version available. What do you mean with it would be enough to focus only on the target version?

Generally new properties should be only introduced if we have new features. I don't see any new features here but improvements.

**Reply by facusantillo** [reply]
I'm saying that when you are in a PR, the CI tool of your choice (in our case Azure DevOps) should only take into consideration the version configuration inherited from the target branch (since you are only calculating how the version would be if that PR is merged in that specific branch).

If you are targeting Main and the rules are minor, then should be Minor

If you are targeting a release branch and it's a patch, then it should be a Patch.

Bumping to a Minor in a PR when the target branch is Release just because we are recursively looking at every branch would cause a wrong version calculation since you are working in a hotfix, not in a feature.

This used to work in v5 like that when using Continuous Deployment Mode.

Since v6 this behaviour changed. 

I'm saying, if this is how the algorithm works from now on, at least we should have a property like "use-target-branch-only" so the PRs just take the inherited configuration for the target branch, and not break the PR process that we have going on.

**Reply by HHobeck** [reply]
Let's take your example:
```csharp
    [Test]
    public void __Just_A_Test__()
    {
        var configuration = GitFlowConfigurationBuilder.New
            .WithBranch("main", _ => _.WithIncrement(IncrementStrategy.Minor))
            .WithBranch("release", _ => _.WithIncrement(IncrementStrategy.Patch))
            .WithBranch("hotfix", _ => _.WithIncrement(IncrementStrategy.Patch))
            .Build();

        using var fixture = new EmptyRepositoryFixture();

        fixture.MakeACommit();
        fixture.ApplyTag("1.2.0");

        // ✅ succeeds as expected
        fixture.AssertFullSemver("1.2.0", configuration);

        fixture.BranchTo("release/1.2.0");
        fixture.BranchTo("hotfix/1.2.0_fixes");
        fixture.MakeACommit("A");

        // ✅ succeeds as expected
        fixture.AssertFullSemver("1.2.1-beta.1+1", configuration);

        fixture.Checkout("release/1.2.0");
        fixture.BranchTo("pull/5/merge");
        fixture.MergeNoFF("hotfix/1.2.0_fixes");

        // ❔ expected: "1.2.1-PullRequest5.2"
        fixture.AssertFullSemver("1.3.0-PullRequest5.2", configuration);
    }
```

This is the resulting structure in git:
![image](https://github.com/user-attachments/assets/2898b1ed-5d5a-4cb6-a415-db0312feaa80)

If we skip the hotfix branch for a moment: How would you make the decision wheither you branched from main or from release?

**Reply by facusantillo** [reply]
That's why I asked how the target branch is being tracked. I thought that we were persisting somehow, the target branch on a PR, and from there we inherited based on the regex the configuration.

**Reply by HHobeck** [reply]
> That's why I asked how the target branch is being tracked. I thought that we were persisting somehow, the target branch on a PR, and from there we inherited based on the regex the configuration.

No we don't have/use the information of the target branch. We only have the structure of git available after the normalization process.

**Reply by HHobeck** [reply]
Can you give some background information how to determine the target branch?

This question needs to be answered for the following build agents:
- AppVeyor
- Azure
- BitBucket
- BuildKite
- CodeBuild
- ContinuaCI
- Drone
- EnvRun
- GitHubActions
- GitLabCi
- Jenkins
- MyGet
- SpaceAutomation
- TeamCity
- TravisCI

**Reply by HHobeck** [reply]
Maybe related to this:
- #3020

**Reply by facusantillo** [reply]
Yup, it's exactly my issue.

I strongly agree with this statement: 

> In other words, when I open a PR against Master, I want to increase the minor part
> When I open a PR against a support branch, I want to increase the patch part

This should be the expected behavior since some of us generate alphas within the PRs in our dev process, so whenever there is a PR, we deploy the version in our test environment. 

If I'm expecting a version to be 1.2.1-alpha.1 and it's a 1.3.0-alpha.1, it's a huge difference, because I don't know if what I'm grabbing from that CI pipeline is a feature or the hotfix. This is important, especially in large dev teams.

**Reply by HHobeck** [reply]
I'm not sure if we have here two problems. In the ticket #3020 was mentioned that the remot branch will be not detected but in your case it is even reproducable locally.

Anyway, if I come back to this figure:
![image](https://github.com/user-attachments/assets/2898b1ed-5d5a-4cb6-a415-db0312feaa80)

From the gitversion point of view this repository state is ambiguous. How would you detect the target branch?

**Reply by HHobeck** [reply]
Would be nice if we fix both issues.

**Reply by facusantillo** [reply]
Not sure about it because it would depend on how each CI tool works, but the funny thing is, I have pipelines working with the 6.0.0-beta.2 version and it's working as expected, not sure what changed there, I'll share here my configuration and logs on that pipeline maybe there is a hint there...

[log.txt](https://github.com/user-attachments/files/17144121/log.txt)


YAML

```
mode: ContinuousDelivery
commit-message-incrementing: enabled

branches:

  main:
    mode: ContinuousDelivery
    label: 'rev'
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    regex: ^main$|^master$
    source-branches: []
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 60000

  develop:
    mode: ContinuousDelivery
    label: 'rev'
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    regex: ^develop$
    source-branches: []
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 60000

  release:
    mode: ContinuousDelivery
    label: 'rev'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^releas(e|es)?[/-]
    source-branches:
      - develop
      - main
      - hotfix
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 30000

  feature:
    mode: ContinuousDeployment
    label: useBranchName
    #increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: ^featur(e|es)?[/-]
    source-branches:
      - feature
      - hotfix
      - develop
      - main
      - release
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000

  hotfix:
    mode: ContinuousDelivery
    label: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: ^hotfix(es)?[/-]
    source-branches:
      - main
      - develop
      - release
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000

  pull-request:
    mode: ContinuousDeployment
    label: 'pr'
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^pull?
    source-branches:
      - develop
      - main
      - release
      - feature
      - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000

ignore:
  sha: []
merge-message-formats: {}
```
