### DISCUSSION TITLE
GitVersion does not calculate the next version correctly

### DISCUSSION THREAD

**Discussion by ChristiansAntrago** [GitTools/GitVersion#4243] [Q&A] [answered]
**Prerequisites**

- [x]  I have written a descriptive issue title
- [x]  I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

**GitVersion version**
5.12.0

**What are you seeing?**

Hello Everybody! I am using GitVersion for the first time and I would like to increment the version of my main branch (named dev) with every merge commit from feature branches. Feature branches and the dev branch are the only branches I use and I only need to update the version in the dev (main) branch. GitVersion is used in an Azure Pipeline to calculate the new version and then the pipeline stores this generated version in a Directory.Build.props file, creates a new tag and pushes the change and the new tag to the repository on the dev branch. But currently always the Minor version gets incremented  by 1 and I don't understand why. My current GitVersion.yaml looks like this ( I also attached an image because i was not able to format the file correctly with the Code tag):

``mode: Mainline
increment: none
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-,/\\\\]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-,/\\\\]*\\))?:"
patch-version-bump-message: "^(fix|perf|revert|docs|chore|test)(\\([\\w\\s-,/\\\\]*\\))?:"
no-bump-message: "^(skip|none)(\\([\\w\\s-,/\\\\]*\\))?:"
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
increment: None
branches:
  main:
    mode: Mainline
    tag: ''
    increment: None
    commit-message-incrementing: Enabled
    prevent-increment-of-merged-branch-version: true
    prevent-increment-of-merged-branch: true
    prevent-increment-when-branch-merged: true
    track-merge-target: false
    regex: dev
    source-branches: []
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    is-main-branch: true
    pre-release-weight: 0
label: '{BranchName}'``

![gitversion_file](https://github.com/user-attachments/assets/68b3c843-8798-4e60-8450-ca0509deec3a)

And my commit history looks like this:
![commit_history](https://github.com/user-attachments/assets/6f6e840b-b4b0-45b1-aabc-5e24e379081c)

**What is expected?**
Only the Patch version is incremented with the help of the commit messages. Am I doing something wrong or is there something I did not fully understand when working with GitVersion?

Thanks and Best Regards
Christian

**Comment by HHobeck** [comment]
Is there a specific reason why you're not using the latest version?

**Reply by ChristiansAntrago** [reply, marked as answer]
The reason was that I wasn't aware of version 6 of GitVersion. I upgraded it and the issue still remained. But I found a solution: the problem was that the built in configuration for "develop" was always applied because it is internally the first configuration that is processed and it matched the name of my "main" branch called dev. So I changed the GitVersion.yml like this and then it worked:

```
major-version-bump-message: "(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-,/\\\\]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "(feat)(\\([\\w\\s-,/\\\\]*\\))?:"
patch-version-bump-message: "(fix|perf|revert|docs|chore|test)(\\([\\w\\s-,/\\\\]*\\))?:"
no-bump-message: "(skip|none)(\\([\\w\\s-,/\\\\]*\\))?:"
strategies:
  - Mainline
branches:
  develop:
    mode: ManualDeployment
    commit-message-incrementing: Enabled
    increment: None
    track-merge-message: false
```

Thanks and Best Regards
Christian
