### DISCUSSION TITLE
Help needed for understanding Gitversion properly

### DISCUSSION THREAD

**Discussion by nishanthcheruku** [GitTools/GitVersion#4254] [Q&A]
Hey Everybody,

I wanted to implement versioning for my projects and somehow I am lost in implementing this GitVersion. 

I have below GitVersion.yml and when I try to merge my PR I can see bump in patch version. What if I want to bump major/minor number? I am committing with message "BREAKING CHANGE: " but I still see that patch version is changed with no effect on major.

```
mode: Mainline
assembly-versioning-scheme: Major
assembly-file-versioning-scheme: MajorMinorPatch
branches: {}
ignore:
  sha: []
merge-message-formats: {}
```

In documentation, I also see mode: ManualDeployment. Is this different from Mainline.

I also tried experimenting "Continuous Delivery" and "Continuous Deployment" with naming the branch names like "Feature Branch" but nothing is working. Can you help in understanding the starting steps so that I can take it further. Though i read the documentation multiple times I failed to understand it thoroughly. 

I also tried with below config:

```
mode: Mainline
branches:
  master:
    increment: Patch
  feature/*:
    increment: Major
    regex: ^feature\/.*
    source-branches: ['master']
  release/*:
    increment: Major
    regex: ^release\/.*
    source-branches: ['master']
  hotfix/*:
    increment: Patch
    regex: ^hotfix\/.*
    source-branches: ['master']
```
when I create feature branch with "feature/" and when I run dotnet-gitversion, I can see bump in major version. However after merge I see only patch version is changing

**Comment by HHobeck** [comment]
The Mainline mode is not supported in version 6. Please try the `TrunkBased/preview1` workflow instead (experimental usage only).

- [Configuration](https://gitversion.net/docs/reference/configuration)

This is the configurated regex to detect bump messages:
```yml
major-version-bump-message: \+semver:\s?(breaking|major)
minor-version-bump-message: \+semver:\s?(feature|minor)
patch-version-bump-message: \+semver:\s?(fix|patch)
```

Generally we cannot helping out with custom workflows. But if you want you can engage me or other person to help you and build custom workflows.

Thank you for your understanding.
