### DISCUSSION TITLE
##[error]Overwriting readonly variable 'GitVersion.Major' is not permitted

### DISCUSSION THREAD

**Discussion by blablas** [GitTools/GitVersion#4322] [Q&A]
Hello all,
maybe I'm doing something wrong but, apparently out of the blue, my azure devops pipeline starts failing on this job (task gitversion/execute@3):

```
jobs:
  - job: GitVersion
    displayName: 'GitVersion job'  

    pool:
      name: IT015PRD-BUILD
  
    steps:
    - checkout: self
      fetchDepth: 0
      clean: true
      persistCredentials: true

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'  # .NET 8.x version
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: gitversion/setup@3
      name: gitVersionSetup
      displayName: Gitversion Setup  
      inputs:
        versionSpec: '6.x'
        preferLatestVersion: false

    - task: gitversion/execute@3
      name: gitVersion
      displayName: Gitversion Execute  
      inputs:
        disableCache: false
        disableNormalization: true
        disableShallowCloneCheck: true
        useConfigFile: true
        configFilePath: './GitVersion.yml'
        updateAssemblyInfo: false
```
        
The errors reported are as follow:
```
##[error]Unable to process command '##vso[task.setvariable variable=GitVersion.Major]0' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Overwriting readonly variable 'GitVersion.Major' is not permitted. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md for details.
... 
```
and keeps going for every GitVersion variable, all marked as readonly.
The weird thing is that until yesterday everything was working smoothly (and I haven't change anything in the pipeline code)

I'm using Gitversion: 6.0.5 and my gitversion.yml is reported below:
```
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
tag-prefix: '[vV]?'
version-in-branch-pattern: (?<version>[vV]?\d+(\.\d+)?(\.\d+)?).*
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
tag-pre-release-weight: 60000
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
semantic-version-format: Strict
strategies:
- Fallback
- ConfiguredNextVersion
- MergeMessage
- TaggedCommit
- TrackReleaseBranches
- VersionInBranchName
branches:
  main:
    label: ''
    increment: Patch
    prevent-increment:
      of-merged-branch: true   
    track-merge-target: false   
    track-merge-message: true
    regex: ^master$|^main$
    source-branches: []
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: true
    pre-release-weight: 55000
  release:
    mode: ManualDeployment
    label: beta
    increment: Patch
    prevent-increment:      
      of-merged-branch: true      
      when-branch-merged: false      
      when-current-commit-tagged: false        
    track-merge-target: false    
    track-merge-message: true
    regex: ^releases?[/-](?<BranchName>.+)
    source-branches:
    - main
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: true
    is-main-branch: false
    pre-release-weight: 30000
  feature:
    mode: ManualDeployment
    label: '{BranchName}'
    increment: Inherit
    prevent-increment:      
      when-current-commit-tagged: false    
    track-merge-message: true
    regex: ^features?[/-](?<BranchName>.+)
    source-branches:
    - main
    - release
    is-source-branch-for: []
    is-main-branch: false
    pre-release-weight: 30000
  pull-request:
    mode: ContinuousDelivery
    label: PullRequest
    increment: Inherit
    prevent-increment:      
      of-merged-branch: true      
      when-current-commit-tagged: false
    label-number-pattern: '[/-](?<number>\d+)'
    track-merge-message: true
    regex: ^(pull|pull\-requests|pr)[/-]
    source-branches:
    - main
    - release
    - feature
    is-source-branch-for: []
    pre-release-weight: 30000
  unknown:
    mode: ManualDeployment
    label: '{BranchName}'
    increment: Inherit
    prevent-increment:      
      when-current-commit-tagged: false    
    track-merge-message: false
    regex: (?<BranchName>.+)
    source-branches:
    - main
    - release
    - feature
    - pull-request
    is-source-branch-for: []
    is-main-branch: false
ignore:
  sha: []
mode: ContinuousDelivery
label: '{BranchName}'
increment: Inherit
prevent-increment:
  of-merged-branch: false
  when-branch-merged: false
  when-current-commit-tagged: true
tagged as 1.0.0'
track-merge-target: false
track-merge-message: true
commit-message-incrementing: Enabled
regex: ''
source-branches: []
is-source-branch-for: []
tracks-release-branches: false
is-release-branch: false
is-main-branch: false
```
Any help would be really appreciated

Thanks
