### DISCUSSION TITLE
How to increment version from commit/merge message ONLY?

### DISCUSSION THREAD

**Discussion by v1ferrarij** [GitTools/GitVersion#4338] [Q&A]
Hello,

I am looking to use GitVersion to version our modules.

I basically only want GitVersion to bump the version depending on the LAST COMMIT/MERGE message.

For example, when we merge a PR, the default message will contain the branch name ```Merged PR 54: feature/example```

All I want Gitversion to do is read this and then increment the version, in the example above the next version would be `0.1.0`

I currently have this setup but it is not performing as expected.

```yaml
mode: ContinuousDeployment
increment: Inherit
major-version-bump-message: '(major|breaking)[\/\\]'
minor-version-bump-message: '(minor|feature)[\/\\]'
patch-version-bump-message: '(fix|patch)[\/\\]'
commit-message-incrementing: MergeMessageOnly
branches: {}
```
How can this be done, is it even possible?

Many Thanks!

**Comment by HHobeck** [comment]
For this you need to use the mainline version strategy which is included in the `TrunkBased/preview1` workflow:

```yaml
workflow: TrunkBased/preview1
mode: ContinuousDeployment
major-version-bump-message: '(major|breaking)[\/\\]'
minor-version-bump-message: '(minor|feature)[\/\\]'
patch-version-bump-message: '(fix|patch)[\/\\]'
commit-message-incrementing: MergeMessageOnly
branches:
  main:
    increment: None
```

Link[1]:
https://gitversion.net/docs/reference/configuration#snippet-/docs/workflows/TrunkBased/preview1.yml
