### DISCUSSION TITLE
Version incrementing is not working

### DISCUSSION THREAD

**Discussion by KarishmaPatniLCI** [GitTools/GitVersion#4353] [Q&A]
I am using GitVersion tool v6.0.5 with below GitVersion.yml configuration:

```
mode: ContinuousDelivery

branches:
  main:
    label: ''
    increment: None # Main holds already deployed code, no automatic increment
    is-release-branch: false
  release:
    label: rc
    increment: Minor # Default increment for release branch if no commit message is found
    is-release-branch: true
  dev:
    label: alpha
    regex: ^dev$
    increment: Patch # Default increment for development work
    is-release-branch: false

commit-message-incrementing: Enabled # Enable commit message-driven versioning
next-version: 1.0.0 # Define the starting version if it's the first setup

```

and below is the GitHubWorkflow action to generate version and tag:

```
name: Generate Version Tag
on:
  workflow_dispatch
jobs:
  generate-tag:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Install GitVersion
        shell: powershell
        run: |
          if (!(Get-Command "dotnet-gitversion" -ErrorAction SilentlyContinue)) {
              Write-Host "GitVersion is not installed, installing..."
              dotnet tool install --global GitVersion.Tool
          } else {
              Write-Host "GitVersion is already installed."
          }

      - name: Generate version and push tag
        shell: powershell
        run: |
            $gitVersionOutput = dotnet-gitversion /config GitVersion.yml /output json     
            $version = ($gitVersionOutput | ConvertFrom-Json).AssemblySemVer
            $username = "${{ github.actor }}"  
            git tag -a "v$version" -m "Version $version created by $username"
            git push origin "v$version"
```

With this above configuration, I am running GitHub workflow action to generate the version but its always incrementing only the "PreReleaseNumber" like below even though the commit message contains +semver: major or +semver: minor

1.0.0-alpha.271
1.0.0-alpha.272
1.0.0-alpha.273

Also, tried with both mode: ContinuousDelivery and mode: ContinousDeployment, but it is not working as expected based on the commit message or GitVersion.yml configuration.

It was working until December 11th with the same configuration as above. Version increment was based on commit messages first and if it does not find any proper commit message then fall back to GitVersion.yml config.

Has anything changed? Please suggest if I am missing anything here. Thanks!
