### DISCUSSION TITLE
Commit message incrementing precedence

### DISCUSSION THREAD

**Discussion by joeshadbolt** [GitTools/GitVersion#4372] [Q&A] [answered]
Hello,

We have been using GitVersion for a while, for what mostly resembles a trunk based branching strategy, using Azure pipelines and making use of the GitTools ADO extension.

Now we are attempting to do 2 things; upgrade to version 6 (been running 5.12) and make some small improvements to our configuration.

We are observing some behaviour and aren't quite sure if this is expected behaviour or not and so would like some input.

Given the below GitVersion configuration, noting the main branch has a default increment of `Minor`, when the merge commit from a PR contains `+semver: patch` the version increment is still minor. We appear to only be able to successfully influence the version increment via commit message when using `+semver: major` otherwise the branch increment seems to take precedence.

Note - this is not the entire config for brevity.
```
...
major-version-bump-message: \+semver:\s?(breaking|major)
minor-version-bump-message: \+semver:\s?(feature|minor)
patch-version-bump-message: \+semver:\s?(fix|patch)
strategies:
  - ConfiguredNextVersion
  - TaggedCommit
  - Mainline
branches:
  main:
    mode: ContinuousDeployment
    label: ''
    increment: Minor
    prevent-increment:
      of-merged-branch: false
    track-merge-target: false
    track-merge-message: true
    regex: ^master$|^main$
    source-branches: []
    is-source-branch-for: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: true
    pre-release-weight: 55000
    ...
``` 

Is this as per design? Is there a way we can override for desired behaviour?

Thanks!
