### DISCUSSION TITLE
Cannot get GitVersion to populate Env. Vars. in localbuild, C#, VS2022

### DISCUSSION THREAD

**Discussion by HerbertScroggins** [GitTools/GitVersion#4398] [Q&A]
I've tried to setup GitVersion for a WinForms app in C# using VS2022.  Everything appears to be correct from what I can tell - I can tell GitVersion on the box is producing the json, I've tried with simple, complex and no gitversion.yml files in various locations, I get no errors that I can find but simply don't get the environment variables populated at the end of the ""BeforeBuild" target in the project file.

I've searched high and low for an answer but can't find anyone with the same issue.  I've asked on SO but haven't had any replies.  I've even resorted to both CoPilot and Gemini (I'm desperate!) but nothing seems to work so here I am.

One of the many GitVersion.yml files I've tried...

```
mode: ContinuousDeployment
branches:
  features:
    regex: ^features[/-]
    label: 'alpha'
    increment: Patch
  develop:
    regex: ^develop$  
    label: 'beta'
    increment: Patch
  main:
    regex: ^main$  
    label: ''
    increment: Minor
  release:
    regex: ^release[/-]
    label: ''
    increment: Minor
ignore:
  sha: []
merge-message-formats: {}
```

The output from `dotnet gitversion /output json`...

```
{
  "AssemblySemFileVer": "8.0.0.0",
  "AssemblySemVer": "8.0.0.0",
  "BranchName": "develop",
  "BuildMetaData": null,
  "CommitDate": "2025-01-08",
  "CommitsSinceVersionSource": 177,
  "EscapedBranchName": "develop",
  "FullBuildMetaData": "Branch.develop.Sha.815d23fe8922aa33c4b6b1d82b3132a6fcd73c72",
  "FullSemVer": "8.0.0-beta.177",
  "InformationalVersion": "8.0.0-beta.177+Branch.develop.Sha.815d23fe8922aa33c4b6b1d82b3132a6fcd73c72",
  "Major": 8,
  "MajorMinorPatch": "8.0.0",
  "Minor": 0,
  "Patch": 0,
  "PreReleaseLabel": "beta",
  "PreReleaseLabelWithDash": "-beta",
  "PreReleaseNumber": 177,
  "PreReleaseTag": "beta.177",
  "PreReleaseTagWithDash": "-beta.177",
  "SemVer": "8.0.0-beta.177",
  "Sha": "815d23fe8922aa33c4b6b1d82b3132a6fcd73c72",
  "ShortSha": "815d23f",
  "UncommittedChanges": 0,
  "VersionSourceSha": "",
  "WeightedPreReleaseNumber": 177
}
```

The only version I can get in the EXE is...

```
File Version: 8.0.0.0
Product Version: 8.0.0+<git commit hash>
```

I've put a step into the project file to log out the environment variables and the result are blank...

```
Target LogGitVersionVariables:
8>  Task "Message"
8>    GitVersion_FullSemVer:
8>  Done executing task "Message".
8>  Task "Message"
8>    GitVersion_AssemblySemVer:
8>  Done executing task "Message".
8>  Task "Message"
8>    GitVersion_AssemblySemFileVer:
8>  Done executing task "Message".
8>  Task "Message"
8>    GitVersion_InformationalVersion:
8>  Done executing task "Message".
```

Can anyone please point out the (undoubtedly basic and obvious!) error I'm making please, I really cannot think what else to try.

Thanks heaps.
