### DISCUSSION TITLE
Confused with PreReleaseNumber that is always set to 1

### DISCUSSION THREAD

**Discussion by smietanka** [GitTools/GitVersion#4422] [Q&A] [answered]
Hey, I am struggling with GitVersion right now. I have this scenario.
I have a build which is generating a Nuget packages.
For main/master branch I want to use MajorMinorPatch versioning schema for these nugets
For feature or other branches I have to generate also proper version for nugets to not have conflicts.

For previous versions (we have updated GitVersion) there was NugetVersionV2 property which was totally good for me. Right now it is not existing

I would like to use "GitVersion.FullSemVer" property, to not complicate other developers (there are about 30 different repos for now that are using GitVersion) but by some reason, all the time I am getting PreReleaseNumber set to `1` which is also included in FullSemVer.

I tried multiple different modes for each branch, but still I got PreReleaseNumber set to 1.
This is my configuration file (Yes now the mode its ManualDeployemtn, but I checked it with ContinuousDeployment and ContinuousDelivery as well but the same result)
I have a strategy `Mainline` to have a specific version on each commit, without this I still get the same version even if there is a new commit.

```
update-build-number: true
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
major-version-bump-message: \+semver:\s?(breaking|major)
minor-version-bump-message: \+semver:\s?(feature|minor)
patch-version-bump-message: \+semver:\s?(fix|patch)

strategies:
- Mainline

branches:
  master:
    mode: ManualDeployment
    increment: Patch
    label: ''
    regex: ^master$|^main$
    source-branches: []
    is-main-branch: true
    is-release-branch: false
  feature:
    mode: ManualDeployment
    increment: Patch
    regex: ^feature?[/-](?<BranchName>.+)
    label: '{BranchName}'
    source-branches: ['main']
    is-release-branch: false
```
This is how my output looks like:
```
{
  "AssemblySemFileVer": "1.0.16.0",
  "AssemblySemVer": "1.0.16.0",
  "BranchName": "master",
  "BuildMetaData": null,
  "CommitDate": "2025-02-18",
  "CommitsSinceVersionSource": 1,
  "EscapedBranchName": "master",
  "FullBuildMetaData": "Branch.master.Sha.8c5592f3931fcacc8b221060ed2c301b7f3a01e8",
  "FullSemVer": "1.0.16-1",
  "InformationalVersion": "1.0.16-1+Branch.master.Sha.8c5592f3931fcacc8b221060ed2c301b7f3a01e8",
  "Major": 1,
  "MajorMinorPatch": "1.0.16",
  "Minor": 0,
  "Patch": 16,
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": 1,
  "PreReleaseTag": "1",
  "PreReleaseTagWithDash": "-1",
  "SemVer": "1.0.16-1",
  "Sha": "8c5592f3931fcacc8b221060ed2c301b7f3a01e8",
  "ShortSha": "8c5592f",
  "UncommittedChanges": 0,
  "VersionSourceSha": "4cd859762878afadb8535b0b6c6c3ea0a2ccae9f",
  "WeightedPreReleaseNumber": 55001
}
```

So again,
for master/main build I could use GitVersion.MajorMinorPatch but this force me to add some `if-else` conditions in azure-pipeline.yaml. I would like to avoid this. Just always use a single property, but again, still PreReleaseNumber is set to 1 which is included in SemVer/FullSemVer which I would like to use in the step of  `dotnet pack` in build. Any help?
