### DISCUSSION TITLE
'System.ArgumentOutOfRangeException' was thrown. (Parameter 'strategy') Actual value was Inherit

### DISCUSSION THREAD

**Discussion by mrt181** [GitTools/GitVersion#4427] [Q&A] [answered]
I am trying to build a commit that has tag `0.88.3-1` on the main branch.

This is the error in the github action
```
 #11 18.95     INFO [25-02-20 16:02:59:61] The branch 'origin/main' has a matching commit.
#11 18.95   INFO [25-02-20 16:02:59:62] -< End: Getting branches containing the commit 'a311d72'. (Took: 371.07ms) >-
#11 18.95   INFO [25-02-20 16:02:59:63] Getting tagged semantic versions. TagPrefix: [vV]? and Format: Strict
#11 18.95   INFO [25-02-20 16:03:00:68] Running against branch: (no branch) ('a311d72' - build: upgrade GitVersion.MsBuild)
#11 18.95   INFO [25-02-20 16:03:00:70] -< Begin: Fetching the base versions for version calculation... >-
#11 18.95     INFO [25-02-20 16:03:00:74] -< Begin: Finding branches source of '(no branch)' >-
#11 18.95       INFO [25-02-20 16:03:00:76] -< Begin: Finding merge base between '(no branch)' and 'origin/feat/cache'. >-
#11 18.95         INFO [25-02-20 16:03:00:78] Found merge base of ''4c07305' - style: added formatter for compose files'
#11 18.95         INFO [25-02-20 16:03:00:78] Merge base of '(no branch)' and 'origin/feat/cache' is ''4c07305' - style: added formatter for compose files'
#11 18.95       INFO [25-02-20 16:03:00:78] -< End: Finding merge base between '(no branch)' and 'origin/feat/cache'. (Took: 20.78ms) >-
#11 18.95       INFO [25-02-20 16:03:00:78] -< Begin: Finding merge base between '(no branch)' and 'origin/feat/check-malformed-infra-data'. >-
#11 18.95         INFO [25-02-20 16:03:00:78] Found merge base of ''a90b442' - feat: set default value when an enum is set to null in infra'
#11 18.95         INFO [25-02-20 16:03:00:79] Merge base of '(no branch)' and 'origin/feat/check-malformed-infra-data' is ''a90b442' - feat: set default value when an enum is set to null in infra'
#11 18.95       INFO [25-02-20 16:03:00:79] -< End: Finding merge base between '(no branch)' and 'origin/feat/check-malformed-infra-data'. (Took: 9.74ms) >-
#11 18.95       INFO [25-02-20 16:03:00:79] -< Begin: Finding merge base between '(no branch)' and 'origin/feat/compose'. >-
#11 18.95         INFO [25-02-20 16:03:00:79] Found merge base of ''4c07305' - style: added formatter for compose files'
#11 18.95         INFO [25-02-20 16:03:00:79] Merge base of '(no branch)' and 'origin/feat/compose' is ''4c07305' - style: added formatter for compose files'
#11 18.95       INFO [25-02-20 16:03:00:79] -< End: Finding merge base between '(no branch)' and 'origin/feat/compose'. (Took: 0.85ms) >-
#11 18.95       INFO [25-02-20 16:03:00:79] -< Begin: Finding merge base between '(no branch)' and 'origin/feat/schema-registry'. >-
#11 18.95         INFO [25-02-20 16:03:00:79] Found merge base of ''4c07305' - style: added formatter for compose files'
#11 18.95         INFO [25-02-20 16:03:00:79] Merge base of '(no branch)' and 'origin/feat/schema-registry' is ''4c07305' - style: added formatter for compose files'
#11 18.95       INFO [25-02-20 16:03:00:79] -< End: Finding merge base between '(no branch)' and 'origin/feat/schema-registry'. (Took: 1.51ms) >-
#11 18.95       INFO [25-02-20 16:03:00:79] -< Begin: Finding merge base between '(no branch)' and 'origin/main'. >-
#11 18.95         INFO [25-02-20 16:03:00:79] Found merge base of ''a311d72' - build: upgrade GitVersion.MsBuild'
#11 18.95         INFO [25-02-20 16:03:00:79] Merge base of '(no branch)' and 'origin/main' is ''a311d72' - build: upgrade GitVersion.MsBuild'
#11 18.95       INFO [25-02-20 16:03:00:79] -< End: Finding merge base between '(no branch)' and 'origin/main'. (Took: 0.21ms) >-
#11 18.95       INFO [25-02-20 16:03:00:79] -< Begin: Finding merge base between '(no branch)' and 'origin/release/0.64'. >-
#11 18.95         INFO [25-02-20 16:03:00:79] Found merge base of ''783974f' - fix: dont use infinity'
#11 18.95         INFO [25-02-20 16:03:00:80] Merge base of '(no branch)' and 'origin/release/0.64' is ''783974f' - fix: dont use infinity'
#11 18.95       INFO [25-02-20 16:03:00:80] -< End: Finding merge base between '(no branch)' and 'origin/release/0.64'. (Took: 2.52ms) >-
#11 18.95     INFO [25-02-20 16:03:00:80] -< End: Finding branches source of '(no branch)' (Took: 64.74ms) >-
#11 18.95     INFO [25-02-20 16:03:00:90] -< Begin: Calculating base versions for 'origin/main' >-
#11 18.95       INFO [25-02-20 16:03:00:90] -< Begin: [Using 'ConfiguredNextVersionVersionStrategy' strategy] >-
#11 18.95       INFO [25-02-20 16:03:00:91] -< End: [Using 'ConfiguredNextVersionVersionStrategy' strategy] (Took: 1.04ms) >-
#11 18.95       INFO [25-02-20 16:03:00:91] -< Begin: [Using 'MainlineVersionStrategy' strategy] >-
#11 18.95         INFO [25-02-20 16:03:00:92] -< Begin: Getting tagged semantic versions on branch '(no branch)'. TagPrefix: [vV]? and Format: Strict >-
#11 18.95         INFO [25-02-20 16:03:00:92] -< End: Getting tagged semantic versions on branch '(no branch)'. TagPrefix: [vV]? and Format: Strict (Took: 4.43ms) >-
#11 18.95         INFO [25-02-20 16:03:00:93] -< Begin: Getting tagged semantic versions on branch 'refs/remotes/origin/main'. TagPrefix: [vV]? and Format: Strict >-
#11 18.95         INFO [25-02-20 16:03:00:95] -< End: Getting tagged semantic versions on branch 'refs/remotes/origin/main'. TagPrefix: [vV]? and Format: Strict (Took: 18.42ms) >-
#11 18.95       INFO [25-02-20 16:03:02:67] -< End: [Using 'MainlineVersionStrategy' strategy] (Took: 1,762.06ms) >-
#11 18.95     INFO [25-02-20 16:03:02:67] -< End: Calculating base versions for 'origin/main' (Took: 1,763.73ms) >-
#11 18.95   INFO [25-02-20 16:03:02:67] -< End: Fetching the base versions for version calculation... (Took: 1,964.60ms) >-
#11 18.98   ERROR [25-02-20 16:03:02:69] An unexpected error occurred:
#11 18.98   System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'strategy')
#11 18.98   Actual value was Inherit.
#11 18.98      at GitVersion.Extensions.IncrementStrategyExtensions.ToVersionField(IncrementStrategy strategy) in /_/src/GitVersion.Core/Extensions/IncrementStrategyExtensions.cs:line 11
```

This is my config, which use `Patch` for increment.
```yaml
# next-version: "1.0.0" #enable only when you want to increment from 0.x.x to 1.0.0
assembly-versioning-format: "{MajorMinorPatch}.{CommitsSinceVersionSource}"
assembly-file-versioning-format: "{MajorMinorPatch}.{CommitsSinceVersionSource}"
assembly-informational-format: "{InformationalVersion}"
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-]*\\))?:"
patch-version-bump-message: "^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"
mode: ContinuousDelivery
commit-message-incrementing: Enabled
label: ci
update-build-number: true
strategies:
  - ConfiguredNextVersion
  - Mainline
branches:
  main:
    regex: ^main$
    mode: ContinuousDelivery
    label: ""
    increment: Patch
    prevent-increment:
      of-merged-branch: true
    track-merge-target: false
    source-branches: []
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: true
    track-merge-message: false
    pre-release-weight: 55000
  release:
    regex: ^release[/-]
    mode: ContinuousDelivery
    label: ""
    increment: Patch
    prevent-increment:
      when-current-commit-tagged: true
    track-merge-target: false
    source-branches: ["main"]
    tracks-release-branches: false
    is-release-branch: true
    is-main-branch: false
    pre-release-weight: 55000
  feature:
    regex: ^feat(ures?)?[/-](?<BranchName>.+)
    mode: ContinuousDelivery
    label: "{BranchName}"
    increment: Patch
    prevent-increment:
      of-merged-branch: false
    track-merge-target: false
    source-branches: ["main", "feature", "fix"]
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 30000
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    label: PullRequest
    increment: Patch
    prevent-increment:
      of-merged-branch: false
    label-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    source-branches: ["main", "feature", "fix"]
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 30000
  fix:
    regex: ^(hot)?fix(es)?[/-](?<BranchName>.+)
    mode: ContinuousDelivery
    label: beta
    increment: Patch
    prevent-increment:
      of-merged-branch: false
    track-merge-target: false
    source-branches: ["main"]
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 30000
```

This only occurs on the ci build, no problem locally
