### DISCUSSION TITLE
How to Configure GitVersion for Stable Main Versions and Pre-Release Feature Tags with Patch Increments?

### DISCUSSION THREAD

**Discussion by daniil-basanets** [GitTools/GitVersion#4438] [Q&A]
I'm trying to set up GitVersion (dotnet-gitversion tool version 6.1) so that:

- The **main** branch always produces stable versions without any pre-release tags.
- All branches, including feature branches, increment the patch version.
- **Feature branches** use a pre-release label derived from their branch name (e.g., `first` becomes `-first`).
- When a feature branch is merged into **main**, the main branch version should increment (e.g., from `1.89.0` to `1.89.1`).

## Expected Behavior

- **main:** Versions like `1.89.0`, `1.89.1`, `1.90.0` (stable, no pre-release)
- **features/first:** Versions like `1.89.0-first.0`, `1.89.0-first.2`  
  _(after merge, main should update to `1.89.1`)_  

We are following [GitLab Flow][1] in our SDLC, and our repository structure is as follows:

- main
    - features/
        - first
        - second
    - test

## Current GitVersion Configuration
```yaml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
increment: Inherit
tag-prefix: '' 
major-version-bump-message: \+semver:\s?(breaking|major)
minor-version-bump-message: \+semver:\s?(feature|minor)
patch-version-bump-message: \+semver:\s?(fix|patch)
no-bump-message: \+semver:\s?(none|skip)
commit-message-incrementing: Enabled

branches:
  main:
    regex: ^main$
    label: ''
    increment: Patch
    is-main-branch: true
    is-release-branch: true
    track-merge-message: true
    prevent-increment:
      when-current-commit-tagged: false
    pre-release-weight: 0

  feature:
    regex: ^feature[/-](?<BranchName>.+)$
    mode: ContinuousDelivery
    label: '{BranchName}'
    increment: Inherit
    source-branches:
      - main
    prevent-increment:
      when-current-commit-tagged: false
    pre-release-weight: 30000

  test:
    regex: ^test$
    mode: ContinuousDelivery
    label: test
    increment: Inherit
    source-branches:
      - main
      - feature
    pre-release-weight: 35000

ignore:
  sha: []
```

## Observed Output
When running dotnet-gitversion /updateassemblyinfo on the main branch, I get:
```json
{
  "AssemblySemFileVer": "1.89.1.0",
  "AssemblySemVer": "1.89.1.0",
  "BranchName": "main",
  "CommitDate": "2025-02-14",
  "CommitsSinceVersionSource": 0,
  "FullBuildMetaData": "Branch.main.Sha.3e221de4547ae017f8a47a47fd82471516651f42",
  "FullSemVer": "1.89.1-0",
  "InformationalVersion": "1.89.1-0+Branch.main.Sha.3e221de4547ae017f8a47a47fd82471516651f42",
  "Major": 1,
  "MajorMinorPatch": "1.89.1",
  "Minor": 89,
  "Patch": 1,
  "PreReleaseLabel": "",
  "PreReleaseNumber": 0,
  "SemVer": "1.89.1-0",
  "Sha": "3e221de4547ae017f8a47a47fd82471516651f42"
}
```
And a snippet of the git log shows:
```bash
3e221de (HEAD -> main, tag: v1.89.3, tag: v1.89.2, tag: 1.89.0, origin/main, origin/HEAD) Update for release +semver: 1.88.20
a9f32aa (tag: v1.88.17, tag: v1.88.0-72) chg gitversion
af679f3 (tag: v1.88.3-17, tag: v1.88.16, tag: v1.88.14) Merge branch 'feature/gitversion-ten' into 'main'
2083671 (tag: 1.88.13, feature/gitversion-ten) fix2
```

# My Question
How can I adjust my GitVersion configuration so that the **main** branch always gets a stable version (without any pre-release tags) and increments the patch version on every commit or merge, while **feature** branches receive versions with a proper pre-release tag derived from their branch name? 
<br>Currently, GitVersion is applying a pre-release tag or not incrementing as expected on the main branch. 
<br>Any insights or recommended changes to the configuration would be greatly appreciated!
