### DISCUSSION TITLE
6.0.5 - Use actual branch name instead of "pull/xx/merge" in pull_requests in GH Action pipelines

### DISCUSSION THREAD

**Discussion by cbugneac-nex** [GitTools/GitVersion#4447] [Q&A]
When triggered in GH Actions the branch name used is `pull/xx/merge`. I would like to use the actual branch name.

Does anyone know how to achieve this ?

GitVersion.yml:
```yaml
---
workflow: TrunkBased/preview1
branches:
  main:
    regex: ^main$
    increment: Patch
    label: ''
  pull-requests:
    mode: ContinuousDeployment
    label: '{BranchName}'
    regex: ''
```

Getting something like this in GH pipeline:
```shell
{
  "AssemblySemFileVer": "0.0.12.0",
  "AssemblySemVer": "0.0.12.0",
  "BranchName": "pull/10/merge",
  "BuildMetaData": null,
  "CommitDate": "2025-03-10",
  "CommitsSinceVersionSource": 0,
  "EscapedBranchName": "pull-10-merge",
  "FullBuildMetaData": "Branch.pull-10-merge.Sha.c9386140fbd82d9c83fbc5d77530f31ce62998e5",
  "FullSemVer": "0.0.12-PullRequest10.0",
  "InformationalVersion": "0.0.12-PullRequest10.0+Branch.pull-10-merge.Sha.c9386140fbd82d9c83fbc5d77530f31ce62998e4",
  "Major": 0,
  "MajorMinorPatch": "0.0.12",
  "Minor": 0,
  "Patch": 12,
  "PreReleaseLabel": "PullRequest10",
  "PreReleaseLabelWithDash": "-PullRequest10",
  "PreReleaseNumber": 0,
  "PreReleaseTag": "PullRequest10.0",
  "PreReleaseTagWithDash": "-PullRequest10.0",
  "SemVer": "0.0.12-PullRequest10.0",
  "Sha": "c9386140fbd82d9c83fbc5d77530f31ce62998e4",
  "ShortSha": "c938614",
  "UncommittedChanges": 0,
  "VersionSourceSha": "c9386140fbd82d9c83fbc5d77530f31ce62998e4",
  "WeightedPreReleaseNumber": 30000
}
```
