### DISCUSSION TITLE
Does GitVersion.MsBuild work with DotNetCoreCLI 'build' command?

### DISCUSSION THREAD

**Discussion by will-scc** [GitTools/GitVersion#4471] [Q&A]
I have a project with a GitVersion.yml config and an Azure DevOps pipeline that builds using the following:

```
- task: DotNetCoreCLI@2
  name: build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore --output $(Build.ArtifactStagingDirectory)\setup'
```

The GitVersion.MsBuild package has been added to the project:

```
<PackageReference Include="GitVersion.MsBuild" Version="6.1.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

However, GitVersion doesn't seem to do anything. Version is always 0.0.0.0 in the published build and the pipeline logs don't have anything mentioning GitVersion.

The [GitVersion docs for MSBuild](https://gitversion.net/docs/usage/msbuild) state:
> Since version 6.0 only MSBuild running on .NET Core (dotnet msbuild) is supported.

According [the MSDN docs](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build#msbuild) `dotnet build` is using `dotnet msbuild`:
> `dotnet build` uses MSBuild to build the project. [...] Running `dotnet build`is equivalent to running dotnet msbuild -restore

So, is this supported, and if so, can anyone suggest what I might be doing wrong?

I have previously used GitVersion successfully with the GitTools Task however I'd prefer to use the nuget package as it's less dependent on the pipeline configuration.
