### DISCUSSION TITLE
Using dotnet-gitversion 6.0.5 and its not calculating the correct SemVer.  Help

### DISCUSSION THREAD

**Discussion by llyons** [GitTools/GitVersion#4510] [General]
Hi, I am implementing gitversion for semantic versioning

i have these labels for a curent application on a "development" branch treating it as mainline

Onlife.Services.Settings.ApiClient-v3.1.7
Onlife.Services.Settings.ApiClient-v3.1.8

i have this gitversion.yml

```
strategies:
  - MergeMessage
  - Mainline
commit-message-incrementing: Enabled

tag-prefix: 'Onlife.Services.Settings.ApiClient-v'

branches:
  development:
    regex: ^development$
    increment: Inherit
    prevent-increment:
      of-merged-branch: true
    track-merge-target: true
    source-branches: ['development']
    is-main-branch: true

  pull-request:
    regex: ^(pull|pull-requests|pr)[/-]
    increment: Patch
    source-branches: ['development']
    track-merge-target: false
    label: pr


major-version-bump-message: 'BREAKING CHANGE(\(.*\))?:'
minor-version-bump-message: '^feat(\(\))?:|^feat(\(.*\))?:|^feat:'
patch-version-bump-message: '^fix(\(\))?:|^fix(\(.*\))?:|^fix:'

```
i am assuming if I run dotnet-gitversion /config gitversion.yml /output json that I would have 3.1.8 calculated as the SemVer but instead i get 3.2.0

{
"AssemblySemFileVer": "3.2.0.0",
"AssemblySemVer": "3.2.0.0",
"BranchName": "dldld",
"BuildMetaData": 1,
"CommitDate": "2025-04-18",
"CommitsSinceVersionSource": 1,
"EscapedBranchName": "dldld",
"FullBuildMetaData": "1.Branch.dldld.Sha.263f9092fced3f3f78f73ca1e72d3a9f7ddb918d",
"FullSemVer": "3.2.0-dldld.1+1",
"InformationalVersion": "3.2.0-dldld.1+1.Branch.dldld.Sha.263f9092fced3f3f78f73ca1e72d3a9f7ddb918d",
"Major": 3,
"MajorMinorPatch": "3.2.0",
"Minor": 2,
"Patch": 0,
"PreReleaseLabel": "dldld",
"PreReleaseLabelWithDash": "-dldld",
"PreReleaseNumber": 1,
"PreReleaseTag": "dldld.1",
"PreReleaseTagWithDash": "-dldld.1",
"SemVer": "3.2.0-dldld.1",
"Sha": "263f9092fced3f3f78f73ca1e72d3a9f7ddb918d",
"ShortSha": "263f909",
"UncommittedChanges": 1,
"VersionSourceSha": "909a99a90f900a98e6f0070fb28b8512a5f68580",
"WeightedPreReleaseNumber": 1
}

What am i missing and with no new commits why wont it calculate 3.1.8

thanks in advance
