### DISCUSSION TITLE
Base version based on tag only!

### DISCUSSION THREAD

**Discussion by ppi-kosipenko** [GitTools/GitVersion#4516] [Q&A]
I am looking for configuration that would set base version based on tag only and ignore merge commits. I tried all these settings to no avail:

```
prevent-increment:
  of-merged-branch: true
  when-branch-merged: false
  when-current-commit-tagged: true
track-merge-target: false
track-merge-message: false
commit-message-incrementing: Disabled
```

it always sets version based on this merge commit: 

>       INFO [25-04-24 17:27:49:53] -< Begin: [Using 'MergeMessageVersionStrategy' strategy] >-
>       INFO [25-04-24 17:27:49:56] Found commit ['a1fc04b' - Merge pull request #618 from XXX/release/1.47.0] matching merge message format: GitHubPull
>       INFO [25-04-24 17:27:49:56] Merge message 'Merge pull request #618 from XXX/release/1.47.0
> 
> release/1.47.0': Version increment '1.47.0' +semver 'None' with label 'story-189467'

Please help
