### DISCUSSION TITLE
Passing version from ManualDeployment branch to ContinousDeployment branch

### DISCUSSION THREAD

**Discussion by chrxmvtik** [GitTools/GitVersion#4531] [Q&A]
Heya, we are trying to implement a workflow, where we create cuts from main branch as hotfixes and merge them back into main.

Our workflow looks like this:

1. We create a hotfix branch from main,
2. We perform some changes in hotfix branch, each change (commit) generates a new version using ManualDeployment mode which results in version like: 1.3.0-hotfix.1,
3. We merge hotfix branch into main expecting that version from hotfix branch will be passed to it.

Our configuration looks this way:
```yaml
  main:
    mode: ContinuousDeployment
    label: ''
    increment: None
    prevent-increment:
      of-merged-branch: false
      when-branch-merged: true
      when-current-commit-tagged: true
    track-merge-target: false
    track-merge-message: true
    regex: ^main$|^main$
    source-branches:
      - test
    is-source-branch-for:
      - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-main-branch: true
    pre-release-weight: 55000
  hotfix:
    mode: ManualDeployment
    label: hotfix
    increment: None
    prevent-increment:
      when-current-commit-tagged: false
    track-merge-target: true
    regex: ^hotfix(es)?[/-](?<BranchName>.+)
    source-branches:
      - main
      - test
    is-source-branch-for: []
    is-release-branch: false
    is-main-branch: false
    pre-release-weight: 30000
```

 When we merge hotfix branch into main it actually does not pass generated version in hotfix branch, it simply returns 1.3.0, how can we solve this? We are out of our minds trying to get this done, but seems like there is a no go, we will be grateful for any insights.
