### DISCUSSION TITLE
GitVersion fails when merging to feature branch

### DISCUSSION THREAD

**Discussion by TaffarelJr** [GitTools/GitVersion#4533] [Q&A]
We've had GitVersion integrated in our GitHub Actions workflows for a couple years with no issues.
With the recent major update, we switched from `Mainline` workflow to `TrunkBased/preview1` without too much trouble.

However, recently it's been failing whenever we have a PR for a feature branch where we've merged changes from `main` back into the feature branch (to keep it up-to-date). If the feature branch is simply rebased on `main`, there's no issue. However there's no additional information from GitVersion--we just get this:

```
Command: /opt/hostedtoolcache/GitVersion.Tool/6.3.0/dotnet-gitversion --roll-forward Major /home/runner/work/pythia/pythia /output json /l console /config GitVersion.yml
Error: GitVersion output is not valid JSON
dotnet-gitversion Output:
-------------------
undefined
-------------------
```

Is there any way to get better information as to the real error message? And is this a problem anyone else is seeing? Or maybe it's just something with our particular setup? 

GitHub Actions YAML uses the latest releases:
```yml
- name: Install GitVersion
  uses: gittools/actions/gitversion/setup@v3
  with:
    versionSpec: 6.3.x
    preferLatestVersion: true

- name: Determine Version
  id: gitversion
  uses: gittools/actions/gitversion/execute@v3
  with:
    useConfigFile: true
```

GitVersion config is simple, just a slightly customized Conventional Commits template:
```yml
# Every commit increments the version number
workflow: TrunkBased/preview1

# Override the default bump messages to support Conventional Commits
# https://www.conventionalcommits.org
major-version-bump-message: "(^\\s*(.*?)(\\s*\\(.*?\\))?\\s*!\\s*:|\\n[Bb][Rr][Ee][Aa][Kk][Ii][Nn][Gg](\\s*[Cc][Hh][Aa][Nn][Gg][Ee][Ss]?\\s*:)?)"
minor-version-bump-message: "^\\s*(feat)(\\s*\\(.*?\\))?\\s*:"
patch-version-bump-message: "^\\s*(build|chore|ci|docs|fix|infra|perf|refactor|revert|style|test)(\\s*\\(.*?\\))?\\s*:"
```
