### DISCUSSION TITLE
GitVersion output is not valid JSON

### DISCUSSION THREAD

**Discussion by kgsosa** [GitTools/GitVersion#4558] [Q&A]
Hello, I just wanted to ask if someone out there had an experience on how to fix the error "GitVersion output is not valid JSON." This is happening when merging the main into a feature branch. Below is my config in YAML

error

```
Command: git -C D:\a\1\s rev-parse --is-shallow-repository
Command: C:\hostedtoolcache\windows\GitVersion.Tool\6.3.0\dotnet-gitversion.exe --roll-forward Major D:\a\1\s /output json /l console
##[error]GitVersion output is not valid JSON
dotnet-gitversion Output:
-------------------
undefined
-------------------
undefined
```

In the pipeline
```
steps:
  - checkout: self
    fetchDepth: 0

  - task: gitversion/setup@3
    displayName: Setup GitVersion
    inputs:
      versionSpec: '6.3.x'

  - task: gitversion/execute@3
    displayName: Determine Version
    inputs:
      configFilePath: './GitVersion.yaml'
```

GitVersion yaml

```
next-version: 2025.3.0
workflow: TrunkBased/preview1

branches:
  main:
    regex: ^master$|^main$
    increment: Patch 

  feature:
    regex: ^feature(s)?/.*
    increment: Minor 

  fix:
    regex: ^(fix(es)?|bugfix(es)?)/.*
    increment: Patch 
```

Is there something I need to change in a config, or is there something wrong with my GitVersion yaml?
