### ISSUE TITLE
Rename tag to label

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#1054]
In GitVersion, a [`tag`](http://gitversion.readthedocs.io/en/latest/configuration/#tag) is not the same thing as a Git tag, which I find a bit confusing. Wanting to reference a **Git tag** and use it as the value of the **pre-release tag** makes it even more confusing. It is currently not possible to do this, but [discussions on Gitter](https://gitter.im/GitTools/GitVersion?at=57f0fb76b0ff456d3ada81a4) might indicate that something like this would be very handy:

``` yaml
branches:
  release:
    tag: useLatestTagLabel
```

However, it would be easier to understand if we renamed the pre-release `tag` to `label`:

``` yaml
branches:
  release:
    label: useFromLatestTag
```

This would allow for alternating pre-release labels on the same branch, such that a `beta` could be promoted to `rc` and stay at `rc` without having to tag every commit on that branch.

Thoughts?
