### ISSUE TITLE
Configure GitVersion default tag

### ISSUE THREAD

**Issue by MrHinsh** [GitTools/GitVersion#1059]
I am struggling with the configuration to reach a desired outcome. I want to have every branch except MASTER use 'Preview' as the "tag" adn MASTER to have no tag. I have MASTER working, but can figure out how to get other branches to use the fallback-tag or to configure it differently...

```yaml
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
continuous-delivery-fallback-tag: 'Preview'
next-version: 0.1.0
branches:
  master:
    mode: ContinuousDeployment
    tag: ''
ignore:
  sha: []
```

**Comment by asbjornu** [comment]
@MrHinsh: The problem is that the `tag` property is not allowed at root?

I suppose you can create a branch regex matching all branches, but sort of related to #881, there's no built-in smarts running the matches in several passes, weighing them on specificity or anything similar, so it's highly likely that it's not going to work.

**Comment by MrHinsh** [comment]
Is it possible to do something like:

```
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
continuous-delivery-fallback-tag: ''
next-version: 0.3.0
branches:
  master:
    mode: ContinuousDeployment
    tag: ''
  feature:
   regex: !master
    mode: ContinuousDeployment
     tag: 'Preview'
ignore:
  sha: []
```

This errors out... cant I do negative matches?

**Comment by MrHinsh** [comment]
Also... why do I get : `Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property 'regex' not found on type 'GitVersion.BranchConfig'.`

**Comment by MrHinsh** [comment]
OK... switched to old 3.0 format, and still cant get the beast to work:
```
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
continuous-delivery-fallback-tag: ''
next-version: 0.3.0
branches:
  master:
    mode: ContinuousDeployment
    tag: ''
  (!master)?[/-]:
     tag: 'Preview'
  (fix)?[/-]:
     tag: 'Preview'
ignore:
  sha: []
```

**Comment by MrHinsh** [comment]
OK! So figured it out!
```
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
continuous-delivery-fallback-tag: ''
next-version: 0.3.0
branches:
  master:
    mode: ContinuousDeployment
    tag: ''
  (!master)?:
     tag: 'Preview'
ignore:
  sha: []
```

Use "(!master)?:" as the branch name and I get the desired effect. All branches other than Master take on the Preview tag...
