### ISSUE TITLE
Minor increment on develop branch

### ISSUE THREAD

**Issue by jeusdi** [GitTools/GitVersion#1064]
I'm an absolutly newbie using gitVersion. According to default branch configuration: 

``` yaml
develop:
    regex: dev(elop)?(ment)?$
    mode: ContinuousDeployment
    tag: unstable
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-develop: true
    is-release-branch: false
```

I don't quite to figure out what `increment: Minor` means.

I've just created a repository, I've just tagged first master commit with v0.1 and then I've branched it off to develop and I've created 4 commits. `GitVersion` information is telling me:

``` json
{
  "Major":0,
  "Minor":1,
  "Patch":0,
  "PreReleaseTag":"unstable.4",
  "PreReleaseTagWithDash":"-unstable.4",
  "PreReleaseLabel":"unstable",
  "PreReleaseNumber":4,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.develop.Sha.9b952d58f746cb47e7589a07da65c79ed87fae88",
  "MajorMinorPatch":"0.1.0",
  "SemVer":"0.1.0-unstable.4",
  "LegacySemVer":"0.1.0-unstable4",
  "LegacySemVerPadded":"0.1.0-unstable0004",
  "AssemblySemVer":"0.1.0.0",
  "FullSemVer":"0.1.0-unstable.4",
  "InformationalVersion":"0.1.0-unstable.4+Branch.develop.Sha.9b952d58f746cb47e7589a07da65c79ed87fae88",
  "BranchName":"develop",
  "Sha":"9b952d58f746cb47e7589a07da65c79ed87fae88",
  "NuGetVersionV2":"0.1.0-unstable0004",
  "NuGetVersion":"0.1.0-unstable0004",
  "CommitsSinceVersionSource":4,
  "CommitsSinceVersionSourcePadded":"0004",
  "CommitDate":"2016-10-07"
}
```

According to last default configuration, develop branch must to increment `Minor` field, mustn't it?
