### ISSUE TITLE
GitVersion 3.6.5 ignoring GitVersion.yml

### ISSUE THREAD

**Issue by asherber** [GitTools/GitVersion#1124]
I've seen other similar issues. I've got a project with GV 3.6.5 from NuGet. My `GitVersion.yml` reads:
```yaml
assembly-informational-format: '{FullSemVer}.{Sha}'
mode: ContinuousDelivery
branches: {}
ignore:
  sha: []
```
`GitVersion /showConfig` does correctly show my custom `assembly-informational-format`, but building the project uses the default `{InformationalVersion}`.

I have tried deleting the `.git/gitversion_cache` folder and rebuilding, but no luck.

Any suggestions would be appreciated.
