### ISSUE TITLE
useBranchName does not work properly

### ISSUE THREAD

**Issue by ltvan** [GitTools/GitVersion#1158]
GitVersion 3.6.4
My config:

```yaml
assembly-versioning-scheme: MajorMinorPatchTag
mode: ContinuousDelivery
branches:
  releases?[/-]:
    tag: build
  features?[/-]:
    tag: useBranchName
ignore:
  sha: []
```

In this case, it works:
```
o release/0.3.0
|  o feature/PROJ-1 <-- we are here
|  |
| /
|
o refs/tags/v0.3.0-build.1
|
...
```
gitversion -> v0.3.0-PROJ-1.1 -> OK

But in this case, it's not work:

```
  o feature/PROJ-1 <-- we are here
  |
 /
o release/0.3.0
|
o refs/tags/v0.3.0-build.1
|
...
```
gitversion -> v0.3.0-build.2+5 -> not as expected
