### ISSUE TITLE
Is it possible to configure a custom workflow ?

### ISSUE THREAD

**Issue by doubret** [GitTools/GitVersion#1245]
Hi,
I would like to use GitVersion with a custom workflow, is this possible to configure a workflow completely ?

Let's say i have master and develop branches.
Develop is for dev and master is for prod.
When i want to put something into production i create a release branch (release/Major.Minor patch is reset to 0) and make a pull request to master.

First thing i need from GitVersion is to take the version from the release branch name if the commit is the one where pull request was merger.
Else, each commit should increment the patch.

I tried with a simple branche config like this but it didn't work as expected. Patch is not incremented.

```yaml
commit-message-incrementing: Disabled
branches:
  master:
    regex: master
    increment: Patch
```

Thanks.
