### ISSUE TITLE
Patch Version Mysteriously Incremented

### ISSUE THREAD

**Issue by thefringeninja** [GitTools/GitVersion#1262]
I have the following GitVersion.yml:
```
next-version: 1.0.0
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
commit-message-incrementing: Disabled
branches:
  (pull|pull\-requests|pr)[/-]:
    tag: PullRequest
    increment: Patch
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: true
  releases?[/-]:
    tag: rc
```

I am invoking `GitVersion` via `cake`:
```
GitVersion(new GitVersionSettings {
    NoFetch = true
})
```

This was working fine until a few weeks ago, when suddenly the output on branches / pull-requests turned into this:
```
{
  "Major":1,
  "Minor":0,
  "Patch":1,
  "PreReleaseTag":"a-branch.1",
  "PreReleaseTagWithDash":"-a-branch.1",
  "PreReleaseLabel":"a-branch",
  "PreReleaseNumber":1,
  "BuildMetaData":77,
  "BuildMetaDataPadded":"0077",
  "FullBuildMetaData":"77.Branch.a-branch.Sha.daf02c9a17569f95adc5874d33d2c0bee9b72ddf",
  "MajorMinorPatch":"1.0.1",
  "SemVer":"1.0.1-a-branch.1",
  "LegacySemVer":"1.0.1-a-branch1",
  "LegacySemVerPadded":"1.0.1-a-branch0001",
  "AssemblySemVer":"1.0.1.0",
  "FullSemVer":"1.0.1-a-branch.1+77",
  "InformationalVersion":"1.0.1-a-branch.1+77.Branch.a-branch.Sha.daf02c9a17569f95adc5874d33d2c0bee9b72ddf",
  "BranchName":"a-branch",
  "Sha":"daf02c9a17569f95adc5874d33d2c0bee9b72ddf",
  "NuGetVersionV2":"1.0.1-a-branch0001",
  "NuGetVersion":"1.0.1-a-branch0001",
  "CommitsSinceVersionSource":77,
  "CommitsSinceVersionSourcePadded":"0077",
  "CommitDate":"2017-07-14"
}
```
There is no 1.0.0 tag in this repository, and in any case I've explicitly set the next version to `1.0.0`. Same results for `3.5.0`, `3.6.5`, and `4.0.0-beta*`.
