### ISSUE TITLE
Per-folder configuration for monorepo support

### ISSUE THREAD

**Issue by AndreiMarukovich** [GitTools/GitVersion#1268]
One way of using Git repository is to put multiple projects in the subfolders of one repository (monorepo). In this case it is desirable to version these projects independently, based on the commits in the corresponding folders. 

How feasible is to introduce a additional mode for GitVersion to track not only the branches, but folders as well?

**Comment by asbjornu** [comment]
I highly doubt this is a use-case we want to support in GitVersion. First, it would be very hard and probably introduce loads of bugs. Second, it's kind of a worst-practice use of Git and something you should avoid at all cost.

**Comment by asbjornu** [comment]
Duplicate of #1170.

**Comment by Jaykul** [comment]
This is **not** a duplicate of #1170 because it's not enough to support multiple gitversion.yml files

**Comment by Nakzz** [comment]
Any update on this?

**Comment by asbjornu** [comment]
Nope, @Nakzz. I don't understand or need the use-case and no one else who does have contributed code to implement it.

**Comment by ichbestimmtnicht** [comment]
Well I have a use case for you: The https://moleculer.services Framework. It has a monorepo structure by default and you build services within folders that then get bundled together. So it makes little sense to split up the repo but helps to have different internal versions from a development side for a compatibility matrix when working with multiple teams at the same time for example.

**Comment by asbjornu** [comment]
It’s not the lack of use-cases that is the limiting factor in this being implemented and supported by GitVersion, it’s the lack of code contributions from people like you who are using monorepos, @ichbestimmtnicht. 

The current maintainers of GitVersion does not use, nor recommend the use, of monorepos. Personally, I view it as an anti-pattern. Therefore, we have no incentive to implement support for monorepos. As a matter of fact, since we aren’t using monorepo ourselves, the incentive to **not** support monorepo is much greater than to support it.

However, if someone who wants to champion monorepo support into GitVersion steps up, contributes the necessary code and tests as well as future maintenance of said feature, I’m not against merging it. 

But so far, no such code have been contributed and therefore GitVersion does not support it.

**Comment by jwittner** [comment]
As a follow up, I was able to version multiple things out of a single repository by having separate GitVersion-<API>.yml files and running the tools with explicit references to which API I was computing. Working out well in several repositories that have multiple versioned _things_ in them. I also add prefixes to the version tags, e.g. <API>-v1.0.0.

I think this achieves the goal of what you propose, though I have to admit I expected to be able to do it in the repository's configuration file as well. It would have probably saved me a bunch of time. =)

**Comment by cmeyertons** [comment]
@jwittner do you mind specifying _how_ you made the explicit references to `API`?

I can't get it to work w/ `tag-prefix` and am unsure of after reading and re-reading the docs, am unsure of how you did so.

Here's my config:

```yml
next-version: 0.1.0
increment: Inherit
# continuous-delivery-fallback-tag: ci
tag-prefix: 'MyAPI'
commit-message-incrementing: Disabled
update-build-number: true
```

**Comment by jwittner** [comment]
For a version tagged e.g. `MyApi-v1.0.0`, you'd want something like the below. I've added customized bump messages for the `api` as well, though I see you have it disabled in your config. 

I'm invoking the tooling in PowerShell through the dotnet cli and using the JSON output rather than the `/output buildServer` flag to do my own setup (due to conversion from legacy system). 

> Note: I've seen bad behavior from `next-version`.
> Note: I've seen bad behavior if you create tags with versions containing 'prerelease' strings.

```yaml
tag-prefix: 'MyAPI-v'
major-version-bump-message: '\+myapi-semver:\s?(breaking|major)'
minor-version-bump-message: '\+myapi-semver:\s?(feature|minor)'
patch-version-bump-message: '\+myapi-semver:\s?(fix|patch)'
no-bump-message: '\+myapi-semver:\s?(none|skip)'
```
