### ISSUE TITLE
+semver:patch does not seem to work with Mainline mode

### ISSUE THREAD

**Issue by pshrosbree** [GitTools/GitVersion#1294]
I do this:

```
λ gitversion /output json /showvariable SemVer
5.6.0

λ git commit -m "+semver:patch" --allow-empty
[develop 4e1b1bf5] +semver:patch

λ gitversion /output json /showvariable SemVer
5.6.0
```

Hmmm... maybe I need a merge another branch to get this effect, so:

```
λ gitversion /output json /showvariable SemVer
5.6.0

λ git checkout -B try-bump
Switched to a new branch 'try-bump'

λ git commit -m "+semver:patch" --allow-empty
[try-bump f532421a] +semver:patch

λ git checkout develop
Switched to branch 'develop'
Your branch is ahead of 'origin/develop' by 30 commits.
  (use "git push" to publish your local commits)

λ git merge try-bump
Updating 4e1b1bf5..f532421a
Fast-forward

λ gitversion /output json /showvariable SemVer
5.6.0
```

OK, let's add a commit on master:

```
λ git commit -m "+semver:patch" --allow-empty
[develop 63e0865c] +semver:patch

λ gitversion /output json /showvariable SemVer
5.6.0
````

So, why?

The GitVersion.yml is:

```
λ gitversion /showconfig
assembly-versioning-scheme: MajorMinorPatchTag
assembly-file-versioning-scheme: MajorMinorPatch
mode: Mainline
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: develop
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
```

If this is correct behavior, how do I get commits (merge or otherwise) on master (develop) to bump the patch version?

```
λ git log

commit 63e0865ce678fbe58f9f4b0daef9142466b06b81 (HEAD -> develop)
Author: Peter Shrosbree <petshr@microsoft.com>
Date:   Fri Sep 15 14:21:33 2017 -0700

    +semver:patch

commit f532421a043da18832c5c34eefb9856ca9bd387e (try-bump)
Author: Peter Shrosbree <petshr@microsoft.com>
Date:   Fri Sep 15 14:19:49 2017 -0700

    +semver:patch

commit 4e1b1bf5c5fd4f7afcb346f2882f62e8151375ac
Author: Peter Shrosbree <petshr@microsoft.com>
Date:   Fri Sep 15 14:18:09 2017 -0700

    +semver:patch
```

**Comment by pshrosbree** [comment]
After posting this I tried doing this on a branch called master with the same configuration as above, and it worked as expected. However, if I changed the configuration so that the master regex is master, it goes back to the previously described behavior:

```
assembly-versioning-scheme: MajorMinorPatchTag
assembly-file-versioning-scheme: MajorMinorPatch
mode: Mainline
increment: Patch
commit-message-incrementing: Enabled
branches:
  master:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: master
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
```

So it seems that I don't understand how to configure GitVersion.

Here is what I want:

Everyone PRs their code to `develop`.
Once we're happy with what is on `develop` we merge it to the `staging` branch and test in staging.
Once we're happy with `staging` we merge it to the `production` branch and deploy.
We would like every commit or merge to `develop` to bump the patch version and honour any `+semver:` commit comments.

How can this be achieved?
