### ISSUE TITLE
Using Mainline mode, patch is being increased oddly on Jenkins 

### ISSUE THREAD

**Issue by AuroraBrignola** [GitTools/GitVersion#1321]
I am using Jenkins for my CICD and every time I commit a fix, on the build server the versioning starts from x.y.1 and only increases to the next odd number, so to 3 and then to 5, skipping all the even numbers.  But when I run gitversion locally, for the same project, the versioning is correct. Also, the minor increment starts from x.y.1 not x.y.0 on the build server, but locally starts from 0. 

This is my yml: 

```yml
mode: Mainline
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag
tag-prefix: '[vV]'
major-version-bump-message: '.*BREAKING CHANGE:.*?'
minor-version-bump-message: '(?i)feat(\(.+\))?:'
patch-version-bump-message: '(?i)fix(\(.+\))?:'
no-bump-message: '^((?!.*BREAKING CHANGE|fix|feat).)*$|fix\s*?(\(\))|feat\s*?(\(\))'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: disabled
branches: {}
ignore:
  sha: []
```

Any thoughts?
