### ISSUE TITLE
Mainline mode requires separate config to use with other modes

### ISSUE THREAD

**Issue by davidarcher** [GitTools/GitVersion#1332]
My team uses a modified GitHubFlow style where we basically have a master branch with small case/feature branches off of that. Every two weeks (each sprint) we create a release branch off master and that code is shipped to our QA department for testing. Any issues found during testing get fixed in master and then cherry-picked back to the appropriate release branches.

Our desired versioning setup would be:

- Every commit on a release branch increments the Patch number by one.
e.g. 3.1.0, 3.1.1, 3.1.2

- Commits on master have an "unstable" prerelease tag and we increment the Minor number by one each sprint.
e.g. 3.1.0-unstable.1+36, 3.1.0-unstable.1+37, 3.2.0-unstable.1+1

So basically, we increment Minor each sprint and we increment Patch for every bug fix we have to cherrypick back to the release branch.

I tried using the ContinuousDelivery and ContinuousDeployment modes but they refuse to increment more than once which is needed for commits on the release branch since we'd like to only tag once at the end of the sprint. I tried using Mainline mode which gets the release branch versions working but then that screws up the versioning for commits to master. For whatever reason, the Mainline versioning mode completely takes over the config so I can't have just one branch type (my release branches) set to Mainline and the rest set to ContinousDelivery.

I eventually got it working by using two different GitVersion.yml config files and swapping them out depending on whether the current branch we're building is branched from master or from a release branch but it doesn't seem like it is WAD.

**GitVersion.master.yml**
```yaml
assembly-versioning-scheme: Major
commit-message-incrementing: Disabled
branches:
  master:
    tag: unstable
    increment: Minor
    regex: ^master
  default:
    tag: useBranchName
    increment: Inherit
    regex: (<number>.*)
    source-branches: ['master']
```

**GitVersion.release.yml**
```yaml
assembly-versioning-scheme: Major
commit-message-incrementing: Disabled
mode: Mainline
branches:
  release:
    tag: ""
    increment: None
    regex: ^release
    is-mainline: true
  default:
    tag: useBranchName
    increment: Inherit
    regex: (<number>.*)
    source-branches: ['release']
```
