### ISSUE TITLE
Provide option to ignore merged branch names in computing base version

### ISSUE THREAD

**Issue by kitgrose** [GitTools/GitVersion#1400]
Someone in our organisation created a branch named `7066-important-updates-from-v2.0`, and it was reviewed and merged into `master`.

Since that point, GitVersion has reported the version as v2.0.0.

The most recent (and highest) tag in the repo is `v1.2.17`.

It's our intention that running GitVersion against any of the subsequent commits in `master` would return `v1.2.18` (based on our config being set to increment Patch).

I wouldn't have expected the problematic branch name to have been interpreted as a base version source, since it doesn't match any of the branch patterns in the config.

Is there any way to configure GitVersion to ignore merged branch names as a base version source? I can't see a directly applicable configuration option for this, and the only option I can see that works is to add those commits' SHAs to the `ignore` config option.

For the record, there is no config override in place, so the GitVersion config looks like:

```
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  releases?[/-]:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  features?[/-]:
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  (pull|pull\-requests|pr)[/-]:
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
  hotfix(es)?[/-]:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  support[/-]:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  dev(elop)?(ment)?$:
    mode: ContinuousDeployment
    tag: unstable
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
ignore:
  sha: []
```
