### ISSUE TITLE
Build Meta Padding ignored in mainline mode

### ISSUE THREAD

**Issue by BenjaminAbt** [GitTools/GitVersion#1427]
On VSTS we use following configuration with GitVersion CLI from NuGet `4.0.0-beta0013`

```yaml
mode: mainline
tag-prefix: '[vV]'
next-version: 0.5.0
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 3
build-metadata-padding: 3
commits-since-version-source-padding: 3
commit-message-incrementing: Enabled
branches: {}
ignore:
  sha: []

```

The default of `build-metadata-padding` is `4`

Expected output: `0.5.21-PullRequest068.009`
Current output: `0.5.21-PullRequest068.9`

other example:

Expected output: `0.5.21-PullRequest068.010`
Current output: `0.5.21-PullRequest068.10`

This results in an issue that `0.5.21-PullRequest068.9` is a newer version than `0.5.21-PullRequest068.10`

PS: `4.0.0-beta0013` is not on NuGet.
