### ISSUE TITLE
tracks-release-branches: true does not work without local branch refs

### ISSUE THREAD

**Issue by AnSmol** [GitTools/GitVersion#1489]
`tracks-release-branches: true` does not work if release-marked branch has not been forked from remote ref locally.

Example:
![image](https://user-images.githubusercontent.com/5318028/46610838-938bd780-cb14-11e8-8fb4-b0cfe92da76b.png)

<details> 
  <summary>GitVersion branches config</summary>

```yaml
branches:
  master:
    mode: ContinuousDeployment
    tag: master
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$
    source-branches:
    - develop
    - release
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: true
 
  release:
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^(pre-)?releases?[/-]\d+\.\d+(\.\d+)?$
    source-branches:
    - develop
    - master
    - support
    - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
```
</details>

BTW, уou can't find this issue if you do  `git clone --mirror` 

GitVersion version: 4.0.0-beta.14+1603.Branch.master.Sha.08f23f662edd0f5161814a1948fd973dd8ae563f
