### ISSUE TITLE
Branch can't inherit parent's branch config right after merged with it.

### ISSUE THREAD

**Issue by AnSmol** [GitTools/GitVersion#1521]
How to reproduce:
1) Create branch with arbitrary name from master, for instance - JIRATASK01. (branch should not have dedicated config in GitVersion.yml).

2) Add some commits to JIRATASK01, run gitversion. Now version is correct. configuration has inherited from master.
_Version: 2.29.0-jiratask01-0003 
diag: [diag_before_merge_with_parent_2.29.0-jiratask01-0003.txt](https://github.com/GitTools/GitVersion/files/2533445/diag_before_merge_with_parent_2.29.0-jiratask01-0003.txt)_

3) Add some commits to master, checkout to JIRATASK01, merge master to JIRATASK01.  Now version is incorrect, falled back to 0.1.0.
_Version: 0.1.0-jiratask01-0007
diag: [diag_after_merge_with_parent_0.1.0-jiratask01-0007.txt](https://github.com/GitTools/GitVersion/files/2533446/diag_after_merge_with_parent_0.1.0-jiratask01-0007.txt)_

4) Add some more commits to master, checkout to JIRATASK01, Now version is correct again.
_Version: 0.1.0-jiratask01-0007
diag: [diag_after_merge_with_parent_parrent_added_commits_2.29.0-jiratask01-0006.txt](https://github.com/GitTools/GitVersion/files/2533448/diag_after_merge_with_parent_parrent_added_commits_2.29.0-jiratask01-0006.txt)_

BTW: As you can see in config below, version source is release branch.
I don't now why, but huge, real-world repository diag, also has warning (unlike attached above):
> Fallback branch wants to inherit Increment branch configuration from itself. Using patch increment instead.

So i suspect this code in [BranchConfigurationCalculator.cs](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BranchConfigurationCalculator.cs):
```C#
   // To prevent infinite loops, make sure that a new branch was chosen.
                if (targetBranch.IsSameBranch(chosenBranch))
                {
                    Logger.WriteWarning("Fallback branch wants to inherit Increment branch configuration from itself. Using patch increment instead.");
                    return new BranchConfig(branchConfiguration)
                    {
                        Increment = IncrementStrategy.Patch
                    };
                }

```
_[HugeRealWorldDiag.txt](https://github.com/GitTools/GitVersion/files/2533480/HugeRealWorldDiag.txt)_

<details> 
  <summary>GitVersion config</summary>
```yaml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
#Guid in tag-prefix cause we don't use tags for versioning
tag-prefix: '74e06765-6c2d-45c5-8fd6-f48d70909ca6'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    mode: ContinuousDeployment
    tag: master
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$
    source-branches:
    - develop
    - release
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: true
  release:
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^(pre-)?releases?[/-]\d+\.\d+(\.\d+)?$
    source-branches:
    - develop
    - master
    - support
    - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
  pull-request:
    mode: ContinuousDeployment
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)'
    track-merge-target: false
    regex: (pull|pull\-requests|pr)[/-]
    source-branches:
    - develop
    - master
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
ignore:
  sha: []
commit-date-format: yyyy-MM-dd
```
</details>

GitVersion versions:
Both 4.0.0-beta.14+1603.Branch.master.Sha.08f23f662edd0f5161814a1948fd973dd8ae563f and 
4.0.0+Branch.master.Sha.e715eb5dd515037d90a257f527e62442cae8c1c5
