### ISSUE TITLE
+semver: major bumps minor, should bump major change

### ISSUE THREAD

**Issue by MiroKov** [GitTools/GitVersion#1539]
> Adding +semver: breaking or +semver: major will cause the major version to be increased, +semver: feature or +semver: minor will bump minor and +semver: patch or +semver: fix will bump the patch.

We use GitVersion 4.0 nuget package.
When we add message +semver: major, it causes a minor change. Should cause a major change.

**Comment by waaromikniet** [comment]
We are having the same issue

**Comment by pietergheysens** [comment]
Same issue here on my side while building in Azure DevOps using GitVersion 4.0.3. Adding +semver:major in commit message only increments the minor version.

**Comment by npiskunov** [comment]
Also facing the same problem

**Comment by FixRM** [comment]
Same problem, any fixes? I use yaml configuration to override semver regex:
``` YAML
mode: ContinuousDelivery
major-version-bump-message: '(breaking|major):'
minor-version-bump-message: '(feature|minor):'
patch-version-bump-message: '(fix|patch):'
no-bump-message: '(none|skip):'
ignore:
  sha: []
```
'breaking' updates minor version
