### ISSUE TITLE
dev's version does not respect master's when using +semver in merge message

### ISSUE THREAD

**Issue by thoemmi** [GitTools/GitVersion#1561]
We're using `master` branch for releases, `dev` for active development and publishing pre-releases, and feature branches.
Whenever there's a breaking change, we add `+semver:major' when merging from `dev` to `master`.
However, succeeding builds from the `dev` branch don't respect the incremented major version. 

Here's our `gitversion.yml`:
```yaml
assembly-versioning-scheme: MajorMinorPatchTag
mode: Mainline
continuous-delivery-fallback-tag: ''
branches:
  develop:
    regex: ^dev(elop(ment)?)?$
    increment: Patch
    tag: unstable
  master:
    tag: ''
    increment: Minor
```
