### ISSUE TITLE
Feature Request: Allow for definition of custom output version formats

### ISSUE THREAD

**Issue by tknerr** [GitTools/GitVersion#1620]
It would be great if we could define additional output version formats in the `GitVersion.yml` config, which are composed of the existing output variables, e.g. via a new `custom-output-vars` setting:

Given this `GitVersion.yml`
```
mode: ContinuousDelivery
custom-output-vars:
  MyVersionFormat: {MajorMinorPatch}-{PreReleaseLabel}.{env:JENKINS_BUILD_NUMBER ?? local}
branches:
  master:
    regex: master
    tag: ci.master
```

Would produce this output:
```
$ gitversion
{
  "Major":1,
  "Minor":1,
  "Patch":0,
  "PreReleaseTag":"ci.master.1",
  "PreReleaseTagWithDash":"-ci.master.1",
  "PreReleaseLabel":"ci.master",
  "PreReleaseNumber":1,
  "BuildMetaData":1,
  "BuildMetaDataPadded":"0001",
  "FullBuildMetaData":"1.Branch.master.Sha.54ceb50f1dd9fa976f920861906a3ffc1992d482",
  "MajorMinorPatch":"1.1.0",
  "SemVer":"1.1.0-ci.master.1",
  "LegacySemVer":"1.1.0-cimaster1",
  "LegacySemVerPadded":"1.1.0-cimaster0001",
  "AssemblySemVer":"1.1.0.0",
  "AssemblySemFileVer":"1.1.0.0",
  "FullSemVer":"1.1.0-ci.master.1+1",
  "InformationalVersion":"1.1.0-ci.master.1+1.Branch.master.Sha.54ceb50f1dd9fa976f920861906a3ffc1992d482",
  "BranchName":"master",
  "Sha":"54ceb50f1dd9fa976f920861906a3ffc1992d482",
  "ShortSha":"54ceb50",
  "NuGetVersionV2":"1.1.0-cimaster0001",
  "NuGetVersion":"1.1.0-cimaster0001",
  "NuGetPreReleaseTagV2":"cimaster0001",
  "NuGetPreReleaseTag":"cimaster0001",
  "CommitsSinceVersionSource":1,
  "CommitsSinceVersionSourcePadded":"0001",
  "CommitDate":"2019-03-01",
  "MyVersionFormat":"1.1.0-ci.master.573"
}
```

This would have the nice benefit that the versioning scheme is codified right at the source (i.e. in `GitVersion.yml`) and can be easily accessed via `gitversion -showvariable MyVersionFormat`.

Also, it would be flexible enough to cover many use cases, without changing the underlying model.

What do you think?

**Comment by tknerr** [comment]
I found that you can more or less do that already with the `InformationalVersion` by setting the `assembly-informational-format`:

```yaml
mode: ContinuousDelivery
assembly-informational-format: {MajorMinorPatch}-{PreReleaseLabel}.{env:JENKINS_BUILD_NUMBER ?? local}
branches:
  master:
    regex: master
    tag: ci.master
```

Is not that flexible and generic as defining your own (multiple) custom vars, but covers my current need so far (except that I'm running into #1626 now)
