### ISSUE TITLE
how to use the exported variables in gitlab?

### ISSUE THREAD

**Issue by holidaycottages** [GitTools/GitVersion#1650]
I am running this inside gitlab and its working great, the output shows me all the variables that it has exported, but I cannot work out what the syntax is to actually get the variable I want and use it in my ci file, can someone give me a direction?

**Comment by micdenny** [comment]
@holidaycottages did you find a way to use gitversion on gitlab? I'm stuck on the same problem, from the source code it should write a file called `gitversion.properties` but I can't find on the build server even if the log reach that point outputting the sentence `Outputting variables to 'gitversion.properties' ... `.

Any help would be much appreciated, thank you 😄

**Comment by benpettman** [comment]
Hi @micdenny (I am using my personal account as opposed to the holidaycottages one)

Yes I solved this issue, here is a snippet from my build file:

```
script:
    - 'nuget restore'
    - 'msbuild /p:Configuration=Live;'
    - 'GitVersion /output buildserver'
    - 'for /f "delims== tokens=1,2" %%G in (gitversion.properties) do set %%G=%%H'
    - 'echo GitVersion_LegacySemVerPadded=%GitVersion_LegacySemVerPadded% >> variables'
```
Essentially you build the project with msbuild, then pass to GitVersion you want to output the vars to a build server and then it creates a `gitversion.properties` file and then I take that and format it into a `variables` file and pass along my pipeline and then you can echo out any var in the file as per the last line above.

Hope that helps

**Comment by micdenny** [comment]
@benpettman Thank you so much, this has helped me understand that the file was not there because I had the second stage that was git cleaning the folder 😄

**Comment by dani-mon** [comment]
@benpettman how did you keep sync the numbers for next builds? Did you push the gitversion.properties file to your repo? How did you solve this, is there any common way? If I push it regularly, the next CI is triggered, isn't it?

**Comment by PilotBob** [comment]
@dani-mon If you mean, how do you use the GitVersion information in later stages, you should add gitversion.properties as an artifact. Then in a later stage you can read the file as needed:

```
build:
  stage: build
  script:
    - gitversion /nocache /updateassemblyinfo /output buildserver
    - if ($LASTEXITCODE -ne 0) { throw "Error running GitVersion" }
    - nuget restore  # restore Nuget dependencies
    - msbuild /p:Configuration=Release  # build the project
  artifacts:
    paths:
      - 'gitversion.properties'

test:
  stage: test
  script:
    - $GitVersion = convertfrom-stringdata (gc gitversion.properties -raw)
    - Write-Host "Testing version $($GitVersion.GitVersion_FullSemVer)"
    - "vstest.console.exe" "**\bin\**\*Test.dll" --logger:"junit;LogFilePath=$env:CI_PROJECT_DIR\test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"  # running Unit tests

```

If you mean, for next pipeline run? That's the point of gitversion. It determines the version based on your current repo, branch, etc.
