### ISSUE TITLE
Use GitVersion on Travis

### ISSUE THREAD

**Issue by dtracers** [GitTools/GitVersion#1673]
My use case is that when a commit/pull request is merged to master I would like to create a new tagged commit with a versioning system.

That way I can then deploy it with that tag to other systems like pypi.

Is there any plans to support linux build systems like travis in the future?
(Or documentation on how to run it on travis?)

**Comment by asbjornu** [comment]
I've successfully set up GitVersion with Docker on Travis. Just enable the [Docker service](https://docs.travis-ci.com/user/docker/) and you should be able to do the following in your `.travis.yml` file:

```yaml
services:
  - docker

install:
- docker pull gittools/gitversion:5.0.0-linux-debian-9-netcoreapp2.2

before_script:
- docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.0.0-linux-debian-9-netcoreapp2.2 /repo -output BuildServer
```
