### ISSUE TITLE
useBranchName is ignored on feature branch configuration

### ISSUE THREAD

**Issue by scott-parillo** [GitTools/GitVersion#1692]
We're currently using GitVersion 4.0.0 and everything works like a charm _except_ for feature branches. In our organization, all of our feature branches are prefixed with `rel-` and are using the following branch configuration within our `GitVersion.yml` file:

```yaml
feature:
    regex: (origin/)?rel-.*$
    tag: useBranchName
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    is-release-branch: false
```

The main driver with this configuration is to overcome the problem with duplicate NuGet versions. e.g. 2 feature branches that calculate the same version and attempt to publish their respective package to an internal NuGet feed. Because the feed is configured to disallow duplicate versions and/or replacing an existing package, our CI build fails otherwise.

With that out of the way, the `useBranchName` tag never seems to work when we inspect the `NuGetVersion` variable. If I use  `alpha` or some other value for the tag, it generates the correct overall `NuGetVersion` variable; however, the value doesn't solve the problem at hand because the package version wouldn't be unique. I have also tried setting `alpha-{BranchName}` for the tag and the calculated `NuGetVersion` seems to ignore `-{BranchName}` altogether?!

Are there any known limitations with `useBranchName` that may not be obvious? For example, does it possibly ignore the branch name if the length is too long? Or is it mutually exclusive with other configuration settings? It's very clear from experimenting with the `GitVersion.yml` that the regex is correct but we cannot seem to find any way for `GitVersion.exe` to include the name within the `NuGetVersion` variable.
