### ISSUE TITLE
I have not been able to set the branches so that only one of them increases

### ISSUE THREAD

**Issue by pandrer** [GitTools/GitVersion#1712]
I have 3 branches
I have master
I have nonprod
and the rest come from nonprod

I must always increase in patch when the merge to nonprod is made

But it's not working

They could tell me what I'm doing wrong

```
assembly-informational-format: '{SemVer}/{BranchName}'
mode: ContinuousDelivery
branches:
  master:
    mode: ContinuousDelivery
    tag: ''
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
  nonprod:
    mode: ContinuousDeployment
    tag: np
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    regex: nonprod
    source-branches:
    - master
  dev:
    regex: \b(?!master|nonprod)\b\S+
    mode: ContinuousDeployment
    tag: unstable
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    source-branches:
    - nonprod
ignore:
  sha:
  - 9a5832d88453eaf2950722ed49a630d90bb7ad55
```
