### ISSUE TITLE
Manually bumping version doesn't work as expected

### ISSUE THREAD

**Issue by 387119** [GitTools/GitVersion#1746]
looks like this issue the same as https://github.com/GitTools/GitVersion/issues/1187

but anyway if I do "+semver:major" or "+semver:minor" more than once it is not working, I didn't find any notes regarding that in documentation, so looks like it`s issue.

```
bash# GitVersion.exe -version
4.0.0+Branch.master.Sha.e715eb5dd515037d90a257f527e62442cae8c1c5
bash# mkdir test
bash# cd test
bash# git init
bash# cp ../GitVersion.yml ./
bash# git commit -a -m "init"
bash test(master)# gitversion | grep FullSemVer
  "FullSemVer":"31.0.0-0.dev.0",
bash test(master)# git commit --allow-empty -m "+semver:major"
[master 1e3e60f] +semver:major
bash test(master)# gitversion | grep FullSemVer
  "FullSemVer":"32.0.0-0.dev.1", -> (as expected)
bash test(master)# git commit --allow-empty -m "+semver:major"
[master 3fe5243] +semver:major
bash test(master)# gitversion | grep FullSemVer
  "FullSemVer":"32.0.0-0.dev.2", -> (expected 33.0.0-0.dev.2)
bash test(master)# git log --pretty=oneline
3fe5243aed054ffbb788160810972f3c1840415a (HEAD -> master) +semver:major
1e3e60fd5bb84889e874f2446a6f3c1489ec21c9 +semver:major
7d2ea5254f841064adfcd6ac0d3f82d077a1e48b init
```

GiVversion.yaml
```
next-version: 31
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
assembly-versioning-scheme: MajorMinorPatchTag
mode: ContinuousDeployment
commit-message-incrementing: Enabled
tag-prefix: v
branches:
  master:
    mode: ContinuousDeployment
    tag: 0.dev
    increment: Major
    is-release-branch: false
    prevent-increment-of-merged-branch-version: true
ignore:
  sha: []
```
