### ISSUE TITLE
Mainline: Support branch off master not auto incrementing patch as master:patch+1

### ISSUE THREAD

**Issue by liv-lee** [GitTools/GitVersion#1769]
I have a support branch(prodsupport) which is branched off master, similar in use to hotfix branches, hence I expect it's patch number to always be _master: patch+1_. I'm also using _mode: mainline_ in order to auto-increment master patch whenever a prodsupport/hotfix branch is merged in as I would rather not rely on commit messages for incrementing patch numbers. My config is as follows:

```
mode: mainline
branches:
    prodsupport:
        regex: prodsupport
        mode: ContinuousDeployment
        tag: 'prodsupport'
        increment: Patch
        source-branches: ['master']   
```

The behaviour when merging into master is exactly as I expect it to work, i.e. patch increments by 1 when a prodsupport/hotfix branch is merged in, regardless of the commit message. However, the reverse is not true, i.e. branching a prodsupport/hotfix off of master results in one patch ahead of the **last release version** that was merged into master, whereas master could be a number of patches ahead of the last release version. I can get the desired incrementing on prodsupport/hotfix if I make sure to name them using master M.m.p+1, however, that's really relying on commit messages and kind of defeats the purpose of using mainline.

The following example scenario may be able to better explain my problem:

_last release version: 1.1.0
master version: 1.1.**3**_

**What I expect:**
_prodsupport/hotfix version: 1.1.**4**_

**What I'm seeing:**
_prodsupport/hotfix version: 1.1.**1**_

I don't suppose anyone has a solution to this problem?
