### ISSUE TITLE
 An error occurred while loading the YAML build pipeline. wrong number of segments

### ISSUE THREAD

**Issue by brunomartinspro** [GitTools/GitVersion#1773]
The latest version released to AzureDevOps gives the error "
An error occurred while loading the YAML build pipeline. wrong number of segments"

When executing:

```
trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: GitVersion@4
  name: "InitializeGitVersion"
  inputs:
    updateAssemblyInfo: true
```
