### ISSUE TITLE
How to update GitVersion Variables in Azure DevOps Pipelines?

### ISSUE THREAD

**Issue by sukruthakittur** [GitTools/GitVersion#1800]
I am trying to use GitVersion in my Az Devops pipeline and was trying to figure out how to override the default “PreReleaseLabel” variable in GitVersion. The current value of the variable is set to “GitVersion”, but I wanted to change it to aplha/beta depending on the branch. I tried setting up a var by the same name in Az devops variables lib, tried adding it as a job var, but none of them seemed to work.

**Comment by sukruthakittur** [comment]
Figured it out, the right way to update it is from the GitVersion.yml as - 

```
branches: 
    feature:
      regex: feature?[/-]
      mode: ContinuousDelivery
      tag: alpha
```
