### ISSUE TITLE
GitVersion CommandLine 5.1.1 Multiple branch configurations match

### ISSUE THREAD

**Issue by zaceverett** [GitTools/GitVersion#1877]
Running command line gitversion 5.1.1 I get the following error

```
Multiple branch configurations match the current branch branchName of 'develop'. Using the first matching configuration, 'GitVersion.Configuration.BranchConfig'. Matching configurations include: 'allbranches
 - develop'
Multiple branch configurations match the current branch branchName of 'develop'. Using the first matching configuration, 'GitVersion.Configuration.BranchConfig'. Matching configurations include: 'allbranches
 - develop'
```

If I then run the command again it works fine.

I do not see this in version 5.0.1.

Causing cake build to fail.

`GitVersion.yml`:

```yaml
branches:
  allbranches:
    regex: ^?.*
    source-branches: []
    increment: None
```

**Comment by asbjornu** [comment]
What's `allbranches` supposed to be doing? If you delete `GitVersion.yml`, does it work then?

**Comment by SamuelEtterlen** [comment]
Same behavor for me with 5.1.3...

When starting the first time gitversion into a new fresh envrionment, I get the same warnings as zaceverett.
When starting a second time, it works fine...

**Comment by DanubeRS** [comment]
I have managed to get around this by setting the output verbosity to `Error`

```c#
Setup(context => {
    version = GitVersion(new GitVersionSettings(){
        Verbosity = GitVersionVerbosity.Error
    });
    Information($"Building version {version.InformationalVersion}");
});
```

Was unable to set as `None` relating to #1949

**Comment by anionDev** [comment]
same problem here. are there any plans to fix this bug?

**Comment by alenmeister** [comment]
I came across this issue today as well when I decided to opt for a default branching strategy.
Here's what my `GitVersion.yml` looks like:
```
mode: Mainline
tag-prefix: ''

branches:
  master:
    increment: None
    prevent-increment-of-merged-branch-version: true
  default:
    regex: ^(?!master)
    tag: beta
    increment: None
    source-branches: ['master']
```

I also have an ongoing [discussion](https://github.com/cake-build/cake/discussions/3274) in the cake-build repo about this, for anyone interested.
