### ISSUE TITLE
GitVersion Azure Pipelines Task not using "GitVersion.yml" configuration by default

### ISSUE THREAD

**Issue by dsbut** [GitTools/GitVersion#1973]
The Azure Pipelines GitVersion task indicates, for the _Configuration File_ that:
>Optional path to config file (defaults to GitVersion.yml)

So, with the following `GitVersion.yml` file in my repository root, specifying a `next-version: 1.0.9`:
``` yaml
next-version: 1.0.9
branches:
  hotfix:
    tag: hotfix
  release:
    tag: rc
ignore:
  sha: []
merge-message-formats: {}
```

And there being no release tags in the master branch, and using this task:

``` yaml
- task: GitVersion@5
  inputs:
    runtime: 'full'
    updateAssemblyInfo: true
```

**Expected SemVer**
1.0.9

but was

**Actual SemVer**
0.1.0

So, it appears that the task is not honoring the _GitVersion.yml_ file in the repository root by default.

**Wrokaround**
Explicitly setting the `configFilePath` value of the task yields the expected result, but should not be necessary according to the _Configuration File_ help information.

``` yaml
- task: GitVersion@5
  inputs:
    runtime: 'full'
    configFilePath: 'GitVersion.yml'
    updateAssemblyInfo: true
```
