### ISSUE TITLE
GitVersion does not update padded prerelease number

### ISSUE THREAD

**Issue by casz** [GitTools/GitVersion#2011]
Currently GitVersion always seemed to be padding with `0001`

See: https://ci.appveyor.com/project/nmklotas/gitlabapiclient/builds/29847139#L84

GitVersion.yml config:
```yml
assembly-versioning-scheme: MajorMinorPatch
branches:
  master:
    tag: beta
```
