### ISSUE TITLE
Can't access variables after adding new Azure DevOps GitVersion tasks

### ISSUE THREAD

**Issue by TabithaLarkin** [GitTools/GitVersion#2035]
We're using a manually checked in version of GitVersion at the moment, and are looking to migrate to the recently released Azure DevOps tasks.

We have tried adding the following tasks:

```yml
- task: gitversion-setup@5
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion-execute@5
  displayName: Run GitVersion
```

This resulted in the `$(GitVersion.Major)` variable not being found.

We've also tried adding the `/output` variable to the execute task, but something about the syntax is not valid.

```yml
  inputs:
    additionalArguments: '/output buildserver'
```
```
Unhandled Exception: GitVersion.Exceptions.WarningException: Could not parse command line parameter '/output buildserver'.
```
