### ISSUE TITLE
Incorrect Minor Version on Pull Request branches

### ISSUE THREAD

**Issue by dsbut** [GitTools/GitVersion#2056]
I'm encountering, what I believe to be an incorrect minor version number, on GitHub Pull Requests with Status Checks using Azure Pipelines.
The scenario is:

1. A GitHub repo using a GitFlow branch strategy.
2. Branch protection requiring GitHub Pull Requests on `master` and `develop` branches.
3. GitHub Status Checks integrated with an Azure Pipeline, which uses the GitVersion Azure DevOps task.
4. Latest commit on `master` branch is tagged with _1.10.0_.
5. A release branch _release/1.11.0_ is the source branch for the Pull Request.

To reproduce, create a Pull Request from `release/1.11.0` to `master`, and observe the version produced by the GitVersion Azure Pipelines task during pipeline execution.

**Expected Behavior**
Because this is a PR with a source branch of `release/1.11.0` into `master` with the latest commit tagged as `1.10.0`, I would expect the FullSemVer on the Pull Request build to begin with "1.**11**.0-PullRequest....".

I hope that I'm not way out there on my expectations!

**Actual Behavior**
The FullSemVer generated during the PR build begins with "1.**12**.0-PullRequest...".

**GitVersion.yml**
``` yaml
next-version: 1.10.0
branches:
  hotfix:
    tag: hotfix
  release:
    tag: rc
ignore:
  sha: []
merge-message-formats: {}
```

**GitVersion task**
Version: 5.0.1
``` yaml
- task: GitVersion@5
  inputs:
    runtime: 'full'
    configFilePath: 'GitVersion.yml'
    updateAssemblyInfo: true
```

**Other Observations**
The behaviour when the PR is from `release/1.11.0` to `develop` is similar. However, in that case as it comes after the PR from `release/1.11.0` to `master` and then master is tagged `1.11.0`, I'd expect the version there to actually begin with `1.12.0-PullRequest...".
