### ISSUE TITLE
Relationship between Azure DevOps yaml task and tool version

### ISSUE THREAD

**Issue by phatcher** [GitTools/GitVersion#2087]
Does the DevOps yaml task automatically bring in the latest version of GitVersion or is it linked to the version of the task, i.e. at the moment the task has a version of 5.0.1 where as the public latest version of  GitVersion.Tool is 5.1.3.

Reason for asking is I'm trying to resolve #1890, so I need to know which commit to look at.

**Comment by arturcic** [comment]
Which extension are you using?

**Comment by phatcher** [comment]
According to the Marketplace extensions tab, GitVersion 5.01, which seems to support v4 or v5, i.e.

```
steps:
- task: GitVersion@4
  displayName: 'GitVersion'
  inputs:
    updateAssemblyInfo: true
    preferBundledVersion: false
```

I presume the "preferBundledVersion" controls whether it uses the version supplied with the task or another one, but there's no evidence in the log of what it being used, just the extension version.
