### ISSUE TITLE
UseGitVersion task needs config file to be specified

### ISSUE THREAD

**Issue by phatcher** [GitTools/GitVersion#2094]
Changed over to the new DevOps task, but it fails to pick up the config file

```
- task: UseGitVersion@5
  displayName: 'GitVersion'
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: false
```
This runs
`/opt/hostedtoolcache/GitVersion.Tool/5.1.3/x64/dotnet-gitversion /home/vsts/work/1/s /output buildserver /nofetch`

And I get the wrong version number e.g. `0.2.0+55` since it doesn't pick up the config file

Change this to
```
- task: UseGitVersion@5
  displayName: 'GitVersion'
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: false
    useConfigFile: true
    configFilePath: './gitversion.yml'
```
and we get
`/opt/hostedtoolcache/GitVersion.Tool/5.1.3/x64/dotnet-gitversion /home/vsts/work/1/s /output buildserver /nofetch /config /home/vsts/work/1/s/gitversion.yml`

which then correctly computes the build number.

I'd expect it to pick up the standard configuration file without being told?

**Comment by asbjornu** [comment]
If you execute `GitVersion.exe`, the config file should indeed be picked up. Perhaps there's a discreapancy between the `exe` and the `dotnet` tool, for some reason?

**Comment by arturcic** [comment]
Both use the same csproj so it should be the same

**Comment by phatcher** [comment]
Can I suggest adding a debug mode for the command line, so we can see the configuration assumptions GitVersion's making - would make debugging this sort of issue much easier.

**Comment by arturcic** [comment]
Please do, please create a separate issue

**Comment by KZeronimo** [comment]
@phatcher - in Azure DevOps what was the default behavior you are expecting in the absence of an explicit config?

I dumped the "default" config `dotnet-gitversion /showconfig` and this matched the behavior I was expecting.

Asking for my learning :)

```yml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  develop:
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: ^dev(elop)?(ment)?$
    source-branches: []
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 0
  master:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$
    source-branches:
    - develop
    - release
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
  release:
    mode: ContinuousDelivery
    tag: beta
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^releases?[/-]
    source-branches:
    - develop
    - master
    - support
    - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 30000
  feature:
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^features?[/-]
    source-branches:
    - develop
    - master
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  pull-request:
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)'
    track-merge-target: false
    regex: ^(pull|pull\-requests|pr)[/-]
    source-branches:
    - develop
    - master
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^hotfix(es)?[/-]
    source-branches:
    - develop
    - master
    - support
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  support:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^support[/-]
    source-branches:
    - master
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
ignore:
  sha: []
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
```
