### ISSUE TITLE
gitversion mainline: increment "minor" by default, except for from specific branch

### ISSUE THREAD

**Issue by dbak-invn** [GitTools/GitVersion#2105]
I have a fairly particular need, and I am hoping that it is possible with gitversion.

I have set up gitversion in mainline mode, so that any commit or merge increments minor. Great!

However, there are some kinds of branches (a branch like test_features/test1) for which I want mainline to increment the patch version instead and not the minor version, when a PR from that branch is merged.

Is this possible?

Here is my GitVersion.yml:

```
assembly-versioning-scheme: MajorMinor
assembly-file-versioning-scheme: MajorMinor
mode: mainline
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$
    source-branches:
    - develop
    - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: true
    pre-release-weight: 55000
  feature:
    tag: useBranchName
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^features?[/-]
    source-branches:
    - master
    - feature
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    tag: beta
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^hotfix(es)?[/-]
    source-branches:
    - master
    - feature
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  test_feature:
    tag: useBranchName
    increment: Patch
    regex: ^test_features?[/-]
    source-branches:
    - master
    - feature
    is-release-branch: false
    is-mainline: false

```

**Comment by asbjornu** [comment]
I might be wrong, but my knee-jerk reaction is that this isn't possible to achieve. `increment` configures the version component to increment when GitVersion is run **on that very branch** and not what's incremented when that branch is merged into another.

There are heuristics around release branches and such that override this default behaviour, but unless you define `test_feature` as release branches and name them with the version number you want as a result of the merge, I don't think what you ask is possible.

**Comment by Dobriy33** [comment]
Hi. I configured GitVersion same way 2 years ago.
Here is the configuration that works with GitVersion 4. Hope this will be useful.

```
assembly-versioning-scheme: MajorMinorPatch
mode: Mainline
branches:
  master:
    is-mainline: false
  develop:
    tag: ""
    is-mainline: true
    increment: none
    is-source-branch-for: ['feature', 'fix']
  feature:
    increment: Minor
  fix:
    regex: fix(es)?[/-]
    increment: patch
    source-branches: ['develop', 'master']
ignore:
  sha: []
```

Merge feature to develop -> increment Minor
Merge fix to develop -> increment Patch
