### ISSUE TITLE
Problem using UseGitVersion targetPath parameter

### ISSUE THREAD

**Issue by robertlarkins** [GitTools/GitVersion#2107]
I'm using the UseGitVersion task in a set of job in Azure DevOps. The first job builds the solution, which is then published as an artifact. The subsequent jobs consume this artifact and are used to publish nuget packages. By default UseGitVersion targets the `$(System.DefaultWorkingDirectory) (c:\agent_work\1)`, but as the artifact is downloaded into `$(Pipeline.Workspace) (c:\agent_work\1\s)` UseGitVersion needs to target the artifact instead.
I tried using the `targetPath` parameter to change where UseGitVersion operates but ran into difficulty.
When using an absolute path for `targetPath`:
```yaml
variables:
  buildArtifactName: 'rezare_lib'
  buildArtifact: '$(Pipeline.Workspace)/$(buildArtifactName)'
```

```yaml
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: '5.x'
      useConfigFile: true
      configFilePath: '$(buildArtifact)/Rezare.Lib-GitVersion.yml'
      includePrerelease: true
      additionalArguments: '/updateassemblyinfo "$(buildArtifact)/Rezare.Lib/Properties/AssemblyInfo.cs"'
      targetPath: '$(buildArtifact)'
```
I get the following:
> Tool 'gitversion.tool' (version '5.1.3') was successfully installed.
> Caching tool: GitVersion.Tool 5.1.3 x64
> Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\GitVersion.Tool\5.1.3\x64
> C:\hostedtoolcache\windows\GitVersion.Tool\5.1.3\x64\dotnet-gitversion.exe d:/a/1/s/d:/a/1/rezare_lib /output buildserver /nofetch /config d:\a\1\rezare_lib\Rezare.Lib-GitVersion.yml /updateassemblyinfo d:\a\1/rezare_lib/Rezare.Lib/Properties/AssemblyInfo.cs
> WARN [02/16/20 22:24:15:94] The working directory 'd:/a/1/s/d:/a/1/rezare_lib' does not exist.
> INFO [02/16/20 22:24:15:95] IsDynamicGitRepository: False
> ERROR [02/16/20 22:24:16:39] An unexpected error occurred:
> System.IO.DirectoryNotFoundException: Can't find the .git directory in 
>    at GitVersion.GitPreparer.GetProjectRootDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 94
>    at GitVersion.GitPreparer.GetProjectRootDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 27
>    at GitVersion.Configuration.ConfigFileLocator.Verify(IGitPreparer gitPreparer) in D:\a\1\s\src\GitVersionCore\Configuration\ConfigFileLocator.cs:line 61
>    at GitVersion.GitVersionExecutor.VerifyConfiguration() in D:\a\1\s\src\GitVersionExe\GitVersionExecutor.cs:line 153
>    at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\1\s\src\GitVersionExe\GitVersionExecutor.cs:line 105
> INFO [02/16/20 22:24:16:39] 
> INFO [02/16/20 22:24:16:39] Attempting to show the current git graph (please include in issue): 
> INFO [02/16/20 22:24:16:39] Showing max of 100 commits
> ERROR [02/16/20 22:24:16:40] Couldn't dump the git graph due to the following error: System.ComponentModel.Win32Exception (267): The directory name is invalid.
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo) in D:\a\1\s\src\GitVersionCore\Helpers\ProcessHelper.cs:line 26
>    at GitVersion.Helpers.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables) in D:\a\1\s\src\GitVersionCore\Helpers\ProcessHelper.cs:line 120
>    at GitVersion.Extensions.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits) in D:\a\1\s\src\GitVersionCore\Extensions\LibGitExtensions.cs:line 120
>    at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\1\s\src\GitVersionExe\GitVersionExecutor.cs:line 138
> INFO [02/16/20 22:24:15:93] Applicable build agent found: 'AzurePipelines'.WARN [02/16/20 22:24:15:94] The working directory 'd:/a/1/s/d:/a/1/rezare_lib' does not exist.INFO [02/16/20 22:24:15:95] IsDynamicGitRepository: FalseERROR [02/16/20 22:24:16:39] An unexpected error occurred:
> System.IO.DirectoryNotFoundException: Can't find the .git directory in 
>    at GitVersion.GitPreparer.GetProjectRootDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 94
>    at GitVersion.GitPreparer.GetProjectRootDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 27
>    at GitVersion.Configuration.ConfigFileLocator.Verify(IGitPreparer gitPreparer) in D:\a\1\s\src\GitVersionCore\Configuration\ConfigFileLocator.cs:line 61
>    at GitVersion.GitVersionExecutor.VerifyConfiguration() in D:\a\1\s\src\GitVersionExe\GitVersionExecutor.cs:line 153
>    at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\1\s\src\GitVersionExe\GitVersionExecutor.cs:line 105INFO [02/16/20 22:24:16:39] INFO [02/16/20 22:24:16:39] Attempting to show the current git graph (please include in issue): INFO [02/16/20 22:24:16:39] Showing max of 100 commitsERROR [02/16/20 22:24:16:40] Couldn't dump the git graph due to the following error: System.ComponentModel.Win32Exception (267): The directory name is invalid.
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo) in D:\a\1\s\src\GitVersionCore\Helpers\ProcessHelper.cs:line 26
>    at GitVersion.Helpers.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables) in D:\a\1\s\src\GitVersionCore\Helpers\ProcessHelper.cs:line 120
>    at GitVersion.Extensions.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits) in D:\a\1\s\src\GitVersionCore\Extensions\LibGitExtensions.cs:line 120
> Finishing: GitVersion

So I tried making the path relative:
```yaml
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: '5.x'
      useConfigFile: true
      configFilePath: '$(buildArtifact)/Rezare.Lib-GitVersion.yml'
      includePrerelease: true
      additionalArguments: '/updateassemblyinfo "$(buildArtifact)/Rezare.Lib/Properties/AssemblyInfo.cs"'
      targetPath: '../$(buildArtifactName)'
```

Which gives this:
> You can invoke the tool using the following command: dotnet-gitversion
> Tool 'gitversion.tool' (version '5.1.3') was successfully installed.
> Caching tool: GitVersion.Tool 5.1.3 x64
> Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\GitVersion.Tool\5.1.3\x64
> ##[error]Error: Directory not found at ../rezare_lib
> Finishing: GitVersion

Is this a bug, or am I just trying to use `targetPath` incorrectly for re-specifying where UseGitVersion should operate?
