### ISSUE TITLE
Not correctly calculating version of child branch using mainline

### ISSUE THREAD

**Issue by dbak-invn** [GitTools/GitVersion#2108]
I have no idea how or why gitversion is producing the version numbers it is.

I have a master branch, which is calculated to be v3.20.0 (I have minor auto-incrementing).

I checkout -b features/fake_new_branch. This is a totally fresh branch. It has version 3.10.2. My version has magically decremented.

Is this a bug? Is this the intended behavior, for some reason?

How can I get the correct version in the feature branch?

```
C:\Users\dbak\Projects\firmware_2 (master -> origin)
λ bin\GitVersion.exe
{
  "Major":3,
  "Minor":20,
  "Patch":0,
  "PreReleaseTag":".46",
  "PreReleaseTagWithDash":"",
  "PreReleaseLabel":"",
  "PreReleaseNumber":"",
  "WeightedPreReleaseNumber":"",
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.master.Sha.0bf9ef08f233c231573532deb1b1cf611ff623cc",
  "MajorMinorPatch":"3.20.0",
  "SemVer":"3.20.0",
  "LegacySemVer":"3.20.0",
  "LegacySemVerPadded":"3.20.0",
  "AssemblySemVer":"3.20.0.0",
  "AssemblySemFileVer":"3.20.0.0",
  "FullSemVer":"3.20.0",
  "InformationalVersion":"3.20.0+Branch.master.Sha.0bf9ef08f233c231573532deb1b1cf611ff623cc",
  "BranchName":"master",
  "Sha":"0bf9ef08f233c231573532deb1b1cf611ff623cc",
  "ShortSha":"0bf9ef0",
  "NuGetVersionV2":"3.20.0",
  "NuGetVersion":"3.20.0",
  "NuGetPreReleaseTagV2":"",
  "NuGetPreReleaseTag":"",
  "VersionSourceSha":"ab548623fc35f6c1660e0f715531404e67e4d86b",
  "CommitsSinceVersionSource":46,
  "CommitsSinceVersionSourcePadded":"0046",
  "CommitDate":"2020-02-18"
}

C:\Users\dbak\Projects\firmware_2 (master -> origin)
λ git checkout -b features/fake_new_branch
Switched to a new branch 'features/fake_new_branch'
M       GitVersion.yml

C:\Users\dbak\Projects\firmware_2 (features/fake_new_branch -> origin)
λ bin\GitVersion.exe
{
  "Major":3,
  "Minor":10,
  "Patch":2,
  "PreReleaseTag":"fake-new-branch.0",
  "PreReleaseTagWithDash":"-fake-new-branch.0",
  "PreReleaseLabel":"fake-new-branch",
  "PreReleaseNumber":0,
  "WeightedPreReleaseNumber":30000,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.features-fake-new-branch.Sha.0bf9ef08f233c231573532deb1b1cf611ff623cc",
  "MajorMinorPatch":"3.10.2",
  "SemVer":"3.10.2-fake-new-branch.0",
  "LegacySemVer":"3.10.2-fake-new-branch0",
  "LegacySemVerPadded":"3.10.2-fake-new-branch0000",
  "AssemblySemVer":"3.10.0.0",
  "AssemblySemFileVer":"3.10.0.0",
  "FullSemVer":"3.10.2-fake-new-branch.0",
  "InformationalVersion":"3.10.2-fake-new-branch.0+Branch.features-fake-new-branch.Sha.0bf9ef08f233c231573532deb1b1cf611ff623cc",
  "BranchName":"features/fake_new_branch",
  "Sha":"0bf9ef08f233c231573532deb1b1cf611ff623cc",
  "ShortSha":"0bf9ef0",
  "NuGetVersionV2":"3.10.2-fake-new-branch0000",
  "NuGetVersion":"3.10.2-fake-new-branch0000",
  "NuGetPreReleaseTagV2":"fake-new-branch0000",
  "NuGetPreReleaseTag":"fake-new-branch0000",
  "VersionSourceSha":"0bf9ef08f233c231573532deb1b1cf611ff623cc",
  "CommitsSinceVersionSource":0,
  "CommitsSinceVersionSourcePadded":"0000",
  "CommitDate":"2020-02-18"
}

```

**Comment by dbak-invn** [comment]
Here is my GitVersion.yml:

```
assembly-versioning-scheme: MajorMinor
assembly-file-versioning-scheme: MajorMinor
mode: mainline
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$
    source-branches:
    - develop
    - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: true
    pre-release-weight: 55000
  feature:
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^features?[/-]
    source-branches:
    - master
    - feature
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    tag: beta
    increment: None
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^hotfix(es)?[/-]
    source-branches:
    - master
    - feature
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
ignore:
  sha: []
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
```
