### ISSUE TITLE
GitHub Actions build fails with private GitHub repo and Dependabot PR

### ISSUE THREAD

**Issue by gitfool** [GitTools/GitVersion#2116]
I've never had a problem with Dependabot PRs before, but then that's always been with public repos.

Now, with a private repo, the GitHub Actions `push` event succeeds, but the `pullrequest` event fails with `LibGit2Sharp.LibGit2SharpException: this remote has never connected`. 😕 

Relevant env vars:
```
GITHUB_ACTION=self
GITHUB_ACTIONS=true
GITHUB_ACTOR=dependabot-preview[bot]
GITHUB_BASE_REF=master
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/github/workflow/event.json
GITHUB_HEAD_REF=dependabot/nuget/Microsoft.Extensions.Configuration.CommandLine-3.1.2
GITHUB_REF=refs/pull/3/merge
GITHUB_REPOSITORY=pharos/extensions-configuration
GITHUB_RUN_ID=42047370
GITHUB_RUN_NUMBER=41
GITHUB_SHA=00c1efad94a92ac038ca47d9b893c7991caaca23
GITHUB_WORKFLOW=Build
GITHUB_WORKSPACE=/github/workspace
HOME=/github/home
PWD=/github/workspace
RUNNER_OS=Linux
RUNNER_TEMP=/home/runner/work/_temp
RUNNER_TOOL_CACHE=/opt/hostedtoolcache
RUNNER_WORKSPACE=/home/runner/work/extensions-configuration
```
[build.log](https://github.com/GitTools/GitVersion/files/4227941/build.log)

**Comment by gitfool** [comment]
Also, note that due to the current lack of support for private docker registries, I'm using a hack to run the build via a docker action defined in the repo itself.

`.github/workflows/build.yml:`
```yml
name: Build
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow

      - name: Docker pull
        run: docker pull *REDACTED*

      - name: Cake build
        uses: ./.github/actions/cake-build
```
`.github/actions/cake-build/action.yml:`
```yml
name: Cake build
runs:
  using: docker
  image: docker://*REDACTED*
  args: [ "bash", "-c", 'dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=diagnostic --target=build --publish=true' ]
```
Not sure it's relevant though as the `push` event succeeds with the same workflow and action.

**Comment by gitfool** [comment]
I've confirmed the above action hack is irrelevant by temporarily using my public [docker image](https://github.com/gitfool/cake-docker/blob/master/Dockerfile) instead:

`.github/workflows/build.yml:`
```yml
name: Build
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow

      - name: Cake build
        run: dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=diagnostic --target=build --publish=true
```
Still fails with `LibGit2Sharp.LibGit2SharpException: this remote has never connected`.
