### ISSUE TITLE
'undefined' in Command line with Azure DevOps task

### ISSUE THREAD

**Issue by pherbel** [GitTools/GitVersion#2169]
Here is my setup:

```
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'
- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
    additionalArguments: ''
```

This is the command line in the Azure DevOps log.

`/opt/hostedtoolcache/GitVersion.Tool/5.2.0/x64/dotnet-gitversion /home/vsts/work/1/s /output json /config /home/vsts/work/1/s/GitVersion.yml undefined`

And I got an error
