### ISSUE TITLE
Azure Pipeline "The feed already contains"

### ISSUE THREAD

**Issue by sb-ulg** [GitTools/GitVersion#2208]
I have been trying for a week to get versioning of dependent projects working.  Would love some help.

I have 2 projects in a solution.  ProjectA depends on ProjectB.

I have left the AssemblyVersion attributes blank in both projects
```
[assembly: AssemblyVersion("")]
[assembly: AssemblyFileVersion("")]
[assembly: AssemblyInformationalVersion("")]
```

I set up 2 GitVersion Azure Tasks to update those Files
```
- task: UseGitVersion@5
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: true
    updateAssemblyInfoFilename: '$(system.defaultworkingdirectory)\ProjectA\Properties\AssemblyInfo.cs'

- task: UseGitVersion@5
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: true
    updateAssemblyInfoFilename: '$(system.defaultworkingdirectory)\ProjectB\Properties\AssemblyInfo.cs'
```

I then Build/Pack/Push the Nuget packages
```
- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.csproj;!**/*.Tests.csproj;!**/*.Tests.Integration.csproj;!**/*.Tests.Unit.csproj'
    includeReferencedProjects: true

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: '08f8cb38-e4e4-4983-8a57-8798faec6761'
```

This works fine the first time I run this pipeline

Pushing MyCo.ProjectA.0.1.0-MyBranch.1.nupkg
Pushing MyCo.ProjectB.0.1.0-MyBranch.1.nupkg

But I assume since there is no way for the Azure Pipeline GetVersion Task to know there is already a .1 version, every time I rerun this pipeline, I get a .1 version.

I want to includeReferencedProjects, so that leaves out so many versioning schemes.  
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops.
```
versioningScheme | Cannot be used with include referenced projects.
```

All I want is for these projects to have the same version number and depend on packages that have the same version number.

Is there anyway to get some sort of versioning scheme to work with the IncludeReferencedProject option set to true?

Using GitVersion or anything else for that matter.

Can it even be done?  or do I have to increment everything manually if I want to IncludeReferencedProject.

I would really appreciate any help on this matter.
