### ISSUE TITLE
[Improvement] - Output Environment Variable names

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#2243]
**Is your improvement request related to a problem? Please describe.**

I am using azure-pipelines and trying to split my builds into multiple jobs that happen in parallel.

As such, I need to execute GitVersion.exe from job, and then access the variables in another.
The pipelines docs explain how a task in one job can set an output variable and then you can access it from another job - that is explained here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable

However the issue is, they only show accessing a variable named `myOutputVar` using an expression:

```
# Set an output variable from job A
- job: A
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the value"
    name: setvarStep
  - script: echo $(setvarStep.myOutputVar)
    name: echovar

# Map the variable into job B
- job: B
  dependsOn: A
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    myVarFromJobA: $[ dependencies.A.outputs['setvarStep.myOutputVar'] ]  # map in the variable
                                                                          # remember, expressions require single quotes
  steps:
  - script: echo $(myVarFromJobA)
    name: echovar
```

The actual variable names gitversion outputs are all prefixed "GitVersion." so for example `GitVersion.SemVer`

Sadly this doesn't seem to work when following the docs:

```
  variables:
    myVarFromJobA: $[ dependencies.A.outputs['setvarStep.GitVersion.SemVer'] ] 

```

Because accessing a variable using "property dereference" syntax requires the property name to adhere to the convention here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#variables

I have tried to guess how to altyer the above to get access to the `GitVersion.*` variables then - but nothing has worked so far - if anyone knows the answer please do chirp up!

## Detailed Description

Perhaps it would be an improvement for GitVersion to start outputting friendlier variable names - so we could use the syntax above to access them.

Simplest thing to do would be to replace the "." with an underscore instead:

GitVersion_SemVer etc.

## Context

I think this change would provide for an easier time using gitversion variables with azure-pipelines

## Possible Implementation

As above, but perhaps also output the old style variables as well to keep backwards compat?
