### ISSUE TITLE
[Bug] Updating Assembly info specifying file resulting in duplicate attributes being defined.

### ISSUE THREAD

**Issue by shaneholder** [GitTools/GitVersion#2278]
Updating Assembly info specifying file resulting in duplicate attributes being defined.

The command line being executed is:

F:\agents\agent00\_work\_tool\GitVersion.Tool\5.3.3\x64\dotnet-gitversion.exe F:/agents/agent00/_work/12/s /output json /output buildserver /updateassemblyinfo F:\agents\agent00\_work\12\s/CommonAssemblyInfo.cs

and at the end of the log I see:

 INFO [05/17/20 14:26:17:15] Updating assembly info files
  INFO [05/17/20 14:26:17:15] Found 51 files
  INFO [05/17/20 14:26:18:21] Done writing 

and the errors are CS0579: Duplicate AssemblyVersion, AssemblyFileVersion, AssemblyInformationalVersion attribute

Perhaps I'm missing an option in the build?

## Your Environment
Azure Devops:
The following two tasks are configured.  I have been using the original GitVersion task for a few years now and I'm just now updating to the new gittools tasks.

```
steps:
- task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
  displayName: gitversion/setup
  inputs:
    versionSpec: 5.x
  enabled: false

steps:
- task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
  displayName: gitversion/execute
  inputs:
    updateAssemblyInfo: true
    updateAssemblyInfoFilename: '$(Build.SourcesDirectory)/CommonAssemblyInfo.cs'
  enabled: false
```
