### ISSUE TITLE
RC tags trigger incorrect increments.

### ISSUE THREAD

**Issue by JimBobSquarePants** [GitTools/GitVersion#2329]
**Describe the bug**
Following an RC release tag version, e.g.`v1.0.0-rc.2` incremented prerelease values are reset and appear to be based upon only the commit count since the release.  This breaks the upgrade path for users. 

I've looked at #1600 which appears to be related but only contains tests without fixes. #1844 may be related but was closed as stale.

## Expected Behavior

I would expect the version to take into consideration the new RC tag and not reset.

## Actual Behavior

Calculated increments are reset which leads to version numbers that are lower than previous builds.

## Steps to Reproduce

Using the following GitVersion.yml

```yaml
continuous-delivery-fallback-tag: ci
branches:
    master:
        tag: unstable
        mode: ContinuousDeployment
    pull-request:
        tag: pr

```
- Build (version increments)
- Create Tag
- Build (version resets)

An example of such appears at the following [Github Action](https://github.com/SixLabors/ImageSharp/runs/776136432?check_suite_focus=true#step:8:85)

## Context

It's rendered my nightly builds effectively useless for consumers.

## Your Environment

- Version Used: Action 0.9.3, GitVersion 5.3.6
- Operating System and version (Windows 10, Ubuntu 18.04): All 
- Link to your project: https://github.com/SixLabors/ImageSharp
- Link to your CI build (if appropriate): https://github.com/SixLabors/ImageSharp/runs/776136432?check_suite_focus=true#step:8:85
