### ISSUE TITLE
[Bug] Versioning sources inconsistent or wrong between defaults and commit messages

### ISSUE THREAD

**Issue by mtaylorfsmb** [GitTools/GitVersion#2342]
I'm really unsure where the actual issue is so I'll describe the scenarios we've tested along with the configurations we're using.

## Expected Behavior

When defining branch properties any unspecified values should inherit from the same properties default outside the branches as documented in the wiki. That does not appear to occur in all cases or something else entirely is going on (see below).

Should be able to increment master branch using minor versioning and still be able to commit PRs to master with a semver message that overrides that versioning.

## Actual Behavior

When specifying the increment mode on master it seems to override semver patch settings and use minor versioning anyway. 

1.0 currently being generated
Commit PR with +semver: patch should produce 1.0.1
1.1 is generated instead

Setting the default to minor, not setting in the branch (or setting to Inherit) causes patch versioning to be used on normal builds.

1.0 currently being generated
Normal PR with no +semver but default set to Minor, not on branch
1.0.1 is generated instead.

## Steps to Reproduce

From our understanding feature branches which the devs work out of out should increment patch # which is fine because we don't care about the versioning there. However master will increment minor version by default which is exactly what we want. It shouldn't matter here but the default versioning is patch.

The issue comes in with hotfixes. We branch from master (using feature branches) to fix the issue. When we commit into the feature branch we include `+semver: patch` which increments the patch version. We then PR into master using squash merge which brings the commit messages along. But just in case we also put the `+semver: patch` in the PR to master. But we found that the minor version is incremented anyway. It seems like putting the increment value in the branch overrides commit messages.

The fix to get this to work for us was to change the default increment to minor and remove the increment from the master branch.

```yaml
increment: Minor
branches:
   master:
      ...
      #increment: Minor
```

But now it seems like the default isn't actually be used because the master branch versions using the patch number on a normal commit (without any commit message). Setting the increment value in the branch to `Inherit` doesn't change anything.

## Context
Historically we have been using the following configuration to version master (note: I'm only including master here as this is the branch we're having issues with).

```yaml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: None
commit-message-incrementing: Enabled 
mode: ContinuousDelivery  
increment: Patch
branches:
  master:
    regex: master
    tag: ''    
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    is-mainline: true        
       
  # features don't care about versioning so we use whatever master happens to be plus a label (+alpha) 
  feature:
     regex: .*
     tag: alpha
     increment: Patch
     tag-number-pattern: '[/-](?<number>\d+)'     
     source-branches:
     - master
```

## Your Environment
Windows 10
Gitversion 
Using Gittools.gitversion@5 from Azure Devops
