### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by faina09** [GitTools/GitVersion#2358]
**Describe the bug**
I have a simple .net core 3.1 project in VS2019 including **GitVersionTask Version=5.3.7** that normally compiles in VS.
I have a GitLab job that compiles too if GitVersionTask is removed from packages

## Expected Behavior
compilation by gitlab job

## Actual Behavior
I got an error:

`C:\Users\xxxx\.nuget\packages\gitversiontask\5.3.7\build\GitVersionTask.targets(46,9): error : GitVersionException: Cannot find commit 37263fb6bcfabee8cff19327eb128314dd5c7be3. Please ensure that the repository is an unshallow clone with `git fetch --unshallow`. [C:\Gitlab-Runner\builds\3VbVuPNg\0\xxxx\blazor\BlazorApp1\BlazorApp1.csproj]`

and cannot continue the compilation.

## Possible Fix
- remove GitVersionTask from packages (!)
- may be [something like this ](https://gitter.im/GitTools/GitVersion)? (search for "GitVersionTask")

## Steps to Reproduce
difficult: it seems to depend from our GitLabRunner for windows application, the previous one was working fine (see Environment)

## Context
- I checked the issues #912 , but my git has a master and the unfound commit is the last in the master branch
- I try to disable GitVersion ref #1723 adding `<DisableGitVersionTask>true</DisableGitVersionTask>` inside the 
  `<PropertyGroup>` of BlazorApp1.csproj but the fatal error persists.

## Environment
- .net core 3.1
- gitlab-runner 13.1.1 (working with previous gitlab-runner 11.2.0)
- Windows Server 2019 STD
- GitLab Community Edition 13.1.4
- my CI build contains: `dotnet publish BlazorApp1.csproj -c Pre-release`

**Comment by asbjornu** [comment]
Are you unable to make the repository unshallow?

**Comment by faina09** [comment]
I do not know how to do this.

**Comment by faina09** [comment]
Solved!
in my CI build  .gitlab-ci.yml I added:

```
variables:
  GIT_DEPTH: "1000"
```

thanks to @asbjornu for push me in the right direction

**Comment by embix** [comment]
> > Are you unable to make the repository unshallow?

> I do not know how to do this.

Simply add `git fetch --unshallow:` to the related `before_script:` section (`script` should work too):

```yml
  before_script:
    # use unshallow instead of GIT_DEPTH
    - git fetch --unshallow --all
```

**Comment by jeanplevesque** [comment]
FYI
If you're seeing this error from **Azure Pipelines**, know that it can be symptom of a [recent change to default options](https://dev.to/kkazala/azure-devops-pipelines-shallow-fetch-1-is-now-default-4656).

**Comment by sushen-dev** [comment]
> > > Are you unable to make the repository unshallow?
> 
> > I do not know how to do this.
> 
> Simply add `git fetch --unshallow:` to the related `before_script:` section (`script` should work too):
> 
> ```yaml
>   before_script:
>     # use unshallow instead of GIT_DEPTH
>     - git fetch --unshallow --all
> ```
> 
> Thus you don't get annoyed, once you hit the 1000 commits threshold (this is when you consider updating the value to 10000).

Hello, I Tried both ` - git fetch --unshallow` and `GIT_DEPTH: "1000"`
both not worked for me still I'm getting warning in sonar job as below. 
_`[WARNING] Shallow clone detected, no blame information will be provided. You can convert to non-shallow with 'git fetch --unshallow'.`_

**Comment by mc0re** [comment]
Just stumbled upon this problem in an Azure pipeline executed on a home-made VM. Possibly I lack some setting somewhere.

*Azure pipeline*
```yaml
    steps:
    - checkout: self
      clean: true
      fetchDepth: 0
      fetchTags: true
      submodules: recursive

    - task: gitversion/setup@1
      displayName: Install GitVersion
      inputs:
        versionSpec: $(GitVersionVersion)

    - task: gitversion/execute@1
      displayName: Determine current version
      inputs:
        useConfigFile: true
        configFilePath: ./GitVersion.yml
```
`GitVersionVersion` is `5.x`

*GitVersion.yml*
```yaml
mode: Mainline
branches:
  master:
    regex: ^master$|^main$
```
