### ISSUE TITLE
How to use when packaging nuget

### ISSUE THREAD

**Issue by greengumby** [GitTools/GitVersion#2360]
I am running the following

```yaml
    - task: gittools.gitversion.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        updateAssemblyInfo: true

    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      inputs:
        command: pack
        packagesToPack: '**\Foo.csproj;**\Bar.csproj'
        packDestination: '$(build.ArtifactStagingDirectory)\nuget'    
        includeReferencedProjects: true
        versioningScheme: byEnvVar
        versionEnvVar: 'GitVersion.NuGetVersion'
```

Which makes the package  Foo 1.1.0-aa-1217-0001  but I'm wondering what the setup should be if I do another commit on that branch as it won't let you push the same versioned package.

Thanks
