### ISSUE TITLE
[Bug] GitVersion not producing the correct version when building a version tag in an Azure DevOps pipeline

### ISSUE THREAD

**Issue by dsbut** [GitTools/GitVersion#2362]
**Describe the bug**
When building a tag that represents a specific version (e.g. `1.1.2`) in and Azure DevOps pipeline, using the `gitversion/execute@0` task, the version number in the tag is not honoured. Instead, it appears that the version is being incremented, and  the `tags/1.1.2` segment of the tag repo path (e.g. `refs/tags/1.1.2`) is being assigned as a `PreReleaseTag`. This results in the unexpected version number  `1.2.0-tags-1-1-2.1.1+8` instead of the expected `1.1.2`.

We use a GitFlow branch strategy, and CI triggers on tags (rather than the `master` branch itself) to trigger builds for Production deployments. For us, being able to produce the correct version number based on a version tag is critical, because our automated processes engage extra steps when build a tag vs merely building the `master` branch.

We've observed this problem with both _GitHub_ and _Azure Repos_.

This works as expected with the now deprecated `GitVerssion@5` (which I believe still invokes GitVersion `5.1.2`) task, and worked fora time with the also obsolete `UseGitVersion@5` - but the issue also now manifests with `UseGitVersion@5`. So, I imagine this is an issue that was introduced into GitVersion itself, rather than the Azure Pipelines task implementations.

## Expected Behavior
When building a version tag, such as `1.1.2`, the version number produced should be based on the tag, resulting in the version `1.1.2`.

## Actual Behavior
The version number when building a tag, appears to be based on the tag repo path, and treated as a pre-release version, producing a version number like `1.2.0-tags-1-1-2.1+8`.

## Steps to Reproduce
All our affected repositories follow the same basic patterns. GitFlow, tagging the release commit with a version tag in the `master` branch, pushing the version tag to trigger the Production automated build and release process w/ Azure DevOps with a tag-base CI trigger.

#### GitVersion.yaml

``` yaml
branches:
  hotfix:
    tag: hotfix
  release:
    tag: rc
ignore:
  sha: []
merge-message-formats: {}
```

#### azure-pipelines.yml

``` yaml
name: '$(GitVersion_FullSemVer)'

trigger:
  batch: true
  branches:
    include:
     - develop
     - feature/*
     - bugfix/*
     - release/*
     - hotfix/*
  paths:
    include:
    - '*'
    exclude:
    - README.md
  tags:
    include:
    - 1.*

stages:
  - stage: 'Build'
    displayName: 'Build'
    jobs:
      - job: 'Build'
        displayName: 'Build'
                    
        pool:
          vmImage: 'ubuntu-latest'

        steps:
        - task: gitversion/setup@0
          displayName: 'Setup GitVersion'
          inputs:
            versionSpec: '5.x'
        
        - task: gitversion/execute@0
          displayName: 'Execute GitVersion'

        ...

```

### gitversion/execute@0 Log file 
See the [log file](https://github.com/GitTools/GitVersion/files/4938702/ExecuteGitVersionDevOpsTaskLog-DiagnosticsEnabled.txt) DevOps task execution demonstrating the problem
See attached  frrom `gitversion/execute@0` task execution, produced with system diagnostics enabled.

## Context
All of our existing automated release processes that leveraged tag CI triggers and GitFlow now produce the wrong version number. Now the previously automated process now requires manual intervention, across several different products and repos.

## Your Environment
- **Build Environment**: Azure DevOps MS hosted agent
- **Agent Image**: `ubuntu-latest`
- **gitversion/execute@0 task**: 0.9.4
- **GitVersion**: 5.3.7
