### ISSUE TITLE
CommitsSinceVersionSource/BuildMetaData Counter Not Consistently Incrementing Forward

### ISSUE THREAD

**Issue by jklaus** [GitTools/GitVersion#2377]
I'm leveraging NuGetVersionV2 to set the package version on library/nuget package builds.  For some reason at random the CommitsSinceVersionSource/BuildMetaData portion of the NuGetVersionV2 string, for pre-release packages, will jump around.  In general it increments forward as you would expect but out of nowhere it will start decrementing, and sometimes just jump around all together.

Here's is what I'm seeing in the builds each time I push a commit, in chronological order:

```
6.20.0-blah0001
6.20.0-blah0002
6.20.0-blah0003
6.20.0-blah0004
6.20.0-blah0005
6.20.0-blah0001  <-- Conflicts, bumping next-version 6.20.1 to work around the issue.
6.20.1-blah0003  <-- Sequence started at 0003, I would have expected 0001
6.20.1-blah0002  <-- Decrements but doesn't result in a conflicting package as 6.20.1-blah0002 doesn't yet exist
6.20.1-blah0003  <-- Conflicts, just committed a minor touch commit to get past 0003
6.20.1-blah0004
6.20.1-blah0001  <-- Sequence jumps down to 0001, expected this should be 0005
```

Note, we are in Azure DevOps on hosted agents.  We have .Net Core 2.1 and 3.1 installed.  The version of `GitVersion.Tool` that was installed on the latest attempt (which yielded `6.20.1-blah0001`) was version 5.3.7.

On a couple of those occasions I may have had a couple local commits which were pushed at the same time, but I'm seeing the same inconsistencies even when I'm pushing a single commit.  I have our packaging build produce release packages anytime a commit lands on origin/develop (currently limited to PRs by means of branch policies), and pre-release packages anytime a commit(s) is pushed to `origin/features/*`.  The issue I'm currently experiencing is related to pushes occurring on said feature branch.  These repos are main-lining off of develop and no other branches have been committed to while all this was going on.

Here's my `GitVersion.yml`:

```yaml
mode: ContinuousDeployment
assembly-versioning-scheme: MajorMinorPatch
continuous-delivery-fallback-tag: ''
increment: Patch
next-version: 6.20.1

branches:
  develop:
    regex: dev(elop)?(ment)?$
    tag: ""
    is-mainline: true
```
