### ISSUE TITLE
[Improvement] Auto-bump Homebrew formula on release

### ISSUE THREAD

**Issue by asbjornu** [GitTools/GitVersion#2430]
As discussed in #2374, we should automatically bump the version of the GitVersion formula in Homebrew on every release.

## Context

Bumping the Homebrew formula is currently manual labour, but it can be automated so it should.

## Possible Implementation

[bump-homebrew-formula-action](https://github.com/mislav/bump-homebrew-formula-action) can do the bumping for us:

```yaml
- uses: mislav/bump-homebrew-formula-action@v1
  with:
    # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
    formula-name: gitversion
  env:
    COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
```
