### ISSUE TITLE
[Bug] Azure DevOps multiple checkout generate wrong semver (PRERELEASELABEL)

### ISSUE THREAD

**Issue by JohanSpannare** [GitTools/GitVersion#2444]
I have two projects, a base project called "Instruction.Processor" that generates an Docker image in the end.
Then i have an other project injecting stuff and generating configuration for the docker image.

In order to know the docker image tag (semver) from the other project. My idea was to checkout the base project and run gitversion resulting in the same semver. But the result differs between self checkout and  multiple checkout.

The semver contains only the version part, not branch and build info like -alpha1.

Results:
GITVERSION_SEMVER=1.3.0-alpha.1 vs GITVERSION_SEMVER=1.3.0

## Expected Behavior
Should return the same result regardless of source is self or by multiple checkout.

Expected result
```
GITVERSION_ASSEMBLYSEMFILEVER=1.3.0.0
GITVERSION_ASSEMBLYSEMVER=1.3.0.0
GITVERSION_BRANCHNAME=develop
GITVERSION_BUILDMETADATA=
GITVERSION_BUILDMETADATAPADDED=
GITVERSION_COMMITDATE=2020-11-03
GITVERSION_COMMITSSINCEVERSIONSOURCE=1
GITVERSION_COMMITSSINCEVERSIONSOURCEPADDED=0001
GITVERSION_FULLBUILDMETADATA=Branch.develop.Sha.e63df81879cccd26a450fbb34c6d8461381fed5c
GITVERSION_FULLSEMVER=1.3.0-alpha.1
GITVERSION_INFORMATIONALVERSION=1.3.0-alpha.1+Branch.develop.Sha.e63df81879cccd26a450fbb34c6d8461381fed5c
GITVERSION_LEGACYSEMVER=1.3.0-alpha1
GITVERSION_LEGACYSEMVERPADDED=1.3.0-alpha0001
GITVERSION_MAJOR=1
GITVERSION_MAJORMINORPATCH=1.3.0
GITVERSION_MINOR=3
GITVERSION_NUGETPRERELEASETAG=alpha0001
GITVERSION_NUGETPRERELEASETAGV2=alpha0001
GITVERSION_NUGETVERSION=1.3.0-alpha0001
GITVERSION_NUGETVERSIONV2=1.3.0-alpha0001
GITVERSION_PATCH=0
GITVERSION_PRERELEASELABEL=alpha
GITVERSION_PRERELEASENUMBER=1
GITVERSION_PRERELEASETAG=alpha.1
GITVERSION_PRERELEASETAGWITHDASH=-alpha.1
GITVERSION_SEMVER=1.3.0-alpha.1
GITVERSION_SHA=e63df81879cccd26a450fbb34c6d8461381fed5c
GITVERSION_SHORTSHA=e63df81
GITVERSION_VERSIONSOURCESHA=8f0f4ff35f136da0763b6136ec4b90ef4f078113
GITVERSION_WEIGHTEDPRERELEASENUMBER=1

```
## Actual Behavior
When using GitVersion on none self source the result differs like below.

```
GITVERSION_ASSEMBLYSEMFILEVER=1.3.0.0
GITVERSION_ASSEMBLYSEMVER=1.3.0.0
GITVERSION_BRANCHNAME=develop
GITVERSION_BUILDMETADATA=
GITVERSION_BUILDMETADATAPADDED=
GITVERSION_COMMITDATE=2020-11-03
GITVERSION_COMMITSSINCEVERSIONSOURCE=1
GITVERSION_COMMITSSINCEVERSIONSOURCEPADDED=0001
GITVERSION_FULLBUILDMETADATA=Branch.develop.Sha.e63df81879cccd26a450fbb34c6d8461381fed5c
GITVERSION_FULLSEMVER=1.3.0
GITVERSION_INFORMATIONALVERSION=1.3.0+Branch.develop.Sha.e63df81879cccd26a450fbb34c6d8461381fed5c
GITVERSION_LEGACYSEMVER=1.3.0
GITVERSION_LEGACYSEMVERPADDED=1.3.0
GITVERSION_MAJOR=1
GITVERSION_MAJORMINORPATCH=1.3.0
GITVERSION_MINOR=3
GITVERSION_NUGETPRERELEASETAG=
GITVERSION_NUGETPRERELEASETAGV2=
GITVERSION_NUGETVERSION=1.3.0
GITVERSION_NUGETVERSIONV2=1.3.0
GITVERSION_PATCH=0
GITVERSION_PRERELEASELABEL=
GITVERSION_PRERELEASENUMBER=
GITVERSION_PRERELEASETAG=
GITVERSION_PRERELEASETAGWITHDASH=
GITVERSION_SEMVER=1.3.0
GITVERSION_SHA=e63df81879cccd26a450fbb34c6d8461381fed5c
GITVERSION_SHORTSHA=e63df81
GITVERSION_VERSIONSOURCESHA=e63df81879cccd26a450fbb34c6d8461381fed5c
GITVERSION_WEIGHTEDPRERELEASENUMBER=

```

## Steps to Reproduce
azure-pipline.yml
```
resources:
  repositories:
    - repository: self
      type: git
    - repository: InstructionProcessor
      type: githubenterprise
      endpoint: github.xxxxxx.se
      name: PAM/Instruction.Processor
      ref: refs/heads/develop
      
variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  ProjectName: "Instruction.Processor.1511PRP.Factory"
   

stages:
  - stage: Build
    jobs:
      - job: Dotnet
        steps:
        - checkout: self
        - checkout: InstructionProcessor

        - script: dir $(AGENT.BUILDDIRECTORY)\s
        - task: GitVersion@5
          inputs:
            runtime: 'core'
            updateAssemblyInfo: true
            targetPath: 'Instruction.Processor'
        - script: set

        - task: GitVersion@5
          inputs:
            runtime: 'core'
            updateAssemblyInfo: true
            targetPath: 'Instruction.Processor.1511PRP'
        - script: set
```

## Context
Calculate same semver from different build pipline on same source.

## Your Environment
On prem Azure Devops Server 2020
