### ISSUE TITLE
Hotfix branch is not increasing Patch

### ISSUE THREAD

**Issue by roofiq** [GitTools/GitVersion#2454]
Hello,

I am using version 5.5. I want to implement semantic versioning to my GitFlow. I got quite a lot of errors but have managed to work it out - the documentation is really poor.
Still I can't manage to achieve one thing. On bugfixing situation, when I am creating new branch from master, it should have increased patch number - i.e. `master` is 1.0.0, so the `hotfix/test` should be 1.0.1 but it is 1.0.0.

I can achieve above when I am adding comment '+semver: patch'.
Then, when I want to create 2nd patch, the version is not increasing at all (even with the comment).
How it should work in this scenario?
Here is mine GitVersion file.

```yaml
next-version: 2.0.0
branches:
  master:        
    regex: master
    mode: ContinuousDelivery
    tag: ''    
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
   hotfix:
    tag: beta
    mode: ContinuousDelivery
    regex: ^hotfix(es)?[/-]
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: false
ignore:
  sha: []
merge-message-formats: {}
```

Thanks,
Rafal
