### ISSUE TITLE
[Bug] on master, patch is incrimented rather than minor on azure pipeline

### ISSUE THREAD

**Issue by TalalYousif** [GitTools/GitVersion#2560]
**Describe the bug**
Started using GiVersion on an existing repo. tagged master with 0.7.0 and created a feature branch. The feature branch had 0.8.0 as expected but after merging to master, master had 0.7.1 instead of 0.8.0.

This is only seen on azure pipeline and not on the local machine.

GitVersion.yml
```

mode: ContinuousDelivery
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
commit-message-incrementing: Enabled
branches: 
  master:
    regex: ^master$|^main$
    mode: ContinuousDeployment
    increment: Minor
    tag: snapshot
  feature:
    regex: ^features?[/-]
    mode: ContinuousDelivery
    tag: ''
    increment: Minor
  bugFix:
    regex: ^bug(fix)?[/-]
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    source-branches: ['master', 'feature', 'bugFix']
ignore:
  sha: []
merge-message-formats: {}

```

## Expected Behavior
0.8.0 on master

## Actual Behavior
0.7.1 on master

## Output from azure-devops
INFO [01/22/21 9:59:05:38] Working directory: /home/vsts/work/1/s
INFO [01/22/21 9:59:05:41] Branch from build environment: refs/heads/master
INFO [01/22/21 9:59:05:41] Project root is: /home/vsts/work/1/s/
INFO [01/22/21 9:59:05:41] DotGit directory is: /home/vsts/work/1/s/.git
    INFO [01/22/21 9:59:05:49] Cache file /home/vsts/work/1/s/.git/gitversion_cache/AC5461CA6541B080EDB759322DD5FB45594A5A0A.yml not found.
  INFO [01/22/21 9:59:05:49] End: Loading version variables from disk cache (Took: 0.88ms)
  INFO [01/22/21 9:59:05:58] Using latest commit on specified branch
  INFO [01/22/21 9:59:05:59] Begin: Attempting to inherit branch configuration from parent branch
    INFO [01/22/21 9:59:05:59] Begin: Finding branch source of 'master'
    INFO [01/22/21 9:59:05:60] End: Finding branch source of 'master' (Took: 8.40ms)
    INFO [01/22/21 9:59:05:60] Begin: Getting branches containing the commit '43d06e7'.
      INFO [01/22/21 9:59:05:60] Trying to find direct branches.
      INFO [01/22/21 9:59:05:60] No direct branches found, searching through all branches.
      INFO [01/22/21 9:59:05:60] Searching for commits reachable from 'feature/ERPINT-244'.
      INFO [01/22/21 9:59:05:61] The branch 'feature/ERPINT-244' has no matching commits.
      INFO [01/22/21 9:59:05:61] Searching for commits reachable from 'origin/feature/ERPINT-244'.
      INFO [01/22/21 9:59:05:61] The branch 'origin/feature/ERPINT-244' has no matching commits.
    INFO [01/22/21 9:59:05:61] End: Getting branches containing the commit '43d06e7'. (Took: 9.25ms)
    INFO [01/22/21 9:59:05:61] Found possible parent branches: 
    WARN [01/22/21 9:59:05:61] Failed to inherit Increment branch configuration, no branches found.
Falling back to master branch config
    WARN [01/22/21 9:59:05:61] Fallback branch wants to inherit Increment branch configuration from itself. Using patch increment instead.
  INFO [01/22/21 9:59:05:61] End: Attempting to inherit branch configuration from parent branch (Took: 28.87ms)
  INFO [01/22/21 9:59:05:64] Running against branch: master (43d06e7 Merged in feature/ERPINT-401 (pull request #15))
  INFO [01/22/21 9:59:05:64] Begin: Calculating base versions
    INFO [01/22/21 9:59:05:64] Fallback base version: 0.1.0 with commit count source b23704b5f9768a82fe51836d69b6db40ab1be67e
    INFO [01/22/21 9:59:05:70] Git tag '0.7.0': 0.7.0 with commit count source 92159dce29f2dd95145582d50d3e8ca692938ee4
    INFO [01/22/21 9:59:05:72] Found multiple base versions which will produce the same SemVer (0.7.1), taking oldest source for commit counting (Git tag '0.7.0')
    INFO [01/22/21 9:59:05:72] Base version used: Git tag '0.7.0': 0.7.0 with commit count source 92159dce29f2dd95145582d50d3e8ca692938ee4
  INFO [01/22/21 9:59:05:72] End: Calculating base versions (Took: 82.04ms)
  INFO [01/22/21 9:59:05:72] 1 commits found between 92159dc Merged in feature/ERPINT-375 (pull request #14) and 43d06e7 Merged in feature/ERPINT-401 (pull request #15)
  INFO [01/22/21 9:59:05:72] Begin: Getting version tags from branch 'refs/heads/master'.
  INFO [01/22/21 9:59:05:73] End: Getting version tags from branch 'refs/heads/master'. (Took: 1.74ms)
  INFO [01/22/21 9:59:05:73] Begin: Creating dictionary
  INFO [01/22/21 9:59:05:74] End: Creating dictionary (Took: 4.77ms)
  INFO [01/22/21 9:59:05:74] Begin: Storing version variables to cache file /home/vsts/work/1/s/.git/gitversion_cache/AC5461CA6541B080EDB759322DD5FB45594A5A0A.yml
  INFO [01/22/21 9:59:05:77] End: Storing version variables to cache file /home/vsts/work/1/s/.git/gitversion_cache/AC5461CA6541B080EDB759322DD5FB45594A5A0A.yml (Took: 35.70ms)
Executing GenerateSetVersionMessage for 'AzurePipelines'.
Executing GenerateBuildLogOutput for 'AzurePipelines'.
{
  "Major": 0,
  "Minor": 7,
  "Patch": 1,
  "PreReleaseTag": "snapshot.1",
  "PreReleaseTagWithDash": "-snapshot.1",
  "PreReleaseLabel": "snapshot",
  "PreReleaseLabelWithDash": "-snapshot",
  "PreReleaseNumber": 1,
  "WeightedPreReleaseNumber": 55001,
  "BuildMetaData": "",
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.master.Sha.43d06e767a093c87199673fe3b4e0aac2af63fa7",
  "MajorMinorPatch": "0.7.1",
  "SemVer": "0.7.1-snapshot.1",
  "LegacySemVer": "0.7.1-snapshot1",
  "LegacySemVerPadded": "0.7.1-snapshot0001",
  "AssemblySemVer": "0.7.1.0",
  "AssemblySemFileVer": "0.7.1.0",
  "FullSemVer": "0.7.1-snapshot.1",
  "InformationalVersion": "0.7.1-snapshot.1+Branch.master.Sha.43d06e767a093c87199673fe3b4e0aac2af63fa7",
  "BranchName": "master",
  "EscapedBranchName": "master",
  "Sha": "43d06e767a093c87199673fe3b4e0aac2af63fa7",
  "ShortSha": "43d06e7",
  "NuGetVersionV2": "0.7.1-snapshot0001",
  "NuGetVersion": "0.7.1-snapshot0001",
  "NuGetPreReleaseTagV2": "snapshot0001",
  "NuGetPreReleaseTag": "snapshot0001",
  "VersionSourceSha": "92159dce29f2dd95145582d50d3e8ca692938ee4",
  "CommitsSinceVersionSource": 1,
  "CommitsSinceVersionSourcePadded": "0001",
  "UncommittedChanges": 0,
  "CommitDate": "2021-01-22"
}
## Your Environment

- Version Used:  5.6.4
- Operating System and version Ubuntu-latest on azure devops
