### ISSUE TITLE
[Bug] Accidental Breacking change with source-branches config

### ISSUE THREAD

**Issue by david-driscoll** [GitTools/GitVersion#2589]
**Describe the bug**
If the source branches configuration currently references `master` then upgrading to 5.6.5 will break gitversion.

## Expected Behavior
Upgrading to 5.6.5 shouldn't see any breaking changes between versions

## Actual Behavior
Upgrade to 5.6.5 causes a breaking change if the `source-branches` configuration references `master`

## Possible Fix
Unsure

## Steps to Reproduce
Example config:
```yml
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
continuous-delivery-fallback-tag: ci
next-version: 0.1.0
branches:
  next:
    regex: ^next$
    mode: ContinuousDeployment
    tag: next
    increment: Major
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
    source-branches: ['master']
ignore:
  sha: []
```

If `source-branches: ['master']` is changed to ``source-branches: ['main']` everything works again.

## Context
https://github.com/GitTools/GitVersion/issues/2570

## Your Environment
Github Actions and local environment

- Version Used: 5.6.5
- Operating System and version (Windows 10, Ubuntu 18.04): All
- Link to your project: https://github.com/RocketSurgeonsGuild/Testing
- Link to your CI build (if appropriate): https://github.com/RocketSurgeonsGuild/Testing/actions/runs/546972012
