### ISSUE TITLE
Version not incrementing correctly in mode ContinuousDeployment for the branch

### ISSUE THREAD

**Issue by brvaland** [GitTools/GitVersion#2628]
**Describe the bug**
I have an issue where version is not incrementing correctly on every commit on release branch. The below method we are trying to implement:-

The master branch (v1.0.0) we create a new branch for the bug and it is merged back to master. Gitversion generate new version v.1.0.0-beta.1. Once we are ready to release i create a release branch (release/v1.0.0)

The build is triggered and with v1.0.0 for the release and if we are go around and fix any bugs on release branch we increment minor version and it only works fine for first commit i.e. pull request merge but later once it is stuck on the same version.

```
master              -- v1.0.0
release/v1.0        -- v1.0.0 (Build is triggered and last commit is tagged to v1.0.0) 
  -- 1st PR Merged  -- v1.0.1 (Build is triggered but not tagged)
  -- 2nd PR Merged  -- v1.0.1 ( Expected it to be v1.0.2)
```

```
mode: Mainline
continuous-delivery-fallback-tag: ""
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
commit-message-incrementing: MergeMessageOnly

branches:
  master:
    increment: None
    tag: "dev"
  release:
    mode: ContinuousDeployment
    regex: release?[/]
    increment: Patch
    tag: ''
    is-release-branch: true
    prevent-increment-of-merged-branch-version: true
  pull-request:
    mode: ContinuousDeployment
    tag: "pr"
    increment: None
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    regex: (pull|pull\-requests|pr|[0-9]+)[/-]
    tracks-release-branches: false
    is-release-branch: false

ignore:
  sha: []
merge-message-formats: {}
```

- Version Used:
   Windows 10
   dotnet-gitversion - v5.6.6
