### ISSUE TITLE
[Bug] Support version conversion on worker service project

### ISSUE THREAD

**Issue by TomGiz** [GitTools/GitVersion#2629]
**Describe the bug**
The Execute GitVersion Task on our Azure DevOps build pipeline is defined as follows:
```yaml
  - task: gitversion/execute@0
    displayName: "GitVersion Execute (sdk style projects)"
    inputs:
      additionalArguments: '/updateprojectfiles'
```

One of the projects is a .NET 5 worker service. When the build pipeline executes the Execute GitVersion Task, we receive the following warning :
```
WARN [03/24/21 13:59:30:77] Specified project file Sdk (Microsoft.NET.Sdk.Worker) is not supported, please ensure the project sdk is of the following: Microsoft.NET.Sdk|Microsoft.NET.Sdk.Web.
```

## Expected Behavior
A .NET 5 worker service should be supported. The DLL's file version property should be set by GitVersion.

## Actual Behavior
The above warning is output.
The DLL's file version property is not set by GitVersion.

## Possible Fix
Allow `Microsoft.NET.Sdk.Worker`.

## Context
For the time being: low impact.
DLL has a default file version set (1.0.0.0).
The Execute GitVersion Task only logs a warning and continues without error.

## Your Environment
Azure DevOps YAML pipeline.
