### ISSUE TITLE
[Bug] PreReleaseNumber for release branch uses diff to remote instead of commit count

### ISSUE THREAD

**Issue by chrbkr** [GitTools/GitVersion#2636]
On my release branch, PreReleaseNumber is calculated wrong: instead of the number of commits since branching off of the develop branch, it shows how far ahead of the remote branch I am.

Suppose this situation:
* locally, the release branch has 3 commits
* 2 of these commits have been pushed to remote

## Expected Behavior

PreReleaseNumber = 3

## Actual Behavior

PreReleaseNumber = 1
Once all commits are pushed, PreReleaseNumber = 0

## Config

```yaml
  release:
    regex: release(s)?[/-]
    mode: ContinuousDeployment
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
    pre-release-weight: 900
```

## Version Used:
* Command line: 5.5.6
* GitVersion.MsBuild: 5.6.7
