### ISSUE TITLE
[Bug] the presence of an outdated `next-version` configuration breaks the version resolution

### ISSUE THREAD

**Issue by franknarf8** [GitTools/GitVersion#2670]
**Describe the bug**

See discussion here : https://github.com/GitTools/GitVersion/discussions/2660

With this dummy git repo :

```
*   0bac05d 3 minutes ago  (HEAD -> master)
|\
| * 2922409 3 minutes ago  (feature/first-feature)
| * 2246a3e 7 minutes ago
|/
* bc00c9f 7 minutes ago  (tag: 1.2.3)
```

The following config resolves (incorrectly) to `1.2.3` :

```yaml
mode: Mainline
next-version: 1.0.0
branches:
  release:
    tag: 'rc'
  feature:
    regex: ^features?[/-]|^(pull|pull\-requests|pr)[/-]
    tag: 'dev'
  develop:
    tag: 'a'
  hotfix:
    tag: 'post'
ignore:
  sha: []
merge-message-formats: {}
```

whereas this config resolves (correctly) to `1.2.4` :

```yaml
mode: Mainline
branches:
  release:
    tag: 'rc'
  feature:
    regex: ^features?[/-]|^(pull|pull\-requests|pr)[/-]
    tag: 'dev'
  develop:
    tag: 'a'
  hotfix:
    tag: 'post'
```

## Expected Behavior

GitVersion should resolve to  `1.2.4` with both configurations

## Actual Behavior

The first config resolves (incorrectly) to `1.2.3`

## Possible Fix (Workaround)

Removing the `next-version` configuration to achieve the expected behavior.

## Context

See discussion : https://github.com/GitTools/GitVersion/discussions/2660

## Your Environment
GitVersion 5.6.8
Windows 10
