### ISSUE TITLE
feat: Incrementing patch instead minor

### ISSUE THREAD

**Issue by allanalves23** [GitTools/GitVersion#2691]
When writing commit messages to feat changes, only minor version is incremented.
Ex: On version 1.0.0
Create a commit with message: "feat: Some feature."

## Expected Behavior
The version should be 1.1.0

## Actual Behavior
The version is 1.0.1

## Steps to Reproduce
1 - Clone the repo: https://github.com/allanalves23/gitversion-minor-bug-fixture
2 - Download command line tool: https://gitversion.net/docs/usage/cli/installation
3 - On master branch create any change and create one commit: "feat: should be 1.1.0"
4 - Check version with command `dotnet-gitversion`

Output of `dotnet-gitversion` before `feat` commit:

```
{
  "Major": 1,
  "Minor": 0,
  "Patch": 0,
  "PreReleaseTag": "1",
  "PreReleaseTagWithDash": "",
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "WeightedPreReleaseNumber": 60000,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.master.Sha.7472e6fd0cb3565e91b5cc22a7f57c4d589dcf82",
  "MajorMinorPatch": "1.0.0",
  "SemVer": "1.0.0",
  "LegacySemVer": "1.0.0",
  "LegacySemVerPadded": "1.0.0",
  "AssemblySemVer": "1.0.0.0",
  "AssemblySemFileVer": "1.0.0.0",
  "FullSemVer": "1.0.0",
  "InformationalVersion": "1.0.0+Branch.master.Sha.7472e6fd0cb3565e91b5cc22a7f57c4d589dcf82",
  "BranchName": "master",
  "EscapedBranchName": "master",
  "Sha": "7472e6fd0cb3565e91b5cc22a7f57c4d589dcf82",
  "ShortSha": "7472e6f",
  "NuGetVersionV2": "1.0.0",
  "NuGetVersion": "1.0.0",
  "NuGetPreReleaseTagV2": "",
  "NuGetPreReleaseTag": "",
  "VersionSourceSha": "e79e24b2cc466ddd1d5138c8488aca389c171a79",
  "CommitsSinceVersionSource": 1,
  "CommitsSinceVersionSourcePadded": "0001",
  "UncommittedChanges": 0,
  "CommitDate": "2021-05-16"
}
```

Output of `dotnet-gitversion` after `feat` commit:
```
{
  "Major": 1,
  "Minor": 0,
  "Patch": 1,
  "PreReleaseTag": "2",
  "PreReleaseTagWithDash": "",
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "WeightedPreReleaseNumber": 60000,https://github.com/allanalves23/gitversion-minor-bug-fixture
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.master.Sha.9b03dd2ceaa5a73a784c0bcd100e722643adaa8a",
  "MajorMinorPatch": "1.0.1",
  "SemVer": "1.0.1",
  "LegacySemVer": "1.0.1",
  "LegacySemVerPadded": "1.0.1",
  "AssemblySemVer": "1.0.1.0",
  "AssemblySemFileVer": "1.0.1.0",
  "FullSemVer": "1.0.1",
  "InformationalVersion": "1.0.1+Branch.master.Sha.9b03dd2ceaa5a73a784c0bcd100e722643adaa8a",
  "BranchName": "master",
  "EscapedBranchName": "master",
  "Sha": "9b03dd2ceaa5a73a784c0bcd100e722643adaa8a",
  "ShortSha": "9b03dd2",
  "NuGetVersionV2": "1.0.1",
  "NuGetVersion": "1.0.1",
  "NuGetPreReleaseTagV2": "",
  "NuGetPreReleaseTag": "",
  "VersionSourceSha": "e79e24b2cc466ddd1d5138c8488aca389c171a79",
  "CommitsSinceVersionSource": 2,
  "CommitsSinceVersionSourcePadded": "0002",
  "UncommittedChanges": 0,
  "CommitDate": "2021-05-16"
}
```

Screenshot after `feat` commit:

![Screenshot from 2021-05-16 20-13-36](https://user-images.githubusercontent.com/27220715/118415915-69fb9b00-b683-11eb-90fd-bb4aff13699a.png)

`GitVersion.yml` are on project below.

- Version Used: 5.6.9+Branch.main.Sha.ecf7f70a3d2fc18be561baeaff4eac1d930f8781
- Operating System and version (Windows 10, Ubuntu 18.04): Ubuntu 20.04.2 LTS
- Link to your project: https://github.com/allanalves23/gitversion-minor-bug-fixture

**Comment by asbjornu** [comment]
Conventional commits aren't supported out of the box, you need to [configure](https://gitversion.net/docs/reference/version-increments#conventional-commit-messages) it. I've created #3034 to make this easier to find in the documentation.

**Comment by allanalves23** [comment]
Its already configured, the settings are on `GitVersion.yml`.

```
mode: Mainline
major-version-bump-message: '\BREAKING CHANGE:\s?'
minor-version-bump-message: '\feat:\s?'
patch-version-bump-message: '\fix:\s?'
commit-message-incrementing: Enabled
branches:
  master:
    regex: ^latest$|^master$|^main$|^release$
  pull-request:
    tag: pr

```
the keyword `fix` doesn't work to increment patch version.

**Comment by asbjornu** [comment]
That is curious. What you've described above is that `feat:` doesn't increment `minor`? As you can see, we have quite a few test cases which should ensure that this is working:

https://github.com/GitTools/GitVersion/blob/666bd37b59ae731b1d2bd40b20364b692b21796e/src/GitVersion.Core.Tests/IntegrationTests/VersionBumpingScenarios.cs#L51-L94

**Comment by gep13** [comment]
@asbjornu in this case, isn't `\f` in the regex looking for a form feed?

Should the `minor-version-bump-message` not simply be: `fix:\s?`?

**Comment by allanalves23** [comment]
> That is curious. What you've described above is that feat: doesn't increment minor? As you can see, we have quite a few test cases which should ensure that this is working

Sorry @asbjornu, i mean `feat` not incrementing minor, not `fix`.

I'm reproduce the bug again, i will return soon.

**Comment by asbjornu** [comment]
> @asbjornu in this case, isn't `\f` in the regex looking for a form feed?
> 
> Should the `minor-version-bump-message` not simply be: `fix:\s?`?

@gep13, good catch! Yeah, the initial backslash looks like an error. Why did you put it there, @allanalves23? Please use the [conventional commit regexes we have documented](https://gitversion.net/docs/reference/version-increments#conventional-commit-messages):

```yaml
mode: MainLine # Only add this if you want every version to be created automatically on your main branch.
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-]*\\))?:"
patch-version-bump-message: "^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"
```

**Comment by allanalves23** [comment]
@asbjornu this works perfectly.

![image](https://user-images.githubusercontent.com/27220715/157277523-c2bd8b04-377b-409b-be78-cf06c7c1bdaa.png)

My GitVersion.yml

```
mode: MainLine # Only add this if you want every version to be created automatically on your main branch.

major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]\\))?(!:|:.\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-]*\\))?:"
patch-version-bump-message: "^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"

branches:
  master:
    regex: ^latest$|^master$|^main$|^release$
  pull-request:
    tag: pr
```

Thx @asbjornu and @gep13 !!
