### ISSUE TITLE
[Bug] GitVersion returns wrong tag

### ISSUE THREAD

**Issue by flavio-cadete-cko** [GitTools/GitVersion#2692]
Locally installed Version:
![image](https://user-images.githubusercontent.com/51323090/118452957-96003600-b6ee-11eb-8ce9-e0f6e1245a73.png)

Locally/PR Git version returns wrong tag
Using `dotnet gitversion /nofetch` works fine, e.g. returns 1.25.0-task-name
![image](https://user-images.githubusercontent.com/51323090/118451741-79173300-b6ed-11eb-86e9-a6208a9290ca.png)
![image](https://user-images.githubusercontent.com/51323090/118452305-ee830380-b6ed-11eb-859e-2e83a7d358f4.png)

---

Cake GitVersion using package:
`GitVersion.Tool&version=5.6.9`

But using GitVersion returns 1.20.0-task-name
![image](https://user-images.githubusercontent.com/51323090/118451927-a237c380-b6ed-11eb-8217-6e24e823a759.png)
![image](https://user-images.githubusercontent.com/51323090/118452046-bd0a3800-b6ed-11eb-9b14-79bae0d1baae.png)

---

My GitVersion.yml
```
mode: ContinuousDeployment
ignore:
  sha: []
branches:
  develop:
    mode: ContinuousDeployment
    tag: unstable
    increment: Minor
    is-release-branch: false
  release:
    regex: ^release(\d+)?.?(\d+)
    mode: ContinuousDelivery
    tag: rc
    increment: Minor
    is-release-branch: false
    prevent-increment-of-merged-branch-version: true
  hotfix:
    mode: ContinuousDelivery
    tag: hf
    increment: Patch
    prevent-increment-of-merged-branch-version: true
  main:
    regex: ^main
    source-branches: ['main']
    mode: ContinuousDelivery
    prevent-increment-of-merged-branch-version: true
```

My releases are being tagged with 1.20.0... instead of 1.25.0.
Can anyone please help me?
---
Edit: using version '5.6.0' seems to work. What breaking changes were made between 5.6.0 and 5.6.6? 
---
