### ISSUE TITLE
[Bug] Cannot specify assembly info file name in Azure DevOps Pipelines task (spec 5.6.10)

### ISSUE THREAD

**Issue by voodooprogramming** [GitTools/GitVersion#2769]
**Describe the bug**
Solution build fails after `gitversion/execution` due to version attributes duplication.

## Expected Behavior
Version attributes are set only in 1 file specified with `/updateassemblyinfofilename` argument.

## Actual Behavior
Version attributes are set in all the `AssemblyInfo.cs` files + in file specified with `/updateassemblyinfofilename` argument.
Build fails because of the version attributes duplication
```
Error CS0579: Duplicate 'AssemblyVersion' attribute
Error CS0579: Duplicate 'AssemblyFileVersion' attribute
Error CS0579: Duplicate 'AssemblyInformationalVersion' attribute
```

## Steps to Reproduce
Here's the task configuration YAML:
```
steps:
- task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
  displayName: gitversion/execute
  inputs:
    useConfigFile: true
    configFilePath: src/GitVersion.yml
    updateAssemblyInfo: true
    updateAssemblyInfoFilename: '$(Build.SourcesDirectory)\src\SharedAssemblyInfo.cs'
```

And command it produced upon execution:
```
dotnet-gitversion D:/a/1/s /output json /output buildserver /config D:\a\1\s\src\GitVersion.yml /updateassemblyinfo D:\a\1\s\src\SharedAssemblyInfo.cs
```

I also tried to pass arguments via `Additional GitVersion arguments` field, but no success either:
```
dotnet-gitversion D:/a/1/s /output json /output buildserver /config D:\a\1\s\src\GitVersion.yml /updateassemblyinfofilename D:\a\1\s\src\SharedAssemblyInfo.cs
Unhandled exception. GitVersion.WarningException: Could not parse command line parameter '/updateassemblyinfofilename'.
```

## Context
The solution contains 13 projects. `AssemblyInfo.cs` files without versioning attributes in all the 13 projects are linked to the `SharedAssemblyInfo.cs` file with versioning attributes.

I'm trying to target `SharedAssemblyInfo.cs` only, but all the assembly info files are modified instead.

## Your Environment
- Version Used: gitversion/setup `0.9.10`, gitversion/execute `0.9.10` with version spec `5.6.10`
- Operating System and version: Microsoft Windows Server 2016
