### ISSUE TITLE
[Bug] release branch SemVer is not incremented after starting a new release/0.2.0 from the develop branch

### ISSUE THREAD

**Issue by dmitry-mightydevops** [GitTools/GitVersion#2778]
**Describe the bug**

```sh

➜ git branch 
* [1] develop
  [2] main

git log -1

commit ca8d35a4d012de8ba62c69b024cd80464f1c9468 (HEAD -> develop, tag: 0.2.0-dev.997, origin/develop, origin/HEAD)
Author: Dmitry Semenov <dmitry@site.com>
Date:   Fri Jul 23 12:09:25 2021 -0700

    feat: add releases/main triggers for gha builds

➜ git checkout -b release/0.2.0
Switched to a new branch 'release/0.2.0'

➜ dotnet-gitversion 
{
  "Major": 0,
  "Minor": 2,
  "Patch": 0,
  "PreReleaseTag": "dev.997",
  "PreReleaseTagWithDash": "-dev.997",
  "PreReleaseLabel": "dev",
  "PreReleaseLabelWithDash": "-dev",
  "PreReleaseNumber": 997,
  "WeightedPreReleaseNumber": 997,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.release-0.2.0.Sha.ca8d35a4d012de8ba62c69b024cd80464f1c9468",
  "MajorMinorPatch": "0.2.0",
  "SemVer": "0.2.0-dev.997",
  "LegacySemVer": "0.2.0-dev997",
  "LegacySemVerPadded": "0.2.0-dev997",
  "AssemblySemVer": "0.2.0.0",
  "AssemblySemFileVer": "0.2.0.0",
  "FullSemVer": "0.2.0-dev.997",
  "InformationalVersion": "0.2.0-dev.997+Branch.release-0.2.0.Sha.ca8d35a4d012de8ba62c69b024cd80464f1c9468",
  "BranchName": "release/0.2.0",
  "EscapedBranchName": "release-0-2-0",
  "Sha": "ca8d35a4d012de8ba62c69b024cd80464f1c9468",
  "ShortSha": "ca8d35a",
  "NuGetVersionV2": "0.2.0-dev997",
  "NuGetVersion": "0.2.0-dev997",
  "NuGetPreReleaseTagV2": "dev0997",
  "NuGetPreReleaseTag": "dev0997",
  "VersionSourceSha": "ca8d35a4d012de8ba62c69b024cd80464f1c9468",
  "CommitsSinceVersionSource": 0,
  "CommitsSinceVersionSourcePadded": "0000",
  "UncommittedChanges": 2,
  "CommitDate": "2021-07-23"
}
```

## Expected Behavior

However I'm expecting `"SemVer": "0.2.0-dev.997"` to be `"SemVer": "0.2.0-beta.1"`,

## Actual Behavior

`"SemVer": "0.2.0-dev.997"`

## Possible Fix

Create a new commit in the release/* branch and then it gets a proper tag.

## Your Environment

GitVersion.yml:

```yaml
assembly-versioning-scheme: MajorMinor
mode: Mainline
tag-pre-release-weight: 0
legacy-semver-padding: 0
build-metadata-padding: 0
branches:
  main:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
  release:
    regex: ^release(s)?[/-]
    mode: ContinuousDelivery
    tag: 'beta'
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
    pre-release-weight: 0
  feature:
    regex: ^feature(s)?[/-]
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
  hotfix:
    regex: ^hotfix(es)?[/-]
    mode: ContinuousDelivery
    tag: 'hotfix'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false
  support:
    regex: ^support[/-]
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
  develop:
    regex: ^dev(elop)?(ment)?$
    mode: ContinuousDeployment
    tag: dev
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: false
    is-release-branch: false
```

- Version Used: 5.6.10+Branch.main.Sha.e9013533474e8e46b6a0ca60d20d02f3680b5980
- I'm using dotnet-gitversion in Fedora.
