### ISSUE TITLE
[Bug] Version is not incrementing after a pull request from Release/1.1.0 to main is merged.

### ISSUE THREAD

**Issue by jeremyruffell** [GitTools/GitVersion#2814]
**Describe the bug**
Version is not incrementing after a pull request from Release/1.1.0 to main is merged.

## Expected Behavior
Version on main will bump to `1.1.0`

## Actual Behavior
Version on main bumps to `1.0.1`

## Steps to Reproduce
This is my GitVersion.yaml:
```yaml
mode: ContinuousDeployment
continuous-delivery-fallback-tag: ''
branches: 
  main:
    tracks-release-branches: true
merge-message-formats: {}
ignore:
  sha: []  
```

1. Create tag named `1.0.0` on the `main` branch
2. Create the `develop` branch off of main (GitVersion shows this as 1.1.0, which is great, this is what I want)
3. Create the `feature/myfeature` branch off of develop
4. Create a commit to `feature/myfeature`
5. Pull request from `feature/myfeature -> develop`
6. At this point we are at `1.1.0`, and this makes complete sense to me.
7. Create the `release` branch off of `develop`
8. If I run GitVersion, I am still at `1.1.0`, again, this makes sense to me.
9. Pull request from release -> main 
10. Main now shows the version is `1.0.1`. 

Why is GitVersion not recognizing the history that I just pulled from the `release` branch?

## Context
Instead of merging release straight into main we need status check to pass, e.g. approval from a set team.

## Your Environment
- Version Used: `5.5.1+Branch.master.Sha.26def753db54e1cf430f0651d5800e5e0e607147`
- Operating System and version (Windows 10, Ubuntu 18.04): `Windows 10`
- Link to your project: `Private Repo`
- Link to your CI build (if appropriate):
