### ISSUE TITLE
Unclear versioning logic 

### ISSUE THREAD

**Issue by user4426** [GitTools/GitVersion#2824]
I am trying to automate the tagging of a git repo but fail to understand how to configure GitVersion to do what I actually want (although I really tried). 
The examples are always based on a newly created git repo with the following GitVersion.yaml:

```yaml
next-version: 1.0.0
assembly-versioning-scheme: None
mode: ContinuousDelivery
increment: None
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
branches: {}
ignore:
  sha: []
```

The version numbers are generated using the [GitVersion docker image](https://hub.docker.com/r/gittools/gitversion) by running `docker run --rm -it -v "$(pwd):/repo" gittools/gitversion /repo` from within the git repo.

### Example 1:
- `git commit --allow-empty -m "Test. +semver: skip"`-> 1.0.0 
- `git commit --allow-empty -m "Test. +semver: minor"` -> 1.1.0
- `git commit --allow-empty -m "Test. +semver: major"` -> 2.0.0
- `git commit --allow-empty -m "Test. +semver: minor"` -> expected 2.1.0 but got 2.0.0

For the last commit, I get 2.0.0 instead of 2.1.0 and I cannot understand the logic behind it. I just cannot increment the version beyond 2.0.0 using commit messages. Why does GitVersion compute this version and how do I get to 2.0.1 with a commit message?

### Example 2:
I want to use the same semantic version to automatically tag the commit. However, it seems that both the commit tags and the commit messages are used to determine the current version.
- `git commit --allow-empty -m "Test. +semver: skip"`-> 1.0.0 
- `git tag -a v1.0.0 -m "my version 1.0.0"` -> 1.0.0 # manually tagging latest commit with the version computed by GitVersion
- `git commit --allow-empty -m "Test. +semver: skip"`-> expected 1.0.0 (or '1.0.0+1') since explicitly asked to 'skip' but got 1.0.1

Why do I get 1.0.1 instead of 1.0.0? And how can I achieve the expected version of 1.0.0?
