### ISSUE TITLE
`+semver: patch` and `+semver: fix` bump Minor version instead of Patch

### ISSUE THREAD

**Issue by mcascone** [GitTools/GitVersion#2827]
**Describe the bug**
`+semver: patch` and `+semver: fix` bump Minor version instead of Patch.

## Expected Behavior
When entering a commit message of `+semver: patch` or `+semver: fix`, I expect the Patch digit of the version to be bumped.

## Actual Behavior
When entering a commit message of `+semver: patch` or `+semver: fix`, the Minor version is being bumped, and the Patch version reset to 0.

## Possible Fix
no idea

## Steps to Reproduce
1. Start with a `develop` branch with a git tag `2.0.1`.
2. Set `commit-message-incrementing: Enabled` in GitVersion.yml.
2. Make a commit directly to `develop`, with `+semver: patch` or `+semver: fix` in the commit message.
3. Inspect the generated versions.

## Context
Running Gitversion in a Jenkins pipeline, trying to implement a standardized versioning scheme for my group/whole org, with as little manual involvement as possible.

## Your Environment
Jenkins 2.277
Powershell 7
Windows Server 2012 R2 (on VMware)
Gitversion 5.6.11+Branch.main.Sha.1680a89918cb1b3b15cd37ccf78079e1fc3bfdff
git version 2.8.2.windows.1

**Comment by asbjornu** [comment]
Are you using `mode: Mainline`? Do you have `next-version` in `GitVersion.yml`?

**Comment by mcascone** [comment]
hi, thanks for the reply. It struck me this morning that I should have included that, here is my config. It does appear that I don't have it set to mainline, but I believe I did try that with no effect and turned it back.

Our process uses `develop` as the 'mainline', it is where production releases are built, as well as being the _next_ possible release. We also use `release-*` and `hotfix-*` branches as releasable builds. `master` is _supposed_ to be rebased onto `develop` after a period of burn-in on the released build, but we're not consistent about it - part of this versioning effort is to start enforcing that.

Our feature branches don't start with `feature-` but with `JIRA-ID-` - how can that be applied to this config? I have a regex to capture it: `JIRA_ID=$(echo "$CURRENT_BRANCH" | grep -Eo "[a-zA-Z0-9]{1,10}-[A-Z0-9]+" | tr [:lower:] [:upper:])`

```yml
assembly-versioning-scheme: MajorMinorPatchTag
mode: ContinuousDelivery
branches:
  develop:
    tag: 'rc'
    is-mainline: true
  main:
    mode: ContinuousDelivery
  master:
    mode: ContinuousDelivery
  feature:
    tag: beta
  release:
    tag: rc
    is-mainline: true
  pull-request:
    tag: rc
  hotfix:
    tag: hotfix
    is-mainline: true
ignore:
  sha: []
merge-message-formats: {}
commit-message-incrementing: Enabled
continuous-delivery-fallback-tag: ci
```

should I put in output from a run with `-diag` or -`showconfig`?

thanks!

**Comment by asbjornu** [comment]
If `mode: Mainline` and the tweak of the `regex` made this work for you, it all makes sense to me. Are you having any other issues?

**Comment by mcascone** [comment]
Yes, i am seeing some other weird behavior.


In a repo that has a > 1.0.0 tag, I am not getting the output I expect, let alone a bump:

```
> git tag
1.0.1-7

> git branch
* PLATDEV-9637-jenkins-onboard
  develop
  master

> $gv = 'path/to/my/shared/GitVersion.yml'

> gitversion -config $gv
{
  "Major": 0,
  "Minor": 14,
  "Patch": 2,
  "PreReleaseTag": "beta.6",
  "PreReleaseTagWithDash": "-beta.6",
  "PreReleaseLabel": "beta",
  "PreReleaseLabelWithDash": "-beta",
  "PreReleaseNumber": 6,
  "WeightedPreReleaseNumber": 30006,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.PLATDEV-9637-jenkins-onboard.Sha.056ca97aee33b5683ce9893038379db1619c436a",
  "MajorMinorPatch": "0.14.2",
  "SemVer": "0.14.2-beta.6",
  "LegacySemVer": "0.14.2-beta6",
  "LegacySemVerPadded": "0.14.2-beta0006",
  "AssemblySemVer": "0.14.2.6",
  "AssemblySemFileVer": "0.14.2.0",
  "FullSemVer": "0.14.2-beta.6",
  "InformationalVersion": "0.14.2-beta.6+Branch.PLATDEV-9637-jenkins-onboard.Sha.056ca97aee33b5683ce9893038379db1619c436a",
  "BranchName": "PLATDEV-9637-jenkins-onboard",
  "EscapedBranchName": "PLATDEV-9637-jenkins-onboard",
  "Sha": "056ca97aee33b5683ce9893038379db1619c436a",
  "ShortSha": "056ca97",
  "NuGetVersionV2": "0.14.2-beta0006",
  "NuGetVersion": "0.14.2-beta0006",
  "NuGetPreReleaseTagV2": "beta0006",
  "NuGetPreReleaseTag": "beta0006",
  "VersionSourceSha": "3a095b213929c823771c53f76719384ff96a7c04",
  "CommitsSinceVersionSource": 6,
  "CommitsSinceVersionSourcePadded": "0006",
  "UncommittedChanges": 0,
  "CommitDate": "2021-08-30"
}

> gitversion -config $gv -showconfig
assembly-versioning-scheme: MajorMinorPatchTag
assembly-file-versioning-scheme: MajorMinorPatch
mode: Mainline
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
tag-pre-release-weight: 60000
commit-message-incrementing: Enabled
branches:
  develop:
    mode: Mainline
    tag: rc
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: ^dev(elop)?(ment)?$
    source-branches: []
    tracks-release-branches: true
    is-release-branch: true
    is-mainline: true
    pre-release-weight: 0
  feature:
    mode: Mainline
    tag: beta
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^[a-zA-Z0-9]{1,10}-[A-Z0-9]+
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  release:
    mode: Mainline
    tag: rc
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^releases?[/-]
    source-branches:
    - develop
    - main
    - support
    - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 30000
  pull-request:
    mode: Mainline
    tag: rc
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)'
    track-merge-target: false
    regex: ^(pull|pull\-requests|pr)[/-]
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    mode: Mainline
    tag: hotfix
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^hotfix(es)?[/-]
    source-branches:
    - develop
    - main
    - support
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 30000
  main:
    mode: Mainline
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$|^main$
    source-branches:
    - develop
    - release
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
  support:
    mode: Mainline
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^support[/-]
    source-branches:
    - main
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
ignore:
  sha: []
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
```

**Comment by mcascone** [comment]
As a side note, I think it would really benefit the community to have some documentation of what the various deeper configs are for. I'm really just shooting in the dark here.

Is there any documentation on these?

```
increment:
prevent-increment-of-merged-branch-version: 
track-merge-target: 
regex: 
source-branches:
tracks-release-branches:
is-release-branch: 
is-mainline:
pre-release-weight:
track-merge-target:
```

**Comment by BinToss** [comment]
> 
> 
> As a side note, I think it would really benefit the community to have some documentation of what the various deeper configs are for. I'm really just shooting in the dark here.
> 
> Is there any documentation on these?
> 
> ```
> increment:
> prevent-increment-of-merged-branch-version: 
> track-merge-target: 
> regex: 
> source-branches:
> tracks-release-branches:
> is-release-branch: 
> is-mainline:
> pre-release-weight:
> track-merge-target:
> ```
> 
> Update: [I found this, but it's still quite vague](https://github.com/AGBrown/GitVersion-abcontrib/blob/master/docs/configuration.md); one more level of detail would be greatly appreciated.

- https://gitversion.net/docs/reference/configuration#increment-1
- https://gitversion.net/docs/reference/configuration#prevent-increment-of-merged-branch-version
- https://gitversion.net/docs/reference/configuration#track-merge-target
- https://gitversion.net/docs/reference/configuration#regex
- https://gitversion.net/docs/reference/configuration#source-branches
- https://gitversion.net/docs/reference/configuration#tracks-release-branches
- https://gitversion.net/docs/reference/configuration#is-release-branch
- https://gitversion.net/docs/reference/configuration#is-mainline
- https://gitversion.net/docs/reference/configuration#pre-release-weight
- https://gitversion.net/docs/reference/configuration#track-merge-target

**Comment by mcascone** [comment]
Thank you @BinToss - I did post that same link in my request for more docs; some of them are detailed, some are not. I was on the receiving end of unintentionally-hurtful comments about documentation recently, so I didn't mean for mine to be the same; but there is a lot of figuring it out on one's own required here, so some more examples would be great.

I did eventually figure out that i was expecting a `mainline` style of operation, not either of the `continuous` modes. My current config looks like this:

```yml
assembly-versioning-scheme: MajorMinorPatchTag
mode: Mainline
tag-prefix: '[vV]'
branches:
  develop:
    increment: none
    tag: 'rc'
    is-mainline: true
    is-release-branch: true
    tracks-release-branches: true
  feature:
    mode: continuousdelivery
    increment: none
    tag: beta
    regex: ^[a-zA-Z0-9]{1,10}-[0-9]+
  release:
    increment: none
    tag: rc
    is-mainline: false
    is-release-branch: true
  pull-request:
    tag: rc
  hotfix:
    increment: none
    tag: hotfix
    is-mainline: false
    is-release-branch: true
ignore:
  sha: []
merge-message-formats: {}
commit-message-incrementing: Enabled
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(no(n|t)-?breaking|feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|bug-?(fix)?|patch|increment(al)?|enhancements?)'
no-bump-message: '\+semver:\s?(none|skip)'
```

As you can see I also added some additional tokens to the auto-bump messages. I'm also having an issue with Release branches adding the metadata info to the tag; it's an extended use case like this that i'm having trouble finding specific help for in the docs.

All of that being said, I believe this can be closed.
