### ISSUE TITLE
[Feature] Should mainline support direct commits with reference branches

### ISSUE THREAD

**Issue by techgeek03** [GitTools/GitVersion#2875]
So this is more of a discussion at the moment that can potentially turn into a feature request :) So the question is; when Mainline mode; should direct commits to the main branch support reference branches? 

## Detailed Description
Consider the following tree:
```
* 9725be0 (HEAD -> main) Merge feature/f3 to main
* 801715a Merge hotfix/h2 to main
* 542c166 Merge feature/f2 to main
* 66e62bd Merge hotfix/h1 to main
* dd199cb Merge feature/f1 to main
* ec5fba3 Initial commit
```

and the following configuration:

```
mode: Mainline
branches:
  main:
    increment: Minor
    regex: ^master$|^main$
  feature:
    tag: beta.{BranchName}
    increment: Minor
  hotfix:
    tag: beta.{BranchName}
    increment: Patch
ignore:
  sha: []
merge-message-formats:
  azure: "^Merge (?<SourceBranch>.+) to (?<TargetBranch>.+)"
```

As you can see all commits are in the main branch and created with merge policy of `Squash, fast-forward only` or `git --squash --ff-only` and the commit messages have a reference to the source and target branches. Today GitVersion will ignore the commit message and use the configured increment version settings from the main branch to calculate the version number. As you can see from the provided configuration the feature branch increment the Minor version, and the hotfix branch increment the Patch version, however when the version is calculated in main it will always increment the patch (since that is how main is configured). 

## Possible Implementation
One possible solution would be to introduce one additional configuration property on the main branch `direct-commits-with-reference-branches` (name up for discussion :) ), by default disabled, so that it does not introduce braking changes, and when enabled can parse the commit message from the provided `merge-message-formats` to figure out the source and the target branches.
