### ISSUE TITLE
[Bug] Inherit behaviour with ContinuousDeployment mode

### ISSUE THREAD

**Issue by xpicio** [GitTools/GitVersion#2902]
Hello, i'm using gitflow as branching models and gitflow-avh as tool to interact with this model.

## Expected Behavior
When a hotfix has been closed the version on master branch should be incremented by a patch.

## Actual Behavior
When a hotfix has been closed the version on master branch has been incremented by a minor.

## Environment
- macOS 11.6, Ubuntu 20
- gitversion 5.7.1 (docker image gittools/gitversion:5.7.1)

## Steps to Reproduce
- update GitVersion.yml
```
mode: ContinuousDeployment
branches:
  main:
    regex: ^master$|^main$
    tag: rc
    increment: Inherit
  feature:
    regex: ^features?[/-]
    increment: Minor
  hotfix:
    regex: ^hotfix(es)?[/-]
    increment: Patch
  release:
    regex: ^releases?[/-]
    increment: Minor
```
- sample repository git log
```
commit f45670446e8d32f460a87f051b63323a8b3cc1ea (HEAD -> master, tag: v4.2.1, origin/master)
Merge: 71041bc bbefe14
Author: Patrizio Bertozzi <xpicio@gmail.com>
Date:   Fri Nov 5 10:32:15 2021 +0100

    Merge branch 'hotfix/config'

commit bbefe14dc50adeed287a4653313380ce12927559
Author: Patrizio Bertozzi <xpicio@gmail.com>
Date:   Fri Nov 5 10:31:59 2021 +0100

    update config

commit 71041bc991c7952a33c77868b8630448644a3aa7 (tag: v4.2.0)
Merge: 06b4832 690d8ae
Author: Patrizio Bertozzi <xpicio@gmail.com>
Date:   Fri Nov 5 10:08:29 2021 +0100

    Merge branch 'hotfix/xyz'
...
```
- on local branch master run `docker run --rm -v "$(pwd)":/repo gittools/gitversion:5.7.1 /repo /nocache` the computed version is `4.2.1` 🟢 
- start a new hotfix `git flow hotfix start demo` update a file and commit it, then `docker run --rm -v "$(pwd)":/repo gittools/gitversion:5.7.1 /repo /nocache` the computed version is `4.2.2-beta.1` 🟢 
- close the hotifx `git flow hotfix finish demo -n`
-- checkout the `develop` branch then `docker run --rm -v "$(pwd)":/repo gittools/gitversion:5.7.1 /repo /nocache` the computed version is `4.3.0-alpha.8` 🟢
-- checkout the `master` branch then `docker run --rm -v "$(pwd)":/repo gittools/gitversion:5.7.1 /repo /nocache` the computed version is `4.3.0-rc.4` 🔴 (should be 4.2.2, right ?)

Any tips about it ? To be honest i'm not sure it's a bug, maybe a misconfigured the GitVersion.yml or i misunderstood the behaviour of `Inherit` value of `increment` setting.
