### ISSUE TITLE
Cannot Run with Only .NET 6 Installed

### ISSUE THREAD

**Issue by mitchelsellers** [GitTools/GitVersion#2906]
**Describe the bug**
Attempting to run this in a project using GitHub actions with ONLY .NET 6 installed results in an error.

## Expected Behavior
Expected support to work with .NET 6, without installing additional frameworks.

## Actual Behavior
The following error is displayed

```
Run gittools/actions/gitversion/execute@v0.9.7
Command: dotnet-gitversion /home/runner/work/icg-website/icg-website /output json /output buildserver /config GitVersion.yml
/home/runner/.dotnet/tools/dotnet-gitversion /home/runner/work/icg-website/icg-website /output json /output buildserver /config GitVersion.yml
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/home/runner/.dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

## Possible Fix
Installation of .NET 5 in addition to 6 works, but adds to build times etc.

## Steps to Reproduce
Run the commend on a machine with only .NET 6 installed.  As example, the following is the first part of our GitHub action that generated the above.

```
name: CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Ensure .NET Installed
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Install EF Tools
      run: dotnet tool install --global dotnet-ef
    
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true 
```

## Context
This blocks our transition of all .NET projects from upgrading to .NET 6, as the added runtime and "temporary" change of the workaround makes an upgrade not feasible.

## Your Environment
GitHub Actions environment, I've added the CI pipeline above

**Comment by arturcic** [comment]
This could not be a bug, as the .net 6.0 was release just couple of hours ago. There is still some work we need to do to have .net 6.0 support. That is planned for version 5.8.0 Hope to have it soon released

**Comment by mitchelsellers** [comment]
@arturcic I wasn't sure which way to categorize it, thanks for updating.

**Comment by johnkors** [comment]
Same boat. Will the release of 5.8.0 also release a new version of the action with .NET 6 support? Any where we can follow progress btw?

**Comment by arturcic** [comment]
Actually there is no need for a new action to be released, as the actions can install by specifying a version number. There is no exact release date yet, there are some infrastructure changes needed to be done. I hope in a week or 2 to have everything solved and a 5.8.0 release to be done

**Comment by johnkors** [comment]
Thanks for the quick response! No hurry, minor annoyance having both .NET 5 + .NET 6 in the pipeline in a pure .NET 6 codebase. But for sure not a huge issue. Thanks again!

**Comment by jvandertil** [comment]
As a workaround you can set the environment variable `DOTNET_ROLL_FORWARD` to `Major` until .NET 6 support is released.

**Comment by esond** [comment]
> As a workaround you can set the environment variable `DOTNET_ROLL_FORWARD` to `Major` until .NET 6 support is released.

This works like a charm. Thank you.

**Comment by mitchelsellers** [comment]
@jvandertil Thank you, this is much more elegant of a workaround

**Comment by candoumbe** [comment]
> As a workaround you can set the environment variable `DOTNET_ROLL_FORWARD` to `Major` until .NET 6 support is released.

Just to be sure ... Is this equivalent to setting `latestMajor` in `global.json` file of .Net Core project ?

**Comment by jvandertil** [comment]
> > As a workaround you can set the environment variable `DOTNET_ROLL_FORWARD` to `Major` until .NET 6 support is released.
> 
> Just to be sure ... Is this equivalent to setting `latestMajor` in `global.json` file of .Net Core project ?

Kind off, that will always roll to the latest major even if the requested major version is available. 

See the docs: https://docs.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward

**Comment by diegosasw** [comment]
I was having the same issue in a GitLab CI pipeline where only .NET 6 SDK is available. Thanks to the environment variable suggested workaround the sample below works fine now. 

```
image: mcr.microsoft.com/dotnet/sdk:6.0

# Other stages and jobs here

publish:
  stage: publish
  before_script:
    - export DOTNET_ROLL_FORWARD=Major # See https://github.com/GitTools/GitVersion/issues/2906 until 5.8.0 is released
    - export PATH=$PATH:/root/.dotnet/tools
    - dotnet tool install --global GitVersion.Tool --version 5.7.0
    - dotnet gitversion
    - SEMVER=$(dotnet gitversion -showvariable semver)
    - mkdir version
    - echo "${SEMVER}" > ./version/semver
    - APP_VERSION=$(cat ./version/semver)
  script:
    - dotnet publish -c Release -o $PUBLISH_OUTPUT_DIR -p:Version=$APP_VERSION
  artifacts:
    paths: 
      - $PUBLISH_OUTPUT_DIR/
      - version/
    expire_in: 8 hour
  rules:
    - if: $CI_COMMIT_TAG
      when: never  
    - when: on_success
```
