### ISSUE TITLE
[Feature] Wrong version from the release branche

### ISSUE THREAD

**Issue by mouradchama** [GitTools/GitVersion#2925]
**Describe the bug**
Hi,

I'm trying the get the right version on my release branch, the release name doesn't respect the pattern used to retrieve the version, my branch name is `release/R2112`.

`gitVersion.yml` content:

```yaml
next-version: 2.0
branches:
  develop:
    tag: beta
  release:
    tag: rc
  hotfix:
    tag: rc
```

I've already released a version on production:
`master`: tag `2.0.0`
`develop`: the generated versions are `2.1.0-beta.x` (which is fine for me)

If I create the release with the name `release/2.1.0` the generated version will be `2.1.0-rc.x`
if I create the release with the name `release/R2112` the generated version will be `2.0.0-rc.x`

## Expected Behavior
The generated version should be `2.1.0-rc.x`

## Actual Behavior
The generated version is `2.0.0-rc.x`

## Your Environment

- Version Used: 5.8.1

Thank you in advance.

**Comment by asbjornu** [comment]
First remove `next-version: 2.0`. If that has no effect, then great; less configuration. If it doesn't help increment the release branch to `2.1` then try to [configure](https://gitversion.net/docs/reference/configuration) `increment: Minor` and `track-merge-target: true` on `release`.

```yaml
branches:
  develop:
    tag: beta
  release:
    tag: rc
    increment: Minor
    track-merge-target: true
  hotfix:
    tag: rc
```
