### ISSUE TITLE
[Bug] Mainline only increases version once on (sub-)Branches.

### ISSUE THREAD

**Issue by TheRealLenon** [GitTools/GitVersion#2943]
**Describe the bug**
When using ``Mainline`` subsequent (all other branches then main eg. develop or feature) branches are just incrementing the desired version once.

When setting the other branches also to ``is-mainline: true`` the whole versioning will not apply based on the related branches (When main is 1.0.0 feature will be 0.1.1).

## Expected Behavior
![image](https://user-images.githubusercontent.com/31377894/146331119-3082872d-4c8a-44bb-880e-6aac34e25a6b.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/31377894/146331327-ada7dfac-5849-42a5-aad1-a4860619606e.png)

## Steps to Reproduce

1. Create a Commit including the ``GitVersion.yml`` attached below on the main branch.
2. Create a feature branch and add a commit
3. Add a second commit to the feature branch (the Version will be still the same as on the first feature branch commit)
4. merge back into main (version gets finally updated)

```yml
mode: MainLine
branches:
  main:
    regex: ^main$
    tag: ''
    increment: Major
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'develop' ]
    tracks-release-branches: true
    is-release-branch: true
    is-mainline: true
    pre-release-weight: 55000
  develop:
    regex: ^dev(elop)?(ment)?$
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches: [ 'main', 'feature' ]
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 40000
  feature:
    regex: ^features?[/-]
    tag: ''
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    source-branches: [ 'develop', 'main' ]
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
ignore:
  sha: []
```

## Context
The branching strategie should automatically increment the version (Major, Minor or Patch) based on desired branches. The reason behind it is to not rely on tags and also being able to build a nuget automatically.

## Your Environment
Using Azure-Pipelines (windows-2022) and the latest GitVersion.
