### ISSUE TITLE
[Bug] Unexpected development version after v5.6.5 when using master branch

### ISSUE THREAD

**Issue by InKahootz** [GitTools/GitVersion#2992]
**Describe the bug**
The v5.6.5 (release where config change from master to main) made an unexpected version

## Expected Behavior
When merging release/v21.3.0 back into master and development, I would expect the calculated version on development to be v21.4.0

## Actual Behavior
The Azure Pipeline build is reporting v21.3.0 on the latest development. Uses `GitVersion.Tool` v5.8.1.

## Possible Fix
* Using gitversion v5.6.4 works as previous.
* Pushing ref `origin/master` to `origin/main` also fixes

## Steps to Reproduce
See context for a graph

I cloned the gitversion repo and ran a `git bisect` from tag 5.2.4 to 5.8.1. 
After every bisect, I would `git clean -fdx` and then dotnet build. I also removed the cache files from my repo and ran the gitversion.exe from the built output folder. Just to make sure everything was clean.

The commit that introduced the change was
```# first bad commit: [8b653e9f75cae9c9918a148de23864feaae736f1] changed the default branch from master to main```

## Context
![image](https://user-images.githubusercontent.com/1909698/153656617-fe630942-bd4a-4f4f-babb-35eb9e30afa4.png)

Our GitVersion.yml file
```
assembly-versioning-scheme: Major
```

Output from `dotnet-gitversion /showconfig`
```
assembly-versioning-scheme: Major
assembly-file-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
tag-pre-release-weight: 60000
commit-message-incrementing: Enabled
branches:
  develop:
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: ^dev(elop)?(ment)?$
    source-branches: []
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 0
  main:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$|^main$
    source-branches:
    - develop
    - release
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
  release:
    mode: ContinuousDelivery
    tag: beta
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^releases?[/-]
    source-branches:
    - develop
    - main
    - support
    - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 30000
  feature:
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^features?[/-]
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  pull-request:
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)'
    track-merge-target: false
    regex: ^(pull|pull\-requests|pr)[/-]
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^hotfix(es)?[/-]
    source-branches:
    - develop
    - main
    - support
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  support:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^support[/-]
    source-branches:
    - main
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
ignore:
  sha: []
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
```

## Your Environment
Local machine I was using GitVersion.Tool 5.2.4. Worked as expected.
Updated to latest and I got the 'bug'.

The pipeline uses the latest version of the tool.
