### ISSUE TITLE
[Bug] Characters truncated in branches with underscore 

### ISSUE THREAD

**Issue by nicolasbouchard1412** [GitTools/GitVersion#3047]
**Describe the bug**
For a branch named like `release/PWB-1234_Description-1`, the `FullSemVer` version generated by GitVersion is broken (`1.0.0-PWB1782-Phase.50`). 

The format that seems to apply:
- Underscore is replaced by hyphen (which is ok)
- We loose two times the "-1" (which is wrong)

Generated variables:

```json
{
  "Major": 1,
  "Minor": 0,
  "Patch": 0,
  "AssemblySemVer": "1.0.0.0",
  "AssemblySemFileVer": "1.0.0.50",
  "FullSemVer": "1.0.0-PWB1782-Phase.50",
  "InformationalVersion": "1.0.0-PWB1782-Phase.50+Branch.release-PWB-11782-Phase-1.Sha.7c6a88f5544c263a65f30a4ac57d5cc33550caeb",
  "BranchName": "release/PWB-11782_Phase-1",
  "EscapedBranchName": "release-PWB-11782-Phase-1",
  "Sha": "7c6a88f5544c263a65f30a4ac57d5cc33550caeb",
  "ShortSha": "7c6a88f",
  "NuGetVersionV2": "1.0.0-pwb1782-phase0050",
  "NuGetVersion": "1.0.0-pwb1782-phase0050",
  "NuGetPreReleaseTagV2": "pwb1782-phase0050",
  "NuGetPreReleaseTag": "pwb1782-phase0050",
  "VersionSourceSha": "8aa4851270ac77cadc14fea8d8d44db75b526bf6",
  "CommitsSinceVersionSource": 50,
  "CommitsSinceVersionSourcePadded": "0050",
  "UncommittedChanges": 18239,
  "CommitDate": "2022-03-11"
}
```

`GitVersion.yml`:

```yaml
mode: ContinuousDeployment
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{InformationalVersion}'
next-version: 1.0.0                                       #Version à incrémenter manuellement
commit-message-incrementing: Disabled
branches:
  main:
    regex: ^master$|^main$                                  #S'applique aux branche "main" et "master"
    mode: ContinuousDelivery                                #Ne génère pas de version unique à chaque commit
    tag: ''                                                 #Aucun tag de prerelease ajouté
    increment: none                                         #Pas d'incrément automatique
    is-release-branch: false
    is-mainline: true
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
 
  feature:
    regex: ^(feature|bugfix)[\/]                            #S'applique aux branche "feature" et "bugfix"
    mode: ContinuousDeployment                              #Génère une version unique à chaque commit
    tag: useBranchName                                      #Utilise le nom de la branche comme tag de prerelease
    increment: none                                         #Pas d'incrément automatique
    source-branches: ['master', 'release']                  #Possibles parents de la branche
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
 
  release:
    regex: ^release?[\/]                                    #S'applique aux branche "release"
    mode: ContinuousDeployment                              #Ne génère pas de version unique à chaque commit               
    tag: useBranchName
    increment: none
    source-branches: ['master']
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
 
  hotfix:
    regex: ^hotfix[\/]                                      #S'applique aux branche "hotfix"
    mode: ContinuousDeployment                              #Génère une version unique à chaque commit
    tag: useBranchName
    increment: none
    source-branches: ['master']
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
```

## Expected Behavior
GitVersion generate a `FullSemVer` version that contains all the branch name characters as the pre-release tag.

## Actual Behavior
GitVersion generate a `FullSemVer` version that truncates some characters unexpectedly.

## Possible Fix
Fix the formatting step when generating the version.

## Steps to Reproduce
1.  Create a branch named `release/PWB-1234_Description-1`
2. Execute GitVersion
3. Consult the generated version

## Context
I want to be able to use the generated FullSemVer as the build identifier and for a Nuget package too. It is working well most of the time, but some characters in branch names provoke odd behaviours in GitVersion.

## Your Environment
We detected this problem in an AzureDevOps CI pipeline, but the same behavior is present when commands runs locally.

- Version Used: GitVersion.Tool 5.9.0 x64
- Operating System and version: Ubuntu 20.04.4

Thanks!

**Comment by nicolasbouchard1412** [comment]
I tried to use {EscapedBranchName} as the pre-release tag in my GitVersion.yml
```
mode: ContinuousDeployment
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{InformationalVersion}'
next-version: 1.0.0                                       #Version à incrémenter manuellement
commit-message-incrementing: Disabled
branches:
  main:
    regex: ^master$|^main$                                  #S'applique aux branche "main" et "master"
    mode: ContinuousDelivery                                #Ne génère pas de version unique à chaque commit
    tag: ''                                                 #Aucun tag de prerelease ajouté
    increment: none                                         #Pas d'incrément automatique
    is-release-branch: false
    is-mainline: true
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
 
  feature:
    regex: ^(feature|bugfix)[\/]                            #S'applique aux branche "feature" et "bugfix"
    mode: ContinuousDeployment                              #Génère une version unique à chaque commit
    tag: {EscapedBranchName}                                     #Utilise le nom de la branche comme tag de prerelease
    increment: none                                         #Pas d'incrément automatique
    source-branches: ['master', 'release']                  #Possibles parents de la branche
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
 
  release:
    regex: ^release?[\/]                                    #S'applique aux branche "release"
    mode: ContinuousDeployment                              #Ne génère pas de version unique à chaque commit               
    tag: {EscapedBranchName}
    increment: none
    source-branches: ['master']
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
 
  hotfix:
    regex: ^hotfix[\/]                                      #S'applique aux branche "hotfix"
    mode: ContinuousDeployment                              #Génère une version unique à chaque commit
    tag: {EscapedBranchName}
    increment: none
    source-branches: ['master']
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
```

I was expecting to have the same behavior as using {BranchName}.
