### ISSUE TITLE
[Bug] ignore parameter does not ignore everything

### ISSUE THREAD

**Issue by ibvhefe** [GitTools/GitVersion#3074]
**Describe the bug**
1) Checkout the support branch of this project ([Gitversion/support-branch](https://github.com/GitTools/GitVersion/tree/support/5.x))
2) Change the GitVersion.yml to

```
mode: Mainline
branches: {}
ignore:
  sha: [ ]
  commits-before: 2023-04-10T01:00:00 #some date in the future
merge-message-formats: {}
```

3) Run GitVersion

## Expected Behavior
A version such as `0.1.0`

## Actual Behavior
The calculated version seems to be too high:
```
{
  "Major": 1,
  "Minor": 2,
  "Patch": 111
  ...
}
```
