### ISSUE TITLE
gitversion.properties is not being generated by BitBucket Pipelines build agent

### ISSUE THREAD

**Issue by davidkeaveny** [GitTools/GitVersion#3088]
The new integration support for Atlassian's BitBucket Pipelines CI/CD system is not working as expected. 

## Expected Behavior

GitVersion should detect that it is running on BitBucket Pipelines (by the presence of the BITBUCKET_WORKSPACE environment variable), calculate the version numbers, and write them to the file `gitversion.properties`, which can then be exported by Pipelines as an artifact to be shared with the rest of the pipeline.

## Actual Behavior

The `gitversion.properties` file is not being generated. I can see from the output of `/diag` that the build agent is correctly calculating the expected version, it's just not being written to file. 

I've attached the log file; looking at it, I can not see any of the output from the `void WriteIntegration(Action<string>?, VersionVariables, bool)` method in `src/GitVersion.Core/BuildAgents/BitBucketPipelines.cs` in the logs.

## Possible Fix

As a workaround, I can write a single variable from GitVersion to an output file e.g.

```yml
- echo export GITVERSION_FULLSEMVER=`dotnet-gitversion /diag /output json /showvariable FullSemVer` >> gitversion.properties
```

## Steps to Reproduce

The YAML for the Pipelines set up is:

```yml
image: mcr.microsoft.com/dotnet/sdk:6.0

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Version
        script:
          - export PATH="$PATH:/root/.dotnet/tools"
          - dotnet tool install --global GitVersion.Tool --version 5.*
          - dotnet-gitversion /diag /buildserver /verbosity:Diagnostic /l gvlog.txt
        artifacts:
          - gitversion.properties
```
