### ISSUE TITLE
[Bug] Executing GitVersion Task - "cannot find the .git directory"

### ISSUE THREAD

**Issue by opax7** [GitTools/GitVersion#3126]
**Description**
Running the GitVersion task is unable to find the ".git" directory with a multi-repo build.

## Expected Behavior
GitVersion is able to execute against a subdirectory of the build working directory.

## Actual Behavior
**********
Task         : Execute GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org/) for projects using Git
Version      : 0.9.13
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
**********
Command: dotnet-gitversion /home/vsts/work/1/s /output json /output buildserver /config /home/vsts/work/1/s/myProjectA/GitVersion.yml
/opt/hostedtoolcache/GitVersion.Tool/5.10.1/x64/dotnet-gitversion /home/vsts/work/1/s /output json /output buildserver /config /home/vsts/work/1/s/myProjectA/GitVersion.yml
INFO [05/25/22 12:51:02:25] Working directory: /home/vsts/work/1/s
INFO [05/25/22 12:51:02:28] Done writing 
Cannot find the .git directory

## Possible Fix
Providing the "workingDirectory" input in the Azure DevOps Pipeline task:
```
- task: gitversion/execute@0
  displayName: Exec Git Version
  inputs:
    workingDirectory: "myProjectA"
    useConfigFile: true
    configFilePath: "myProjectA/GitVersion.yml"
```
Should set the actual working directory of the task in order to change this:
`/opt/hostedtoolcache/GitVersion.Tool/5.10.1/x64/dotnet-gitversion /home/vsts/work/1/s /output json /output buildserver /config /home/vsts/work/1/s/myProjectA/GitVersion.yml`
To this:
`/opt/hostedtoolcache/GitVersion.Tool/5.10.1/x64/dotnet-gitversion /home/vsts/work/1/s/myProjectA /output json /output buildserver /config /home/vsts/work/1/s/myProjectA/GitVersion.yml`

## Steps to Reproduce
Azure DevOps Pipeline Yaml
### Checkout two repos (myProjectA = self)
```
steps:
  - checkout: self
    clean: false
    fetchDepth: 0
  - checkout: git://$(System.TeamProject)/$(myProjectB)@$(main)
```
This creates two subdirectories in the build working directory:
- /home/vsts/work/1/s/myProjectA
- /home/vsts/work/1/s/myProjectB

"ProjectB" is a testing harness repository in which a container is built from. It is not being versioned. "Project A" is the project which needs to be versioned.

### Setup and execute GitVersion
```
- task: gitversion/setup@0
  displayName: Setup Git Version
  inputs:
    versionSpec: "5.x"
- task: gitversion/execute@0
  displayName: Exec Git Version
  inputs:
    workingDirectory: "myProjectA"                       # Has no impact (tried "targetPath" as well with no success)
    useConfigFile: true                                  # Works
    configFilePath: "myProjectA/GitVersion.yml"          # Works
```

## Context
Implementing automated testing into the pipeline using a separate test harness. The test harness is made up of a Docker container that must be built as part of the pipeline, i.e. I cannot pull it from a repository which is why I need to checkout this repo, plus the test harness repo.

**Comment by opax7** [comment]
Discovered that the following was the proper way to handle this. In summary, you need to use the "targetPath" input parameter, and specify the full path to the working directory. When I had previously tried this, I used a relative path. 

```
- task: gitversion/execute@0
  displayName: Exec Git Version
  inputs:
    targetPath: "$(System.DefaultWorkingDirectory)/myProjectA"
    useConfigFile: true
    configFilePath: "myProjectA/GitVersion.yml"
```
