### ISSUE TITLE
Issue with Mainline

### ISSUE THREAD

**Issue by Vinko90** [GitTools/GitVersion#3138]
I am trying to configure a very simple Mainline workflow to be introduced in our team at work. What I am trying to achieve is exactly what is showed in this picture:

https://raaviblog.com/wp-content/uploads/gitversion-2.png

We use DevOps Git repo + Pipeline. Main is locked by policy, and you can only push to it via PR and Squash mode (We want a clean commit), and we use only feature/* (Bump minor by 1) and fix/* branch (Bump patch by 1). 
Pipeline have to do this:
1) Build on feature/fix branches -> Generate NuGet packages needed to test from other microservices
2) Build on PR (No NuGet are generated)
3) Build when PR is merged into Main -> Generate release NuGet -> Auto-tag Main repo with this extension: https://marketplace.visualstudio.com/items?itemName=jabbera.git-tag-on-release-task

However I see that the version generated by the PR build and the build after PR complete is wrong. It look like that PR doesn't understand from which branch is coming from, same for Main when PR complete. Here is the outcome after merging a feature into main:

![Outcome](https://i.imgur.com/emsSJao.png)

That's my GitVersion.yml
```yml
mode: Mainline
branches:
  feature:
    regex: ^feature?[/-]
    increment: Minor
    source-branches: ['main','master']
    tag: alpha-{BranchName}
  fix:
    regex: fix(es)?[/-]
    increment: Patch
    source-branches: ['main','master']
    tag: fix-{BranchName}
  pull-request:
    tag: PR-
ignore:
  sha: []
merge-message-formats: {}
````

Can somebody please clarify what is going on?
