### ISSUE TITLE
Version is not incrementing on develop after creating the release branch

### ISSUE THREAD

**Issue by mouradchama** [GitTools/GitVersion#3149]
Hi,

**Describe the bug**
I'm facing an issue with GitVersion, I'm following the GitFlow strategy, this is my GitVersion file:

```yaml
next-version: 3.0.0
update-build-number: true
assembly-informational-format: '{SemVer}'
branches:
  develop:
    tag: beta
  feature:
    mode: ContinuousDeployment
  release:
    tag: rc
    increment: Minor
    track-merge-target: true
  main:
    track-merge-target: true
  hotfix:
    tag: rc
```

The meta data was incrementing until I created the release branch:
From the release branch I have the right versions (3.0.0-rc1, 3.0.0-rc2 ....), but from develop GitVersion continue using the 3.0.0-beta.x, without incrementing the minor.
The stable package (merge release into master) is not created yet.
The release name does not include the version (the name is : Releases/R2207), I'm taging the release branch after each build.

## Expected Behavior
On develop I expect versions: 3.1.0-beta.1

## Actual Behavior
3.0.0-beta.1

## Your Environment
Azure Devops
GitVersion 5.10.3

- Version Used:
- Operating System and version : Ubuntu 20.04.4
