### ISSUE TITLE
no-bump-message should take precedence over *-version-bump-message

### ISSUE THREAD

**Issue by jeanplevesque** [GitTools/GitVersion#3172]
## Detailed Description

It seems like when both `no-bump-message` and `*-version-bump-message` are matched, the version bump wins.

**Is that the intended behavior?**

## Context

I configured the `*-version-bump-message` to follow conventional commits.
I would like that if I add `+semver: skip` to a conventional commit, the version isn't incremented.

Basically, the following commit currently increments the version and that's not what I want.
```
ci: Some commit message
+semver: skip
```

Here's my config:
```
assembly-versioning-scheme: MajorMinorPatch
mode: MainLine
next-version: '' # Use git tags to set the base version.
continuous-delivery-fallback-tag: ""
commit-message-incrementing: Enabled
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-]*\\))?:"
patch-version-bump-message: "^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"
branches:
  master:
    regex: ^master$|^main$
    tag: ''
ignore:
  sha: []
```

## Workaround
Although this isn't a perfect solution, we've decided that the "ci" conventional commit type would not bump the version.

We've changed our configuration as such:
```
patch-version-bump-message: "^(build|chore|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"
no-bump-message: "^(ci)(\\([\\w\\s-]*\\))?:"
```
