### ISSUE TITLE
[Bug] Default configuration not working as Gitflow

### ISSUE THREAD

**Issue by mleneveut** [GitTools/GitVersion#3209]
**Describe the bug**
I'm using gitversion Azure Devops tasks without any configuration (no GitVersion.yml file).

I tagged master 1.2.1 and merged master to develop.

The FullSemVer calculated at each step is not was I expect.

## Expected Behavior
I would like to achieve : 
PR master -> develop : 1.2.1-PullRequest5174.53
develop version after merge : 1.2.1-alpha.53
branch feature from develop : 1.2.1-PullRequest5175.55
merge feature in develop : 1.2.2-alpha.55
branch release/1.3.0 from develop : 1.3.0-beta.1+0
new commit to release/1.3.0 : 1.3.0-beta.1+1
PR to merge release/1.3.0 to master : 1.3.0-PullRequest5177.5
merge to master : 1.3.0
branch hotfix/1.3.1 from master : 1.3.1-PullRequest5178.1
merge hotfix to master : 1.3.1
merge master to develop: 1.3.1-alpha.56

## Actual Behavior
PR master -> develop : 1.3.0-PullRequest5174.53
develop version after merge : 1.3.0-alpha.53
branch feature from develop : 1.3.0-PullRequest5175.55
merge feature in develop : 1.3.0-alpha.55
branch release/1.3.0 from develop : 1.3.0-beta.1+0
new commit to release/1.3.0 : 1.3.0-beta.1+1
PR to merge release/1.3.0 to master : 1.4.0-PullRequest5177.5
merge to master : 1.2.2+5

## Your Environment
Azure Devops online.

```
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.9.0'
- task: gitversion/execute@0
  displayName: Determine Version
- bash: |
    echo "== STARTED VERSIONING $(GitVersion.FullSemVer) =="
    echo "##vso[build.updatebuildnumber]$(GitVersion.FullSemVer)"
  displayName: 'Versioning'
```

- Version Used:
```
Task         : Setup GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org/) for projects using Git
Version      : 0.9.13
````

- Operating System and version (Windows 10, Ubuntu 18.04): ubuntu-latest
