### ISSUE TITLE
Regression ins 5.11.x

### ISSUE THREAD

**Issue by cfauchere** [GitTools/GitVersion#3273]
**Describe the bug**
There was no issue with 5.10.3. Inputs haven't changed. Switching to 5.11.0 I now get an error.
Failed to parse 22.10.0 into a Semantic Version
  INFO [11/07/22 21:18:52:29] Done writing 
##[error]SyntaxError: Unexpected end of JSON input

## Expected Behavior
No error (backcompat)

## Actual Behavior
See the error above.

## Steps to Reproduce
```
mode: ContinuousDeployment
assembly-versioning-scheme: MajorMinorPatchTag
tag-prefix: v20|20|v
next-version: 22.10.0
continuous-delivery-fallback-tag: ''
commit-message-incrementing: Disabled
ignore:
  sha: []
branches:
  develop:
    tag: alpha
    increment: None
    prevent-increment-of-merged-branch-version: true
  master:
    tag: ''
    increment: None
  release(/v):
    regex: '^release(/v)'
    tag: release
    source-branches: []
    increment: None
  cloud-release:
    regex: '^release[/-]'
    tag: useBranchName
    source-branches: []
    increment: None
  pull-request:
    tag: pr.
    increment: None
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
```

## Context
Build break.

## Your Environment
Ubuntu
5.11.0
