### ISSUE TITLE
[Bug] Failed to parse 0.1 into a Semantic Version (v 6.0.0-alpha.1)

### ISSUE THREAD

**Issue by mtufe-delhaize** [GitTools/GitVersion#3341]
**Describe the bug**
next-version is failed to parse 0.1 into a Semantic Version

## Actual Behavior
Failed to parse 0.1 into a Semantic Version

## Steps to Reproduce
Agent : ubuntu-latest or windows-latest
Azure Devops Pipeline GitVersion.Tools Preview
GitVersion.Tools v6.0.0-alpha.1

## Context
**GitVersion.yml**
```
next-version: 0.1
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{InformationalVersion}'
mode: ContinuousDelivery
continuous-delivery-fallback-label : ci
increment: Inherit
label-prefix: '[vV]'
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
commit-message-incrementing: Enabled
commit-date-format: 'yyyy-MM-dd'
ignore:
  sha: []
merge-message-formats: {}
branches:
  master:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    label: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
```

## Your Environment
Azure Devops Pipeline

- Version Used: 6.0.0-alpha.1
- Build Agent ubuntu-latest or windows-latest
