### ISSUE TITLE
[Feature] Prevent version increment of versions from tracked release branches

### ISSUE THREAD

**Issue by rkieslinger** [GitTools/GitVersion#3352]
I'm using a Release Flow branching strategy and I can almost configure GitVersion to do proper versioning for my scenario, except this one case:

* New branch `release/v4.0` from `main`
* New commit on branch `release/v4.0` _(it gets `SemVer` set to `4.0.0-rc.1` -> nice!)_
* New branch `fix/bug` from `release/v4.0`
* New commit on branch `fix/bug` _(it gets `SemVer` set to `4.0.1-bug.1` -> **WRONG - should be `4.0.0-bug.1`**!)_
* New tag `v4.0.0` on top commit of branch `release/v4.0` _(it gets `SemVer` set to `4.0.0` -> nice!)_
* GitVersion on branch `fix/bug` now gets `SemVer` set to `4.0.1-bug.1` -> nice!

Here is my `GitVersion.yml`:

```yml
mode: ContinuousDeployment
commit-message-incrementing: Disabled
branches:
  master:
    increment: Minor
    tag: beta
    tracks-release-branches: true
    track-merge-target: true
    prevent-increment-of-merged-branch-version: false
  release:
    increment: Patch
    tag: rc
  fix:
    tag: useBranchName
    increment: Patch
    regex: ^fix(es)?[/-]
    source-branches:
    - release
    - fix
    tracks-release-branches: true
    pre-release-weight: 30000
```

## Possible Implementation
It seems the `BaseVersions` resulting from `TrackReleaseBranchesVersionStrategy` always have `shouldIncrement` set to `true`. As there's already a configuration parameter called `prevent-increment-of-merged-branch-version`, is it possible to introduce a new parameter called `prevent-increment-of-tracked-release-version` which defaults to `false` and I could set to `true` on my configuration for branch type `fix`? I looked into the source code a bit and it seems, that this could be implemented relatively easy.

**Comment by HHobeck** [comment]
May I ask you what version your issue is related to? It seems to me that you have tested your scenario on the version 5.x which not reflacting the latest development initiatives. Better go with the master branch because we have done allot of work and changed the behavior e.g. how the branch configurations are determined.

Anyway in my opinion this is already solved (please use for your test release/v4.0.0 for now because of a known issue https://github.com/GitTools/GitVersion/issues/3341).

Cheers.

**Comment by rkieslinger** [comment]
Yes, you are right. We are currently using `5.11.1` in production. I tested the behavior using `6.0.0-alpha.1`, but it still gives me `4.0.1` on my `fix/bug` branch, where I would expect `4.0.0`. It seems the behavior hasn't changed in my scenario using v6.

**Comment by HHobeck** [comment]
Hmm I see... you need to ensure that on your release and fix branch the option tracks-release-branches is set to false.

Try this configuration:

```yaml
mode: ContinuousDeployment
commit-message-incrementing: Disabled
branches:
  main:
    increment: Minor
    label: 'beta'
    tracks-release-branches: true
    track-merge-target: true
    prevent-increment-of-merged-branch-version: false
  release:
    increment: Patch
    label: 'rc'
  fix:
    label: '{BranchName}'
    increment: Inherit
    regex: ^fix(es)?[/-]
    source-branches:
    - release
    - fix
```

BTW: You can also use the feature branch instead of defining your own fix branch.
