### ISSUE TITLE
[Feature] Allow to specify the increment number.

### ISSUE THREAD

**Issue by arturcic** [GitTools/GitVersion#3419]
Currently when configuring a branch in the GitVersion.yml we can specify which `increment` strategy to choose.
For example

```yaml
branches:
  develop:
    mode: ContinuousDeployment
    label: alpha
    increment: Minor
```

What would be nice to be able to is to configure how the increment is done - currently the increment happens by adding 1 to the previous value.

What would be handy is to be able to specify to add 2 or any other number that is relevant
