### ISSUE TITLE
[Bug] GitVersion creates pre-release of X after release of X

### ISSUE THREAD

**Issue by tyb-dev** [GitTools/GitVersion#3426]
**Describe the bug**
GitVersion creates version numbers that are not strictly ordered.

## Expected Behavior
Assuming the configuration shown under Context below, we get strictly ordered versions that get higher. 
- 2.0.0-pre.1 [regular commit]
- 2.0.0-pre.2 [regular commit]
- 2.0.0 [tagging]
- 2.0.1-pre.3 or 2.0.1-pre.1 [regular commit]
- 2.0.1-pre.4 or 2.0.1-pre.2 [regular commit]

## Actual Behavior
Our configuration generates the following sequence of versions:
- 2.0.0-pre.1 [regular commit]
- 2.0.0-pre.2 [regular commit]
- 2.0.0 [tagging]
- 2.0.0-pre.3 [regular commit]
- 2.0.0-pre.4 [regular commit]

Note that `2.0.0-pre.3` < `2.0.0`, so we got a lower version number after a commit.

## Possible Fix
Force auto-bump at least patch label after tag. 

## Steps to Reproduce
```
git init

echo 1 > file.txt
git add *
git commit -m "Initial"
git tag 1.0.0

echo 2 > file.txt
git add *
git commit -m "+semver: major"
dotnet gitversion /showvariable FullSemVer

echo 3 > file.txt
git add *
git commit -m "Some changes"
dotnet gitversion /showvariable FullSemVer

git tag 2.0.0

echo 4 > file.txt
git add *
git commit -m "Some changes"
dotnet gitversion /showvariable FullSemVer

echo 5 > file.txt
git add *
git commit -m "Some changes"
dotnet gitversion /showvariable FullSemVer
```

## Context
We use GitHubFlow with ContinuousDeployment. We'd like to manually control when Major.Minor.Patch is changed. Our approach is the following:
```
mode: ContinuousDeployment
increment: None
major-version-bump-message: '\+semver:\s?(breaking|major)'
branches:
  main:
    mode: ContinuousDeployment
    tag: pre
```

I understand that with `increment: None` we indicate no auto-bumping. But GitVersion applies some logic after initializing a fresh repo by starting with "0.1.0-pre.0". For consistency reasons, one could argue that it would be more consistent to use "0.0.0-pre.0" or "0.0.0-pre.1" (somehow assuming an initialized repo is like a tagged 0.0.0 release). 

We build a NuGet library that is passed to downstream projects every 2 weeks. After a couple of months, we may decide to release the library. This is similar to how Microsoft (see e.g. https://www.nuget.org/packages/System.Buffers under Versions) releases their NuGet packages. 

## Your Environment
Environment independent

**Comment by tyb-dev** [comment]
My suggestion would probably make `increment: None` and `increment: Patch` equivalent and I could have simply used the latter.

**Comment by HHobeck** [comment]
Hi @tyb-dev  .

Thank's for your input. What version of GitVersion you are using? May I ask you to create a integration test for your scenario? It helps us alot.  Please use the latest main branch which targeting the next release version 6.x.

```csharp
    [Test]
    public void Just_A_Test()
    {
        // * 2373a87 58 minutes ago  (HEAD -> main)

        var configuration = GitFlowConfigurationBuilder.New
            .WithVersioningMode(VersioningMode.ContinuousDeployment)
            .WithBranch("main", builder => builder
                .WithLabel("ci")
                .WithVersioningMode(VersioningMode.ContinuousDeployment)
            )
            .Build();

        using var fixture = new EmptyRepositoryFixture();

        fixture.MakeACommit();

        // ✅ succeeds as expected
        fixture.AssertFullSemver("0.0.1-ci.1", configuration);

        // or

        // ❌ expected: 0.0.1-ci.5"
        fixture.AssertFullSemver("0.0.1-ci.1", configuration);

        fixture.Repository.DumpGraph();
    } 
```

**Comment by HHobeck** [comment]
By the way in the preview version we have changed the fallback version from 0.1.0 to 0.0.0. ;)

**Comment by HHobeck** [comment]
After following your steps with git I got the following result: `2.0.1-pre.2`

Thus it seems to be solved already in version 6.x. Thank you very much for reporting.

**Comment by HHobeck** [comment]
> After following your steps with git I got the following result: `2.0.1-pre.2`
> 
> Thus it seems to be solved already in version 6.x. Thank you very much for reporting.

Sorry I was mistaken. If I take the following configuration in version 6.x:

```yaml
mode: ContinuousDeployment
increment: None
major-version-bump-message: '\+semver:\s?(breaking|major)'
branches:
  main:
    increment: None
    mode: ContinuousDeployment
    label: pre
```
then I still get `2.0.0-pre.2`. In my opinion it makes no sense to define on the one hand a pre-release label and on the other hand a increment of `none`. GitVersion doesn't increment the version when you specify it to `none`!! Please try this following configuration instead:

```yaml
mode: ContinuousDeployment
increment: None
major-version-bump-message: '\+semver:\s?(breaking|major)'
label: null
branches:
  main:
    increment: None
    mode: ContinuousDeployment
    label: null
```
