### ISSUE TITLE
The patch version is being incremented , even if the increment tag is set to none

### ISSUE THREAD

**Issue by kabilanmani93** [GitTools/GitVersion#3429]
**Describe the bug**
The patch version is being incremented , even if the increment tag is set to none

## Expected Behavior
To patch version should not be incremented , if the increment attribute in gitversion.yml is set to None under the specified branch
```
  hotfix:
    regex: '(hotfix)([/-])'
    tag: 'hotfix'
    increment: None
    prevent-increment-of-merged-branch-version: false
    source-branches: ['release']
    is-source-branch-for: []  
```

## Actual Behavior
The patch version is being incremented 

## Context
We are working on hotfixes on release branch ( refer the below sc for the graph)

-We create a release tag(on Gitlab using release-cli) only on master/main branch based on semversion ( gitversion tool)
-When a release branch is created out of master , the artifacts uploaded with the release tag (main) are used automatically

**issue is when we start having bugs on release branches**
- Current execution
           - We checkout the hotfix branch from release ( pipeline publishes artifacts with pipeline id)
           - when merged to release branch ( we have to manually override the env variable to pull the artifacts which needs to be deployed) ---> this is a manual task, we need to eliminate this by running semversion and create a releasetag in hotfix branch and use the same tag in release branch ( by running the gitversion command)
           
           **issue here is that**
            --> when i make a commit on hotfix branch the patch is incrementing. i do not want that to increment
           --> secondly is there a way to add a prefix having the commitid or random-number. say 2.0.2-hotfix:ef245.5

i have taught of below way of tagging.

![image](https://user-images.githubusercontent.com/46244764/223524922-d57c8285-6c4d-456e-828e-73fe7eed4978.png)

## Your Environment
Gitlab : 14.10.5
Gitlab runners on EKS

**Comment by kabilanmani93** [comment]
@HHobeck 

I have already setup the gitversion, but based on the gitversion.yml setting, the hotfix branch should not increment. but it is

Secondly, is it possible to have a dynamic tag ? example i have made the **tag as hotfix**. Can it prefix with a dynamic variable say commitid ? hotfix.commitid

```
  hotfix:
    regex: '(hotfix)([/-])'
    tag: 'hotfix'
    increment: None
    prevent-increment-of-merged-branch-version: false
    source-branches: ['release']
    is-source-branch-for: [] 
```
