### ISSUE TITLE
[Bug] Performance issue in pre 6.0.0-beta.1

### ISSUE THREAD

**Issue by facusantillo** [GitTools/GitVersion#3442]
**Describe the bug**
Moving pipeline from release 6.0.0-alpha.1 to 6.0.0-beta.1 with same definition files takes 5x times more to calculate the version

## Expected Behavior
Calculate version in release 6.0.0-alpha.1 took around 2 minutes.

## Actual Behavior
In version 6.0.0-beta.1 took approx 10 min

## Context
This is a little bit tricky. In repos with 200+ tags with lots of PR's in the alpha version calculating the version is almost instant while the beta takes too long to finish. We are using the continuous delivery mode. 

## Your Environment

- Version Used: 6.0.0-beta.1
- Operating System and version: Azure DevOps, Self-Hosted Agent with Windows-2022 as vmImage
- Link to your project: it's private project from the organization
- Link to your CI build (if appropriate): it's private project from the organization

## GitVersion YAML:
```
mode: ContinuousDelivery
commit-message-incrementing: enabled

branches:
  release:
    mode: ContinuousDelivery
    regex: ^release?
    label: 'rc'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    tracks-release-branches: false
    track-merge-target: false
    source-branches:
      - develop
      - hotfix
    is-release-branch: true
    is-mainline: false

  develop:
    mode: ContinuousDelivery
    regex: ^develop$
    prevent-increment-of-merged-branch-version: true
    label: 'rc'
    tracks-release-branches: false
    track-merge-target: true
    increment: Minor
    is-release-branch: false
    is-mainline: true
    source-branches: []
    pre-release-weight: 60000

  hotfix:
    mode: ContinuousDelivery
    regex: ^hotfix?
    prevent-increment-of-merged-branch-version: false
    label: hotfix
    tracks-release-branches: true
    track-merge-target: true
    increment: Patch
    is-release-branch: false
    is-mainline: false    
    source-branches:
      - develop
      - release
    pre-release-weight: 30000

  pull-request:
    mode: ContinuousDelivery
    label: 'PR'
    increment: Inherit
    regex: ^pull?
    is-release-branch: false
    prevent-increment-of-merged-branch-version: false
    is-mainline: false
    tracks-release-branches: false
    track-merge-target: false
    source-branches:
      - feature
      - hotfix
      - develop
      - release
    pre-release-weight: 30000
    
  feature:
    mode: ContinuousDelivery
    label: 'rc'
    increment: Inherit
    regex: ^feature?
    is-release-branch: false
    prevent-increment-of-merged-branch-version: false
    is-mainline: false
    tracks-release-branches: false
    track-merge-target: true
    source-branches:
      - feature
      - hotfix
      - develop
      - release
    pre-release-weight: 30000
```

Logs: 

[gitlog alpha version.txt](https://github.com/GitTools/GitVersion/files/10999155/gitlog.alpha.version.txt)
[gitlog beta version.txt](https://github.com/GitTools/GitVersion/files/10999157/gitlog.beta.version.txt)
