### ISSUE TITLE
[Bug] Incrementing `patch` version automatically on `main` without tags nor specific commit messages

### ISSUE THREAD

**Issue by ni-fgenois** [GitTools/GitVersion#3570]
### Discussed in https://github.com/GitTools/GitVersion/discussions/2660

<div type='discussions-op-text'>

<sup>Originally posted by **franknarf8** April 13, 2021</sup>
Hello,

I have just upgraded my GitVersion to the latest, but I can't find a way to reproduce the behavior I expect, and used to achieve with the previous GitVersion. (the change appeared between since 5.0.0)

When using `Mainline`, I would expect that each merge commits to `master` cause the `patch` version to increment. (Without any commit messages required)

Using the following `GitVersion.yml` (I'm generating pip versions here, please disregard the `branches`) :

```
mode: Mainline
next-version: 1.0.0
branches:
  release:
    tag: 'rc'
  feature:
    regex: ^features?[/-]|^(pull|pull\-requests|pr)[/-]
    tag: 'dev'
  develop:
    tag: 'a'
  hotfix:
    tag: 'post'
ignore:
  sha: []
merge-message-formats: {}
```

With this dummy git repo :
```
*   0bac05d 3 minutes ago  (HEAD -> master)
|\
| * 2922409 3 minutes ago  (feature/first-feature)
| * 2246a3e 7 minutes ago
|/
* bc00c9f 7 minutes ago  (tag: 1.2.3)
```

GitVersion 5.6.8 is inferring : `1.2.3`
whereas 5.0.0 inferred : `1.2.4`

I would expect `1.2.4` here, how can I achieve this?</div>
