### ISSUE TITLE
[Bug]  When using ContinuousDeployment, Version number restarts at 1 every day. (devops)

### ISSUE THREAD

**Issue by vllama** [GitTools/GitVersion#3577]
**Describe the bug**
In Azure Devops:
We have library set up for ContinuousDeployment when committing to a Sprint* or develop* branch. Every morning the preview number resets to 1. As well it resets to 1 when a build is manually run.

<img width="598" alt="image" src="https://github.com/GitTools/GitVersion/assets/43180217/14485862-c310-45d9-9010-b021d253dda6">

## Expected Behavior
The preview number should increment indefinitely.

## Actual Behavior
The Preview number resets to 1.

## Possible Fix

N/A
## Steps to Reproduce

```
assembly-file-versioning-format: '{Major}.{Minor}.{Patch}.{WeightedPreReleaseNumber ?? 0}'
assembly-versioning-scheme: MajorMinorPatch
branches:  
  release:
    regex: releases?[/-]
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
  develop:
    regex: ^(dev(elop)?(ment)?)|(Sprint.+)$
    mode: ContinuousDeployment
    tag: 'Preview'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: false
    is-release-branch: false    
ignore:
  sha: []
```

## Your Environment

- Version Used:  Tool 'gitversion.tool' (version '5.12.0') 
- Operating System and version (Windows 10, Ubuntu 18.04):  windows-latest agent in devops
- Link to your project:
- Link to your CI build (if appropriate):
