### ISSUE TITLE
[Question] How to get tag to take precedence over branch?

### ISSUE THREAD

**Issue by tig** [GitTools/GitVersion#3591]
I posted this on the chat, but got no response.

Hi. I need some help; I've been struggling to figure this out for two days and I'm either massively misunderstanding something, or something ;-).

Project: https://github.com/gui-cs/Terminal.Gui

For v1 gitversion is working fine. main is the release branch and develop is the develop branch. We publish to Nuget via publish.yml on a push of a new tag: 

https://github.com/gui-cs/Terminal.Gui/blob/main/.github/workflows/publish.yml

For our next major version (v2), we want to temporarily publish with -alpha on a push to v2_develop of a new tag. : 

https://github.com/gui-cs/Terminal.Gui/blob/v2_develop/.github/workflows/publish.yml

What ends up getting generated looks like this: `2.0.0-tags-v2-0-0-alpha-14.1` instead of `2.0.0-alpha-14`

Here's my gitversion.yml: 

```yaml
branches: 
  v2_develop:
    regex: v2_develop
    tag: alpha
    source-branches: 
      - v2_develop
```

What am I doing wrong?
