### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JohnnHidalgo** [GitTools/GitVersion#3623]
**Describe the bug**
Im implementing CI/CD process with github actions into my flutter app, Im using gitversion to manage verions that is my  actions file configuration

```
name: desarrollo_ci_cd
on:
  push:
    branches:
      - main

jobs:

  version:
    name: Creando numero de compilacion
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v0.10.2
          with:
            versionSpec: '5.x'

        - name: Use GitVersion
          id: gitversion
          uses: gittools/actions/gitversion/execute@v0.10.2
       
        - name: Create version.txt with nuGetVersion
          run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt

        - name: Upload version.txt
          uses: actions/upload-artifact@v2
          with:
            name: gitversion
            path: version.txt
```

On github panel the pressese was stopped on Use GitVersion step with this error:
`Error: Error: The process '/opt/hostedtoolcache/GitVersion.Tool/5.12.0/x64/dotnet-gitversion' failed with exit code 1`

Im trying with diferent version in versionSpec  with the same result
