### ISSUE TITLE
Wrong version number even the correct one seems to be calculated

### ISSUE THREAD

**Issue by lbass2** [GitTools/GitVersion#3633]
Hello,

We are using the GitVersion task in our Azure pipeline. Now it seems like GitVersion produces the wrong version number, even though the output suggests the correct one was found.
A merge from a feature branch to develop was done by completing a pull request. A previous tag "32.35.0-alpha.25" exists and seems to be found and and used as base. Next expected version on develop would be 32.35.0-alpha.26.

Everything looks fine, but in the end version "32.35.0-alpha.2" is set as build number.

See the following output

![image](https://github.com/GitTools/GitVersion/assets/140484585/ff900fd6-47de-4fa2-a117-4470e665741a)

GitVersion is running as a task inside Azure pipelines. 
GitVersion Task version 5.0.1 is used. 

Our GitVersion.yml looks like this:

```
next-version: 32.12.0
branches:
  master:
    regex: master
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
  release:
    regex: releases?[/-]
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
  feature:
    regex: feature(s)?[/-]
    mode: ContinuousDelivery
    tag: Feature.{BranchName}
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
  develop:
    regex: develop
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false
``` 

Any ideas what the problem might be?
