### ISSUE TITLE
[Bug] wrong number bumped on conventional-commits 

### ISSUE THREAD

**Issue by mrt181** [GitTools/GitVersion#3678]
**Describe the bug**
Given this history

```shell
$ git log --max-count 27 --pretty="%C(auto)%h %(describe) %s" | awk -F':' '{print $1}'
a03a4d2 1.0.0-35-ga03a4d2 ci
8cf0672 1.0.0-34-g8cf0672 ci
dbe3aac 1.0.0-33-gdbe3aac Add renovate.json
c8f65f5 1.0.0-32-gc8f65f5 chore
f193afc 1.0.0-31-gf193afc ci
4e44801 1.0.0-30-g4e44801 ci
1516cce 1.0.0-29-g1516cce ci
be1f963 1.0.0-28-gbe1f963 ci
d62399f 1.0.0-27-gd62399f build
67408a8 1.0.0-26-g67408a8 ci
1117058 1.0.0-25-g1117058 ci
a6a437c 1.0.0-24-ga6a437c ci
bab150b 1.0.0-23-gbab150b chore
2fc16c0 1.0.0-22-g2fc16c0 feat(csharp)
22a687d 1.0.0-21-g22a687d build
58ccbef 1.0.0-20-g58ccbef build
813491f 1.0.0-19-g813491f docs
e10a246 1.0.0-18-ge10a246 build
92f25fa 1.0.0-17-g92f25fa Merged PR 1782
e1dac61 1.0.0-16-ge1dac61 docs
a811312 1.0.0-15-ga811312 build
ae78c6c 1.0.0-14-gae78c6c docs
7586e6f 1.0.0-13-g7586e6f Merged PR 1778
10a4d19 1.0.0 release
65b7297 1.0.0-beta.2-1-g65b7297 docs
8c7a1c3 1.0.0-beta.2 release
d5bb6e8 1.0.0-beta.1-41-gd5bb6e8 Merged PR 1777
```

The latest tag is `1.0.0` at commit `10a4d19`

## Expected Behavior
I should get a version like this
```shell
dotnet gitversion | jq '.FullSemVer'
"1.1.0+35"
```

Because of the `1.0.0` tag and the feature commit `2fc16c0 1.0.0-22-g2fc16c0 feat(csharp)` that appears later.

## Actual Behavior
But I get a version like this
```shell
dotnet gitversion | jq '.FullSemVer'
"1.0.1+35"
```

## Context
I am trying to create packages containing proto files only for java and dotnet.
For java I am using this plugin [Git.SemVersioning.Gradle](https://github.com/jmongard/Git.SemVersioning.Gradle)

This one returns the expected version:
```shell
$ ./gradlew printVersion | grep 'Version: ' | awk -F' ' '{print $2}'
1.1.0-SNAPSHOT+035.sha.a03a4d2
```

## Your Environment
This is my gitversion.yml
```yaml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
assembly-informational-format: '{InformationalVersion}'
mode: Mainline
continuous-delivery-fallback-tag: ci
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-]*\\))?:"
patch-version-bump-message: "^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"
update-build-number: false
```
- Version Used:
- Ubuntu 23.04
- GitVersion 5.12.0
