### ISSUE TITLE
[Improvement] Add a way to disable default/base config branch policies

### ISSUE THREAD

**Issue by gerardog** [GitTools/GitVersion#3736]
It is confusing that there is a set of "secret" default branch policies that cant be easily removed.
Re: #3735

This is my gitversion file
```
mode: Mainline
branches:
  master:
    regex: '^master$|^main$'  
  other:
    mode: ContinuousDelivery
    regex: '^(?!master$|^main$/).*$'  # All branches except main, master
    tag: '{BranchName}'               # Shall have a prerelease tag based on the branch name.
    source-branches: ['main', 'master']
    increment: patch
``` 

... and I dont expect it to throw 'Multiple branch configurations match the current branch' warning because there are 6 implied default policies I need to delete: develop, release, feature, pull-request, hotfix and support
... and that I discovered by chance while diagnosing this warning message, when I ran `/showconfig`

If I create a branch that matches any of those 6 branch policies regex, while also matching my `other`, it will throw the error.
This problem was triggered when someone pushed a branch with a naming that matched both policies, like `feature/something`

The warning break the pipeline as described in #3735

## Context
So I don't have to clutter my gitversion with disabling 6 policies, which i dont know how to do btw. Shall I put bad regex to all of them?.

## Possible Implementation

Either:
- I don't like the idea of a implied (and so large) base config. But I guess remove that is really breaking.
- Add a config to avoid loading base config branch policies: 
- if the branch regex matches only one user-config policy, dont throw the warning even if it also matches a base-config policy
- fix the error message #3735 `Multiple branch configurations match the current branch`
