### ISSUE TITLE
[Feature] The increment of the target branch will be ignored when prevent-increment is set to true on the source branch

### ISSUE THREAD

**Issue by HHobeck** [GitTools/GitVersion#3922]
## Detailed Description

Introduce a new branch related property of name `prevent-increment-when-branch-merged`. This property can be used like the `prevent-increment-ob-merged-branch` to control the behavior how to increment the version of merged branches on the source branch.

The configruation could be look like as following:
```yaml
prevent-increment:
  of-merged-branch: false
  when-branch-merged: false // new branch related property
  when-current-commit-tagged: true
```

## Context

Following business statement applies:

The increment of the target branch will be ignored, regardless of whether the merged branch has a version number or not, when
- `prevent-increment-of-merged-branch` is set to true on the target branch or
- `prevent-increment-when-branch-merged` is set to true on the source branch
