### ISSUE TITLE
[ISSUE]: dotnet-gitversion fails using 6.0.0-beta.6 in mainline mode

### ISSUE THREAD

**Issue by DSpirit** [GitTools/GitVersion#3947]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.0-beta.6

### Operating system

Linux, Windows

### What are you seeing?

Could not build the configuration instance because following exception occurred: 'Requested value 'Mainline' was not found.' Please ensure that the /overrideconfig parameters are correct and the configuration file is in the correct format.

### What is expected?

Previous builds on 6.0.0-beta.5 had no issues and something like:
Begin: Getting tagged semantic versions of mainline branches. Format: Strict...

### Steps to Reproduce

``` bash
dotnet tool update --global GitVersion.Tool --prerelease
dotnet-gitversion /config .\GitVersion.v6.yml
```
using this config:
``` yaml
mode: Mainline
update-build-number: false
branches:
  main:
    regex: ^master$|^main$
  feature:
    regex:  ^feature(s)?[/-]
    label: 'beta'
    increment: minor
    mode: ContinuousDeployment
  hotfix:
    regex: ^(hot|bug)?fix(es)?[/-]
    label: 'beta'
    increment: Patch
    mode: ContinuousDeployment
  release:
    regex: ^releases?[/-]
    label: rc
    mode: ContinuousDeployment
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    label: alpha
  dependabot:
    mode: ContinuousDelivery
    regex:  ^dependabot?[/-]
    source-branches: ['feature','main','hotfix','dependabot']
    label: 'alpha'
    increment: Patch
ignore:
  sha: []
```
