### ISSUE TITLE
[ISSUE]: GitVersion complains about shallow repository in Azure DevOps

### ISSUE THREAD

**Issue by mc0re** [GitTools/GitVersion#4094]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

5.12.0

### Operating system

Windows

### What are you seeing?

Just stumbled upon this error in an Azure pipeline executed on a home-made VM. Possibly I lack some setting somewhere.
*Error*
```
Running on: 'Azure Pipelines'
Disable Telemetry
Executing GitVersion
Command: git -C C:/agent/_work/1/s rev-parse --is-shallow-repository
C:\agent\externals\git\cmd\git.exe -C C:/agent/_work/1/s rev-parse --is-shallow-repository
true
##[error]The repository is shallow. Consider disabling shallow clones. See https://github.com/GitTools/actions/blob/main/docs/cloning.md for more information.
```

### What is expected?

No error.

### Steps to Reproduce

Create a VM in Azure, install the latest GIT and other tools.

*Azure pipeline*
```yaml
    steps:
    - checkout: self
      clean: true
      fetchDepth: 0
      fetchTags: true
      submodules: recursive

    - task: gitversion/setup@1
      displayName: Install GitVersion
      inputs:
        versionSpec: $(GitVersionVersion)

    - task: gitversion/execute@1
      displayName: Determine current version
      inputs:
        useConfigFile: true
        configFilePath: ./GitVersion.yml
```
`GitVersionVersion` is `5.x`

*GitVersion.yml*
```yaml
mode: Mainline
branches:
  master:
    regex: ^master$|^main$
```
