### ISSUE TITLE
[FEATURE]: Support of '=semver: none|minor|major|patch' bump message to suppress the version increment

### ISSUE THREAD

**Issue by HHobeck** [GitTools/GitVersion#4144]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.1

### Operating system

Windows

### What are you seeing?

[FEATURE]: Support of '=semver: none|minor|major|patch' bump message to suppress the version increment

This feature was inspired from the following discussion:
- https://github.com/GitTools/GitVersion/discussions/4143

We need a new bump message format to suppress the version increment of a version calculation run. I think e.g. `=semver: none|minor|major|patch` bump message should be used as a default format for the following workflows:
- GitFlow/v1
- GitHubFlow/v1
- TrunkBased/preview1

### What is expected?

If you specify `=semver: none` the increment value of the e.g. branch configuration will be overruled.

### Steps to Reproduce

Using the configuration:
```yaml
workflow: TrunkBased/preview1
branches:
  main:
    mode: ContinuousDelivery
    increment: Patch
```

**USE CASE 1:**
with the following commits on main:
- 'a commit with a tag' (tag: 1.0.0)
- 'message one =semver: none'
- 'message two =semver: none'
- 'message three =semver: none'

should yield to:
1.0.0-3

**USE CASE 2:**
with the following commits on main:
- 'a commit with a tag' (tag: 1.0.0)
- 'message one +semver: minor'
- 'message two =semver: none'
- 'message three =semver: none'

should yield to:
1.1.0-3

**USE CASE 3:**
with the following commits on main:
- 'a commit with a tag' (tag: 1.0.0)
- 'message one =semver: none'
- 'message two +semver: minor'
- 'message three =semver: none'

should yield to:
1.1.0-2

**USE CASE 4:**
with the following commits on main:
- 'a commit with a tag' (tag: 1.0.0)
- 'message one =semver: none'
- 'message two =semver: none'
- 'message three +semver: minor'

should yield to:
1.1.0-1

Using the configuration:
```yaml
workflow: GitFlow/v1
branches:
  main:
    mode: ContinuousDelivery
    increment: Patch
```

**USE CASE 5:**
with the following commits on main:
- 'a commit with a tag' (tag: 1.0.0)
- 'message one =semver: none'
- 'message two =semver: none'
- 'message three =semver: none'

should yield to:
1.0.0-3

**USE CASE 6:**
with the following commits on main:
- 'a commit with a tag' (tag: 1.0.0)
- 'message one +semver: minor'
- 'message two =semver: none'
- 'message three =semver: none'

should yield to:
1.0.0-3

**USE CASE 7:**
with the following commits on main:
- 'a commit with a tag' (tag: 1.0.0)
- 'message one =semver: none'
- 'message two +semver: minor'
- 'message three =semver: none'

should yield to:
1.0.0-3

**USE CASE 8:**
with the following commits on main:
- 'a commit with a tag' (tag: 1.0.0)
- 'message one =semver: none'
- 'message two =semver: none'
- 'message three +semver: minor'

should yield to:
1.1.0-3

**Comment by Jaykul** [comment]
This already exists, but In [the configuration](https://gitversion.net/docs/reference/configuration) the default requires the `+semver:none` or `+semver:skip` because of the configuration:

```yaml
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
```

I always tell people to remove the + from the front, and require it to be on a new line, to make the message a valid git trailer:

```yaml
major-version-bump-message: '^semver:\s?(breaking|major)'
minor-version-bump-message: '^semver:\s?(feature|minor)'
patch-version-bump-message: '^semver:\s?(fix|patch)'
no-bump-message: '^semver:\s?(none|skip)'
```

But in any case, it does suppress the version increment...
