### ISSUE TITLE
[ISSUE]: Cannot git fetch --unshallow with AzureDevOps

### ISSUE THREAD

**Issue by jzabroski** [GitTools/GitVersion#4146]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

5.12

### Operating system

Windows

### What are you seeing?

This may not be a "GitVersion" issue but I imagine half of all GitVersion users have the same problem as me. On a NEW AzureDevOps pipeline (created today), `fetchDepth: 0` does not seem to be respected. The error message I get on GitVersion/Execute@0 is 

```
  INFO [08/06/24 15:43:06:60] Begin: Calculating base versions
    INFO [08/06/24 15:43:06:63] NextVersion in GitVersion configuration file: 5.2.0 with commit count source External Source
  INFO [08/06/24 15:43:06:66] End: Calculating base versions (Took: 63.77ms)
  ERROR [08/06/24 15:43:06:87] An unexpected error occurred:
GitVersion.GitVersionException: Cannot find commit 89e8138 #1848: Ensure English validation messages in tests. Please ensure that the repository is an unshallow clone with `git fetch --unshallow`.
 ---> LibGit2Sharp.NotFoundException: object not found - no match for id (214345132f8b599ce72fdd21bf966baf894aae2d)
```

I've configured my ci/cd build pipeline to use `fetchDepth: 0`, as described in AzureDevOps pipleine official documentation [steps.checkout Shallow Fetch](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#shallow-fetch)

https://github.com/fluentmigrator/fluentmigrator/blob/c7efaa137419963f2126cfb98a8fc96fac6230fc/azure-pipelines-pullrequests.yml#L24-L25

I'm not the only user with this problem, c.f. https://github.com/GitTools/GitVersion/issues/3612#issuecomment-2214040845

Worth noting, on GitHub, if you change your default branch name from master to main, you need to re-create your AzureDevOps pipeline, as AzureDevOps permanently caches that pipeline file as belonging to the master branch (this isn't documented anywhere online, and something I figured out empirically through testing).

### What is expected?

Perhaps a better guidance than just `git fetch --unshallow`.  Perhaps working more closely with key CI/CD vendors to ensure GitVersion works as expected.  It's almost as if these vendors have no idea how users use their pipelines when fundamental things like these break, so the hope/aspiration is that education is key.

### Steps to Reproduce

1. Create new Azure DevOps pipeline file with the following:
    ```yaml
    trigger: none

    pr:
      branches:
        include:
        - main

    pool:
      vmImage: 'windows-latest'

    steps:
     - checkout: self
       fetchDepth: 0

     - task: gitversion/setup@0
       displayName: 'Install GitVersion (using GitTools 0.10.2.23031113 or later)'
       inputs:
         versionSpec: '5.12'
         includePrerelease: true

     - task: gitversion/execute@0
       displayName: 'Execute GitVersion (using GitTools 0.10.2.23031113 or later)'
       inputs:
         updateAssemblyInfo: false
   ```
2. Give Azure DevOps access to your GitHub repo
4. Run pipeline

### Output log or link to your CI build (if appropriate).

```shell
This build will be deleted automatically in a few weeks as its a free organization (open source project):

https://dev.azure.com/fluentmigrator/fluentmigrator/_build/results?buildId=981&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=63e8042a-f367-5aec-692c-fcc654be55e4
```

**Comment by jzabroski** [comment]
Changing
```yaml
 - checkout: self
   fetchDepth: 0
```
to
```yaml
 - checkout: self
   clean: true
   fetchDepth: 0
   fetchTags: true
```

Fixed the problem, but I do not understand why.
