### ISSUE TITLE
[ISSUE]: GitHubFlow workflow isn't bumping versions

### ISSUE THREAD

**Issue by travaille-dev** [GitTools/GitVersion#4165]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

6.0.2

### Operating system

Linux, macOS

## Background
I have a class library. With our ci/cd pipeline for prs we test, build, and publish that nuget package to a snapshot nuget repo.
After a pr gets merged, we'd like to consider this a 'release', version accordingly, and publish to a production nuget repo. That means no pre release tags.

We use conventional commits to bump versions based on commit messages. Things have upgraded with the library since the docs have provided guidance on conventional commits and I don't think mainline mode is supported anymore

Our config
``` yml
workflow: GitHubFlow/v1
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|config)(\\([\\w\\s-,/\\\\]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-,/\\\\]*\\))?:"
patch-version-bump-message: "^(fix|perf|config|refactor|chore)(\\([\\w\\s-,/\\\\]*\\))?:"
ignore:
  sha: []
```

## Issue
I can't get the minor/patch to increment for my life on a feature branch.

I have tried removing my bump-message overrides to just the default `+semver: whatever` ones and still it's a no go.

### What is expected?

If I write a commit message like `chore(help):please bump the patch` I would like the patch to be bumped up. 
If I write a commit message like `feat(help): please bump the minor` I would like the. minor to be bumped up.

If I'm thinking of this workflow incorrectly then let me know, but how can I get these major/patch increments to work.
the full semver does increment because it has build metadata

### Steps to Reproduce

have 6.0.2 installed as a dotnet tool
create a feature/fake branch off of main
make commit(s) like `chore(help):please bump the patch` and `feat(help): please bump the minor` 
run `dotnet-gitversion` and see no minor or patch increments. Just the build metadata
