### ISSUE TITLE
[ISSUE]: Azure DevOps execute task uses wrong path for dotnet-gitversion(.exe)

### ISSUE THREAD

**Issue by vanmash** [GitTools/GitVersion#4320]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

5.12.0

### Operating system

Windows, Linux

### What are you seeing?

Linux
```
/bin/sh: 1: /opt/agent/_work/_tool/GitVersion.Tool/5.12.0/dotnet-gitversion: not found
```

Windows
```
'C:\agent\_work\_tool\GitVersion.Tool\5.12.0\dotnet-gitversion.exe' is not recognized as an internal or external command,
```

### What is expected?

use correct paths (x64 is missing)

Windows:
```
C:\agent\_work\_tool\GitVersion.Tool\5.12.0\x64\dotnet-gitversion.exe
```

Linux:
```
/opt/agent/_work/_tool/GitVersion.Tool/5.12.0/x64/dotnet-gitversion
```

### Steps to Reproduce

```
- task: gitversion/setup@3
   displayName: Install GitVersion
   inputs:
     versionSpec: '5.x'

- task: gitversion/execute@3
  displayName: Execute GitVersion
  inputs:
    updateAssemblyInfo: true
```

### Output log or link to your CI build (if appropriate).

```shell

```
