### ISSUE TITLE
[ISSUE]: gitversion/setup@3 fails to install GitVersion 6.1.0

### ISSUE THREAD

**Issue by almguru** [GitTools/GitVersion#4343]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

6.1.0

### Operating system

Linux

### What are you seeing?

I'm running

```yml
- task: gitversion/setup@3
  displayName: 'Install GitVersion'
  inputs:
    versionSpec: '6.x'
```

and it fails with an error: "Version spec '6.x' resolved as '6.1.0' does not satisfy the range '>=5.2.0 <6.1.0'.See https://github.com/GitTools/actions/blob/main/docs/versions.md for more information."

### What is expected?

it should install Gitversion v6.1.0 with no issues.

### Steps to Reproduce

Run the pipeline that contains:

```yml
- task: gitversion/setup@3
  displayName: 'Install GitVersion'
  inputs:
    versionSpec: '6.x'
```

### Output log or link to your CI build (if appropriate).

```shell

```
