### ISSUE TITLE
[ISSUE]: Gitversion does not generate semvers as expected

### ISSUE THREAD

**Issue by noebuerki** [GitTools/GitVersion#4378]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

5.12.0

### Operating system

Linux

### What are you seeing?

Hello

I am currently trying to configure gitversion but can't set it up the way i would like.

We do all of our development directly on the dev branch, feature branches are not used.
This is because a single project most of the time only has 1 person working on it.
We automatically deploy to the test-stage from dev.

As soon as the code on the dev branch is deemed stable, it gets merged into main.
This pull request causes the code to be deployed to prod.

Currently, i am using the configuration below. I tried multiple configurations but none of them worked the way i intended.
```
mode: Mainline
increment: Inherit
update-build-number: true
branches:
 main:
   tag:
   regex: ^main$
   increment: Minor
   is-mainline: true
   source-branches: [ 'dev' ]
 dev:
   tag:
   regex: ^dev$
   increment: Patch
   source-branches: [ 'feature' ]
ignore:
 sha: []
```

### What is expected?

In light of this workflow, we would wish for the following behaviour 
- Any time a commit goes into dev, the patch version should be bumped: 1.1.0 -> 1.1.1 -> 1.1.2
- Any time a pull request goes into main, the minor version should be bumped: 1.1.0 -> 1.2.0 -> 1.3.0

Is it possible to implement this behaviour using the config?

### Steps to Reproduce

See the config described above

### Output log or link to your CI build (if appropriate).

```shell

```

**Comment by noebuerki** [comment]
Update:
i was now able to create a config that increments the minor version on every commit to main.
i still struggle with the version number on dev. it currently looks like this: 1.2.0-alpha.4
how could i resolve this issue?

the current config is as follows: 
```
mode: Mainline
increment: Inherit
update-build-number: true
branches:
  main:
    regex: ^main$
    increment: Minor
    is-mainline: true
    is-release-branch: true
    source-branches: ["develop"]
  develop:
    regex: ^dev$
    increment: Minor
ignore:
  sha: []
```
