### ISSUE TITLE
[ISSUE]: ADO execute@0 Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by grixxie** [GitTools/GitVersion#4394]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

5.11.1

### Operating system

Linux

### What are you seeing?

A YAML CI/CD pipeline in ADO that has been working for a long time, is suddenly failing since last night. The agent is self-hosted Linux, with Git version 2.34.1 installed.

The install task is installing version 5.11.1 of the GitVersion Tool, which is the same version the pipeline was using yesterday when this was working.
The install and execute tasks are both version 0.13.6, which is the same version the pipeline was using yesterday when this was working.

The settings of the pipeline are configured to have ```shallow fetch``` disabled.

The ```Install``` task appears to work fine.
The ```Execute``` task is failing with the following:
```
Starting: Use GitVersion
==============================================================================
Task         : Execute GitVersion Task
Description  : Easy Semantic Versioning (https://semver.org) for projects using Git
Version      : 0.13.6
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
Agent: 'Azure Pipelines'
Command: git rev-parse --is-shallow-repository
/usr/bin/git rev-parse --is-shallow-repository
fatal: not a git repository (or any of the parent directories): .git
Command: dotnet-gitversion /agent/_work/18/s /output json /output buildserver /config /agent/_work/18/s/GitVersion.yml
/agent/_work/_tool/GitVersion.Tool/5.11.1/x64/dotnet-gitversion /agent/_work/18/s /output json /output buildserver /config /agent/_work/18/s/GitVersion.yml
unsupported extension name extensions.worktreeconfig
INFO [01/24/25 14:27:57:48] Working directory: /agent/_work/18/s
INFO [01/24/25 14:27:57:51] Done writing 
##[error]TypeError: Cannot read property 'message' of undefined
Finishing: Use GitVersion
```

I don't believe that anything on my side has changed since yesterday, so I'm struggling to fix this! Any more information required let me know!

Any suggestions or help is much appreciated.

### What is expected?

I would expect this to not error. As mentioned, the same pipeline with the seemingly the same versions of the tools was working fine yesterday.

### Steps to Reproduce

My GitVersion tasks in the pipeline look like the following:

```
stages:
  - stage: Build_and_Publish
    jobs:
      - job: Build
        pool:
          name: MyAgents

        steps:
          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: '5.11.1'

          - task: gitversion/execute@0
            displayName: Use GitVersion
            inputs:
              updateAssemblyInfo: false
              useConfigFile: true
              configFilePath: './GitVersion.yml'

          - task: Bash@3
            displayName: 'Set Build Number to Semantic Version'
            inputs:
              targetType: 'inline'
              script: 'echo "##vso[build.updatebuildnumber]$(fullSemVer)"'
```

As mentioned above, issue is on the Execute task.

### Output log or link to your CI build (if appropriate).

```shell

```

**Comment by adm-carewk** [comment]
We are also getting this error with the latest version of the ADO task `gitexecute@3`, suddenly failing all our pipeline runs since last week.

Relevant tasks in **pipelines/config/gitVersionBranch.yml**:
```steps:
    - task: gitversion/setup@3
      inputs:
        versionSpec: '6.0.x'

    - task: gitversion/execute@3
      inputs:
        useConfigFile: true
```

**Pipeline run logs** for `gitversion/execute@3`:
```Starting: gitversionexecute
==============================================================================
Task         : Execute GitVersion Task
Description  : Easy Semantic Versioning (https://semver.org/) for projects using Git
Version      : 3.1.11
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
Running on: 'Azure Pipelines'
Disable Telemetry
Command: git -C /__w/12/s rev-parse --is-shallow-repository
Command: /__t/GitVersion.Tool/6.0.5/dotnet-gitversion --roll-forward Major /__w/12/s /output json /l console /config /__w/12/s/pipelines/config/gitVersionBranch.yml
##[error]GitVersion output is not valid JSON
dotnet-gitversion Output:
-------------------
undefined
-------------------
undefined
Finishing: gitversionexecute
```

The `gitversion/setup@3` run logs also includes the "undefined" output at the end, but the task itself doesn't fail:
```Starting: gitversionsetup
==============================================================================
Task         : Setup GitVersion Task
Description  : Easy Semantic Versioning (https://semver.org/) for projects using Git
Version      : 3.1.11
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
Running on: 'Azure Pipelines'
Disable Telemetry
--------------------------
Acquiring GitVersion.Tool for version spec: 6.0.x
--------------------------
Querying tool versions for GitVersion.Tool@6.0.x 
Found matching version: 6.0.5
Looking for local tool GitVersion.Tool@6.0.5
Directory /__t/GitVersion.Tool/6.0.5 not found
Command: dotnet tool install GitVersion.Tool --tool-path /__w/_temp/dc030274-9a09-4145-8863-5afcba1b9044 --version 6.0.5
--------------------------
GitVersion.Tool version: 6.0.5 installed.
--------------------------
Prepending /__t/GitVersion.Tool/6.0.5 to PATH
Updated PATH: /__t/GitVersion.Tool/6.0.5:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Set GITVERSION_PATH to /__t/GitVersion.Tool/6.0.5
dotnet-gitversion installed successfully
dotnet-gitversion Output:
-------------------
undefined
-------------------
GitVersion setup successfully
Finishing: gitversionsetup
```

**Comment by skorobkov-expd** [comment]
Yeah, it is not first time this action is broken. I am done, today was the last straw.
I have decided to stop using action and switch to run GitVersion in container, hope I won't see broken pipelines anymore.
```
resources:
  containers:
    - container: gitVersionContainer
      image: gittools/gitversion:6.0.5
      mapDockerSocket: false
      options: --entrypoint ""
      env:
        TF_BUILD: true
        BUILD_SOURCEBRANCH: $(Build.SourceBranch)
stages:
  - stage: GitVersion
    jobs:
      - job: SemVer
        workspace:
          clean: all
        steps:
          - checkout: self
            fetchDepth: 0
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                /tools/dotnet-gitversion /__w/1/s /config /__w/1/s/packaging/GitVersion.yml /l console /output buildserver
            target:
              container: gitVersionContainer
            displayName: Run GitVersion
            name: output
          - task: Bash@3
            inputs:
              targetType: inline
            script: |
              echo "##vso[task.setvariable variable=FullSemVerRPM;isOutput=true]${GITVERSION_FULLSEMVER//-/_}"
            displayName: RPM FullSemVer
            name: outputRPM
  - stage: ShowVarsStage
    variables:
      FullSemVerRPM: $[stageDependencies.GitVersion.SemVer.outputs['outputRPM.FullSemVerRPM']]
      FullSemVer: $[stageDependencies.GitVersion.SemVer.outputs['output.GitVersion.FullSemVer']]
      CommitSha: $[stageDependencies.GitVersion.SemVer.outputs['output.GitVersion.Sha']]
    jobs:
      - job: show_vars_in_bash
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                echo ${FullSemVerRPM}
                echo ${FullSemVer}
                echo ${CommitSha}
```

**Comment by grixxie** [comment]
Managed to get the issue I was facing sorted.

``` unsupported extension name extensions.worktreeconfig ```
This line was a big hint that I didn't pay enough attention to. So before the ```gitversion/setup``` task in my pipeline, I'm simply doing the following now:

```
- task: PowerShell@2
   displayName: 'Disable git worktreeconfig'
   inputs:
     targetType: 'inline'
     script: |
       git config --unset-all extensions.worktreeconfig
```

And this allowed GitVersion's execute task to run as it should.
I have **no idea** how this suddenly became an issue for all of my pipelines overnight though.
