### ISSUE TITLE
[ISSUE]: unsupported extension name extensions.worktreeconfig

### ISSUE THREAD

**Issue by GaryFail** [GitTools/GitVersion#4512]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

GitVersion.Tool

### GitVersion version

5.12.0

### Operating system

Linux

### What are you seeing?

This was working fine last Thursday (17th April 2025) in Azure DevOps

```
           - checkout: self
             fetchDepth: 0
             persistCredentials: true

            - task: gitversion/setup@3.0.3
              displayName: Install GitVersion
              inputs:
                versionSpec: "5.x"

            - task: gitversion/execute@3.0.3
              displayName: Determine Version
              inputs:
                useConfigFile: true
                configFilePath: '$(build.sourcesdirectory)/GitVersion.yml'
```

However it now fails on the Determine Version with the following:

Executing GitVersion
Command: git -C /azp/_work/1/s rev-parse --is-shallow-repository
Command: /azp/_work/_tool/GitVersion.Tool/5.12.0/dotnet-gitversion /azp/_work/1/s /output json /output buildserver /config /azp/_work/1/s/GitVersion.yml
##[error]Command failed: /azp/_work/_tool/GitVersion.Tool/5.12.0/dotnet-gitversion /azp/_work/1/s /output json /output buildserver /config /azp/_work/1/s/GitVersion.yml
unsupported extension name extensions.worktreeconfig

### What is expected?

The Version to be determined

### Steps to Reproduce

Azure Pipeline Run with the given steps

### Output log or link to your CI build (if appropriate).

```shell

```
