### ISSUE TITLE
master branch is considering pre-release tags created in other branches

### ISSUE THREAD

**Issue by lsgroi** [GitTools/GitVersion#498]
I have a development branch used to create pre-release versions. I pre-release tag every version e.g. `0.2.0-unstable0002`. When I merge into master I do merge as well every pre-release tag.

The problem I find is that GitVersion (currently I use the command line) does consider pre-release tags when it works out the new version in master. Let's say I create and tag pre-relase `0.2.0-unstable0002`in the development branch, merge that into master in which the last tag is `0.1.5`; now, I would expect GitVersion to consider the merge as `0.2.0` version while the SemVer property is `0.2.0-unstable0002` after the merge hence GitVersion in master is considering pre-release tags created on other branches. I do rebase merge if it makes any difference so I don't have a merge commit.

I have tried this configuration but still I did not achieve the behaviour I wanted
```
mode: ContinuousDelivery
branches:
  master:
    tag: 
    increment: Patch
    prevent-increment-of-merged-branch-version: false
  develop:
    mode: ContinuousDelivery
    tag: unstable
    increment: Minor
    track-merge-target: true
```

I am not sure if this is an issue or not. Perhaps someone can help me to put together the appropriate configuration.
