### ISSUE TITLE
Allow ignoring part of history when calculating version

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#538]
Based on discussions from #470 we reached a consensus that you should be able to ignore before a time period. This can be a configuration value:

`ignore-commits-before: 2015/01/01` 

This allows when repositories have bad commit messages or something else which is causing a high version number (see #443).

```
ignore-shas:
    sha1
    sha2
```

could be another option, the logs tell you what commits different versions are coming from, so it would be copied straight out of the logs to ignore that particular commit. Having both would not be bad.

**Comment by asbjornu** [comment]
If you go for a date, please use RFC 3999 (subset of ISO 8601) for the format. That means the above example should be "2015-01-01". :)

**Comment by asbjornu** [comment]
And perhaps it would be better for extensibility to group everything under an `ignore` section, like so?
```yaml
ignore:
    shas: b6c0c9fda88830ebcd563e500a5a7da5a1658e98 6c19c7c219ecf8dbc468042baefa73a1b213e8b1
    commits-before: 2015-01-01
```
Grouping it like this would make it easy to add `commits-between` in the future, for instance.

What should the syntax for several SHAs be, by the way? Separated by space or linefeed and indented?
