### ISSUE TITLE
How to invalidate cache file so that it's either ignored or deleted before calculation?

### ISSUE THREAD

**Issue by PreetSangha** [GitTools/GitVersion#798]
```
next-version: 3.10.2
branches: {}
mode: ContinuousDeployment
continuous-delivery-fallback-tag: Alpha
branches: 
  develop:
    mode: ContinuousDeployment
    tag: Alpha
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
  
  release[/-]:
    mode: ContinuousDeployment
    #tag: XXX
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false

```

I was getting this output before I used the log to determine that there was a cache file

```
C:\Dev\Development\ayata\ProjectName>C:\Dev\GitVersion\build\GitVersionTfsTaskBuild\GitVersionTask\GitVersion.exe
  
     {
      "Major":3,
      "Minor":10,
      "Patch":2,
      "PreReleaseTag":"v3-10-0.0",                            
      "PreReleaseTagWithDash":"-v3-10-0.0",
      "PreReleaseLabel":"v3-10-0",
      "PreReleaseNumber":0,
      "BuildMetaData":"",
      "BuildMetaDataPadded":"",
      "FullBuildMetaData":"Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
      "MajorMinorPatch":"3.10.2",
      "SemVer":"3.10.2-v3-10-0.0",
      "LegacySemVer":"3.10.2-v3-10-0-0",
      "LegacySemVerPadded":"3.10.2-v3-10-0-0000",
      "AssemblySemVer":"3.10.2.0",
      "FullSemVer":"3.10.2-v3-10-0.0",
      "InformationalVersion":"3.10.2-v3-10-0.0+Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
      "BranchName":"Release/v3.10.0",
      "Sha":"15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
      "NuGetVersionV2":"3.10.2-v3-10-0-0000",
      "NuGetVersion":"3.10.2-v3-10-0-0000",
      "CommitsSinceVersionSource":0,
      "CommitsSinceVersionSourcePadded":"0000",
      "CommitDate":"2016-02-18"
    }

```
	
After deleting the cache file I got this version calculation

```
C:\Dev\Development\ayata\ProjectName>del C:\Dev\Development\ayata\ProjectName\.git\gitversion_cache\2AFD573A72D9897F57F4051974C54865B8B58B66.yml
    
    C:\Dev\Development\ayata\ProjectName>C:\Dev\GitVersion\build\GitVersionTfsTaskBuild\GitVersionTask\GitVersion.exe
    {
      "Major":3,
      "Minor":10,
      "Patch":2,
      "PreReleaseTag":"beta.0",
      "PreReleaseTagWithDash":"-beta.0",                        << ------------------------------
      "PreReleaseLabel":"beta",
      "PreReleaseNumber":0,
      "BuildMetaData":"",
      "BuildMetaDataPadded":"",
      "FullBuildMetaData":"Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
      "MajorMinorPatch":"3.10.2",
      "SemVer":"3.10.2-beta.0",
      "LegacySemVer":"3.10.2-beta0",
      "LegacySemVerPadded":"3.10.2-beta0000",
      "AssemblySemVer":"3.10.2.0",
      "FullSemVer":"3.10.2-beta.0",
      "InformationalVersion":"3.10.2-beta.0+Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
      "BranchName":"Release/v3.10.0",
      "Sha":"15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
      "NuGetVersionV2":"3.10.2-beta0000",
      "NuGetVersion":"3.10.2-beta0000",
      "CommitsSinceVersionSource":0,
      "CommitsSinceVersionSourcePadded":"0000",
      "CommitDate":"2016-02-18"
    }

```
	
So I was wondering how I can invalidate the file without having to discover it from the folder first please.

**Comment by gep13** [comment]
@PreetSangha at the minute, I don't think that there is an option to do this.  I agree that there are times when invalidating the cache would make sense, however, this would only be after making modifications to the configuration file, right?  At all other times, you would expect the generated version number to be the same?

**Comment by asbjornu** [comment]
If I understand this correctly, won't including the last modified date or content hash of `GitVersionConfig.yaml` as a part of the hashed cache file name fix this problem?

**Comment by gep13** [comment]
@asbjornu that is a very good point, and yes, I believe that would correct the issue as well.

**Comment by PreetSangha** [comment]
@asbjornu  Thank you but that was my thinking too. 

However as I've found before (with 3.6) and now (with 4.0) that updating the GitVersionConfig.yaml file didn't do anything until I'd deleted the cache file.

I raised this question on [stackoverflow ](http://stackoverflow.com/questions/35306594/git-version-always-sets-prerelase-label-to-unstable-how-to-make-it-respect-c) when I had the problem on 3.6. 

I'm trying to recreate this problem but if I recall correctly the change I made to the the yaml file was 

I'll post when I have more details.

**Comment by PreetSangha** [comment]
Here is a recreation I think. Please feel free correct my understanding


first I clear the cache

```

C:\MyProj>del .git\gitversion_cache
C:\MyProj\.git\gitversion_cache\*, Are you sure (Y/N)? y

```

This is my branch

```

C:\MyProj>git branch
* Release/v3.10.0
  develop
  master
  trunk
  vs2015

```

and my gitverion.yaml file

```

C:\MyProj>type GitVersionConfig.yaml
next-version: 3.10.2
branches: {}
mode: ContinuousDeployment
continuous-delivery-fallback-tag: Alpha
branches:
  develop:
    mode: ContinuousDeployment
    tag: Release
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false

  release[/-]:
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false

```
and the output of git version 

```

C:\MyProj>C:\Dev\GitVersion\build\GitVersionTfsTaskBuild\GitVersionTask\GitVersion.exe
{
  "Major":3,
  "Minor":10,
  "Patch":2,
  "PreReleaseTag":"v3-10-0.0",                                      <<< from useBranchName
  "PreReleaseTagWithDash":"-v3-10-0.0",
  "PreReleaseLabel":"v3-10-0",
  "PreReleaseNumber":0,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "MajorMinorPatch":"3.10.2",
  "SemVer":"3.10.2-v3-10-0.0",
  "LegacySemVer":"3.10.2-v3-10-0-0",
  "LegacySemVerPadded":"3.10.2-v3-10-0-0000",
  "AssemblySemVer":"3.10.2.0",
  "FullSemVer":"3.10.2-v3-10-0.0",
  "InformationalVersion":"3.10.2-v3-10-0.0+Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "BranchName":"Release/v3.10.0",
  "Sha":"15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "NuGetVersionV2":"3.10.2-v3-10-0-0000",
  "NuGetVersion":"3.10.2-v3-10-0-0000",
  "CommitsSinceVersionSource":0,
  "CommitsSinceVersionSourcePadded":"0000",
  "CommitDate":"2016-02-18"
}

```

I se a cache file has been created

```


C:\MyProj>dir .git\gitversion_cache
 Volume in drive C has no label.
 Volume Serial Number is C082-FC4A

 Directory of C:\MyProj\.git\gitversion_cache

02/03/2016  10:05 AM    <DIR>          .
02/03/2016  10:05 AM    <DIR>          ..
02/03/2016  10:05 AM               796 4835E6A696C86089F8817AA06F673923068431B4.yml
               1 File(s)            796 bytes
               2 Dir(s)  87,388,692,480 bytes free

C:\MyProj>type .git\gitversion_cache\4835E6A696C86089F8817AA06F673923068431B4.yml
Major: 3
Minor: 10
Patch: 2
PreReleaseTag: v3-10-0.0                                            <<< from useBranchName
PreReleaseTagWithDash: -v3-10-0.0
PreReleaseLabel: v3-10-0
PreReleaseNumber: 0
BuildMetaData:
BuildMetaDataPadded:
FullBuildMetaData: Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a
MajorMinorPatch: 3.10.2
SemVer: 3.10.2-v3-10-0.0
LegacySemVer: 3.10.2-v3-10-0-0
LegacySemVerPadded: 3.10.2-v3-10-0-0000
AssemblySemVer: 3.10.2.0
FullSemVer: 3.10.2-v3-10-0.0
InformationalVersion: 3.10.2-v3-10-0.0+Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a
BranchName: Release/v3.10.0
Sha: 15beae0f6cac4b2c850334af9caf6dd1fbd65f6a
NuGetVersionV2: 3.10.2-v3-10-0-0000
NuGetVersion: 3.10.2-v3-10-0-0000
CommitsSinceVersionSource: 0
CommitsSinceVersionSourcePadded: 0000
CommitDate: 2016-02-18

```

so I make an edit to my configuration file (see highlighed line that I commented out)

```


C:\MyProj>type GitVersionConfig.yaml
next-version: 3.10.2
branches: {}
mode: ContinuousDeployment
continuous-delivery-fallback-tag: Alpha
branches:
  develop:
    mode: ContinuousDeployment
    tag: Release
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false

  release[/-]:
    mode: ContinuousDeployment
    #tag: useBranchName                                 <<<< Commented out
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false

```

with this new version  get this gitverion output

```


C:\MyProj>C:\Dev\GitVersion\build\GitVersionTfsTaskBuild\GitVersionTask\GitVersion.exe
{
  "Major":3,
  "Minor":10,
  "Patch":2,
  "PreReleaseTag":"v3-10-0.0",                  <<< (UNCHANGED) from useBranchName
  "PreReleaseTagWithDash":"-v3-10-0.0",
  "PreReleaseLabel":"v3-10-0",
  "PreReleaseNumber":0,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "MajorMinorPatch":"3.10.2",
  "SemVer":"3.10.2-v3-10-0.0",
  "LegacySemVer":"3.10.2-v3-10-0-0",
  "LegacySemVerPadded":"3.10.2-v3-10-0-0000",
  "AssemblySemVer":"3.10.2.0",
  "FullSemVer":"3.10.2-v3-10-0.0",
  "InformationalVersion":"3.10.2-v3-10-0.0+Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "BranchName":"Release/v3.10.0",
  "Sha":"15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "NuGetVersionV2":"3.10.2-v3-10-0-0000",
  "NuGetVersion":"3.10.2-v3-10-0-0000",
  "CommitsSinceVersionSource":0,
  "CommitsSinceVersionSourcePadded":"0000",
  "CommitDate":"2016-02-18"
}

```

And deleting the cache file 

```

C:\MyProj>del .git\gitversion_cache\4835E6A696C86089F8817AA06F673923068431B4.yml

```

I get this output

C:\MyProj>C:\Dev\GitVersion\build\GitVersionTfsTaskBuild\GitVersionTask\GitVersion.exe
{
  "Major":3,
  "Minor":10,
  "Patch":2,
  "PreReleaseTag":"beta.0",                    <<< Now beta as tag is commented out
  "PreReleaseTagWithDash":"-beta.0",
  "PreReleaseLabel":"beta",
  "PreReleaseNumber":0,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "MajorMinorPatch":"3.10.2",
  "SemVer":"3.10.2-beta.0",
  "LegacySemVer":"3.10.2-beta0",
  "LegacySemVerPadded":"3.10.2-beta0000",
  "AssemblySemVer":"3.10.2.0",
  "FullSemVer":"3.10.2-beta.0",
  "InformationalVersion":"3.10.2-beta.0+Branch.Release/v3.10.0.Sha.15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "BranchName":"Release/v3.10.0",
  "Sha":"15beae0f6cac4b2c850334af9caf6dd1fbd65f6a",
  "NuGetVersionV2":"3.10.2-beta0000",
  "NuGetVersion":"3.10.2-beta0000",
  "CommitsSinceVersionSource":0,
  "CommitsSinceVersionSourcePadded":"0000",
  "CommitDate":"2016-02-18"
}

C:\MyProj>

```
