### ISSUE TITLE
assembly-informational-format: ignored

### ISSUE THREAD

**Issue by kevinneufeld** [GitTools/GitVersion#870]
I am trying to customize the AssemblyInformationalVersion, either with GitVersion.yml or with command line argument `/overriderconfig:assembly-informational-format="{NuGetVersion}"`

Unfortunately neither appear to be working. Maybe I am missed something in the docs?
Is there hidden argument to force an update from GitVersion.yml? 

My AssemblyInfo.cs is always updated with 
```C#
[assembly: AssemblyInformationalVersion("2.4.0-beta.1+35.Branch.release-2.4.0.Sha.edee73f7b0e1384954d0f3b1d50a1e6e772eac42")]
``` 

when I want 
 ```C#
 [assembly: AssemblyInformationalVersion("2.4.0-beta0001")]
 ``` 

**GitVersion.yml:** (located in the root of the repo)

```yml
assembly-informational-format: '{NuGetVersionV2}'
mode: ContinuousDeployment
branches: {}
ignore:
  sha: []
```

Using the following commands: 

```
  PS> GitVersion /updateassemblyinfo
  PS> GitVersion /overrideconfig:assembly-informational-format="{NuGetVersion}" /updateassemblyinfo
```
**GitVersion /showconfig**
```
  PS> gitversion /showconfig
      assembly-versioning-scheme: MajorMinorPatch
      mode: ContinuousDelivery
      tag-prefix: '[vV]'
      continuous-delivery-fallback-tag: ci
      major-version-bump-message: '\+semver:\s?(breaking|major)'
      minor-version-bump-message: '\+semver:\s?(feature|minor)'
      patch-version-bump-message: '\+semver:\s?(fix|patch)'
      legacy-semver-padding: 4
      build-metadata-padding: 4
      commits-since-version-source-padding: 4
      commit-message-incrementing: Enabled
      branches:
        master:
          mode: ContinuousDelivery
          tag: ''
          increment: Patch
          prevent-increment-of-merged-branch-version: true
          track-merge-target: false
        releases?[/-]:
          mode: ContinuousDelivery
          tag: beta
          increment: Patch
          prevent-increment-of-merged-branch-version: true
          track-merge-target: false
        features?[/-]:
          mode: ContinuousDelivery
          tag: useBranchName
          increment: Inherit
          prevent-increment-of-merged-branch-version: false
          track-merge-target: false
        (pull|pull\-requests|pr)[/-]:
          mode: ContinuousDelivery
          tag: PullRequest
          increment: Inherit
          prevent-increment-of-merged-branch-version: false
          tag-number-pattern: '[/-](?<number>\d+)[-/]'
          track-merge-target: false
        hotfix(es)?[/-]:
          mode: ContinuousDelivery
          tag: beta
          increment: Patch
          prevent-increment-of-merged-branch-version: false
          track-merge-target: false
        support[/-]:
          mode: ContinuousDelivery
          tag: ''
          increment: Patch
          prevent-increment-of-merged-branch-version: true
          track-merge-target: false
        dev(elop)?(ment)?$:
          mode: ContinuousDeployment
          tag: unstable
          increment: Minor
          prevent-increment-of-merged-branch-version: false
          track-merge-target: true
      ignore:
        sha: []
  ```
