### ISSUE TITLE
continuous-delivery-fallback-tag - use case in ContinousDeployment mode and when the tag is empty?

### ISSUE THREAD

**Issue by Ashtonian** [GitTools/GitVersion#888]
I'm using octopus deploy and an internal nuget feed (for utility packages) to "deploy" actual products. We use forks and PullRequests to master. I think we would like the nuget version to just increment on every build as master is considered deploy-able and octo needs to see a difference in the feed. Which makes me think we want to use ContinousDeployment and have PullRequests used in integration testing and builds with a pre-release tag. 

So it would look something like: 
**Master** 
Commit 1 -> 1.0.0.1
Commit 2 -> 1.0.0.2
**PR**
PR 1 -> 1.0.0.3-PullRequest-1
PR 2 -> 1.0.0.4-PullRequest-2

If that doesn't make anysense or you see major problems with it other then its not standard semvr please let me know :) 

So the problem is commits on master have a -ci pre-release tag. 

The gitversion.yml is:

```
mode: ContinuousDeployment
next-version: 1.0.0
branches: {}
```

gitversion /showconfig shows:

```
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
next-version: 1.0.0
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    mode: ContinuousDeployment
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
...
```

So the builds are being created as 1.0.0-ci.buildnumber which seems to be because the `continuous-delivery-fallback-tag` setting is being used.

I'm  a little confused:
- Why is continuous-delivery-fallback-tag being used in ContinousDeployment mode?
- Why is that field being used even though the tag is set for master to be empty string?
