### ISSUE TITLE
Alias branch types in config

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#995]
Lets be honest. Regexes as keys kinda sucks...

```
branches:
  (pull|pull\-requests|pr)[/-]:
    tag-name-pattern: '[/-](?<number>\d+)[-/]'
```

Lets fix this in v4 and change to something like:

```
branches:
  pullrequest:
    match: '(pull|pull\-requests|pr)[/-]'
    tag-name-pattern: '[/-](?<number>\d+)[-/]'
```
